### ISSUE TITLE
how encrypt script?

### ISSUE THREAD

**Issue by gitlsl** [oleg-shilo/cs-script#1]
welcome to git,I watch you on codeplex long time,I have a question about:how encrypt script?

**Comment by oleg-shilo** [comment]
> welcome to git,I watch you on codeplex 

Txs. Let's see how much difference this move makes. :)

> how encrypt script?

If you are hosting the engine then it is reasonably obvious:

```C#
string code = encryptedCode.Decrypt();
dynamic script = CSScript.Evaluator.LoadCode(code);
script.DoTheWork();
```
Though for the stand alone execution you could use custom compiler and just decrypt the encrypted script file into the plain one and feed it into the actual compiler. Though in this case you are going to create the plain files on HD and you will be responsible for clearing them.  

But I think you can more benefit from Precompiler extension: http://www.csscript.net/help/precompilers.html

This way you are going to decrypt the script only and only in memory. The approach is equally simple but much cleaner. And you can keep your precompiler in a .cs form or compile it into a dll.

I have attached the whole "Precompilers Sample", which I extended with your specific scenario. The following is just a brief highlight:

```C#
public class EncryptionPrecompiler
{
    static public bool Compile(ref string code, string scriptFile, bool IsPrimaryScript, Hashtable context)
    {
        code = File.ReadAllBytes(scriptFile)
                   .Decrypt()
                   .GetString();

        //add ref asms if you need to
        var newRefs = (List<string>)context["NewReferences"];
        newRefs.Add("System.Windows.Forms.dll");

        return true;
    }
}

static class Extensions
{
    static byte shift = 7;

    public static byte[] Decrypt(this byte[] data)
    {
        //simplistic encryption technique
        for (int i = 0; i < data.Length; i++)
            data[i] = (byte)(data[i] - shift); 
        return data;
    }

    public static string GetString(this byte[] data)
    {
        return Encoding.Default.GetString(data);
    }
}
```
And to start the script pass the precompiler as an argument:
```
cscs /precompiler:decrypt.cs encrypted.cs
``` 


[AdvancedSamples.zip](https://github.com/oleg-shilo/cs-script/files/181910/AdvancedSamples.zip)

**Comment by gitlsl** [comment]
@oleg-shilo nice ! thank you
