### ISSUE TITLE
Basic host question and failure with such in referenced DLL's/Nuget

### ISSUE THREAD

**Issue by ShawnPierce** [oleg-shilo/cs-script#100]
I have a much more complicated version of the attached but this attached basic version is showing what the problem is any help would be appreciated. I have been using it very successfully for many years having my own host system.

The basic idea is I have a C# script host and it's dealing with many many scripts in a package the host breaks out the script and executes them according to the design but that's not too important :), I finally wanted to attempt to use nuget to get the SignalR I added the // at the top of the script

//css_dir C:\ProgramData\CS-Script\nuget\Microsoft.AspNet.SignalR.Client\Microsoft.AspNet.SignalR.Client.2.2.2\lib\net40;
//css_dir C:\ProgramData\CS-Script\nuget\Microsoft.AspNet.SignalR.Client\Newtonsoft.Json.6.0.4\lib\net40;
//css_nuget -noref Microsoft.AspNet.SignalR.Client
//css_nuget -noref Newtonsoft.Json

Running Verbose I can see it's working 

css /cd /verbose C:\Work\BasicHost\BasicHost\Script\nugetexample.cs

...
Installing package 'Microsoft.AspNet.SignalR.Client
...
Installing package 'Newtonsoft.Json' to 'C:\ProgramData\CS-Script\nuget\Newtonsoft.Json'.
...

Also in Verbose I can see where the reference if (I attempted to add locally as well so it found them here)

 References:
   0 - C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
   1 - C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Linq\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Linq.dll
   2 - C:\windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
   3 - C:\Work\BasicHost\BasicHost\Script\Microsoft.AspNet.SignalR.Client.dll
   4 - C:\Work\BasicHost\BasicHost\Script\Newtonsoft.Json.dll

Additionally, if I use cs-script to open the .cs file the references are added correctly and there is no problem running the script in the debugger.

Now when I attempt to use CSScript it will compile the DLL through my host

Assembly dll = ScriptRunner.GetCompiledDLL(ScriptCode, true);
            IScriptInterface scriptref = Activator.CreateInstance(dll.GetTypes()[0]).AlignToInterface<IScriptInterface>();
            string reply = scriptref.Test();

It will not run the Test Method with the error:

Additional information: Could not load file or assembly 'Microsoft.AspNet.SignalR.Client, Version=2.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Thank you for any thoughts/advice you might have? I attached a simple demo.

Shawn

[BasicHost.zip](https://github.com/oleg-shilo/cs-script/files/1662322/BasicHost.zip)

**Comment by oleg-shilo** [comment]
Hi Shawn,

You will need to add your own assembly probing. CS-Script engine does it for you. But since you are not using it to instantiate the script objects and use raw Reflection (`Activator.CreateInstance`) you are now responsible for assembly probing. 

It is actually simple. You can even use CS-Script generic assembly probing solution:
```C#
SimpleAsmProbing.For(@"E:\dir1", @"E:\dir2", .... );
```
Just have the code above executed globally (once) before any probing. Pass the list of all probing directories you can imagine (e.g. CS-Script probing directories.).

You are done.

**Comment by ShawnPierce** [comment]
After a bit of experimenting, I think I understand it a lot better, however, some clarification the SimpleAsmProbing was introduced only in recent versions I was running a very old version of CSScriptLibrary (3.9. I think) and it does not like paths that are not local to the machine I.E. \\Server\Location or mapped drives I:\Location even though the initial script that we are executing was on a shared location the references needed to all be on the local machine. Does that sound right?

Thank you for the help,
 Shawn

**Comment by oleg-shilo** [comment]
The class itself is incredibly simple and you can have your own assembly probing solution based on tts core:

```C#
     public class SimpleAsmProbing : IDisposable
    {
        ...
        public static SimpleAsmProbing For(params string[] probingDirs)
        {
            return new SimpleAsmProbing(probingDirs);
        }

        public SimpleAsmProbing(params string[] probingDirs)
        {
            Init(probingDirs);
        }

        static bool initialized = false;
        static string[] probingDirs = new string[0];

        public void Init(params string[] probingDirs)
        {
            SimpleAsmProbing.probingDirs = probingDirs;
            if (!initialized)
            {
                initialized = true;
                AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve;
            }
        }

        public void Uninit()
        {
            if (initialized)
            {
                initialized = false;
                AppDomain.CurrentDomain.AssemblyResolve -= CurrentDomain_AssemblyResolve;
            }
        }

        Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
        {
            foreach (string dir in probingDirs)
            {
                try
                {
                    string file = Path.Combine(dir, args.Name.Split(',').First().Trim() + ".dll");
                    if (File.Exists(file))
                        return Assembly.LoadFrom(file);
                }
                catch { }
            }
            return null;
        }
    }
```

However loading the assemblies form the network location is prohibited by default by CAS. You will need to have loading assemblies from untrusted sources enabled if you want to support shared locations.

Thus it is a common .NET runtime configuration challenge.
