### ISSUE TITLE
How to use hosted script with VB.NET scripts

### ISSUE THREAD

**Issue by billpeet** [oleg-shilo/cs-script#102]
How do I go about implementing a script loader for VB.NET scripts? 
I can see plenty of info in the docs about alternative compilers, but most of it seems to apply to the CLI rather than the hosted scripts.
I've found the CSScript.GlobalSettings.UseAlternativeCompiler field, and have implemented a CSSCodeProvider class, but the sourceFile seems to come in with a '.tmp' file extension when I use CSScript.Evaluator.LoadFile("file.ext").
Furthermore, the behaviour seems to be slightly different.
I have 2 test files:
```csharp
//script.cs
using System;
class Script
{
    public void Hello(string greeting)
    {
        Console.WriteLine(greeting);
    }
}
```
```vb.net
'script.vb
' //css_reference System.dll;
Imports System
Class Script
    Public Sub Hello(greeting As String)
        Console.WriteLine(greeting)
    End Sub
End Class
```

And load them using the same methods:
```vb
Public Interface IScript
Sub Hello(message As String)
End Interface

CSScript.EvaluatorConfig.Engine = CSScriptLibrary.EvaluatorEngine.CodeDom
CSScript.GlobalSettings.UseAlternativeCompiler = "path\to\CSSCodeProvider.dll"

'C#
Dim cs As IScript = CScript.Evaluator.LoadFile(Of IScript)("script.cs")
'Works correctly
cs.Hello("Hello")

'VB
'System.ApplicationException: 'The object (My.MyApplication) cannot be aligned to CSScriptTest.IScript interface.'
Dim cs As IScript = CScript.Evaluator.LoadFile(Of IScript)("script.vb")
```

Any pointers what I'm doing wrong?

**Comment by oleg-shilo** [comment]
Your code seems OK. 

Let's see if it is the alignment (third-party routine) is playing up. 

Change your code to avoid alignment:
```vb
Dim cs As Object = CScript.Evaluator.LoadFile("script.vb")
```
Under debugger see what is the actual type of `cs`. 
Try to typecast it to `IScript` directly instead of using ducktyping.

Let me know your observations.

**Comment by billpeet** [comment]
Hmm - I get this:
```vb
Dim vb As Object = CSScript.Evaluator.LoadFile("script.vb")
Console.WriteLine(vb.GetType().Name) ' "MyApplication"
vb.Hello("foo") ' System.MissingMemberException Public member 'Hello' on type 'MyApplication' not found
```

My CSSCodeProvider is as follows:
```vb
Public Class CSSCodeProvider
    Public Shared Function CreateCompiler(sourceFile As String) As ICodeCompiler
        Dim errMsg As String = "Alternative compiler for file extension " & Path.GetExtension(sourceFile) & "cannot be created."
        Try
            Select Case Path.GetExtension(sourceFile.ToLower())
                Case ".cs"
                    Return New Microsoft.CSharp.CSharpCodeProvider().CreateCompiler()
                Case ".vb"
                    Return New Microsoft.VisualBasic.VBCodeProvider().CreateCompiler()
                Case ".tmp"
'Added to make this work - all files come in with '.tmp' extension
                    Return New Microsoft.VisualBasic.VBCodeProvider().CreateCompiler()
            End Select
        Catch ex As Exception
            Throw New Exception(errMsg, ex)
        End Try
        Throw New Exception(errMsg)
    End Function
End Class
```

**Comment by oleg-shilo** [comment]
Good. It actually makes sense.  

This is what `LoadFile` does:
```C#
CompileCode(File.ReadAllText(scriptFile), scriptFile).CreateObject("*");
```
`CreateObject("*")` always returns the first class found. In C# scripts it is exactly the class you need. However in in VB code the first class is `Application` and it is not what you are looking for. Thus you will need to specify the exact name of the script class:

```vb
Dim script as object= CScript.Evaluator.CompileFile(File.ReadAllText("script.vb"), "script.vb").CreateObject("Script")
```

Alternatively you can use your existing routine and just jump to your class with the reflection; 
```vb
Dim cs As Object = CScript.Evaluator.LoadFile("script.vb")
                                    .GetType()
                                    .Assembly
                                    .CreateObject("Script");
```

Though, the ducktyped proxy is created according C# script "rules" thus your VB script cannot be ducktypes. Meaning that if you want to use interface then your script object will need to inherit from IScript. Then you can do a simple typecasting of the `cs` object into `IScript`interface.

And, of course, you can use "dynamic" type but I don't even know what is the VB syntax for it.

**Comment by billpeet** [comment]
Ahh yep makes sense @oleg-shilo, thanks for your help.
Can close this issue now.
