### ISSUE TITLE
Question related to Debugger.Break() in a hosted script

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#104]
Calling `System.Diagnostics.Debugger.Break()` in a script is expected to let Windows pop up a message box, asking whether to connect a debugger (e.g. Visual Studio) to the process. This properly works when e.g. running the following script directly with `cscs.exe Test.cs`:
```
using System;

namespace Test
{
    public static class Script
    {
        public static int Main()
        {
            System.Diagnostics.Debugger.Break();

            int result = -1;
            if (result < 0)
                Console.WriteLine("Result is {0}, i.e. below 0, this means [something].", result);
        ////else if (result == 0)
        ////    Upps, this got forgotten when implementing the script, and has to be debugged.
            else if (result > 0)
                Console.WriteLine("Result is {0}, i.e. above 0, this means [something else].", result);

            return (result);
        }
    }
}
```
Running it with `cscs.exe -dbg -out:Test.dll Test.cs` even lets Visual Studio show the call to `System.Diagnostics.Debugger.Break()` in the source code.

However, this script doesn't work when being hosted in the release build of my application. Actually, it works too good, as the call to `Break()` is simply ignored and the scripts continues as if there was no call to `Break()`.

Note, when running my application from within Visual Studio (Debug|Release), as well as when attaching Visual Studio to my application before starting the script, the call to `Break()` is properly handled.

Am I missing something? Haven't found an answer to this question in neither `CSScript.chm` nor the online documentation.

**Comment by oleg-shilo** [comment]
I can only guess that `Break` similarly to other debugger commands (e.g. Assert) is just ignored if no debug symbols are available at startup. I remember my early experiments with with .NETCore and Mono Debugger showed an interesting behavior: a dependency assembly proper debug symbols could not be loaded by the debugger unless the host assembly had symbols available at startup.

Though it may have changed now.

This topic it truly outside of CS-Script scope. It will be OS/Debugger integration domain. Though try using Assert instead. I remember that despite being very similar they have different level of integration with the OS default debugger.

**Comment by maettu-this** [comment]
Good input. I was hoping that adding debug symbols of my hosting application will make a change. It didn't. But instead, adding `System.Diagnostics.Debugger.Lauch()` has helped. So my example now states:
```
System.Diagnostics.Debugger.Break();  // In case a debugger is already attached, this will break execution.
System.Diagnostics.Debugger.Launch(); // In case no debugger is attached yet, this will break execution and let
                                      // the OS pop up a message box letting you to lauch the desired debugger.
```

This question can be marked as resolved. Thanks!

**Comment by oleg-shilo** [comment]
Actually your work around makes perfect sense. No wander it looked some how familiar. This is what `CSExecutor.ExecuteImpl` has:
```C#
if (options.startDebugger)
{
    SaveDebuggingMetadata(options.scriptFileName);

    System.Diagnostics.Debugger.Launch();
    if (System.Diagnostics.Debugger.IsAttached)
    {
        System.Diagnostics.Debugger.Break();
    }
}
```

**Comment by maettu-this** [comment]
Perfect, and even better, as it will not break if the user choses not to attach the debugger.

**Comment by maettu-this** [comment]
Even more refined, preventing hitting a breakpoint twice when no debugger was attached:
```
if (System.Diagnostics.Debugger.IsAttached) // In case a debugger is already attached,
    System.Diagnostics.Debugger.Break();    // Break() execution to start debugging.
else                                        // Otherwise, Launch() will break execution
    System.Diagnostics.Debugger.Launch();   // and let the OS pop up a message box to
                                            // let you to lauch the desired debugger.
```

**Comment by oleg-shilo** [comment]
👍
