### ISSUE TITLE
//css_imp does not always work

### ISSUE THREAD

**Issue by rp0815** [oleg-shilo/cs-script#105]
After changing from CS-Script.bin 3.14.0 to CS-Script.lib 3.28.0.1 I found, that //css_imp (and //css_inc) does not work anymore when using a path like so "//css_imp .\anyfile.cs". Trying to compile this brings up an error telling me that the file cannot be found. I can fix this by using "//css_imp anyfile.cs". But, meanwhile there are many scripts on many computers on the run...

**Comment by oleg-shilo** [comment]
I have just retested it and it seems to work OK. Please provide the test case that shows the problem.

Please note that `.\` referees to the location of the parent script, not the CurrentDirectory.
