### ISSUE TITLE
Compiling to Byte[]/File in .NET Standard

### ISSUE THREAD

**Issue by zcanann** [oleg-shilo/cs-script#110]
From what I understand, the full-framework cs-script library is able to compile to file by leveraging CodeDom.

I'm not sure if the Roslyn compiler supports something similar, but for our use case we would like to be able to compile scripts to a byte[] or file.

Unfortunately serializing the `Assembly` object that the `RoslynEvaluator` returns is not an option, because `Assembly` objects are not really serializable even though they implement `ISerializable`

**Comment by oleg-shilo** [comment]
The current state of API of .NET Standard 2 allows doing that. I considered having in-memory (as opposite to file based) assemblies rather beneficial thus the current interface does not allow compiling into a file.

Though I have reworked interface and now you can do the following:

```C#
var info = new RoslynEvaluator.CompileInfo 
{ 
    AssemblyFile = @"E:\temp\asm.dll" 
};

Assembly asm = CSScript.Evaluator
                       .Cast<RoslynEvaluator>()
                       .CompileCode(@"using System;
                                      public class Script
                                      {
                                          public int Sum(int a, int b)
                                          {
                                              return a+b;
                                           }
                                      }",
                                      info);
```

The interface will be available with the very next release. If you don't want to wait you can grab the HotFix release from NuGet:
```txt
Install-Package CS-Script.Core -Version 1.0.0.4-HotFix 
```

**Comment by zcanann** [comment]
This looks perfect-- thanks!
