### ISSUE TITLE
Right click open Error attempting to start VS

### ISSUE THREAD

**Issue by ShawnPierce** [oleg-shilo/cs-script#117]
Has anyone seen this issues where right clicking on the .cs file and selecting Open in VS2017 results in "Unable to start process associated with the context mwnu item." however running "csws.exe /c DebugVS14.0.cs %1" where %1 is the script does work...

**Comment by oleg-shilo** [comment]
I would expect t to be `DebugVS15.0.cs`:
![image](https://user-images.githubusercontent.com/16729806/41909569-a79afb42-798a-11e8-902d-035eb8001aee.png)

What if you try to invoke "Open in VS2015"?
