### ISSUE TITLE
Reference to Mono.CSharp in nuget package?

### ISSUE THREAD

**Issue by fhurta** [oleg-shilo/cs-script#12]
Just installed through nuget into my solution and I can see it added also reference to Mono.CSharp. I don't use Mono at all. Does it have to be there?

**Comment by oleg-shilo** [comment]
Yes it does.
CS-Script uses Mono compiler-as-service. It is one of the 3 supported
underlying compilation platforms: CodeDOM, Mono and Roslyn.


Oleg Shilo
--------------------------------------------------------------------------------------------
Website: http://www.csscript.net
E-Mail: csscript.support@gmail.com
