### ISSUE TITLE
scripting.cs file

### ISSUE THREAD

**Issue by apobekiaris** [oleg-shilo/cs-script#120]
Hi

I have a .NET40 dependencyso I had to go with an old nuget package of yours v3.9.17. But this nuget adds a Scripting.cs every time installed. Is there a way to avoid or somehow auto remove?

**Comment by oleg-shilo** [comment]
There are a few NuGet packages. What you need is `CS-Script.bin`. It only contains binaries, while `CS-Script` contains `CS-Script.bin`+"scripting.cs" sample file.

Unfortunately for you the separation on package and package.bin has happens only from v3.10. My be using this version is the way to address your problem? It still targets .NET40:

![image](https://user-images.githubusercontent.com/16729806/43694136-3eacda00-9975-11e8-9d35-fbb8f9de0dfa.png)

**Comment by apobekiaris** [comment]
thnks I will try3.10

btw how good is the performance back then? is there some caching buildin?

**Comment by oleg-shilo** [comment]
Yes it is there. The caching was introduced in ~2009. It was one of the first features borrowed from Python and brought to the CS-SCriptLibrary.

**Comment by apobekiaris** [comment]
thanks again!

another issue a user reported is 
>missing DLL / reference Mono.Posix
https://github.com/expand/eXpand/issues/135

does cs-script have such requirement?

**Comment by oleg-shilo** [comment]
Yes it does. It's unfortunate but I had to implement system wide Mutex (not available on Mono-Linux) that requires Mono.Posix. 
I have posted there my detailed explanation.
