### ISSUE TITLE
cs-script.Core compile only

### ISSUE THREAD

**Issue by seertenedos** [oleg-shilo/cs-script#124]
Just wondering if the asm during a compile is auto loaded into the app domain etc. Basically i am looking for a while to verify a script can compile and to return any errors but do not want to load it into the app domain. I was wondering if that is even possible or a way to unload them in netstandard 2.0 if they must be loaded.

**Comment by oleg-shilo** [comment]
Excellent questions.

> ...wondering if the asm during a compile is auto loaded into the app domain etc.

Yes it is:
``` C#
if (IsDebug)
{
    . . .
    return AppDomain.CurrentDomain.Load(buffer, pdbBuffer);
}
else
    return AppDomain.CurrentDomain.Load(buffer);
```

> ...to verify a script can compile and to return any errors but do not want to load it into the app domain.

It is possible but it is not currently implemented. I do think it is a good feature to have, particularly because it is available in CS-Script .NETFull and it is easy to implement. Thus I am marking this as a feature request. 

> I was wondering if that is even possible or a way to unload them in netstandard 2.0 if they must be loaded.

I can only smile... :o)
This is one of the nastiest architectural flaws of .NET. In FULL there is an un-elegant but working work around - unloading the whole AppDomain. .CS-Script uses this feature to conditionally unload the loaded assemblies. Though... sadly .NET Core just does not implement this feature at all.

**Comment by seertenedos** [comment]
Thanks if there can be a compile method that does not load the dll and i can access the errors it solves my issues so that feature would be great.

a little off topic but i see that you are loading it from a buffer above. does that mean it would be possible to save to disk as well? I have no use case for that yet but opens new possibilities to consider in future especial related to my next question which i do have a use case for. 

If it could be added to save the dll would it be possible to build an exe and save that? My use-case here is i am building a lib to spawn child processes to isolate work that could crash dotnet like stackoverflow or contains user supplied code that we don't trust (endless loop etc). It works but uses existing exe which means every process looks the same in task manager. If i could generate custom exe instead the code could be cleaner in the child process, more efficient and i could name the exe after the code so that they show as different names.

**Comment by oleg-shilo** [comment]
You make me smile.

You are asking for the functionality that is implemented in cs-script.full for years. Just too bad .NET Core is still catching up.  

Anyway I have just published the latest changes on NuGet:
https://www.nuget.org/packages/CS-Script.Core/1.0.2

_Changes:_
- Issue #123: cs-script.core and <PrivateImplementationDetails>1 error
- Issue #124: cs-script.core compile only
- Added `CompileAssemblyFromCode`
- Added `CompileAssemblyFromFile` 

```C#
string asm = CSScript.Evaluator
                     .CompileAssemblyFromCode(
                                      @"using System;
                                        public class Script
                                        {
                                            public int Sum(int a, int b)
                                            {
                                                return a+b;
                                            }
                                        }", 
                                        "Test.dll");
```
Though compiling the executable is problematic as Roslyn just does not support it via scripting API.

But you can have your own little assembly executor and pass your script dll into it. Similar to 'rundll32.exe':


_runasm.exe:_
```C#
...
void Main(string[] args)
{
   AppDomain.CurrentAppDomain.ExecuteAssembly(args.First(), args.Skip(1));
}
...
```

**Comment by seertenedos** [comment]
Sorry i still need a variation that just does the compile and does not save anything if possible as well. The ability to save to disk will be useful for something i am building but existing code needs a compile that does not save or returns the data as an object like a byte array or something. This use case is just a compile to check for compile errors and to give feedback to the user so i don't really want to save and have to manage the cleanup of the disk for every build that may or may not be concurrent.

The other methods i am integrating now and will put some tests around and let you know.

**Comment by oleg-shilo** [comment]
You just asked " does that mean it would be possible to save to disk as well? " so I assumed it is what you are interested in.

If you are only about validating your script then you can use `Evaluator.Compile`.

``` C#
(byte[] asm, byte[] pdb) Compile(string scriptText, string scriptFile, CompileInfo info);
. . .

try
{
    CSScript.Evaluator.Compile(scriptText, null, null);
}
catch
{
    . . . 
}

```

The only problem is that currently it is not public. I will meke it public in the next release. but for now it can only be used with the Reflection.

``` C#
static class CSScriptExtensions
{
    public static  (byte[] asm, byte[] pdb) Compile(this IEvaluiator evaluator, string scriptText, string scriptFile, CompileInfo info)
    {
        object[] args = new []{scriptText, scriptFile, info}
        return (byte[], byte[])evaluator.GetType().GetMethod("Compile").Invoke(evaluator, args); 
    }
}
```

**Comment by seertenedos** [comment]
Thanks. Yea I was interested in both. We actually use your library in 5 of
our systems currently and all use cases differ slightly.

Saving generated code would be good for 1-2 of them and 3 of them run
scripts user exits on UI over REST so compile and not save is great there
for checking the code and giving errors to users.

**Comment by oleg-shilo** [comment]
Done.
Please use CS-Script.Core 1.0.3 package
- Added `CSScript.Evaluator.Check`

**Comment by seertenedos** [comment]
Thanks it is working great
