### ISSUE TITLE
CS0433 type is defined multiple times.

### ISSUE THREAD

**Issue by heroius** [oleg-shilo/cs-script#128]
I'm working on a .net framework 4.6 desktop app using regular expression in script (see attachment), meeting error CS0433: The imported type 'System.Text.RegularExpressions.Regex' is defined multiple times.
The csharp project references nuget CS-Script 3.28.7. In the main function no configration is set and LoadMethod<T> method is used.

Is there anything I should do to avoid this error?
thx

[ConsoleApp2.zip](https://github.com/oleg-shilo/cs-script/files/2522940/ConsoleApp2.zip)

**Comment by oleg-shilo** [comment]
Done: 7cf28383cb2fa312ef8274f3d93c64b9023e5bdf

**Comment by heroius** [comment]
> 
> 
> The problem is caused by the internal defect in the Mono compiler, which is a default compiler engine. In cases like this you are better off to switch to the alternative underlying compiler service. IE Roslyn:
> 
> ```cs
> CSScript.EvaluatorConfig.Engine = EvaluatorEngine.Roslyn;
> ```
> 
> I remember it happens before for one or a couple users. But after your report I I think it is time to make Roslyn into a default engine. Will be done in the next release.

Problem solved! Thank you!
