### ISSUE TITLE
"Bad IL format" on self-contained linux-x64 builds if using self namespace in executed code

### ISSUE THREAD

**Issue by ABCRic** [oleg-shilo/cs-script#129]
### Steps to reproduce

1. Create .NET Core App project
2. Reference CS-Script.Core 1.0.4
3. Use the following code
```csharp
using System;
using CSScriptLib;

namespace EvalTest
{
    public class Program
    {
        static void Main(string[] args)
        {
            dynamic func1 = CSScript.Evaluator.LoadMethod(@"
                    public object Func()
                    {{
                        return 1;
                    }}");
            Console.WriteLine("Result: " + func1.Func().ToString());

            dynamic func2 = CSScript.Evaluator.LoadMethod(@"
                    public object Func()
                    {{
                        return EvalTest.Program.CallMe();
                    }}");
            Console.WriteLine("Result: " + func2.Func().ToString());

            dynamic func3 = CSScript.Evaluator.LoadMethod(@"
                    using EvalTest;
                    public object Func()
                    {{
                        return 3;
                    }}");
            Console.WriteLine("Result: " + func3.Func().ToString());
        }

        public static int CallMe() => 2;
    }
}
```
4. Publish from Visual Studio targeting netcoreapp2.1, linux-x64, deployment mode *self-contained*

Expected output (seen if running from VS or if targeting netcoreapp2.1, win-x64, self-contained):
```
Result: 1
Result: 2
Result: 3
```
Actual output (using step 4 above):
```
Result: 1
Result: 2

Unhandled Exception: System.BadImageFormatException: Bad IL format.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at CSScriptLib.RoslynEvaluator.ReferenceAssembly(String assembly)
   at CSScriptLib.RoslynEvaluator.ReferenceAssembliesFromCode(String code, String[] searchDirs)
   at CSScriptLib.RoslynEvaluator.Compile(String scriptText, String scriptFile, CompileInfo info)
   at CSScriptLib.RoslynEvaluator.LoadMethod(String code)
   at EvalTest.Program.Main(String[] args) in (...)\Program.cs:line 22
Aborted (core dumped)
```

Other tests indicate that referencing other assemblies seems fine; the problem seems to stem from referencing the root namespace in the assembly (?) in a using statement. Note also that full qualification as shown in func2 bypasses the problem.

I suspect that the assembly loader is somehow attempting to load EvalTest (which is the linux executable) as an assembly instead of EvalTest.dll, but I have not confirmed this.

**Comment by oleg-shilo** [comment]
> Publish from Visual Studio targeting netcoreapp2.1, linux-x64, deployment mode self-contained

Can you please elaborate what exact action you did for "Publish from Visual Studio"? I know about `dotnet publish` but I am not sure I understand what you mean in context of Visual Studio and .NET Core App project.

**Comment by oleg-shilo** [comment]
Even before you provide me the guidance on how to reproduce the problem I can give you a hint for solving it.

It looks like it is caused by the script engine attempting to load `EvalTest.dll`, which happens to be of a wrong IL format in this case. The attempt to load this assembly is triggered by the script engine default behavior when it tries to probe and load the assembly matching the "using statement". 

I will need to rethink the error handling strategy in this case but for now you can easily disable "using"  resolution with this setting:

```C#
RoslynEvaluator.DisableReferencingFromCode = true;
```

**Comment by oleg-shilo** [comment]
Another point...

You don't need to use double brackets:
```C#
dynamic func1 = CSScript.Evaluator.LoadMethod(@"
                    public object Func()
                    {{
                        return 1;
                    }}");
```
May be it was just a typo.

**Comment by ABCRic** [comment]
The Publish action is in the Build menu - I usually do it from there but I assume it does the same as `dotnet publish` in the case of .NET Core apps.

The double brackets are just a leftover that I forgot to remove from the test case (the real case it was extracted from was using `$` interpolated strings).

**Comment by oleg-shilo** [comment]
Did `RoslynEvaluator.DisableReferencingFromCode = true;` help?

**Comment by ABCRic** [comment]
Yes, that fixes it.

**Comment by oleg-shilo** [comment]
Despite the work around, I am having difficulties of reproducing the exact behavior you are describing.

Could you please send me your project so I can investigate it further.

**Comment by oleg-shilo** [comment]
Don't worry I got it right now.
