### ISSUE TITLE
Extensions collision (.NET Core version)

### ISSUE THREAD

**Issue by rumen-yankov** [oleg-shilo/cs-script#132]
Hello,

Can i suggest you to put Extensions in own namespace cause they cause collision with other .net extension methods from other assemblies. In example **System.Linq.Enumerable** already has an extension method 
**public static IEnumerable<TResult> Cast<TResult>(this IEnumerable source)** 
and this method conflict with cs-script one.

**Comment by oleg-shilo** [comment]
Agree. The extension methods left undecorated with namespace by mistake.
The fix will be available very soon.

**Comment by Grauenwolf** [comment]
I'm using CS-Script.Core v1.0.5.0 for .NET Standard 2.0 and I'm still seeing this issue.

Looking at the F12 header, looks like an old version of CSScriptLib was packaged with the new version of cs-script.core.

#region Assembly CSScriptLib, Version=**1.0.4.0**, Culture=neutral, PublicKeyToken=null
// C:\Users\greyw\.nuget\packages\cs-script.core\**1.0.5**\lib\netstandard2.0\CSScriptLib.dll
#endregion

**Comment by oleg-shilo** [comment]
Indeed it was a packaging (building) mistake. 

The package CS-Script.Core v1.0.5.0 was built from the correct source code and contains correct binaries. However the assembly version was not incremented and remained v1.0.4.0. While this would not affect the product functionality it was a mistake and it is corrected now.

The new repackaged version v1.0.6.0 just has been published on NuGet.

Thank you for reporting this problem.

It was a
