### ISSUE TITLE
BuildEval() and Eval() missing

### ISSUE THREAD

**Issue by halittiryaki** [oleg-shilo/cs-script#133]
Hello,

I'm missing the `BuildEval()` and `Eval()` functions under `CSScript`. They are still in the docs but no more available in the lib?

**Comment by oleg-shilo** [comment]
This API has been deprecated and mentioning it in the documentation is a mistake. Will be corrected in the next release.

Could you please assis me with the fix by providing the link to the inaccurate documentation content?

Txs

**Comment by oleg-shilo** [comment]
You can use `LoadMethod` AP instead of the deprecated one:
```C#
dynamic script = CSScript.RoslynEvaluator
                         .LoadMethod(@"void Hello()
                                       {
                                           Console.WriteLine(""Hello World!"");
                                       }");
script.Hello();
```

Or with legacy API:

```C#
var product = CSScript.CreateFunc<int>(@"int Product(int a, int b)
                                         {
                                             return a * b;
                                         }");
int result = product(3, 4);
```

**Comment by halittiryaki** [comment]
> Could you please assis me with the fix by providing the link to the inaccurate documentation content?

I ve found some on the old dox site:
- [here](http://www.csscript.net/help/script_hosting_guideline_.html)
- [here](http://www.csscript.net/help/evaluator.html)

but obviously also some in the examples repo, [1 here](https://github.com/oleg-shilo/cs-script/blob/master/Source/deployment/samples/Hosting/HostingScenarios.cs) (containing also `Run()` calls)

> You can use LoadMethod AP instead of the deprecated one:

thx. Already saw that approaches, which not do not suite for my needs though. I'm in need for a real scripting engine. In my scenario, I know the method and the arguments to pass on runtime. 

I could write some helpers as work arounds for that, but then I would face the limitation that my previously loaded Classes, Objects,.. are not available in the Eval context. In case of the current cs-script implementation, this would mean I have to keep track of dyn. built assemblies and continuously chain them to next assembly being generated, etc.. .

Also I couldnt load an interface alone, as it expects it to be a class and tries to auto create an instance.

**Comment by oleg-shilo** [comment]
As for 
> I ve found some on the old dox site:
    here
    here

Thank you, The first article is OK as it is stated that the article demonstrates no longer recommended technique.  But I will update it anyway.

But the second aricle is completely valid as it describes the current evaluator model.
