### ISSUE TITLE
UnauthorizedAccessException when running on Android using Unity.

### ISSUE THREAD

**Issue by asusralis** [oleg-shilo/cs-script#135]
Works when running on PC, but when built to Android it throws this exception when trying to load code: 

2-17 04:12:38.889 19090 19106 E Unity   : UnauthorizedAccessException: Access to the path "/tmp" is denied.
12-17 04:12:38.889 19090 19106 E Unity   :   at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x0005e] in <f2e6809acb14476a81f399aeb800f8f2>:0
12-17 04:12:38.889 19090 19106 E Unity   :   at System.IO.Directory.CreateDirectory (System.String path) [0x0008f] in <f2e6809acb14476a81f399aeb800f8f2>:0
12-17 04:12:38.889 19090 19106 E Unity   :   at System.IO.DirectoryInfo.Create () [0x00000] in <f2e6809acb14476a81f399aeb800f8f2>:0
12-17 04:12:38.889 19090 19106 E Unity   :   at (wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.Create()
12-17 04:12:38.889 19090 19106 E Unity   :   at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x00036] in <f2e6809acb14476a81f399aeb800f8f2>:0
12-17 04:12:38.889 19090 19106 E Unity   :   at System.IO.Directory.CreateDirectory (System.String path) [0x0008f] in <f2e6809acb14476a81f399aeb800f8f2>:0
12-17 04:12:38.889 19090 19106 E Unity   :   at csscript.CSExecutor.GetScriptTempDir () [0x0003d] in <41062a0058f34fd19baea8490c719ead>:0
12-17 04:12:38.889 19090 19106 E Unity   :   at csscript.CSExecutor.GetScriptTempFile (System.String subDir) [0x00015] in <41062a0058f34fd19baea8490c719ead>:0
12-17 04:12:38.889 19090 19106 E Unity   :   at CSScriptLibrary.CSScript.LoadCode (System.String scriptText, System.String tempFileExtension, System.S

`GameEvent script = (GameEvent)CSScript.LoadCode(serializedEvent.Script)
                .CreateInstance(serializedEvent.Data.Name.Replace(" ", ""));`

**Comment by oleg-shilo** [comment]
Never tested it on Android, but judging from the exception stack your host app needs to have access to the `/tmp` folder.

Though even if you grant the access right you may find that the compiler services are not available on Android. Just don't know if the required services are available on Android.
