### ISSUE TITLE
Auto-completion is not working for a custom dll's object

### ISSUE THREAD

**Issue by sadasd1** [oleg-shilo/cs-script#140]
Hi,
I am trying to use my c# .NET dlls in my cs script and instantiating object for them. The problem I see is for one of my object, not able to see auto completion. More details follows: As shown in the below screenshot, I have two objects device and ntlLocal. I could access all the methods from device whereas with ntlLocal I couldn't.
![image](https://user-images.githubusercontent.com/25536966/51344088-e1926e80-1a65-11e9-94fa-598d60d29724.png)
![image](https://user-images.githubusercontent.com/25536966/51344329-61b8d400-1a66-11e9-8d4b-5891e9b83853.png)
![image](https://user-images.githubusercontent.com/25536966/51344401-8f058200-1a66-11e9-88dc-b04454f23b90.png)

**Comment by oleg-shilo** [comment]
I am glad you have attached the screenshot.
You will be surprised to learn that the autocompletion you see is not CS-Script autocompletion. :)

It is an ambitious but inferior Notepad++ native autocompletion that ist poped up before C_Script has a chance to show its own. Basically Notepad++ disabling CS-Script autocompletion.

The solution is to disable Notepad++ native autocompletion and allow CS-Script to do its job. 

This article describes how to do that: https://github.com/oleg-shilo/cs-script.npp/wiki/Dealing-with-Notepad%E2%80%A0%E2%80%A0-native-auto-complete.

If you have further issues with CS-Script for Notepad++ you may prefer to log them against the dedicated project: https://github.com/oleg-shilo/cs-script.npp
