### ISSUE TITLE
IEvaluator doesn't appear to process css_import statements

### ISSUE THREAD

**Issue by Kittyfisto** [oleg-shilo/cs-script#141]
I'm using CSScript to execute some scripts, but I cannot get css_include to work. Given the following sample application:

*Program.cs*:
```using System.IO;
using CSScriptLibrary;

namespace CsscriptTest
{
	class Program
	{
		static void Main(string[] args)
		{
			var code = File.ReadAllText(@"..\..\Test.cs");
			dynamic script = CSScript.Evaluator.LoadCode(code);
			script.Main();
		}
	}
}
```

*Test.cs*:
```
//css_import Foo.cs

namespace MyScript
{
	public class Test
	{
		public void Main()
		{
			Foo.Bar();
		}
	}
}
```

and *Foo.cs* (in the same folder as Foo.cs):

```
using System;

namespace MyScript
{
	public class Foo
	{
		public static void Bar()
		{
			Console.WriteLine("Hello, World!");
		}
	}
}
```

I get the following exception:

> Unhandled Exception: csscript.CompilerException: (9,4): error CS0103: The name `Foo' does not exist in the current context
   at CSScriptLibrary.MonoEvaluator.HandleCompilingErrors(Action action)
   at CSScriptLibrary.MonoEvaluator.CompileCode(String scriptText)
   at CSScriptLibrary.MonoEvaluator.LoadCode(String scriptText, Object[] args)
   at CsscriptTest.Program.Main(String[] args) in <...>Program.cs:line 11

I've read the documentation related to script hosting and script importing, but didn't find a concrete passage as to whether or not that's even possible with an IEvaluator.

*edit*
If this isn't supposed to work, what are my options to host scripts and to share code between different scripts?

*edit2*
I'm using CS-Script v3.28.7, targeting net461.

**Comment by oleg-shilo** [comment]
This is the limitation of both Roslyn and Mono evaluators. They can only work with a single source code module at the time.

Though if you are using CodeDom evaluator then you don't have this limitation.

**Comment by oleg-shilo** [comment]
I will review the documentation and ensure the limitation is described.
Txs

BTW you can also use
```C#
CSScript.Evaluator.LoadFile(@"..\..\Test.cs")
```

**Comment by Kittyfisto** [comment]
Thanks for clearing that up. I must have missed that while reading the documentation. I'll give the CodeDom evaluator a try.

Speaking of documentation, I think there's a copy & paste mistake regarding the CSScript.RoslynEvaluator and CSScript.CodeDomEvaluator properties. Both claim to wrap around Roslyng. The same goes for the documentation of the CodeDomEvaluator itself.

**Comment by oleg-shilo** [comment]
Most likely you haven't missed that bit in the documentation. It simply was not clearly expressed. Hopefully it is addressed now.

With regards to "CSScript.RoslynEvaluator and CSScript.CodeDomEvaluator properties". They indeed have the same properties since they implement the same interface. Did you mean something else?

**Comment by Kittyfisto** [comment]
I meant that their **documentation** is identical. I would presume that the CodeDomEvaluator does not have anything to do with roslyn, yet its comment states:

```
	//
	// Summary:
	//     A wrapper class that encapsulates the functionality of the Roslyn evaluator (Microsoft.CodeAnalysis.CSharp.Scripting).
	public class CodeDomEvaluator : IEvaluator
```

**Comment by oleg-shilo** [comment]
You are right. This comment needs to be changed. Txs
