### ISSUE TITLE
COM tutorial: interop.zip corrumpted

### ISSUE THREAD

**Issue by burque505** [oleg-shilo/cs-script#142]
Hello, thank you for the great program. As I'm going through the tutorials, I find that the archive at (http://www.csscript.net/help/Tutorial/interop/interop.zip) is corrupted. It can't be opened by Windows natively or by 7zip.
Thanks!

**Comment by oleg-shilo** [comment]
Thank you, I am glad you like CS-Script. :)

As for the sample you are asking about, I have tested the link you provided and it seems OK

![image](https://user-images.githubusercontent.com/16729806/52413427-b1566100-2b35-11e9-882f-ddf4b6be1e3d.png)

May be it got corrupted during the download...

**Comment by burque505** [comment]
Thank you very much for responding. The file can be opened with 7zip, though not Windows natively. The contents of Interop.cs, however, look like this (the directory listing from 7zip is just like yours, including file sizes).
![interop](https://user-images.githubusercontent.com/46876254/52423600-ad82fa00-2ab5-11e9-9501-2b11a30e8810.gif)

**Comment by oleg-shilo** [comment]
I see. Then indeed the content of that file is corrupted. 

Unfortunately all backup copies of this file that I have are also corrupted. The best chance to resorye it is just to follow the tutorial: http://www.csscript.net/help/Using_COM_tutorial.html

**Comment by burque505** [comment]
Thanks once again. I followed the tutorial ( I should have seen that interop code earlier, my apologies) but I get errors related to obsolescence. I've attached a file with the error messages.
Regards,
burque505
[interop_errors.txt](https://github.com/oleg-shilo/cs-script/files/2847851/interop_errors.txt)

**Comment by oleg-shilo** [comment]
Oh, this error is easy to fix. You see, support for COM is kind of "in low demand" so it gets easy out of sinc with the rest of the CS-Script features. In this case `CSSEnvironment.PrimaryScriptFile` has been replaced with more convenient technique (see _reflect.cs_ sample) and _com.cs_ script that is a part of COM interop is still using the old API.   

Anyway, you can fix it by commenting out the offending lines (107-108) in _com.cs_.

```C#
static string EntryScript
{
    get
    {
        if (Environment.GetEnvironmentVariable("EntryScript") != null) //standalone execution
            return Environment.GetEnvironmentVariable("EntryScript");
	// else if (CSSEnvironment.PrimaryScriptFile != null) //hosted execution 
        //     return CSSEnvironment.PrimaryScriptFile;
        else
            throw new Exception("Error: Cannot obtain the entry script path");
        }
    }
}
```

**Comment by burque505** [comment]
Thanks, that got me farther down the road. I have one last obstacle :)
![x64](https://user-images.githubusercontent.com/46876254/52534529-ec0bf500-2cff-11e9-90cd-69178cc47694.GIF)
COM interop is a high priority for me, so I hope there is a possibility. I use AutoHotkey for COM interop quite a bit - I will take a look at the old posts and possibly the AHK source code to see if there is an x64 fix that might be incorporated in CS-Script. (although it would likely require porting from C++ to C#,  I am guessing).

**Comment by oleg-shilo** [comment]
This error means that registration of the COM server dll has failed. If you have a look at _com.cs_ you will see how the registration is implemented. It's fairly simple and actually very useful for understanding/troubleshooting.

In this case it may be because the server dll is corrupted as the other files. Or because you are trying to register x32 fro x64 process. 
You can test this by trying to register the dll manually with the corresponding _regsvr32.exe_.

**Comment by burque505** [comment]
I will try that, thank you!
