### ISSUE TITLE
Code for CSSCodeProvider.v4.6 is missing

### ISSUE THREAD

**Issue by burque505** [oleg-shilo/cs-script#143]
The folder cs-script\Source\CSSCodeProvider.v4.6 contains only README.md.

**Comment by oleg-shilo** [comment]
it is a left over of the old legacy code. 
Currently the provider source is in `cs-script\Source\CSSCodeProvider.v4.6\CSSRoslynProvider`

**Comment by burque505** [comment]
Thank you very much, I appreciate the clarification. However, in the archive I downloaded on February 3, 2019, ``cs-script\Source\CSSCodeProvider.v4.6\README.md`` is the only file in that directory.

**Comment by oleg-shilo** [comment]
Sorry, I probably did not explain it well...

`CSSCodeProvider.v4.6.dll` is no longer included in CS-Script distro. The folder with the same name contains only a single readme file. This folder was a legacy source and right now it is deleted so it is no longer a part of the CS-Script codebase.

The same provider is now implemented as `CSSRoslynProvider.dll` and it is a part of CS-Script codebase and it is distributed with CS-Script. Its source is available at [`cs-script\Source\CSSRoslynProvider`](https://github.com/oleg-shilo/cs-script/tree/master/Source/CSSRoslynProvider)

**Comment by burque505** [comment]
Ah, now I understand, thank you. I do of course have CSSRoslynProvider.
Regards,
burque505
