### ISSUE TITLE
GetMethodInvoker doesn't like methods with string[] params

### ISSUE THREAD

**Issue by brettgman** [oleg-shilo/cs-script#144]
Hello.  I'm having trouble evaluating cs-script.  Here's my code that calls the script:

            AsmHelper helper = new AsmHelper(CSScript.LoadFile(@"cs-scripts\Test.cs"));
            var param = new string[] { "test" };
            var method = helper.GetMethodInvoker("MyApp.Test.MyMethod", param);
            var val = method(null, param);

Here's the script:

namespace MyApp
{
    public class Test
    {
        public static int MyMethod(string[] parms)
        {
            return 1;
        }
    }
}

When helper.GetMethodInvoker is called I get this error below.  But it works with other param types, eg. int[], string, etc.

    {"Method MyApp.Test.MyMethod(System.String) cannot be found."}

**Comment by oleg-shilo** [comment]
Yes, it is a limitation of the method invoker, which is no longer a recommended approach. Today you have much better options (e.g. using interfaces, true duck typing, dynamic). 

Though if you prefer `AsmHelper` you can still use it. You'll just need to typecast your array to `object`.

```C#
var helper = new AsmHelper(CSScript.LoadFile(@"cs-scripts\Test.cs"));
object param = new string[] { "test" };
var method = helper.GetMethodInvoker("MyApp.Test.MyMethod", param);
var val = method(null, param);
```

And with _dynamic_ your code can be something like this:

_script (note the method is no longer static)_
```C#
namespace MyApp
{
    public class Test
    {
        public int MyMethod(string[] parms)
        {
            return 1;
        }
    }
}
```
_host_
```C#
dynamic test = CSScript.Load(@"cs-scripts\Test.cs").CreateObject("*");
int result = test.MyMethod(new [] { "test" });
```

**Comment by brettgman** [comment]
Thanks, I'm using interfaces with no troubles
