### ISSUE TITLE
Ctrl + C does not cause finalizer/destructor to fire

### ISSUE THREAD

**Issue by bddogcatball** [oleg-shilo/cs-script#147]
If I execute a C# script containing a class with an infinite loop (strictly for testing Ctrl+C purpose) and break it using Ctrl + C, the destructor of MyClass does not appear to execute.  Should it?  If not, could I code it differently to ensure it executes upon Ctrl + C?

public class MyClass
{
  public MyClass()
  {
     Console.WriteLine( "in constructor");
  }
  ~MyClass()
 {
   Console.WriteLine( "in destructor" );
 }

  public void Infinite()
  {
    while( true ) {}
  }
}

new MyClass().Infinite()

**Comment by oleg-shilo** [comment]
This is rather a .NET question as it has nothing to do with CS-Script or even scripting.

`Crtl+C` is a forceful way of terminating an application. Thus you give no chance to the application to exit gracefully. IE do proper garbage collection.  A simple console app below will never call finalizer on `Ctrl+C`  

```C#
class Program
{
    static void Main(string[] args)
    {
        var t = new test();
        for (int i = 0; i < 10; i++)
            Thread.Sleep(1000);
    }
}

class test
{
    ~test()
    {
        Console.WriteLine("!!!");
    }
}
```

If you indeed need to handle `Ctrl+C` then you need to use interop:
```C#
  [DllImport("Kernel32")]
  private static extern bool SetConsoleCtrlHandler(EventHandler handler, bool add);

```

**Comment by bddogcatball** [comment]
Thank you for your helpful response
