### ISSUE TITLE
Just a hint

### ISSUE THREAD

**Issue by haftado3** [oleg-shilo/cs-script#148]
pls add Evaluator object creating to documentaion i was looking for this , for 1 hour
```
        public static Assembly Load_CS_Code(String cod)
        {
            //CodeDomEvaluator e1 = new CodeDomEvaluator();
            MonoEvaluator e1 = new MonoEvaluator();
            //var e1 = CSScript.Evaluator;
            e1.Reset(true);
            e1.ReferenceAssemblyByName("System.Data");
            Assembly d1 = e1.CompileCode(cod);
            return d1;
        }
```

**Comment by oleg-shilo** [comment]
The intended use of  CS-Script.Evauator API is fully captured (~100% coverage) in the 3 code sample files that are installed alongside with the NuGet package `cs-script`. 

Additionally it is described on Wiki: https://github.com/oleg-shilo/cs-script/wiki/Hosted-Script-Execution
See the whole article as well as the "https://github.com/oleg-shilo/cs-script/wiki/Hosted-Script-Execution" section.

You can also access the samples online: https://github.com/oleg-shilo/cs-script/blob/master/Source/NuGet/content/net46/Scripting.evaluator.cs

About your code sample... Unfortunately it is not entirely optimized use of cs-script API. 
The code below shows the preferred technique:
```C#
Assembly script = CSScript.MonoEvaluator
                          .ReferenceAssemblyByName("System.Data")
                          .CompileCode(cod);
```

**Comment by haftado3** [comment]
Can I Debug Dynamically loaded cs code? what is correct way to do this ?

**Comment by oleg-shilo** [comment]
You will need to ensure the debug symbols are generated for your script:
```C#
CSScript.EvaluatorConfig.DebugBuild = true;
```
It will not work for `MonoEvaluator` though as Mono compiler-as-service has a bug - it does not support debug builds. You will either need to call RoslynEvaluator directly ar have it configured globally:

```C#   
CSScript.EvaluatorConfig.DebugBuild = true;

dynamic script = CSScript.RoslynEvaluator
                         .ReferenceAssembly("System.ValueTuple")
                         .LoadMethod(@"void Hello()
                                       {
                                           (int count, double sum) Test()
                                           {
                                               Console.WriteLine(""Local method..."");
                                               return (1, 2);
                                            }

                                           var t = Test();
                                           Console.WriteLine(""Hello ! - ""+t.count);
                                       }");
script.Hello(); // F11 here
```

Or 

```C#
CSScript.EvaluatorConfig.DebugBuild = true;
CSScript.EvaluatorConfig.Engine = EvaluatorEngine.Roslyn;

dynamic script = CSScript.Evaluator
                         .ReferenceAssembly("System.ValueTuple")
. . .
```

**Comment by haftado3** [comment]
ty dude 
what about debugging this:
`method.Invoke(obj, parameters)`

**Comment by haftado3** [comment]
never mind its working like a charm

**Comment by haftado3** [comment]
but there is no RoslynEvaluator and Evaluator returns null for it

**Comment by oleg-shilo** [comment]
I am not sure I follow. If you add NuGet `cs-script` or `cs-script.bin` then you will have RoslynEvaluator: 

![image](https://user-images.githubusercontent.com/16729806/54070217-52f5dd00-42b1-11e9-9bb1-00033f17d5b7.png)

You can also change the global config to point `CSScript.Evaluator` to Roslyn evaluator:

![image](https://user-images.githubusercontent.com/16729806/54070209-3d80b300-42b1-11e9-9309-38c5cb05460c.png)

**Comment by haftado3** [comment]
i am not using NuGet, because my .net version is 4 . i am using source v4 .i add cssroslynprovider project too but there is no namespace in that class i am not sure how it is going to work!

**Comment by haftado3** [comment]
![Untitled](https://user-images.githubusercontent.com/8863902/54070995-73f00b00-427c-11e9-8007-e25a9c3b9f61.png)

**Comment by haftado3** [comment]
![qweqwe](https://user-images.githubusercontent.com/8863902/54071003-89653500-427c-11e9-8468-7e560bc2c551.png)

**Comment by oleg-shilo** [comment]
> i am not using NuGet...

Then probably we should have started from that...

You are expected to use NuGet package as it has all dependencies that you need.

If you cannot use the latest .net version then you cannot use Roslyn. Roslyn is not available for v4.0. This also means that you cannot use any of NuGet packages.

Then I suggest you get CSSCriptLibrary.dll from any nuget package and add this assembly manually to your v4.0 project.

After that you will need to choose appropriate compilation engine. Roslyn, as we have established, cannot be used. Mono can but it has a bug - no support for debugging. Then the only choice is CodeDom: 

```C#
using System.Threading.Tasks;
using CSScriptLibrary;

class Program
{
    static void Main(string[] args)
    {
        CSScript.EvaluatorConfig.DebugBuild = true;
        CSScript.EvaluatorConfig.Engine = EvaluatorEngine.CodeDom;

        dynamic script = CSScript.Evaluator
                                 .LoadMethod(@"void Hello()
                                               {
                                                   Console.WriteLine(""Hello ! - v4"");
                                               }");

        script.Hello(); // F11 here
    }
}
```

This will work but of course you will be limited to C#5 syntax in your scripts. What is expected as you are using .NET v4.0 host anyway.

**Comment by haftado3** [comment]
i forget to mention its 4.5.2 not 4.0

**Comment by oleg-shilo** [comment]
You will still have problems with Roslyn. Since you have no freedom of upgrading to Roslyn compatible CLR you will have to use CodeDom. 
It's a small price to pay...
