### ISSUE TITLE
Suggesting to normalize paths in CompilingInfo.Input

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#149]
After compilation, `CSScript.LastCompilingResult` holds all the details about the last compilation. When debugging a assembly/reference related issue, I saw that `CompilingInfo.Input` contains somewhat strangly formatted paths:

        C:\<MyWork>\<MyProject>\.\Bin\Debug\<MyAssembly>.dll
        C:\Windows\assembly\GAC_MSIL\System.Xml.resources\2.0.0.0_de_b77a5c561934e089\System.Xml.resources.dll
        ...

The **\<MyProject>\\.\Bin\Debug\\** is a result of the `//css_reference .\Bin\Debug\<MyAssembly>.dll` in my script. When I write `//css_reference Bin\Debug\<MyAssembly>.dll` the path will properly be identified as:

        C:\<MyWork>\<MyProject>\Bin\Debug\<MyAssembly>.dll
        C:\Windows\assembly\GAC_MSIL\System.Xml.resources\2.0.0.0_de_b77a5c561934e089\System.Xml.resources.dll
        ...

From a script's perspective, the preceding `.\` does make things more obvious. But when looking at the absolute paths in the `CompilingInfo.Input.ReferencedAssemblies` the additional `.\` seems strange. Therefore, I am suggesting to normalize the paths in `CompilingInfo.Input.EmbeddedResources`, `CompilingInfo.Input.LinkedResources`, `CompilingInfo.Input.ReferencedAssemblies`,... before passing it on to the compiler.

**Comment by oleg-shilo** [comment]
`.\` denotes a current directory thus there is nothing wrong with the path `C:\<MyWork>\<MyProject>\.\Bin\Debug\<MyAssembly>.dll`.

To be honest I am struggling to see any benefit in hiding/or showing the fact that the user referenced assembly with the `.\` reading prefix. Kind of no usability value...

Even though, when I tested it in my case it showed the path fully expanded:
![image](https://user-images.githubusercontent.com/16729806/54072127-6d888000-42ca-11e9-9a0a-cc140539a050.png)

**Comment by maettu-this** [comment]
Benefit? What I ran into last week: Something not working as expected, having to debug quite deep into CSScript, suspecting that issue could be caused by an erroneous dealing with relative paths. After all, we have had several issues with paths (#26, #44, #71, #82, #83). Of course I hope that everything now perfectly works, but one can never know. So I try to rule out every potential source of error.

Observations in my case:

- `ScriptParser.Init()` line 777 `foreach (string asmName in mainFile.ReferencedAssemblies)` does contain the strange looking path identification: "asmName = "C:\\<MyWork\>\\<MyProject\>\\.\Bin\\Debug\\<MyAssembly\>.dll"
  - `CSScript.InitExecuteOptions()` line 1256 `options.searchDirs` is still OK.
  - `CSExecutor.Compile()` line 1614 `if (options.searchDirs.Length == 0)` is still OK.
  - `FileParser.ProcessFile()` line 243 `this.parser = new CSharpParser(fileName, true, null, this.searchDirs);` is OK on invocation but then first shows the issue.
    - `CSharpParser.ctor` line 457 is still OK.
    - `statement` at `Utils.NormaliseAsDirectiveOf` line 133 correctly contains relative path, e.g. ".\Bin\\Debug\\<MyAssembly\>.dll""
    - But after line 136 `text = Path.Combine(Path.GetDirectoryName(parentScript), text);` the strangly looking path appears as "C:\\<MyWork\>\\<MyProject\>\\.\Bin\\Debug\\<MyAssembly\>.dll"

Potential locations to normalize the paths:

- `Utils.NormaliseAsDirectiveOf()`
- `ScriptParser.Init()`
- `CSExecutor.AggregateReferencedAssemblies()`
- `CSExecutor.NormalizeGacAssemblyPath()` => `CSExecutor.NormalizeAssemblyPath()`

**Comment by oleg-shilo** [comment]
When I questioned benefits I assumed that the value with the "strange looking path" is a valid path. Thus the way it looks has no practical value simply because it is a valid path and it points to the right location. The code below illustrates the point:

```C#
var p1 = Path.GetFullPath(@"c:\temp\.\test.txt");
var p2 = Path.GetFullPath(@"c:\temp\test.txt");
var same = (p1 == p2); // it is always 'true'
``` 
However if the value you are referring to is in fact **invalid** then it is no longer about the benefits but about fixing the defective behavior. Thus my first question is "Is the path value valid or not?".

Now, the second part. Even if a feature bears small benefit it is still reasonable to implement depending on the associated effort. And in order to assess the effort I need to reproduce the problem.

In my prev post I provided the sample that exhibits no problems even though dot-based references were used. Can you please provide a simple test case that shows the problem? It would really help.

**Comment by maettu-this** [comment]
Finally, finally I am able to get back to this, sorry for the inactivity.
(Soon after initially working on this I got distracted with a high prio task...)

Attached find a ScriptHost which demonstrates the issue. The project is based on the CSScript source code, so you may directly debug in there. The folder structure is 1:1 what I use in my hosting application project, never mind the additional folder depth.

1. Download [CSScript_Issue_149.zip](https://github.com/oleg-shilo/cs-script/files/3047833/CSScript_Issue_149.zip) and unzip
2. Open the "\cs-script\CSScriptHostingTest\CSScriptHostingTest.sln" solution in VS2015 or above
3. Select [ScriptHost] as [StartUp Project]
4. [Debug > Start]
5. [Select]
6. Browse to "\Scripts\Issue_149\SomeFolder" and select "SomeAssemblyToReference.cs"
7. [Build]
    => "\Scripts\Issue_149\SomeFolder\SomeAssemblyToReference.dll" gets created.
8. [Select]
9. Browse to "\Scripts\Issue_149" and select "Script.cs"
10. [Build]
    => "\Scripts\Issue_149\Script.dll" gets created.
11. [Run]
    => The [Script Output] will show the probing dirs. In my case, the second last line as shown below contains the non-normalized `\.\`.
12. [Close]

`Script #2:  > <MyWorkspace>\CSScriptHostingTest\Scripts\Issue_149\Issue_149\.\SomeFolder`

**Comment by oleg-shilo** [comment]
OK. Txs. Now, after I can reproduce it the fix is simple. It is in fact is done and waiting for the release. 
If you want to use it immediately you can just change the `utils.cs(136)` as below:
```c#
135:    if (text.Length > 1 && (text[0] == '.' && text[1] != '.')) //just a single-dot start dir
136:        text = Path.GetFullPath(Path.Combine(Path.GetDirectoryName(parentScript), text));
```

**Comment by maettu-this** [comment]
Thanks!
