### ISSUE TITLE
Cannot process NuGet package

### ISSUE THREAD

**Issue by SergGrey** [oleg-shilo/cs-script#152]
Hello, I use the program RutonyChat, which uses cs-script version 3.19. When using the program, I had a problem with the inability to connect the nugetpackage. When I try to use "// css_nuget Discord.Net", I get the error "Cannot process NuGet package 'Discord.Net'". What could be the problem? The author of the program does not want to update the version of the cs-script, due to some compatibility problems. My knowledge is not enough to identify the problem. But I found an empty folder "C: \ ProgramData \ CS-Script \ nuget", but I did not find where the "nuget.exe" might be located. Can you help with this problem?

**Comment by oleg-shilo** [comment]
It looks like there is something wrong with the nuget downloading your package.

Try this in command promp:

```
nuget install Discord.Net  -OutputDirectory C:\ProgramData\CS-Script\nuget\Discord.Net
```

If this succeeds then cs-script will skip downloading the package and just compile the script against already downloaded assemblies.

**Comment by SergGrey** [comment]
Thank you very much, the problem has been fixed. I hope there will be no more problems
