### ISSUE TITLE
Install nuget package

### ISSUE THREAD

**Issue by SergGrey** [oleg-shilo/cs-script#153]
Recently, I wrote here about my problem with the inability to install a nuget package via the // css_nuget command and you helped me. But there was another problem. Simple nuget packages are installed easily and without problems, but with complex, which are not similar to other nuget packages, problems arise. All necessary nuget packages are downloaded to the folder with the nuget package that we installed.
![image](https://user-images.githubusercontent.com/30808171/55942979-49fc8080-5c4e-11e9-8d11-7419ac1a96a3.png)
Although they are installed, the nuget package does not see them. Connecting and installing each nuget package manually does not help.
![image](https://user-images.githubusercontent.com/30808171/55942370-ecb3ff80-5c4c-11e9-9b80-98e81cafab53.png)
Code:
//css_nuget Discord.Net
using Discord;
Error:
(Original)error CS0246: Не удалось найти имя типа или пространства имен "Discord" (пропущена директива using или ссылка на сборку?)
(Translated)error CS0246: The type or namespace name 'Discord' could not be found (are you missing a using directive or an assembly reference?)

**Comment by oleg-shilo** [comment]
You are right. the default auto referencing behavior of `//css_nuget` directive cannot cope with very complex nested packages. Tht's why you may need to reference the required package assemblies explicitly.

Thus you may suppress auto referencing with `-noref` argument:
```
-noref         - switch for individual packages if automatic referencing isn't desired.
                 You can use 'css_nuget' environment variable for further referencing package content (e.g. //css_dir
                 %css_nuget%\WixSharp\**)
```
However.... a simple test in Notepad++ and command prompt reviled that in this case `//css_nuget` seems to work just fine:

![image](https://user-images.githubusercontent.com/16729806/55957035-b0ae8800-5ca8-11e9-95dd-f6ba5a7b43a8.png)

![image](https://user-images.githubusercontent.com/16729806/55956958-7e048f80-5ca8-11e9-955a-a5c0df643deb.png)

**Comment by SergGrey** [comment]
I tried, but when I connect via "// css_ref C: \ ProgramData \ CS-Script \ nuget \ Discord.Net \ Discord.Net.Webhook.2.0.1 \ lib \ netstandard1.3 \ Discord.Net.Webhook.dll "and trying to use something from the namespace Discord.WebSocket, then I get an error:
(Original) error CS1705: Сборка "Discord.Net.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null" использует "System.Interactive.Async, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263" более поздней версии, чем сборка "System.Interactive.Async, Version=3.0.1000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263", на которую дается ссылка
(Translated) error CS1705: Assembly "Discord.Net.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null" uses 
"System.Interactive.Async, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263" 
which has a higher version than referenced assembly
"System.Interactive.Async, Version=3.0.1000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263"

**Comment by oleg-shilo** [comment]
Can you please provide a code sample that shows the problem?
Txs

**Comment by SergGrey** [comment]
`//css_nuget Discord.Net
//css_ref C:\ProgramData\CS-Script\nuget\Discord.Net\Discord.Net.Core.2.0.1\lib\netstandard1.3\Discord.Net.Core.dll
//css_ref C:\ProgramData\CS-Script\nuget\Discord.Net\Discord.Net.WebSocket.2.0.1\lib\netstandard1.3\Discord.Net.WebSocket.dll
//css_ref C:\ProgramData\CS-Script\nuget\Discord.Net\Discord.Net.Webhook.2.0.1\lib\netstandard1.3\Discord.Net.Webhook.dll
//css_ref C:\ProgramData\CS-Script\nuget\Discord.Net\Discord.Net.Rest.2.0.1\lib\netstandard1.3\Discord.Net.Rest.dll
using System;
using System.Collections.Generic;
using System.Threading;
using System.Runtime.InteropServices;
using System.Speech.Synthesis;
using System.Collections;
using System.IO;
using System.Net.Sockets;
using System.Xml;
using System.Text;
using System.Linq;
using System.Collections.Concurrent;
using System.Threading.Tasks;
using System.Text.RegularExpressions;
using Discord;
using Discord.API;
using Discord.Audio;
using Discord.Commands;
using Discord.Net;
using Discord.Rest;
using Discord.Webhook;
using Discord.WebSocket;
namespace RutonyChat
{
    public class Script
    {
        private async Task MessageReceived(SocketMessage message)
        {
            if (message.Content == "!ping")
            {
                await message.Channel.SendMessageAsync("Pong!");
            }
        }`

**Comment by oleg-shilo** [comment]
Indeed `Discord.Net` has a complicated dependency that it is hard for cs-script NuGet manager to process. 

On top of this the package has the dependency on Roslyn. Meaning one has to use full Roslyn friendly distros like CS-Script full or CS-Script.Core. 

I have aggregated the all required assemblies with VS nuget manager and packed them in the attached test case. You can run the included script by executing `run.cmd`.

I am planing to revisit nuget manager in the next release or so and quite possible some improvement can be maid. But right now is referencing previously downloaded packages the simplest solution:

```C#
//css_inc refs.cs
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Sockets;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using Discord;
using Discord.API;
using Discord.Audio;
using Discord.Commands;
using Discord.Net;
using Discord.Rest;
using Discord.Webhook;
using Discord.WebSocket;

class Script
{
    static void Main(string[] args)
    {
        Console.WriteLine("> " + typeof(SocketMessage));
    }

    private async Task MessageReceived(SocketMessage message)
    {
        if (message.Content == "!ping")
        {
            await message.Channel.SendMessageAsync("Pong!");
        }
    }
}
```

[New Script11.zip](https://github.com/oleg-shilo/cs-script/files/3077306/New.Script11.zip)

Thank you

**Comment by SergGrey** [comment]
When I try to run this code, I get the error "Could not load the file or assembly 'Discord.Net.WebSocket, Version = 2.0.1.0, Culture = neutral, PublicKeyToken = null' or one of its dependencies. The system cannot find the file specified. "
```
//css_dir D:\Program Files (x86)\Steam\steamapps\common\RutonyChat\scripts
//css_ref Discord.Net.Commands.dll
//css_ref Discord.Net.Core.dll
//css_ref Discord.Net.Rest.dll
//css_ref Discord.Net.Webhook.dll
//css_ref Discord.Net.WebSocket.dll
//css_ref Microsoft.Extensions.DependencyInjection.Abstractions.dll
//css_ref Microsoft.Extensions.DependencyInjection.dll
//css_ref Microsoft.Win32.Primitives.dll
//css_ref Newtonsoft.Json.dll
//css_ref System.AppContext.dll
//css_ref System.Collections.Immutable.dll
//css_ref System.Console.dll
//css_ref System.Diagnostics.DiagnosticSource.dll
//css_ref System.Globalization.Calendars.dll
//css_ref System.Interactive.Async.dll
//css_ref System.IO.Compression.dll
//css_ref System.IO.Compression.ZipFile.dll
//css_ref System.IO.FileSystem.dll
//css_ref System.IO.FileSystem.Primitives.dll
//css_ref System.Net.Http.dll
//css_ref System.Net.Sockets.dll
//css_ref System.Runtime.InteropServices.RuntimeInformation.dll
//css_ref System.Security.Cryptography.Algorithms.dll
//css_ref System.Security.Cryptography.Encoding.dll
//css_ref System.Security.Cryptography.Primitives.dll
//css_ref System.Security.Cryptography.X509Certificates.dll
//css_ref System.Xml.ReaderWriter.dll
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Sockets;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using Discord;
using Discord.API;
using Discord.Audio;
using Discord.Commands;
using Discord.Net;
using Discord.Rest;
using Discord.Webhook;
using Discord.WebSocket;
namespace RutonyChat
{
    public class Script
    {
        public void InitParams(string param)//Runs first, after the script is compiled by the program.
        {
            new Script().MainAsync().GetAwaiter().GetResult();
        }
        private DiscordSocketClient _client;
        public async Task MainAsync()
        {
            _client = new DiscordSocketClient();

            _client.Log += Log;

            await _client.LoginAsync(TokenType.Bot,
                Environment.GetEnvironmentVariable("Test"));
            await _client.StartAsync();

            await Task.Delay(-1);
        }
        private Task Log(LogMessage msg)
        {
            Console.WriteLine(msg.ToString());
            return Task.CompletedTask;
        }
    }
}
```

**Comment by oleg-shilo** [comment]
Sorry but it is not what I wanted you to test. :)
Did you try the test sample that I shared with you?

**Comment by oleg-shilo** [comment]
As a side note...

CS-Script.Core has enhanced package dependency resolving algorithm, which in case of Discord.Net (unfortunately) does not work because of the code defect. 

However when I fixed the defect the script engine started working right away with your script. And this is without the need to configure cs-script for using Roslyn and referencing assemblies manually. A single directive `//css_nuget Discord.Net` will be sufficient.

The fix will be available in the very next CS-Script.Core release. I will also aim on porting the "package dependency resolving algorithm" into the next release of CS-Script (full).

**Comment by SergGrey** [comment]
It's a good news. But, unfortunately, the developer of the program is not going to update csscript in the near future. Citing a version conflict. Is it possible to cope with my problem without a program developer?

**Comment by oleg-shilo** [comment]
Yes it is possible. You have missed my post starting with "_Sorry but it is not what I wanted you to test_".

**Comment by SergGrey** [comment]
I apologize for my blindness. I could not run your script. I do not understand what the "cscs.exe" file is and where to get it. And in the folder with RutonyChat (the program in which I use my scripts) I found only "CSScriptLibrary", "CSSRoslynProvider" is not there.

**Comment by oleg-shilo** [comment]
OK, we need to reset this discussion. :)

1. I was under impression that you were executing stand alone scripts with the script engine executable 'cscs.exe'. This is a typical scenario of using `//css_nuget *` directive. And since MS stopped distributing C# compilers for versions higher than C#5 CS-Script distribution included Roslyn compilers for that. And the assembly that integrates Roslyn compiling services into CS-Script is called 'CSSRoslynProvider.dll'. 

2. When CS-Script is hosted by another application it is distributed in a different way - as a NuGet package. And the assembly that the package delivers is '_CSScriptLibrary.dll_'. It looks like your case. Though it was never confirmed. 

Now, for the hosted script execution using `//css_hnuget` directive is possible but more challenging. This is because the host application is always responsible for assembly probing, which is non-trivial for NuGet assemblies. 

In case of standalone execution (`#1`) _cscs.exe_ does it for you. But in case of hosted execution (`#2`) your application is responsible as _CSScriptLibrary.dll_ is not aware about your app context.

That why it is much easier if the host application aggregates the required assemblies (e.g. `Discord.Net` suite) either at runtime or during deployment and then simply references them with `//css_ref *`. Thus the user does not even have to use `//css_nuget *`

Just to illustrate this technique I have attached the sample.
[ConsoleApp1.zip](https://github.com/oleg-shilo/cs-script/files/3082372/ConsoleApp1.zip)

**Comment by SergGrey** [comment]
I apologize for my very long answer. Thanks to your help, I was able to understand what needs to be done. The solution to this problem is very simple. You need to connect the dll file through "// css_ref" and add this file to the program folder (RutonyChat). Thanks again for all the help)

**Comment by oleg-shilo** [comment]
Not a problem. I am glad you solved it. :)
