### ISSUE TITLE
System.Environment.CurrentDirectory not working correctly as of version 3.29.0.

### ISSUE THREAD

**Issue by AriyoDroid** [oleg-shilo/cs-script#154]
Using cs-script v3.29.0 - It seems that 'System.Environment.CurrentDirectory' returns the location were the actual .cs file is at instead of what the system setting is. The issue was tested on both the default compiler and Roslyn compiler but the problem persists.

This issue is not appearing on v3.27.1.0 and it was behaving correctly then.

**Comment by oleg-shilo** [comment]
The current_dir management is critical for assembly and script probing, which are typically expressed with relative paths with respect to the script file directory.   

The default behavior is to set the current_dir to the parent dir of the script being executed. This behavior is controlled by the `-l` CLI argument and it is enabled by default starting from [v3.28.5.0](https://github.com/oleg-shilo/cs-script/releases/tag/v3.28.5.0). 

If you don't to disable this behavior you will need to to pass `-l:0` switch when executing your scripts. You can do it by one of this options:
- Pass this argument from CLI
  `cscs -l:0 script.cs`
- Specify the switch from the script itself
  ```
  //css_args -l:0
  your script code
  ```
- Set this switch from CLI to be used globally:
  `cscs -config:set:DefaultArguments=add:-l:0`
