### ISSUE TITLE
C# files are added in VB project

### ISSUE THREAD

**Issue by HugoRoss** [oleg-shilo/cs-script#155]
When adding the NuGet package "CS-Script" to a VB-project, C# sample files are added.

I would expect that into VB translated sample files would be added instead.

Here a tested translation (in VS2017, maybe needs to be checked in older versions):
[CSScript-VB.zip](https://github.com/oleg-shilo/cs-script/files/3146022/CSScript-VB.zip)

**Comment by oleg-shilo** [comment]
Excellent. Thank you.
Will add the files in the next release package.

In a mean time you can use `cs-script.bin` package. It is identical to `cs-script` but does not include samples' files. So it will not interfere with your VB project.

**Comment by oleg-shilo** [comment]
Since NuGet specification (prior .NET Core) does not support language specific content It is not possible to add VB source files without heavy tweaking of _install.ps1_.

Thus I have added the following clause in the C# samples instead:

```
// 
// The VB.NET samples can be found here: https://github.com/oleg-shilo/cs-script/tree/master/Source/NuGet/content/vb
```
