### ISSUE TITLE
choco repository out of date: 3.15.0.0 (404 error, can't install)

### ISSUE THREAD

**Issue by jaredthirsk** [oleg-shilo/cs-script#16]
Looks like we still need 3.15.1.0 on choco.

**Comment by oleg-shilo** [comment]
Thank you. 
Done. 3.16 was on the way anyway so here we go:
https://github.com/oleg-shilo/cs-script/releases/tag/v3.16.0.0
https://chocolatey.org/packages/cs-script/3.16.0.0
