### ISSUE TITLE
Assembly is (tried to be) loaded from GAC instead of local dir

### ISSUE THREAD

**Issue by shadow1runner** [oleg-shilo/cs-script#161]
In order to reproduce, make sure that:
1. `System.Value.Tuple.dll` resides in your application's output directory
1. `System.Value.Tuple.dll` can also be found in GAC (maybe with a different version, not sure if this part is mandatory though)
* Now we start our cs-script application which loads the assembly of 1. - everything fine, but the loading of the assembly is necessary.
* Next step, we have a file watcher on any cs script files; let's assume one of these change which causes cs-script to generate a new assembly; as part of this it checks if a change in (the dependent) assemblies can be found: and indeed, it does find a change as the timestamp of 2. and 1. differ and cs-script thinks that 2. is the correct assembly, but it isn't - causing issues further on.

The problem is in `Utils.cs` in the foreach loop around line `:1982`: Because `CSExecutor.options.searchDirs` lists the global directories _first_, the `dependencyFile` is set to the global directory, but the loaded assembly resides in the (correct) local directory.

Is there are reason why you don't use `FileParser.ResolveFile` here?
We've got a PR ready illustrating the fix, which should make discussion easier. We do think that this is a legacy branch and that `FileParser` was added later than that.

**Comment by oleg-shilo** [comment]
Working on it. Thx

**Comment by oleg-shilo** [comment]
Indeed it was a flaw in the probing algorithm. Most likely residual legacy code. 
It's fixed now. The fix will be available in the very next release.

Thank you for reporting

**Comment by shadow1runner** [comment]
Thank you for the quick, answer - I will close the PR

**Comment by oleg-shilo** [comment]
Yeah, sorry I haven't process PR and just added this simple fix manually. So, yes PR needed to be closed without merging.

**Comment by shadow1runner** [comment]
@oleg-shilo sry for bothering you once more, but I just wanted to kindly ask what's your upcoming release plan for this? Thanks!

**Comment by oleg-shilo** [comment]
Done. Release v3.30.0.0
