### ISSUE TITLE
string interpolation error

### ISSUE THREAD

**Issue by haftado3** [oleg-shilo/cs-script#163]
comipling with string interpolation failed for example :
`var str = $"test {somevar}"`

**Comment by oleg-shilo** [comment]
Could you please elaborate? Are you using standalone script engine or hosting in in the app?

In any case make yourself familiar with these sections:
https://github.com/oleg-shilo/cs-script/wiki

![image](https://user-images.githubusercontent.com/16729806/58761282-df006380-8585-11e9-9dc5-cfd6445ed184.png)
