### ISSUE TITLE
Can I do "type sharing" between the host and the precompiler?

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [oleg-shilo/cs-script#164]
My purpose is that the script's content can change based on information from the host. So I thought about the C# preprocessor directives.
Let's see the host code:
```csharp
public class SomeClass {
   public static string Setting = null;
   public static void Init() {
      Setting = PullFromOutsideSource(); // for example: "SAY_HELLO"
      // run cs-script
   }
}
```
And the script:
```csharp
public class Script {
    public static void Main() {
#if SAY_HELLO
        Console.WriteLine("Hello World!");
#elif SAY_GOOD_BYE
        Console.WriteLine("Goodbye Everyone!");
#endif
    }
}
```
I tried to make a precompiler like this:
```csharp
public class Precompiler {
   public static bool Compile(ref string code, string scriptFile, bool isPrimaryScript, Hashtable context) {
      if (ThisIsTheScriptThatIWantToChange(scriptFile)) {
          code = "#define " + SomeClass.Setting + "\r\n" + code;
      }
      return true;
   }
}
```
But Cs-Script just throw Exception that it cannot not resolve SomeClass.Setting.
So is there anyway I can do this?

> Why do I not just use the traditional **if else**, isn't it easier?

Because I also want to do this for class field and property declarations, for example:
```csharp
// this can be used as a config file for every other script files
public static class Options{
#if SAY_HELLO
        static string Output = "Hello Guy!";
#elif SAY_GOOD_BYE
        static string Output = "Goodnight!";
        static int Delay = 23;
#endif
}
```

**Comment by oleg-shilo** [comment]
It is actually much easier...
Have a look at https://github.com/oleg-shilo/cs-script/wiki/Hosted-Script-Execution

```C#
using CSScriptLibrary;

namespace ConsoleApp8
{
    public class Settings
    {
        public bool VisuallyImpairedReader = false;
    }

    class Program
    {
        static void Main(string[] args)
        {
            var script_code = @"using System;
                                using ConsoleApp8;

                                public class Script
                                {
                                    public void Say(string message, Settings settings)
                                    {
                                        Console.WriteLine(settings.VisuallyImpairedReader
                                                            ? message.ToUpper()
                                                            : message);
                                    }
                                }";

            dynamic script = CSScript.Evaluator
                                     .LoadCode(script_code);

            var settings = new Settings { VisuallyImpairedReader = true };
            script.Say("Hello!", settings);
        }
    }
}}

```

**Comment by Meigyoku-Thmn** [comment]
That won't work for me. My Settings class is also in script file too.

**Comment by oleg-shilo** [comment]
You don't need to go to such drastic measures as conditional compilation. Remember, your script at runtime is nothing else but an assembly and as such it benefits the most when it is handled by using all traditional design/architectural approaches.   

Just one one script to create your `Settings` instance and simply pass it to another one. Thus you need to design your data model with shared types in mind (e.g. interfaces):

```C#
namespace Host
{
    public interface ISettings
    {
        bool VisuallyImpairedReader { get; set; }
    }

    class Program
    {
        static void Main()
        {
            var script_a_code = @"using System;
                                  using Host;

                                  public class Script
                                  {
                                      public class Settings : ISettings
                                      {
                                          public bool VisuallyImpairedReader { get; set; }
                                      }

                                      public ISettings Create()
                                          => new Settings { VisuallyImpairedReader = false };
                                  }";

            var script_b_code = @"using System;
                                  using Host;

                                  public class Script
                                  {
                                      public void Say(string message, ISettings settings)
                                      {
                                          Console.WriteLine(settings.VisuallyImpairedReader
                                                            ? message.ToUpper()
                                                            : message);
                                      }
                                  }";

            dynamic settings = CSScript.Evaluator.LoadCode(script_a_code);
            dynamic script = CSScript.Evaluator.LoadCode(script_b_code);

            ISettings data = settings.Create();
            script.Say("Hello!", data);
        }
}
```

**Comment by Meigyoku-Thmn** [comment]
Thank you for your response! But unfortunately if I go with your route, that means I have to redesign my entire code base :(

My system that I'm building, it likes a... runtime patcher, for example: there is a game written in dotnet, and I want to translate (or mod) that game, so I make a system that can check the game's checksum, then download the corresponding patch from my github repository, and I want the patch to work with some version of this game.

My system works like this: The host app will download game patch (consist of C# script files), then run it to let the patch constructs a configuration (method to hook, implement hook method, patch some method's body), then the host will run target game and apply the configuration to it. I also expose some properties, fields and methods of the host app to the patch script.

To let the patch works with many versions of the game, at first, I expose a field called "TargetVersion" (pulled from a list in the patch to match the game's checksum) to the patch. The patch can read it, yes, but in a part of the patch, I declare a lot of Type properties (for method hooking), for example:
```csharp
class Types {
   public static Type Vector2T = GameAsm.GetType("A.B.Vector2");
}
```
Let's assume that version _1_0 of the game has Vector2 class in namespace A.B, and version _1_1 of the game has Vector2 class in namespace A.B.C, if I just use the TargetVersion field, then I have to write like this:
```csharp
static class Types {
   public static Type Vector2T;
   static Types () {
      if (Host.TargetVersion == "_1_0") Vector2T = GameAsm.GetType("A.B.Vector2");
      else if (Host.TargetVersion == "_1_1") Vector2T = GameAsm.GetType("A.B.C.Vector2");
   }
}
```
Imagine writting 10 types like this, it's just too long and dense.

For now I decide to use Harmony (the library I use to patch methods of the game) to hook into the constructor of Hashtable and add TargetVersion to it's instance. So when the Compile method of Precompiler runs, "Hashtable context" will contain TargetVersion so I can use it to insert #define to the script. I think the ability to customize the context parameter for Precompiler is a nice feature to add.

**Comment by oleg-shilo** [comment]
I still believe that your problem can be solved by using traditional programming techniques. But of course if you are comfortable with your alternative solution.... then it's all that matters.
