### ISSUE TITLE
Cs-Script for VS Code Portable

### ISSUE THREAD

**Issue by mmickael** [oleg-shilo/cs-script#165]
I am using VS Code in portable mode, which places all user files and extensions under the the "VS Code Folder"/Data.  Cs-Script does not recognize the portable installation and still installs updates under "User Folder"/AppData/Code/User.  Is this an issue with VS Code or Cs-Script?  Thanks in advance.

**Comment by oleg-shilo** [comment]
It is done by CS-Script, not VSCode. I will see if portable mode can be reliably detected.
I made it into Enhancement. Will be available in the next release.

If you want to migrate the existing deployment into _portable_ then just follow these instructions:
https://code.visualstudio.com/docs/editor/portable

**Comment by oleg-shilo** [comment]
Moved to https://github.com/oleg-shilo/cs-script.vscode/issues/15
Fixed there.
