### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Tatitooo** [oleg-shilo/cs-script#166]
On evaluator.CreateDelegate when reading the code, could maybe accept 
string a = "string";
$"This type of {a}"

**Comment by oleg-shilo** [comment]
Can you elaborate?

**Comment by Tatitooo** [comment]
This code 
```
string a = "string";
Console.WriteLine($"This type of {a}");
```
will output 'This type of string', will it be possible to use this with CSScript?

**Comment by oleg-shilo** [comment]
It is possible but it needs C# 7 compiler (the default is C# 5), which MS has stop shipping with .NET installation years ago. You will need to bring it as an additional cs-script package : https://github.com/oleg-shilo/cs-script/wiki/C%23-7-support-%28hosted%29#usage---cs-scriptevaluator

Though if your hosting app is .NET Core and you are using `cs-script.core` nuget package C# 7 syntax supported out of box.
