### ISSUE TITLE
Linux，css_inc   XXXX.cs or css_import XXXX.cs   error.....

### ISSUE THREAD

**Issue by snikeguo** [oleg-shilo/cs-script#17]
run css_config.exe is error!
![qq 20161104191007](https://cloud.githubusercontent.com/assets/20830435/20003624/84fc829a-a2c2-11e6-9315-d559a953cf8e.png)
i write a cs file,name is Builder.cs,and copy Builder.cs   to inc path and lib path.
write a test.cs file:
//css_import Builder.cs
using System;
using Build.CppBuild;
namespace testDll
{
    public class host
    {
        public static void Main(String[] d)
        {
            Console.WriteLine(CppModule.Version);
            Console.ReadLine();
        }
    }
}
![qq 20161104191429](https://cloud.githubusercontent.com/assets/20830435/20003800/5e161ca8-a2c3-11e6-8773-296711b4ceae.jpg)

**Comment by oleg-shilo** [comment]
css_config.exe is a configuration console, which is relevant only for Windows. On Linux C-SCript follows the minimalistic approach and keeps very minimal deployment footprint. Thus in the majority of cases you only need a single cscs.exe file. This became particularly possible because the latest release(s) delivered all major components of the extended functionality (e.g. caching, config, validating) being embedded into cscs.exe itself.   

If you tel me what you are trying to do then may be I can guide you through but css_config shouldn't be even be brought on Linux.

**Comment by snikeguo** [comment]
@oleg-shilo i want to make a library file like build_compiler_script_tools that make be "scons",it can be save in %CSSCRIPT_DIR%\LIB,then i will write it down in the other path:

css_import Builder.cs
using System;
using Build.CppBuild;
namespace Microcontrollers
{
public class ArmMcuGccBuild
{
public static void Main(String[] d)
{
	CppBuild cc=new CppBuild();
	
	cc.AddIncludePath("/root/arm-none-eabi-gcc/include");
	cc.AddCompilerCFiles("1.c","2.c","3.c");
	cc.AddCompilerCxxFiles("a.cpp","b.cpp","c.cpp");
	cc.AddDefine("STM32F407");
	cc.AddDefine("Cortex_M4");
	cc.AddDefine("DEBUG=1");
	cc.Building();
}
}
}

**Comment by oleg-shilo** [comment]
It looks like your post is incomplete at I didn't see the question.
The only point I can comment is the location of your `builder.cs` script. Arguably include folder (%CSSCRIPT_INC%) is a better fit for the task. The idea was that user  can have a global dir defined by envvar for a system wide include directory for the all frequently used **user** scripts. And `%CSSCRIPT_DIR%\Lib` was designed for frequently used **CS-Script's** resources.

**Comment by snikeguo** [comment]
My English is bad,I come from China....
 I do not know how to express what I mean.

**Comment by oleg-shilo** [comment]
Great, I am glad you managed it. :)

**Comment by snikeguo** [comment]
OK！！！ DONE！！
![qq 20161106164139](https://cloud.githubusercontent.com/assets/20830435/20036366/beffcc24-a441-11e6-81d0-77854b0c0480.jpg)

**Comment by snikeguo** [comment]
Great, I am glad you managed it. :)
.....
It looks weird. My "great" comment above was actually posted to the next "OK! DONE!" post but it appears after the earlier "English is bad" post that makes it look like I am mocking the guy. But I am not...
-------------------------------------------------
ha ha ha ha ha ha.I know what you mean. TKX~
