### ISSUE TITLE
css_import

### ISSUE THREAD

**Issue by iamxor** [oleg-shilo/cs-script#171]
День добрый, возможно ли загрузка формы из двух файлов .cs где класс partial и имеется namespace? Здесь я упростил пример того чего я пытаюсь добиться.

string code = File.ReadAllText(Application.StartupPath + "\\app.cs", Encoding.UTF8);
CSScript.GlobalSettings.ReportDetailedErrorInfo = true;
CSScript.EvaluatorConfig.Engine = EvaluatorEngine.Roslyn;
IEvaluator evaluator = CSScript.Evaluator;
evaluator.Reset(false);
evaluator.ReferenceDomainAssemblies().ReferenceAssemblyByNamespace("System.Windows.Forms").ReferenceAssembliesFromCode(code);
dynamic script = evaluator.LoadCode(code);
script.main();

я пытаюсь у меня ничего не получается

сам файл app.cs

//css_import formMainZ.cs;
using System; 
using System.Windows.Forms;
public class Script
{
  public void main()
  {   
    formMainZ frm = new formMainZ();
  }
}

файл formMainZ.cs

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
public  class formMainZ : Form
{
  public formMainZ()
  {
  }
}

Пишет

csscript.CompilerException: '(15,5): error CS0246: The type or namespace name 'formMainZ' could not be found (are you missing a using directive or an assembly reference?)
(15,25): error CS0246: The type or namespace name 'formMainZ' could not be found (are you missing a using directive or an assembly reference?)

Что я делаю не так?

Подскажите пожалуйста

**Comment by oleg-shilo** [comment]
Unfortunately it's not possible as Roslyn (the compiler service of CS-Csript) has the design flaw which allows execution only a single source code module at the time.

Thus the only chances you have for multiscript execution is to merge the both scripts content before passing it to the engine for the compilation.

Though... if you use EvaluatorEngine.CodeDom engine then your code should work stright away. But... your C# syntax in this case will fall back to C#5. :(

**Comment by iamxor** [comment]
Thanks for the answer, i have rewriten the code:

            CSScript.EvaluatorConfig.Engine = EvaluatorEngine.Roslyn;
            string script_asm = "";
            string host_asm = Assembly.GetExecutingAssembly().Location;
            var master_script = File.ReadAllText(Application.StartupPath + "\\app.cs", Encoding.UTF8);
            script_asm = CSScript.CompileCode(master_script, host_asm);
            dynamic script = Assembly.LoadFrom(script_asm).CreateObject("*");
            script.main();

this way, so my idea is working
Thank you again

**Comment by oleg-shilo** [comment]
Glad you found the solution. :)
