### ISSUE TITLE
CsvHelper loads the wrong ValueTuple version in CSScript?

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [oleg-shilo/cs-script#172]
I use the CsvHelper to read some csv files, when I run my script on a computer with dotnet 4.6 is the highest dotnet framework version, something weird happens, this is my code:
```cs
//css_args -provider:%CSSCRIPT_DIR%\lib\CSSRoslynProvider.dll
//css_nuget CsvHelper
using CsvHelper;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Reflection;
using Microsoft.Win32;

public class GameScriptBuilder
{
   static void Main(string[] args)
   {
      Console.WriteLine($".NET Runtime Version: {Environment.Version}");
      Get45PlusFromRegistry();
      var CsvHelperName = Assembly.GetExecutingAssembly().GetReferencedAssemblies()[1];
      Console.WriteLine($"CsvHelper fullname: \n   {CsvHelperName}");
      var ValueTupleName = Assembly.Load(CsvHelperName).GetReferencedAssemblies()[4];
      Console.WriteLine($"ValueTuple fullname: \n   {ValueTupleName}");
      var ValueTupleLocation = Assembly.Load(ValueTupleName).Location;
      Console.WriteLine($"ValueTuple location: \n   {ValueTupleLocation}");
      Console.WriteLine("Try to use CsvHelper library, in which has System.ValueTuple dependency.");
      Console.WriteLine(new CsvReader((TextReader)null));
   }
   // https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed
   static void Get45PlusFromRegistry()
   {
      const string subkey = @"SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\";
      using (var ndpKey = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry32).OpenSubKey(subkey))
      {
         if (ndpKey != null && ndpKey.GetValue("Release") != null) {
            Console.WriteLine($".NET Framework Version: {CheckFor45PlusVersion((int) ndpKey.GetValue("Release"))}");
         }
         else {
            Console.WriteLine(".NET Framework Version 4.5 or later is not detected.");
         } 
      }   
      // Checking the version using >= enables forward compatibility.
      string CheckFor45PlusVersion(int releaseKey)
      {
         if (releaseKey >= 528040)
            return "4.8 or later";
         if (releaseKey >= 461808)
            return "4.7.2";
         if (releaseKey >= 461308)
            return "4.7.1";
         if (releaseKey >= 460798)
            return "4.7";
         if (releaseKey >= 394802)
            return "4.6.2";
         if (releaseKey >= 394254)
            return "4.6.1";      
         if (releaseKey >= 393295)
            return "4.6";      
         if (releaseKey >= 379893)
            return "4.5.2";      
         if (releaseKey >= 378675)
            return "4.5.1";      
         if (releaseKey >= 378389)
            return "4.5";      
         // This code should never execute. A non-null release key should mean
         // that 4.5 or later is installed.
         return "No 4.5 or later version detected";
      }
   }
}
```
The output is like this:
```
.NET Runtime Version: 4.0.30319.42000
.NET Framework Version: 4.6.2
CsvHelper fullname:
   CsvHelper, Version=12.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823
ValueTuple fullname:
   System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
ValueTuple location:
   C:\ProgramData\CS-Script\nuget\CsvHelper\System.ValueTuple.4.4.0\lib\net47\System.ValueTuple.dll
Try to use CsvHelper library, in which has System.ValueTuple dependency.
Error: Specified file could not be executed.

System.TypeLoadException: Could not load type 'System.ValueTuple`2' from assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at CsvHelper.ReadingContext..ctor(TextReader reader, Configuration configuration, Boolean leaveOpen)
   at CsvHelper.CsvReader..ctor(TextReader reader)
   at GameScriptBuilder.Main(String[] args)
```
CsvHelper in my computer decides to load the ValueTuple assembly built for dotnet 4.7 (in which doesn't have any ValueType class because dotnet 4.7 already has ValueTuple classes) instead of the correct assembly for dotnet 4.6 (in C:\ProgramData\CS-Script\nuget\CsvHelper\System.ValueTuple.4.4.0\lib\net461\System.ValueTuple.dll). 
If I manually copy net461\System.ValueTuple.dll into the same folder of my script then the script can run properly.
Is it a bug in Csscript or it's just CsvHelper bug?

**Comment by oleg-shilo** [comment]
Unfortunately it is a limitation of CS-Script package probing algorithm. By default it references the latest version of target runtime for the downloaded package. It is a limitation that is hard to avoid as with a script (in contrast to Visual Studio project) it is very difficult to specify (and determine) which version of runtime it will be running. 

The recent enhancement in `//css_nuget` allows you to specify the preferred runtime with `-rt:<runtime name>` but unfortunately this switch has no effect on dependency packages. As in your case.

I have just addressed this problem by cascading the preferred runtime to the dependency packages. The work around will be available in the very next release. You will be able to load the desired assembly with a simple `-rt` option:
```C#
//css_nuget -rt:net461 CsvHelper
```
Though this solution is not ideal as it may not help in some complicated nuget dependency cases when primary package runtime version is completely out of sync with dependency package runtime. 

For such cases the only solution is to reference the package as usual (`//css_nuget`) but suppres automatic referencing of the nuget assemblies and ref then explicitly:

```C#
//css_nuget -noref CsvHelper
//css_dir %css_nuget%\CsvHelper\**\net45
//css_dir %css_nuget%\CsvHelper\System.ValueTuple*\**\net461
//css_ref CsvHelper.dll
//css_ref System.ValueTuple.dll
. . .
``` 
The code above will work for your solution right away.

**Comment by Meigyoku-Thmn** [comment]
I think you can build CSScript CLI in a way that it contains the TargetFramework attribute, or a static field indicates the targeted framework, that way you can base on it to deduce how to choose the correct folder in nuget package.
If in Hosted script execution then just leave it for the user.

**Comment by oleg-shilo** [comment]
Not exactly. 

CS-Script CLI (cscs.exe) is built against target framework v4.5. However the target framework of the host assembly (cscs.exe) is completely irrelevant.

The problem you are experiencing is caused by the discrepancy in target frameworks of the the nuget package and its dependency package. 

Thus CsvHelper targets net45 but it depends on System.ValueTuple which targets the version of net47. Thus when referencing these packages' assemblies the host application needs to make the decision on what assembly versions to pick for what package.  The target runtime of the host is irrelevant. It can be built for net2 but run on net45. 

When you do it in VS you can control the versions for every dependency package. However with cs-script currently you can do it only for the primary package but not for the dependency.

This deficiency has been addressed and te fix will be available in the next release.

**Comment by Meigyoku-Thmn** [comment]
Yeah, after many hours, I realized I have misunderstood about target runtime of the host :( . For now it seems that this problem can only be solved from the script side. Thanks for your elaborate answer.

**Comment by oleg-shilo** [comment]
Bingo! :smile:

This is what one would do when referencing **very precisely** the package assemblies "from the script side"
```C#
//css_nuget -noref CsvHelper
//css_ref %css_nuget%\CsvHelper\CsvHelper.12.1.2\lib\net45\CsvHelper.dll
//css_ref %css_nuget%\CsvHelper\System.ValueTuple.4.4.0\lib\net461\System.ValueTuple.dll
```
The first line ensures the package is downloaded. The next two reference the two required assemblies.

And if you want to use simplified version:
```C#
//css_nuget -noref CsvHelper
//css_ref %css_nuget%\**\net45\CsvHelper.dll
//css_ref %css_nuget%\**\net461\System.ValueTuple.dll
```
