### ISSUE TITLE
C# script installation on Window10 / WSL linux does not work

### ISSUE THREAD

**Issue by tapika** [oleg-shilo/cs-script#173]
Tried to install cscs (with base of mono) to windows 10, wsl linux subsystem.
Installation goes ok, but symbolic link pinpoints incorrectly:

```
user1@laptop:/mnt/c/dev1$ ls -la /usr/local/bin/cscs
lrwxrwxrwx 1 root root 18 Aug 15  2017 /usr/local/bin/cscs -> cs-script/cscs.exe
```

Found one executable, but it does not shows .net mono version correctly.

```
/usr/local/bin/cs-script/cscs.exe
C# Script execution engine. Version 3.27.2.1.
Copyright (C) 2004-2017 Oleg Shilo. www.csscript.net (github.com/oleg-shilo/cs-script)

   CLR:             4.0.30319.42000 (.NET Framework v4.6.2 or later)
   System:          Microsoft Windows NT 6.2.9200.0
```

Should it read .NET mono or something ?

**Comment by oleg-shilo** [comment]
This is the code that pronts that output:
```
string dotNetVer = null;

if (Runtime.IsWin)
    dotNetVer = DotNetVersion.Get45PlusFromRegistry();

builder.Append(AppInfo.appLogo.TrimEnd() + " www.csscript.net (github.com/oleg-shilo/cs-script)\n");
builder.Append("\n");
builder.Append("   CLR:             " + Environment.Version + (dotNetVer != null ? " (.NET Framework v" + dotNetVer + ")" : "") + "\n");
builder.Append("   System:          " + Environment.OSVersion + "\n");

```
As you an see it never check the CLR type (.net vs mono) but instead relies on OS type (Linux vs Win).
I expected that `Runtime.IsWin` would return `false` on WSL as it does on Linux. I guess I was wrong. Meaning that you can trust only the `CLR:  x.x.x` part.

===============
Fixed. The fix will be available in the very next release. The output will be as below:

![image](https://user-images.githubusercontent.com/16729806/64535514-ce1c7680-d35a-11e9-88d3-68fe45d03172.png)

**Comment by tapika** [comment]
I guess symbolic link is also does not work out of box.
Running cscs results in nothing.

**Comment by oleg-shilo** [comment]
> I guess symbolic link is also does not work out of box...

Not exactly. Symbolic link works only works only on the systems that transparently tunnel the execution of CLR assemblies (e.g. cscs.exe, cscs) to mono so one can execute it as:
```
pc-name:~$ cscs
```

However if your OS is very raw Linux then you need to do it via mono
```
mono /usr/local/bin/cscs  
```

According the the discussion below "Good Linux distributions set this up automatically as part of the mono runtime package."
https://unix.stackexchange.com/questions/47320/how-to-set-bash-to-run-exe-with-mono

If you let me know if these tricks worked for you.
