### ISSUE TITLE
404 in Wiki

### ISSUE THREAD

**Issue by UweKeim** [oleg-shilo/cs-script#175]
On the page 

> https://github.com/oleg-shilo/cs-script/wiki/Standalone-Script-Execution

You link to many pages on csscript.net, e.g.

> http://csscript.net/Features.html

Following these links I get lots of 404 errors.

### My question

Please fix these links, I want the documention back for things like `css_ref`, `css_import`, etc.

**Comment by oleg-shilo** [comment]
Hi Uwe,

The documentation is here: https://github.com/oleg-shilo/cs-script/tree/master/docs/help-legacy

Somehow the links got broken and do not redirect to github pages. 

Will have a look.

**Comment by oleg-shilo** [comment]
OK, checked. It is actually invalid url in the wiki. Will need to check them all.

The address of the help content that you are looking for is here:
* [Legacy help pages](https://oleg-shilo.github.io/cs-script/help-legacy/root) - help content of the pre-MIT releases. Still relevant in many cases.

**Comment by oleg-shilo** [comment]
Done

**Comment by UweKeim** [comment]
Thanks a lot, Oleg!
