### ISSUE TITLE
.NET Core 3 Migration

### ISSUE THREAD

**Issue by rumen-yankov** [oleg-shilo/cs-script#176]
Hey Oleg,

During migration of our project  to .NET Core 3 , we found a strange problem related to CSScript.Evaluator. It throws TargetInvocationException. Here are details:

Message: Inner Excception -"The type initializer for 'Microsoft.CodeAnalysis.Scripting.ScriptOptions' threw an exception."} System.Exception {System.TypeInitializationException}

StackTrace: 
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at System.LazyHelper.CreateViaDefaultConstructor[T]()
   at System.Lazy`1.CreateViaDefaultConstructor()
   at System.Lazy`1.ViaConstructor()
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at CSScriptLib.CSScript.get_RoslynEvaluator()
   at CSScriptLib.CSScript.get_Evaluator()

Probably not related but, this happens on following line of code in our project
ICodeVariable scriptObject = CSScript.Evaluator.LoadCode<ICodeVariable>(sourceCode);

**Comment by rumen-yankov** [comment]
github removed part of my code: here is correction : ICodeVariable scriptObject = CSScript.Evaluator.LoadCode**<ICodeVariable>**(sourceCode);

**Comment by oleg-shilo** [comment]
Thank you, I haven't try it on .NET Core 3 yet. Quite possibly there are some types missing or assembly probing gets wrong.

Will have a look.

**Comment by rumen-yankov** [comment]
I use correct latest package. Maybe the only difference between your usage and mine that i use generic method LoadCode ( github editor clears my triangle "<" squires and content between. 

ICodeVariable scriptObject = CSScript.Evaluator.LoadCode " < " ICodeVariable " >" (sourceCode);

**Comment by rumen-yankov** [comment]
The package i use is "CS-Script.Core" Version="1.1.1"

**Comment by rumen-yankov** [comment]
`using CSScriptLib;

namespace ConsoleApp1
{
	public interface ICodeVariable
	{
		object Evaluate();
	}


	class Program
	{
		static void Main(string[] args)
		{
			ICodeVariable script = CSScript.Evaluator
						 .LoadCode<ICodeVariable>(@"using System;
									using ConsoleApp1;

                                     public class Test : ICodeVariable
                                     {
                                         public object Evaluate(){
											return ""Hello World"";
										 }
                                     }");

			var x = script.Evaluate();
		}
	}
}
`
Here is an example that throws exception on Core 3

**Comment by oleg-shilo** [comment]
> github editor clears my triangle "<" squires and content between.

You need to enclose your code in the pair of ``` lines
![image](https://user-images.githubusercontent.com/16729806/66124234-317e8900-e627-11e9-96c2-0bfbd794c7bd.png)
![image](https://user-images.githubusercontent.com/16729806/66124298-5c68dd00-e627-11e9-8136-2e80d3b95379.png)

I have fixed your message.

**Comment by oleg-shilo** [comment]
I have checked and indeed `LoadCode<T>` is broken. I have already fixed it. will make the release later today. The release will also bring targeting .NET Core 3.

**Comment by rumen-yankov** [comment]
Hey, 
I see that you released new version today. Does it include fix for the problem ? I am asking cause my code continue to throw exception after update to 1.2.2.  Excuse me being so importunate with my comments, but this problem holds release of our ERP project migrated to core 3, and several other projects based on it.

**Comment by oleg-shilo** [comment]
Yes the fix is there.
I have attached working VS project with your very sample:

[ConsoleApp6.zip](https://github.com/oleg-shilo/cs-script/files/3693142/ConsoleApp6.zip)

**Comment by oleg-shilo** [comment]
If you discover a new .NET Croe problem please report it on the CS-Script.Core page: https://github.com/oleg-shilo/cs-scrip.core

**Comment by yanglr** [comment]
> If you discover a new .NET Croe problem please report it on the CS-Script.Core page: https://github.com/oleg-shilo/cs-scrip.core

The link has a typo, should be <https://github.com/oleg-shilo/cs-script.core>.

**Comment by oleg-shilo** [comment]
Thank you @yanglr, Can you please give me details about the location of this type?

**Comment by yanglr** [comment]
@oleg-shilo
Hi, the original link missing the last "t" character in the "scrip**t**.core", finally I went to your profile page to find it.

**Comment by oleg-shilo** [comment]
:)
Where is this "original link". Where should I go to fix the typo?

**Comment by yanglr** [comment]
@oleg-shilo 
The original link I meant is <https://github.com/oleg-shilo/cs-scrip.core> you ever posted in <https://github.com/oleg-shilo/cs-script/issues/176#issuecomment-538644221>, see below screenshot.
![image](https://user-images.githubusercontent.com/3152813/108843477-b64fb580-7615-11eb-9ac4-d62e1496704d.png)

The correct link is <https://github.com/oleg-shilo/cs-script.core>. That's it.

**Comment by oleg-shilo** [comment]
Silly me, I completely misread your first post about it. 
![image](https://user-images.githubusercontent.com/16729806/108844438-3e42b900-7630-11eb-80b8-b0f1e5a9347a.png)

Updated.
Txs.

**Comment by yanglr** [comment]
It is indeed difficult to find it, I tried to access the link the first time, I got a 404. Thanks for your patience.
