### ISSUE TITLE
On the Nuget package manager, only .net 2.0 project can install it

### ISSUE THREAD

**Issue by kkle1994** [oleg-shilo/cs-script#180]
Because of the Microsoft.CodeAnalysis.CSharp.Scripting only support the .net 2.0, the nuget package installation will failed in 4.5.2. Should I use the .net 2.0 to run this?\

Thank you.

**Comment by oleg-shilo** [comment]
You probably can upgrade the "Microsoft.CodeAnalysis.CSharp.Scripting" package to whatever version that supports v4.5.2. 

Because cs-script engine itself is completely neutral to the .NET runtime. 

Try it and let me know it it worked.

**Comment by oleg-shilo** [comment]
Only now I have tested it. I am puzzled currently `Microsoft.CodeAnalysis.CSharp.Scripting` package is not available for any target platform above version 2.0. Even though I am sure I tested it before and it was fine on v4.0 at least. I an not sure if MS has changed something...

**Comment by oleg-shilo** [comment]
Mystery solved :)
It is backward, not forward incompatibility. You need to use .net 4.6 or higher. Roslyn compiler cannot be hosted on anything below v4.6.

You can still use CS-Script even on v2.0 but in this case it will be using CodeDom compiler so C# 6+ syntax will not be available. Only C# 5.

**Comment by kkle1994** [comment]
Ya! It's okay in .net framework 4.7.2, thank you so much!! :D
