### ISSUE TITLE
Roslyn Debug

### ISSUE THREAD

**Issue by Steve0212a** [oleg-shilo/cs-script#181]
Simple one here :-)

On this page (https://github.com/oleg-shilo/cs-script/wiki/Choosing-Compiler-Engine) in the table near the top, for Roslyn, you list "Debugging" as a yes.  However, at the bottom of the page, you say "The compiled scripts are in-memory assemblies. Meaning that they cannot be debugged. There is no any work around." under the disadvantages of Roslyn.

Which is it - can they or can't they be debugged?

Thanks.

**Comment by oleg-shilo** [comment]
Thank you for bringing it to my intention. The ""The compiled scripts..." section is an old content that was left there by mistake. It's corrected now.

You **can** debug with Roslyn engine. Just don't forget to enable generation of debug symbols:

```C#
CSScript.EvaluatorConfig.DebugBuild = true;
dynamic script = CSScript.RoslynEvaluator
                            .CompileMethod(@"int Sqr(int data)
                                                {
                                                    System.Diagnostics.Debugger.Break();
                                                    return data * data;
                                                }")
                                .CreateObject("*");

var result = script.Sqr(7);

```

**Comment by Steve0212a** [comment]
Great - thanks for the update!
