### ISSUE TITLE
It is possible to limit the code to namespaces (or smiliar things)

### ISSUE THREAD

**Issue by MaZyGer** [oleg-shilo/cs-script#182]
I am looking for few scripting systems like lua, js and now csharp and I want to make possible to use these in a game and maybe also with multiplayer possibility.

In lua and js I can define my own globals. So far I know it is not possible to load and make bad things. I would like to make csharp available too (or even as primary language) but I am not sure about the security.
if I make this available in a online game and they could use libraries like to delete files, they maybe could make really evil things. 

An example I made a text file and loaded it with CSScript.Load but the file contains the CSScriptLibrary but it shouldn't be allowed and give error.

So the question is: Is there any limits possible to avoid this? Or even say only this one namespace is possible? The Idea is loaded scripts which contains "**unknown**" namespaces or libaries (example System) should give an error.

**Comment by oleg-shilo** [comment]
From the code execution security CS-Script is not different to any other scripting system form. 
The security is dictated by security context of the hosting system. 

For example if Python runtime (interpreter) is hosted directly on the target system (default mode) then your script can do any damage imaginable. And if you want to restrict that you will need to place your interpreter in the sandboxed host or use sandboxing provided by your runtime. But there is nothing for code security that can be available via the script language itself.

C# scripting follows the same model. If you want to restrict some API execution from the script you will need either to host your runtime (CLR) in a sandbox or use sandboxing features offered by CLR. Thee features are CAS.

Meaning that you would need to restrict a script code execution the very same way as you would restrict the execution of a partially trusted assembly for any C# scenario of this sort. Thus your challenge is not script related abut a typical .NET scenario.

This is a simplistic example if utilizing CAS with CS-Script:
https://github.com/oleg-shilo/cs-script/blob/master/Source/deployment/samples/Sandboxing/HostSimplified.cs
