### ISSUE TITLE
Byte array initialization with RoslynEvalutor throws a MissingMethodException

### ISSUE THREAD

**Issue by Monvvv** [oleg-shilo/cs-script#183]
There is a error when I using the code below:
```C#
var foo = @"public static void Bar()
{
    byte[] bytes = new byte[]
    {
        1,
        1,
        1,
    };
}";
CSScript.Evaluator.LoadMethod(foo);
```
it throws a `System.MissingMethodException`:
```
System.MissingMethodException
  HResult=0x80131513
  Message=Constructor on type '<PrivateImplementationDetails>1' not found.
  Source=mscorlib
  StackTrace:
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark) in f:\dd\ndp\clr\src\BCL\system\rttype.cs:line 5345
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes) in f:\dd\ndp\clr\src\BCL\system\activator.cs:line 107
   at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes) in f:\dd\ndp\clr\src\BCL\system\reflection\assembly.cs:line 1017
   at CSScriptLibraryExtensionMethods.CreateInstance(Assembly assembly, String typeName, Object[] args)
   at CSScriptLibrary.AsmBrowser.CreateInstance(String typeName, Object[] args)
   at CSScriptLibraryExtensionMethods.CreateObject(Assembly obj, String typeName, Object[] args)
   at CSScriptLibrary.RoslynEvaluator.LoadMethod(String code)
   at Test.Program.Test() in E:\Test\just_for_test\Test\Test\Program.cs:line 68
   at Test.Program.Main(String[] args) in E:\just_for_test\\Program.cs:line 25
```
In fact, there is alwasy an exception when initializing a byte array whose elements number are greater than 2.
It's just happened in `Evaluator.XXX`, and working fine in CSI or all codes below:
```c#
CSScript.LoadMethod(foo).GetStaticMethod("*.Bar")()
```
or
```c#
var foo = @"public static void Bar()
{
    byte[] bytes = new byte[]
    {
        1,
        1,
    };
}";
```
But, i'm not skilled at C# and don't know it's my fault or someway else anymore. Could anyone give me some tips?
```
CS-Script version: 3.30.0
.net Framework 4.7.2
```

**Comment by oleg-shilo** [comment]
It is an interesting one and it has quite a few angles :)

1. You need to drop `public static` as `CSScript.Evaluator.LoadMethod(...);` expects an instance method.
2. The problem you are experiencing is caused b by the changed Roslyn team implemented between one of their assemblies in the .NET 4.7 compatible nuget package you are using and the .NET 4.6.1 package that CS-Script was built against. The possible solutions:
    * Switch to earlier (.NET 4.6.1 compatible) version of `Microsoft.CodeAnalysis.CSharp.Scripting` package. (May not be available unless you downgrade your target runtime, not sure...)
    * Wait until I upgrade the CS-Script package to target .NET 4.7
    If it is what is holding you I can squeeze it this year. Otherwise Jan. 
3. If none of the options above is acceptable you can simply use the same compiling engine as for `CSScript.LoadMethod(foo).GetStaticMethod("*.Bar")`:
```C#
// call code below before executing any scripts
CSScript.EvaluatorConfig.Engine = EvaluatorEngine.CodeDom;
```
This worked in my test.

**Comment by Monvvv** [comment]
@oleg-shilo Downgrading to .Net 4.6 does not work. The same problem is still here. The only way  i found to solve this problem is to change `EvaluatorEngine` or use methods in `CSScript` instead of in `CSScript.Evaluator`. 
Btw, this exception is not throwed with `CSScript.Evaluator.CreateDelegate` or `LoadDelegate`. There are some examples below:
```c#
var script = @"
void Foo()
{
    byte[] b = new byte[3]
    {
        1,
        2,
        3,
    };
}";
var wraped = @"
public class Script
{
    public void Foo()
    {
        byte[] b = new byte[3]
        {
            1,
            2,
            3,
        };
    }
}";
```
got `MissingMethodException`:
```c#
CSScript.Evaluator.LoadMethod(script);
CSScript.Evaluator.CompileMethod(script).CreateObject("*");

CSScript.Evaluator.LoadCode(wrapped);
CSScript.Evaluator.CompileCode(wrapped).CreateObject("*");
```

no exception:
```c#
var foo1 = CSScript.Evaluator.CreateDelegate(script);
foo1();
var foo2 = CSScript.Evaluator.LoadDelegate<Action>(script);
foo2();
```

**Comment by oleg-shilo** [comment]
Something is not right. :(

I can also reproduce the defect. Though in my case I need to use the later package of "*.Scripting". Tnis is the one that now emits a new class `<PrivateImplementationDetails>1`. Roslyn did not produce this class before. They introduced it recently and CS-Script which does not expect this class takes it by mistake and tries to instantiate. 

I have created a HotFix nuget package with the fix, which deliverers handling of that unexpected class - v3.30.1

Try it, it should solve the problem.

**Comment by Monvvv** [comment]
This problem has disappeared in 3.30.1. Thanks. :)

**Comment by oleg-shilo** [comment]
Great.
I will keep this issue opened until a proper release is published.

**Comment by Monvvv** [comment]
@oleg-shilo So maybe I should to reopen this issue?

**Comment by oleg-shilo** [comment]
ha-ha. I said I would reopen it but forgot to actually do it. Txs. It is "open issue" now.
