### ISSUE TITLE
Invalid cast exception

### ISSUE THREAD

**Issue by mrn-aglic** [oleg-shilo/cs-script#184]
Hi there, I wanted to try out CS-Script. I have a console application, and I tried all three engines, each threw a different exception. Here is my code

```
CSScript.EvaluatorConfig.Engine = EvaluatorEngine.Roslyn; 
dynamic script = CSScript.Evaluator.CompileCode(@"using System;
                                         public class Script
                                         {
                                             public int Sum(int a, int b)
                                             {
                                                 return a+b;
                                             }
                                         }").CreateObject("*");
```
I am running this on OS X Catalina, and using .NET Core 3.1. 

Here is the exception for Roslyn:

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.UnresolvedMetadataReference' to type 'Microsoft.CodeAnalysis.PortableExecutableReference'.
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at CSScriptLibrary.RoslynEvaluator.ReferenceAssembly(Assembly assembly)
   at CSScriptLibrary.RoslynEvaluator.ReferenceDomainAssemblies(DomainAssemblies assemblies)
   at CSScriptLibrary.RoslynEvaluator..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at System.LazyHelper.CreateViaDefaultConstructor[T]()
   at System.Lazy`1.CreateViaDefaultConstructor()
   at System.Lazy`1.ViaConstructor()
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at CSScriptLibrary.CSScript.get_RoslynEvaluator()
   at CSScriptLibrary.CSScript.get_Evaluator()
```

For CodeDom I get the following issue: 

`Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.CodeDom, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specifie`

For Mono engine:
```
Unhandled exception. csscript.CompilerException: (1,1): error CS0518: The predefined type `System.Object' is not defined or imported

   at CSScriptLibrary.MonoEvaluator.HandleCompilingErrors(Action action)
   at CSScriptLibrary.MonoEvaluator.CompileCode(String scriptText)
```

Note: I haven't tried cs-script.core yet.

**Comment by oleg-shilo** [comment]
You are hosting CS-Script .NET Core runtime, meaning you need to use "CS-Script.Core" package. 
Can you please try it.

I am actually quite interested in seeing if .NET-Core provides any better compatibility on Mac. Honestly Mono, was such a pain....

Keep in mind  "CS-Script.Core" only supports Roslyn evaluator.

**Comment by mrn-aglic** [comment]
Yeah, I tried it and CS-Script.Core seems to work! 
The downside is that Roslyn doesn't support Scripting with namespaces. However, I think I can think of a workaround.

**Comment by oleg-shilo** [comment]
My recommendation - stick to .NET Core. Mono is too flaky and CodeDom was always only available on Win anyway. 

Saying that, I managed to bring the CodeDom equivalent to the standalone engine so potentially the same approach can be extended to the hosted execution (your case). 
 
I am marking this as a feature request "Support for CodeDom evaluator" and if it get upvoted will implement on the very next opportunity.

**Comment by mrn-aglic** [comment]
Great! Glad to hear that.

**Comment by oleg-shilo** [comment]
I have just published the first 2020 release of CS-Script.Core nuget package. 

Read [this](https://github.com/oleg-shilo/cs-script.core/wiki/Advanced-hosting-scenarios). It explains the new feature "custom root class name", which in turn allows the referencing experience almost the same as when using namespaces.

**Comment by mrn-aglic** [comment]
Thanks, I've read the explanations. Just an idea: would it be possible to reference the assembly compiled in CSScript in Roslyn CSharpScript. Maybe expose the assembly through a method or get-only property. 
I know this feels like duck taping Roslyn limitations but would allow a way for them to be interoperable.

**Comment by mrn-aglic** [comment]
I've just tried what I asked about. It seems to work, with both file-less and file-full script assembly.

This is the code:

```
Assembly ass = CSScript.RoslynEvaluator.CompileCode(code2, new CompileInfo
            {
                RootClass = "code3"
            });
            var ss1 = CSharpScript.Create("",
                ScriptOptions.Default
                    .WithImports(_root.GetUsings())
                    .AddReferences(ass.Location)
                    .AddImports("code3")
                    .AddReferences(typeof(Enumerable).Assembly.Location)
            );
            var ss2 = ss1.RunAsync().Result;
            var ss4 = ss2.ContinueWithAsync("var x = new Usings();");

```
The runtime variable x is of type code3+Usings

**Comment by oleg-shilo** [comment]
> I've just tried what I asked about. It seems to work. It seems the code3.dll is getting created, despite not supplying AssemblyFile path.

Correct. The idea is that if user supplied class-root name then it he/she is intended to use the script assembly with the associate file. 
![image](https://user-images.githubusercontent.com/16729806/71778894-a76c0500-3007-11ea-96dc-95344077347f.png)

> What is strange is that, when setting PreferLoadingFromFile = false, the assembly.Location is an empty string.

Yes this property controls if loading the assembly from file (or from memory). 

![image](https://user-images.githubusercontent.com/16729806/71778962-2a8d5b00-3008-11ea-9d1a-b13d058fda14.png)

And this is the  implementation:

```C#
private Assembly CompileCode(string scriptText, string scriptFile, CompileInfo info)
{
    // scriptFile is needed to allow injection of the debug information

    (byte[] asm, byte[] pdb) = Compile(scriptText, scriptFile, info);

    if (info?.PreferLoadingFromFile == true && info?.AssemblyFile.IsNotEmpty() == true)
    {
        return Assembly.LoadFrom(info.AssemblyFile);
    }
    else
    {
        if (pdb != null)
            return AppDomain.CurrentDomain.Load(asm, pdb);
        else
            return AppDomain.CurrentDomain.Load(asm);
    }
}
```

**Comment by oleg-shilo** [comment]
Closing as it was not upvoted
