### ISSUE TITLE
Where to find compile errors in this scenario: 

### ISSUE THREAD

**Issue by NealWalters** [oleg-shilo/cs-script#186]
I got the "Hello world" examples working, and now I'm trying something more real-world. 

```
           string codeFileName = @"c:\path\Demo3Verified.cs";
            string csCode = System.IO.File.ReadAllText(codeFileName);
            dynamic script = CSScript.LoadCode(codeFileName).CreateObject("*");
```

When I run it, I get this error: 
An unhandled exception of type 'csscript.CompilerException' occurred in CSScriptLibrary.dll

Additional information: c:\Users\nealw\AppData\Local\Temp\CSSCRIPT\dynamic. 

In that folder, I see a file for each time I have run it, but when I open that file, it simply has the name of the file being compiled:  c:\path\Demo3Verified.cs

Also, any recommendation for best practices?  I put Demo3Verified.cs in another C# project so I could write it with Intellisense and make sure it compiled.  I think I've added the same references to the C# program that is calling CSScript.Load,  

Thanks
Neal Walters

**Comment by NealWalters** [comment]
Ah - I noticed when I click View Details - I can see the value of csscript.CompilerExecution. 

However, not sure I understand why I have these errors when I already made sure the code compiled. 

Got a lot of these: 

> tmp(1,1): error CS1056: Unexpected character '\\'\r\nc:\\Users\\nealw\\AppData\\Local\\Temp\\CSSCRIPT\\dynamic\\14120.187cef15-0b1e-4b84-a2f6-8090118a8485.tmp(1,2): error CS1056: Unexpected character '\\'\r\

and ended with this: 

> CS0116: A namespace cannot directly contain members such as fields or methods

**Comment by NealWalters** [comment]
I found it now... 

dynamic script = CSScript.LoadCode(codeFileName).CreateObject("*");
should be 
dynamic script = CSScript.LoadCode(csCode ).CreateObject("*");

I was passing the filename instead of the data.  (I had previously tried the LoadCode from file, which was apparently deprecated.

**Comment by NealWalters** [comment]
Also, seems like I have to include using statements like this: 

using BREPipelineFramework;
using BREPipelineFramework.SampleInstructions; 
using BREPipelineFramework.SampleInstructions.MetaInstructions;

when I tested in another program, the only one I needed was: 
using BREPipelineFramework.SampleInstructions.MetaInstructions;

Is there some reason to include each part of the using and then build up to the full using?

**Comment by NealWalters** [comment]
One more issue that has me stuck. 

{"c:\\Users\\nealw\\AppData\\Local\\Temp\\CSSCRIPT\\dynamic\\10096.848b7940-af5d-4d55-953b-096a77c0f771.tmp(40,13): error CS0103: The name 'DL' does not exist in the current context\r\n"}

I have a class defined as follows: 

```
namespace DL.BREHelpers   
{
    public static class MoreXMLHelpers 
```

As I said above, I have my C# in a project to get it to compile (but not test) before running it through CSScript.LoadCode.  I have referenced DL.BREHelpers.dll in both that test project and the project called CSharpRules2 - which is where the CSScript.LoadCode runs from.  When I run the LoadCode, it gives the above error.  I cannot think of any other way to reference it.  It's a static class and method. 

Thanks,
Neal

**Comment by NealWalters** [comment]
I read these three posts and now more confused about how to do references: 
https://stackoverflow.com/questions/22916467/how-to-add-a-reference-to-a-c-sharp-script
https://github.com/oleg-shilo/cs-script/issues/122
https://github.com/oleg-shilo/cs-script/issues/9

I tried: 

```
 CSScript.Evaluator.ReferenceAssembly(@"c:/mypath\TestAddNodeBREFunction\DL.BREHelpers\bin\Debug\DL.BREHelpers.dll");
            Console.WriteLine("Assembly DL.BREHelpers have been referenced");
            dynamic script = CSScript.Evaluator.LoadCode(csCode); 

```

and got this error now on the ReferenceAssembly method: 

System.IO.FileNotFoundException was unhandled by user code
  FileName=System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  FusionLog==== Pre-bind state information ===
LOG: DisplayName = System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file://c:/mypath/Projects/TestAddNodeBREFunction/CSharpRules2/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.CodeAnalysis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: c:/mypath\TestAddNodeBREFunction\CSharpRules2\bin\Debug\CSharpRules2.vshost.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file://c:/mypath/Projects/TestAddNodeBREFunction/CSharpRules2/bin/Debug/System.IO.FileSystem.DLL.
LOG: Attempting download of new URL file://c:/mypath/Projects/TestAddNodeBREFunction/CSharpRules2/bin/Debug/System.IO.FileSystem/System.IO.FileSystem.DLL.
LOG: Attempting download of new URL file://c:/mypath/Projects/TestAddNodeBREFunction/CSharpRules2/bin/Debug/System.IO.FileSystem.EXE.
LOG: Attempting download of new URL file://c:/mypath/Projects/TestAddNodeBREFunction/CSharpRules2/bin/Debug/System.IO.FileSystem/System.IO.FileSystem.EXE.

  HResult=-2147024894
  Message=Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  Source=Microsoft.CodeAnalysis
  StackTrace:
       at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)
       at Microsoft.CodeAnalysis.MetadataReference.CreateFromAssemblyInternal(Assembly assembly, MetadataReferenceProperties properties, DocumentationProvider documentation)
       at Microsoft.CodeAnalysis.Scripting.ScriptOptions.CreateReferenceFromAssembly(Assembly assembly)
       at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.<>c__DisplayClass4_0`2.<SelectChecked>b__0(T item)
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.AddRangeChecked[T](ArrayBuilder`1 builder, IEnumerable`1 items, String parameterName)
       at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.ConcatChecked[T](ImmutableArray`1 existing, IEnumerable`1 items, String parameterName)
       at Microsoft.CodeAnalysis.Scripting.ScriptOptions.AddReferences(IEnumerable`1 references)
       at Microsoft.CodeAnalysis.Scripting.ScriptOptions.AddReferences(IEnumerable`1 references)
       at Microsoft.CodeAnalysis.Scripting.ScriptOptions.AddReferences(Assembly[] references)
       at CSScriptLibrary.RoslynEvaluator.ReferenceAssembly(Assembly assembly) in c:/mypath\cs-script-master\Source\CSScriptLibrary\CSScriptLib.Eval.Roslyn.cs:line 769
       at CSScriptLibrary.RoslynEvaluator.ReferenceDomainAssemblies(DomainAssemblies assemblies) in c:/mypath\cs-script-master\Source\CSScriptLibrary\CSScriptLib.Eval.Roslyn.cs:line 893
       at CSScriptLibrary.RoslynEvaluator..ctor() in c:/mypath\cs-script-master\Source\CSScriptLibrary\CSScriptLib.Eval.Roslyn.cs:line 147
  InnerException:

**Comment by NealWalters** [comment]
My temporary get-around is to put the .dll in the GAC.

**Comment by oleg-shilo** [comment]
Hi Neal,

It's difficult to comment as I do not have your code that is failing for you. The fact that you can compile it externally is a good start but it does not warranty the success as during your scripting you may not reference the same dependency assemblies as you do with Visual Studion. Basically it is an "Apple vs Orange" situation.

I suggest you create a HelloWorld project and add CS-Script Nuget package, which comes with the comprehensive set of samples.  

Judging from you post you will need to have a look at "Scripting.Native.cs" samples file.
