### ISSUE TITLE
Does CSScript work with WebGL? Getting errors with loading Code.

### ISSUE THREAD

**Issue by SkyanSam** [oleg-shilo/cs-script#187]
![image](https://user-images.githubusercontent.com/31390605/72031925-eeeacf00-325b-11ea-8b7c-cad18518abeb.png)
NotSupportedException: Specified method is not supported.
  at System.Threading.Mutex..ctor (System.Boolean initiallyOwned, System.String name) [0x00000] in <00000000000000000000000000000000>:0 
  at CSScriptLibrary.CSScript.LoadCode (System.String scriptText, System.String tempFileExtension, System.String assemblyFile, System.Boolean debugBuild, System.String[] refAssemblies) [0x00000] in <00000000000000000000000000000000>:0 
  at CSScriptLibrary.CSScript.LoadCode (System.String scriptText, System.String assemblyFile, System.Boolean debugBuild, System.String[] refAssemblies) [0x00000] in <00000000000000000000000000000000>:0 
  at CSScriptLibrary.CSScript.LoadMethod (System.String methodCode, System.String assemblyFile, System.Boolean debugBuild, System.String[] refAssemblies) [0x00000] in <00000000000000000000000000000000>:0 
  at CSScriptLibrary.CSScript.LoadMethod (System.String methodCode, System.String[] refAssemblies) [0x00000] in <00000000000000000000000000000000>:0 
  at LevelLoader+<Load>d__2.MoveNex

The debug issue is in the red text that was outputted by Unity. I used a webgl dev export.
It works great in UnityEngine but I get errors with WebGL. Here is a snippet of the code that is being called creating the error.

```
using (UnityWebRequest www = UnityWebRequest.Get(QuizInfo.beatmapUrl + "/script.txt"))
        {
            yield return www.SendWebRequest();
            print(www.downloadHandler.text);
            string script = www.downloadHandler.text;
            LevelManager.Level.Script.Start = CSScript.LoadMethod(script).GetStaticMethod("*.Start");
            LevelManager.Level.Script.Update =CSScript.LoadMethod(script).GetStaticMethod("*.Update");
            outputDisplay.text = "Script loaded @ " + QuizInfo.beatmapUrl + "/script.cs";
        }

```

[note: this code is in a IEnumerator]

Is there an issue with CSScript? or is it System.Threading.Mutex..ctor. Im not sure.

**Comment by oleg-shilo** [comment]
The error means that an external assembly method, which is to be invoked at runtime and which availability on that assembly was verified at compile time was not found at runtime. Ususally this problem is caused by the incompatibuility of the assembly with its host.


A typical scenario for that host version mismatch or a spec deviation of the alternative vendor implementation. For example if the Mutex constructor exists in `System.Threading.dll` of .NET but not in Mono, the you will have this problem when you run on Mono but not on .NET.

You may find that different version of your hosting environment may support the method in question.

**Comment by SkyanSam** [comment]
Hmm.. Does CSScript use threading? System.Threading isn't supported by WEBGL. 
https://docs.unity3d.com/Manual/webgl-gettingstarted.html
Oop it looks like dynamic generation of code doesn't work either.
Maybe CSScript just doesn't work with WebGL.

I'll just have to make a custom text parser myself. (not too hard but still annoying)
I am using CSScript for a different project but I guess it just wont work for this one :(

Or maybe it will but wouldn't dynamic scripts be apart of System.Reflection.Emit?

**Comment by oleg-shilo** [comment]
Yeah it looks like it is a limitation of WEBGL. 

You see, CS-Script does not implement its own interpreter. It simply links hosting environment to the dynamic code generation of the CLR adn provide simplified user experience. But if the implementation of .NET that user is using does not fully covers .NET spec (at least _.NET standard_) then it's not much CS-Script can do to help. :(
