### ISSUE TITLE
CS-SCRIPT problem

### ISSUE THREAD

**Issue by hansonqC** [oleg-shilo/cs-script#188]
Hi Oleg. I have a problem after cs-script tool installation on VS2017. I'm getting this.
https://gifyu.com/image/mXdy 
Thank You for You help.
Regards

**Comment by oleg-shilo** [comment]
THis message means that the extension cannot detect CS-Script on your system. I suggest you download it form [Chocolatey](https://chocolatey.org/packages/cs-script)
