### ISSUE TITLE
Cs-Script Initialization Problem Vs-Code 1.44.0

### ISSUE THREAD

**Issue by mmickael** [oleg-shilo/cs-script#191]
Hi Oleg, after upgrading VS Code to 1.44.0, Cs-Script seems to have a problem with initialization and the extension stops working.  Please see the lower left corner of the attached screenshot. 

![Error](https://user-images.githubusercontent.com/13186185/78940970-5e02da00-7a7c-11ea-9cc0-b28723aa0a05.jpg)

**Comment by mmickael** [comment]
Cs-Script version 1.6.0-2 (8 Apr, 2020)

**Comment by oleg-shilo** [comment]
Moved to cs-script.vscode project:
https://github.com/oleg-shilo/cs-script.vscode/issues/22
