### ISSUE TITLE
the“css_import ” is invalid

### ISSUE THREAD

**Issue by snikeguo** [oleg-shilo/cs-script#192]
My console program is using .net core 3.1 framework.
nuget:CS-Script.Core 1.3.1

B.cs:

```
//css_import A.cs
my code ...
```
A.Cs and B.cs are in the same directory

#141

**Comment by snikeguo** [comment]
"CSScript.EvaluatorConfig.Engine  =  EvaluatorEngine.CodeDom"  is invalid  in .net core 3.1

**Comment by snikeguo** [comment]
OK，i will modify framework to .net framework4.7 ,that is ok
question2：

A.cs have a Student Type,
B.cs:
```
//css_import A.cs

var assembly=CSScript.Evaluator.CompileCode(File.ReadAllText("B.cs"));

var types = assembly.GetTypes();
foreach (var type in types) 
{
   //How to know if type belongs to the type defined in this document？
  like is:
 if( ThisFileIs.FindType(type.FullName)==true)
  {
    ......
  }
}
```
How to know if type belongs to the type defined in this document？

**Comment by oleg-shilo** [comment]
Question `#1`: yes CS-Script for .NET-Core only supports `EvaluatorEngine.Roslyn`. This is the limitation of .NET-Core 

Question `#2`: I am not sure I follow what you are trying to do. I'll use your terminology and pseudo code to illustrate: 

```C#
var assembly_b = CSScript.Evaluator.CompileCode(File.ReadAllText("B.cs"));
var assembly_of_this_document =  Assembly.GetExecutingAssembly();

var types_of_b = assembly_b.GetTypes();
var types_of_this_document = assembly_of_this_document.GetTypes();

foreach (var type in types) 
{
    if (types_of_this_document.Any(t => t.FullName == type.FullName))
    {
        we will never get here because FullName always includes assembly name and 
        both assemblies are different
        ......
    }
}
```

**Comment by snikeguo** [comment]
I am doing a code generation library, all data types in A.cs generate A.Cpp and A.h
B.cs depends on A.cs and also generates B.cpp and B.h (cannot include the type of A.cs)

https://github.com/snikeguo/EmbedXrpc/blob/5db8bea163b3b8e7ff4787dbc9720d8e79650e26/EmbedXrpcIdlParser/ICodeGenerater.cs#L277

**Comment by oleg-shilo** [comment]
Closing as the problem description was not provided
