### ISSUE TITLE
DirectoryNotFoundException(C:\ProgramData\CS-Script\ShellExtension) when fresh installing

### ISSUE THREAD

**Issue by fredlllll** [oleg-shilo/cs-script#193]
i just tried installing 3.30.0.0 on windows 10 where csscript has never been installed before, and i get this error message https://i.imgur.com/AfZxZKv.png

running the install script a second time does not produce an error, but im unsure if it actually finished the installation. running uninstall and then install will produce the error again

**Comment by oleg-shilo** [comment]
I will have a look at it.
But if you are not sure if the engine was installed then check from a new command prompt session:
![image](https://user-images.githubusercontent.com/16729806/80210717-8e9b6400-8677-11ea-9287-999ba0cd4555.png)

Installation doesn't do much. Just set a few environment variables. That's it

**Comment by fredlllll** [comment]
cscs seems to work. wait, if it just sets some environment variables, how do i get the context menu then? i have it on another computer with a much older version of cs-script

**Comment by oleg-shilo** [comment]
>cscs seems to work.

Then what it means that the install/initialization routine of cs-script is still relying (on first start) on the presence the old folder shell extension folder. I will look into it. But the error message should can be ingnored as in this context it is rather a warning.

> wait, if it just sets some environment variables, how do i get the context menu then? i have it on another computer with a much older version of cs-script 

The old shell extension is now a separate individual product that can be installed from Chocolatey:
```C#
choco install shell-x
```

Read more here: https://github.com/oleg-shilo/cs-script/wiki/REPL,-IDE-and-OS-integration#os-integration-ide-and-repl

**Comment by oleg-shilo** [comment]
Please test the v3.30.2 release:
https://github.com/oleg-shilo/cs-script/releases/tag/v3.30.2.0
It should fix the problem. 

_I have difficulties testing it in my environment so will appreciate if you can tell me if fix works. 
Then I will publish it on Chocolatey._
