### ISSUE TITLE
"//css_nuget" does not appear to work on Linux?

### ISSUE THREAD

**Issue by limeschool** [oleg-shilo/cs-script#195]
Heyo! If this is user error, sorry for wasting your time. This is a fantastic project, and I appreciate your dedication in maintaining it. I'm using it in my static site generator, [WDHAN](https://github.com/MadeByEmil/WDHAN), to implement C# plugins.

I'm trying to write such as plugin that needs two dependencies, [CodeHollow.FeedReader](https://www.nuget.org/packages/CodeHollow.FeedReader/) and [SmartReader](https://www.nuget.org/packages/SmartReader/). My code is as follows:

```
//css_nuget SmartReader
//css_nuget CodeHollow.FeedReader
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Globalization;
using System.Diagnostics;
using System.Net;
using System.IO.Compression;

public class GetArticles
{
  public void Main(string[] args)
  {
    Console.WriteLine("Plugin is ready.");
    getPublisher("http://feeds.bbci.co.uk/zhongwen/simp/rss.xml", "_bbc-zh");
  }
  public static void getPublisher(string publisherUrl, string collection)
  {
    var feed = FeedReader.Read(publisherUrl);
    int i = 0;
    foreach(var item in feed.Items)
    {
      SmartReader.Article article = SmartReader.Reader.ParseArticle(item.Link);
      if(article.IsReadable)
      {
        i++;
        article.ConvertImagesToDataUriAsync().Wait();
        string fileContents = "---\ntitle: " + item.Title + "\nlink: " + item.Link + "\ndate: " + item.PublishedDateString + "\n---\n" + article.Content;
        using (FileStream fs = File.Create("./" + collection + "/" + i + ".md"))
	{
		fs.Write(Encoding.UTF8.GetBytes(fileContents), 0, Encoding.UTF8.GetBytes(fileContents).Length);
	}
        Console.WriteLine("Processed " + item.Title + " (" + item.Link + ")");
      }
    }
  }
}
```

When running this script on Linux, I get the following output:
```bash
CSScriptLib.CompilerException: (22,16): error CS0103: The name 'FeedReader' does not exist in the current context
(26,7): error CS0246: The type or namespace name 'SmartReader' could not be found (are you missing a using directive or an assembly reference?)
(26,37): error CS0103: The name 'SmartReader' does not exist in the current context

   at CSScriptLib.RoslynEvaluator.Compile(String scriptText, String scriptFile, CompileInfo info)
   at CSScriptLib.RoslynEvaluator.CompileCode(String scriptText, String scriptFile, CompileInfo info)
   at CSScriptLib.RoslynEvaluator.CompileCode(String scriptText)
   at CSScriptLib.RoslynEvaluator.LoadCode(String scriptText, Object[] args)
```

It appears that the nuget dependencies are not downloading for whatever reason. Apologies if this is intentional and it's user error.

**Comment by oleg-shilo** [comment]
I am glad you like this project. 

I am afraid your task is not simple. 

This is my guess. Your solution appears to work on win simply because the packages are already downloaded.But on Linux they are not.

The truth is that `//css_nuget` is not intended to work in hosting scenarios (like yours).

Read this usefull discussion.

**Comment by limeschool** [comment]
Apologies for the continued trouble.

I'm simply trying to have a script read an RSS feed and write a file. This isn't intended to run on a server or any sort of hosting/web environment.

The only limitation is, I'm running this script through another program (WDHAN) in a CLI environment. This means I don't have a .CSPROJ or .SLN file with the script.

How may I go about providing CS-Script the packages it needs to run my script? Do I have to manually download the packages and specify a path to them? I thought the point of using "//css_nuget" was to avoid this and have CS-Script download the packages itself.

**Comment by limeschool** [comment]
I've run CS-Script directly in the CLI and come across the reason why I'm getting this error.

`cscs` is calling `nuget install`, which does not work on Linux. The current `nuget` package on Linux is quite out-of-date. Instead, `dotnet nuget` works correctly.

It appears the solution would be to call `dotnet nuget install` instead of `nuget install` when having CS-Script download packages.

**Comment by oleg-shilo** [comment]
sorry, in my message (third up) I forgot to provide the link to the discussion I was referring. 
Here we go: https://github.com/oleg-shilo/cs-script/issues/167

**Comment by EmilSayahi** [comment]
Thank you so much for your response!

I actually am using CS-Script.Core in the 'hosted' environment, as you call it. I thought of using it in a CLI instead (using the `css` command), but the package is broken as it has a hard-coded path to the .dll it's looking for.

I'll try out the manual downloading, then referencing approach. Thanks.

**Comment by oleg-shilo** [comment]
I would like to look at the debian package Can you please give me the reference to the package you are using.

As a temp measure, manual download + referencing will do the trick

**Comment by limeschool** [comment]
Apologies for following up so late.

I'm using [this .deb package](https://github.com/oleg-shilo/cs-script.core/blob/master/docs/linux/ubuntu/cs-script.core_1.2.1.0_all.deb) for running CS-Script.Core in the CLI. It attempts to run a .dll file at a path which does not exist (I think you hardcoded it to point to a path on your own PC).

I'll try out manually downloading and referencing for now. Thanks for your help so far.

**Comment by oleg-shilo** [comment]
OK. 

I am glad you provided the url. I can see now that you are not using [CS-Script](https://www.cs-script.net/cs-script/) but [CS-Script.Core](https://www.cs-script.net/cs-script.core/). Two completely different distributions. Built from two different codebase due to the incompatibility of the hosting environments: .NET Framework and .NET Core.

Effectively CS-Script exists in two parallel forms: CS-Script but CS-Script.Core :(

It will need to stay this way till .NET5, which will stop .NET Framework stream evolution.

===============

Anyway, will have a look when I have the next chance.

**Comment by limeschool** [comment]
Hello, @oleg-shilo. I just wanted to jump in to let you know that I believe I've discovered the source of the error. I've made [a pull request](https://github.com/oleg-shilo/cs-script.core/pull/12) in the [oleg-shilo/cs-script.core](https://github.com/oleg-shilo/cs-script.core) repository. If you could look into merging it, it would be much appreciated. Thanks!

**Comment by oleg-shilo** [comment]
txs. will do
