### ISSUE TITLE
Referenced assemblies are loaded but cannot use them

### ISSUE THREAD

**Issue by Bit00009** [oleg-shilo/cs-script#196]
Dear oleg , I faced a wired situation.
I have an C++ application and a C# script engine developed using **cs-script.**
C++ application has a .net loader too and loads .net assemblies using CLR Hosting.
Now there's 2 .net library I have **"APIKit.dll"** and **"SDKBridge.dll"** , I placed them at exe root and C# script engine has references to them.
**So this is how I execute script on my Host :**
```
    static dynamic scriptData;
    ...
    ...
    ...
    using (SimpleAsmProbing.For(Assembly.GetExecutingAssembly().Location.GetDirName()))
            {
                scriptData = CSScript.RoslynEvaluator.LoadCode(script);
                scriptData.OnStart();
                scriptData.OnShutDown();
            }
```

Now in host app everything works fine I can access all of methods and classes in APIKit and SDKBridge dlls but when I want to do the same in script I get this error : 
> error CS0234 : The type or namespace name `APIKitClass` does not exist in the namespace `APIKit` (are you missing an assembly reference?)

I thought there's something wrong with loaded assemblies but I tried to print all domain loaded assemblies using **in script** : 
```
     Assembly[] asms = AppDomain.CurrentDomain.GetAssemblies();
        string loaded_asm = "";
        for (int i = 0; i < asms.Length; i++)
        {
            loaded_asm += $"Asm [{i+1:D2}] -> {asms[i].GetName()}\r\n";
        }
       MessageBox.Show(loaded_asm);
```
and I see both APIKit.dll and SDKBridge.dll are loaded.
So what's the problem ? why is this happening ?

**Comment by Bit00009** [comment]
The solution is : 
Loading assemblies by name just before calling script : 
```
        AppDomain.CurrentDomain.Load(new AssemblyName("APIKit"));
        AppDomain.CurrentDomain.Load(new AssemblyName("SDKBridge"));
        ...
        ...
        // Execute Script...
```

**Comment by oleg-shilo** [comment]
The best type of issues. 
Resolved quickly.
The solution is useful for others.
😄 👍  

thank you for sharing

**Comment by oleg-shilo** [comment]
Using refs in your script will probably solve the issue too:
``` C#
//css_ref APIKit.dll
//css_ref SDKBridge.dll
```
