### ISSUE TITLE
Changes from version 3.29 to 3.30

### ISSUE THREAD

**Issue by reprogroup** [oleg-shilo/cs-script#198]
Code from file script.js:
`//css_reference "System.dll";
...`
has exception in csparser.cs file at line 326:
`if (!Path.IsPathRooted(this.file) && ResolveRelativeFromParentScriptLocation)`

Solution: trimming double quotes before parsing at line 318:
`statementToParse = statementToParse.Replace("\t", "").Trim().Trim('"');`
or
`statementToParse = statementToParse.Replace("\t", "").Trim(" \"".ToCharArray());`

**Comment by oleg-shilo** [comment]
Thank you for reporting that.
I do agree that trimming would solve the problem. I have added the change.

Though, to be honest it is a little bit of over-engineering. There is no good use case when user would need to pass the quatation chars. Thus this work around is the case when the engine takes an invalid user input and fixes it. Kind of "no harm" but masking the real problem - user defining the `//css_ref` directive incorrectly.

Anyway, the enhancement will be available in the next release.  

===================

Interestingly enough `Path.IsPathRooted("\"System.dll\"");` throws on .NET and does not on .NET-Core

**Comment by reprogroup** [comment]
![JS_HelloWorld](https://user-images.githubusercontent.com/20625453/86512918-8fd2d500-be0e-11ea-9ba4-13c5a1689c26.PNG)

**Comment by oleg-shilo** [comment]
Uh.... My apologies for the inaccurate documentation. 

This is a legacy documentation that arguably should not be used for the current version(s). Interestingly enough it was a few other doc pages with the same mistake but none for C# samples but only for VB.NET and J#.  

 
Nevertheless I have updated the page and now it contains the corrected sample:
![image](https://user-images.githubusercontent.com/16729806/86514062-781d4000-be52-11ea-924e-03ddd94db10d.png)

**Comment by reprogroup** [comment]
> but none for C# samples
Fixed already in csparser.cs file at line 254:
`statementToParse = statementToParse.Replace("\t", "").Trim().Trim('"');`

**Comment by oleg-shilo** [comment]
I think there is a confusion here :)

I agree with the the fix but I do question the need for it as it serves an invalid use-case. 

I do not question  your suggestion but rather my own early decision to implement it (line 254).

And even though I question it i agreed with you and extended the "questionable" work around and now it is done in both locations: line 254 and 318.

All good. Thank you.

**Comment by reprogroup** [comment]
I found #160, where we discussed this earlier.

Thank you Олег.

**Comment by oleg-shilo** [comment]
LOL
We are both still very consistent with our year ago positions. :)
