### ISSUE TITLE
How to enable unsafe code

### ISSUE THREAD

**Issue by xmuhcd** [oleg-shilo/cs-script#20]
Hello,

I am trying to use the unsafe code in CS script, such code:

_unsafe public static double fittingFunction(IntPtr data, Intptr para)
{
	double* input = (double*)data.ToPointer(); double* variable = (double*)para.ToPointer();
	double x = input[0];//x coordinate
	double y = input[1]; // y coordinate
	double A = variable [0];//Amplitude
	double x0 = variable [1]; // x center
	double y0 = variable [2]; // y center
	double sigmalX = variable [3];
	double sigmalY = variable [4];
	return A * Math.Exp( -((x - x0) * (x - x0) / (sigmalX * sigmalX) + ((y - y0) * (y - y0)) / (sigmalY * sigmalY))/2);
}_

I use **CSScript.Evaluator.CreateDelegateAsync(sourceText)** to get the compile result, but it says the unsafe code is not allowed:
error cs0227: unsafe code requires the `unsafe' command line option to be specified.

Could you please instruct me how to walk around this issue? I know for C# there is any option in project properties. But I have no idea how to specify that for CSS. Thanks

**Comment by oleg-shilo** [comment]
Unfortunately all engines allow compiler options in a different way.

CodeDom requires passing the option directly to the compiler. One of the ways is with CS-Script directives. This is how you can do it:
```C#
[Fact]
public async void CreateUnsafeDelegateAsync()
{
    var test = await CSScript.CodeDomEvaluator
                             .CreateDelegateAsync(
                                      @"//css_co /unsafe
                                        unsafe float UnsafeFunction(IntPtr data)
                                        {
                                            return (float)data + 5f;
                                        }");
    var data = (IntPtr)10;
    var result = test(data);
    Assert.Equal(15f, result);
}
```
Strangely enough Roslyn doesn't need any special instruction:
```C#
var test = await CSScript.RoslynEvaluator
                         .CreateDelegateAsync(
                                  @"unsafe float UnsafeFunction(IntPtr data)
                                    {
                                        return (float)data + 5f;
                                    }");
    ...
```
And with mono you need to access an internal CompilerSettings object:
```C#
var eval = CSScript.MonoEvaluator;
eval.CompilerSettings.Unsafe = true;
var test = await eval.CreateDelegateAsync(
                                    @"unsafe float UnsafeFunction(IntPtr data)
                                    {
                                        return (float)data + 5f;
                                    }");
```
Thus as you can see from the samples above it's impossible to unify that and provide one transparent API. CodeDom and Mono tunnel compiler options in an inconsistent way and Roslyn is not using compiler options at but some magic instead.

**Comment by xmuhcd** [comment]
@oleg-shilo Many thanks, I use the Mono Evaluator, and the last code snippet works perfectly for me. Cheers!

**Comment by oleg-shilo** [comment]
Great. And with the next release you will be able to specify Mono compiler options globally:
```C#
MonoEvaluator.CreateCompilerSettings = () => new Mono.CSharp.CompilerSettings { Unsafe = true };
```
It's already done in the codebase but not released yet
