### ISSUE TITLE
I don't understand

### ISSUE THREAD

**Issue by Tatitooo** [oleg-shilo/cs-script#201]
I have a issue while trying to use CSScript and it's related to mono. I'm using Windows 10 and i get that "C:/Dir/mono/mini/mono.exe was not found" i searched on google but i've found nothing, i also installed mono and still not working... I don't know what should i do.

**Comment by oleg-shilo** [comment]
I can only suggest you give it a try with .NET Core. If it is still applicable to your business case.
CS-Script comes in .NET Core form as well
