### ISSUE TITLE
question about MemoryManagement.cs sample

### ISSUE THREAD

**Issue by fivegg** [oleg-shilo/cs-script#204]
I want use cs-script with asp.net.
I test MemoryManagement.cs sample wtih  3.30.3.The result shows Hybrid_FixedScript_Test() function much faster than  Hybrid_FixedClassName_Test().I don't understand.The Fixed class changes nothing and Fixed script changes methods.Why?

    static public string GetCode(string className, string methodName = null)
    {
        string methodIndex = methodName==null ? (index2++).ToString(): "";
        return codeTemplate.Replace("Div", "Div" + methodIndex)
                           .Replace("[CLASS_NAME]", className);
    }

    static public string GetClass()
    {
        return "Script" + index++;
    }

    static string codeTemplate =
          @"using System;
            public class [CLASS_NAME]
            {
                public int Sum(int a, int b)
                {
                    return a+b;
                }

                public int Div(int a, int b)
                {
                    return a/b;
                }
            }";

    static void Hybrid_FixedClassName_Test()
    {
        string className = "Script";
        string code = GetCode(className);

        dynamic script = CSScript.Evaluator.LoadCode(code);

        int result = script.Sum(1, 2);
    }

    static void Hybrid_FixedScript_Test()
    {
        string className = "Script";
        string code = GetCode(className, "");

        dynamic script = CSScript.Evaluator.LoadCode(code);

        int result = script.Sum(1, 2);
    }

btw I have to add follow line to run in Win10 otherwise there will be an error while runing
CSScript.EvaluatorConfig.Engine = EvaluatorEngine.CodeDom;
[MemoryManagement.zip](https://github.com/oleg-shilo/cs-script/files/5289382/MemoryManagement.zip)

**Comment by oleg-shilo** [comment]
Fixed script is faster because it is only compiled once. Next time you run it (unchanged script) the script engine simply takes already compiled assembly and executes it without compilation.

Whereas `Hybrid_FixedClassName_Test` runs a new script with every iteration of your test loop. And since the script code is changed the script engine has to compile it into assembly every time before the execution.

**Comment by fivegg** [comment]
I think so too.But Hybrid_FixedClassName_Test() changed nothing ,and  Hybrid_FixedScript_Test() changed method "Div" to "Div" + (index2++) everytime,So Hybrid_FixedClassName_Test() should be much faster than Hybrid_FixedClassName_Test().The result is the opposite.
`
Mono.CSharp - Fixed script：5MonoCSharp_FixedScript_Test
 Cycle = 0100: MemoryPrivateBytes = 36160 KB;  AppDomainAssemblies = 121
 Cycle = 0200: MemoryPrivateBytes = 38516 KB;  AppDomainAssemblies = 158
 Cycle = 0300: MemoryPrivateBytes = 38520 KB;  AppDomainAssemblies = 158
 Cycle = 0400: MemoryPrivateBytes = 38532 KB;  AppDomainAssemblies = 158
 Cycle = 0500: MemoryPrivateBytes = 38504 KB;  AppDomainAssemblies = 158

 Time: 2100
-------------------------------------------------------
CSScript.Evaluator - Fixed script：6Hybrid_FixedScript_Test
 Cycle = 0100: MemoryPrivateBytes = 38308 KB;  AppDomainAssemblies = 149
 Cycle = 0200: MemoryPrivateBytes = 38308 KB;  AppDomainAssemblies = 149
 Cycle = 0300: MemoryPrivateBytes = 38308 KB;  AppDomainAssemblies = 149
 Cycle = 0400: MemoryPrivateBytes = 38308 KB;  AppDomainAssemblies = 149
 Cycle = 0500: MemoryPrivateBytes = 38308 KB;  AppDomainAssemblies = 149

 Time: 1278
-------------------------------------------------------
CSScript.CodeDOM - Fixed script：7CSScript_FixedScript_Test
 Cycle = 0100: MemoryPrivateBytes = 38312 KB;  AppDomainAssemblies = 149
 Cycle = 0200: MemoryPrivateBytes = 38312 KB;  AppDomainAssemblies = 149
 Cycle = 0300: MemoryPrivateBytes = 38312 KB;  AppDomainAssemblies = 149
 Cycle = 0400: MemoryPrivateBytes = 38312 KB;  AppDomainAssemblies = 149
 Cycle = 0500: MemoryPrivateBytes = 38312 KB;  AppDomainAssemblies = 149

 Time: 186
-------------------------------------------------------
>>>>>>>>>>>>>>>>>>>>>>>>>>
Mono.CSharp - Fixed class name：8MonoCSharp_FixedClassName_Test
 Cycle = 0100: MemoryPrivateBytes = 42560 KB;  AppDomainAssemblies = 249
 Cycle = 0200: MemoryPrivateBytes = 44968 KB;  AppDomainAssemblies = 286
 Cycle = 0300: MemoryPrivateBytes = 45008 KB;  AppDomainAssemblies = 286
 Cycle = 0400: MemoryPrivateBytes = 45020 KB;  AppDomainAssemblies = 286
 Cycle = 0500: MemoryPrivateBytes = 44976 KB;  AppDomainAssemblies = 286

 Time: 1684
-------------------------------------------------------
CSScript.Evaluator - Fixed class name：9Hybrid_FixedClassName_Test
 Cycle = 0100: MemoryPrivateBytes = 47600 KB;  AppDomainAssemblies = 376
 Cycle = 0200: MemoryPrivateBytes = 50224 KB;  AppDomainAssemblies = 476
 Cycle = 0300: MemoryPrivateBytes = 53008 KB;  AppDomainAssemblies = 576
 Cycle = 0400: MemoryPrivateBytes = 58944 KB;  AppDomainAssemblies = 676
 Cycle = 0500: MemoryPrivateBytes = 62884 KB;  AppDomainAssemblies = 776

`

**Comment by oleg-shilo** [comment]
Not exactly, `Hybrid_FixedScript_Test()` does not change method "Div" 

 `Hybrid_FixedScript_Test()` passes `methodName` as `""`. Meaning that it is not `null` so `methodIndex` is always an empty string:
```C#
static public string GetCode(string className, string methodName = null)
{
    string methodIndex = methodName==null ? (index2++).ToString(): "";
    return codeTemplate.Replace("Div", "Div" + methodIndex)
                       .Replace("[CLASS_NAME]", className);
}

```

**Comment by fivegg** [comment]
Thanks,it's ok now.
