### ISSUE TITLE
CS1685 warning when compiling with MonoEvaluator

### ISSUE THREAD

**Issue by markcanary** [oleg-shilo/cs-script#205]
I have an application that uses cs-script for hosting c# scripting within the application. I am getting the following warning whenever I compile script code in my application. I can't figure out how to determine where the conflict is coming from.

warning CS1685: The predefined type `System.Runtime.InteropServices.DefaultParameterValueAttribute' is defined multiple times. Using definition from `System.dll'

This is my code to compile the script into an assembly:

    monoEvaluator = CSScript.MonoEvaluator;
    var scriptInstance = monoEvaluator.LoadCode(sourceCode, _screen);

Any ideas how to find the conflict?

Thanks!

**Comment by oleg-shilo** [comment]
am not sure you need to to resolve this conflict.

**Comment by markcanary** [comment]
OK, so it seems like I can safely ignore the error.

Moving forward, is it possible to use CS-Script.Core inside a .NET Framework application. Or do we have to convert the application to .NET Core first?

**Comment by oleg-shilo** [comment]
You do need to convert. These two (Framework and Core) are not mixable.

Saying that when .NET 5 is completely out you will be able to tunnel your Framework-targeting functionality (e.g. WinForms, WPF) through the same Core-based entry assembly. But this is for stand alone scripts. 

Your case is _script engine hosting_ from the app. Meaning that most likely it needs to be core->core only. Of course I don't know it for sure. Bu the safest bet is to start switching to .NET Core.

**Comment by markcanary** [comment]
Thanks for the information. I believe I understand your intentions for support of CS-Script and .NET Core and .NET 5. As our application runs as a WCF server, porting to .NET Core will not be trivial. But it appears that is what we will need to do.

**Comment by oleg-shilo** [comment]
Just because you mentioned WCF. 
.NET Core has support for WCF client but I don't think you can implement WCF server. 

Meaning that if you stay with WCF you may need to stick with .NET Framework. Thus you need to use CS-Script (not CS-Script.Core). Though yon may consider switching to Roslyn instead of Mono.  Unless you have your specific reasons not to.

**Comment by markcanary** [comment]
We are using the Mono compiler because we understand it is significantly faster than the Roslyn compiler. Our application users load "dashboards" in our application that have to compile any script that may have been added on load. The compiling needs to be fast. If I am mistaken about the Roslyn compiler performance, please tell me.

**Comment by oleg-shilo** [comment]
Mono is indeed faster than Roslyn but mI think dramatically ~10-20%. 
Thus if i is significant your your product then indeed you should stick to Mono.

Though Roslyn has significantly slower initialization time. First time you call it from the running app. After that I say you do not loose much.  

That initialization overhead can be addressed by executing some dummy script like art application startup:
 ```C#
CSharpScript.EvaluateAsync("1 + 2"); //this will loaded all required assemblies
```

**Comment by markcanary** [comment]
Our service lets users load what we call "applications" that render dashboard type content into a web browser. This "applications" can have script that gets compiled and runs. In order to be able to unload these script assemblies that we are generating on the fly, we load each "application" into a separate app domain. My understanding is that the Roslyn initialization time occurs in each new app domain since that is where the script is compiled and loaded. If this is true, it would significantly slow down our load time every time a user loads an application. Am I understanding this correctly?

**Comment by oleg-shilo** [comment]
Not exactly. Roslyn will be initialized per process not per AppDomain.

But you can only truly understand the benefits/impact with some simple profiling.

I am only trying to make a point that you might be limiting yourself by sticking with Mono. Framework vs Core is a different story. Indeed it can be a big porting task. But Mono->Roslyn should be simple enough.

Still.... make a note what I am saying but don't follow my advice unless you have a business case for any change? 😄

**Comment by markcanary** [comment]
OK, that's good to know. I was misunderstanding when the Roslyn compiler initialization happened. We will definitely consider trying the Roslyn compiler and see if the performance is adequate. That seems like a logical step in our migration toward .NET 5.

Thanks for all the help and information.
