### ISSUE TITLE
How to unload file referenced by //css_reference

### ISSUE THREAD

**Issue by cuiliang** [oleg-shilo/cs-script#208]
After executing code which contains `//css_reference path/to/dll.dll`
the file was locked and can not be deleted. 
Is there any way to release reference?

I have added `assembly.UnloaedOwnerDomain()`.
```c#
 var assembly = evaluator.CompileMethod(code);
                    var Exec = assembly.GetStaticMethod("*.Exec", stepContext);
                    Exec(stepContext);                    
                    assembly.UnloadOwnerDomain();
```

Thanks~

**Comment by oleg-shilo** [comment]
Locking is perfectly normal and in fact expected. 
Though I would expect ``UnloadOwnerDomain` to release the file. Unless of course your host app inadvertently loads the referenced assembly too.
    
The simplest way avoid it is to do the referencing from the host code:
```C#
var assembly = evaluator.ReferenceAssembly(Assembly.Load(File.ReadAllBytes("<path/to/dll.dll>")))
                        .CompileMethod(code);
```
That will definitely leave the file unlocked. 
Of course you will need to remove `//css_reference path/to/dll.dll`

**Comment by cuiliang** [comment]
Thank you! @oleg-shilo
