### ISSUE TITLE
Building CSScriptLibrary source code in Visual Studio on Windows results in Mono related errors

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#210]
In normal operation, my CSScript hosting application uses the CSScriptLibrary binaries. All fine there. But for being able to deep dive debug the CSScriptLibrary I have also included the source code into my Visual Studio project. Several of my previously submitted issues used that approach.

So far I have always commented out the Mono related source code in `SystemWideLock` and `*Evaluator*`. Also removed the Roslyn and Mono specific files from the `.csproj`. This is still possible, but a bit cumbersome on each upgrade.

Now my questions:
- How do you handle this? How did you add the Mono assemblies to your environment? Using https://www.mono-project.com/docs/getting-started/install/windows/?
- Would it be possible to guard for `#if (MONO)` and add non-Mono configurations to the `.csproj`?

**Comment by oleg-shilo** [comment]
I am not sure why it is not the case on your environment but I do not have this problem. YOu only need a single Mono assembly that is included in the source code:

![image](https://user-images.githubusercontent.com/16729806/97016612-a9a04f80-1598-11eb-9dc2-5ce02afb4ff6.png)

As a heads up. With the immanent arrival of .NET5 CS-Script will stop support for .NET Framework distro and continue solely the .NET Core model. Exaclty as .NET does from version 5.

Meaning that I will not need to maintain basically two products CS-Script and CS-Script.Core. 
This will simplify the whole API as .NET Core (.NET 5) is not compatible with Mono and CodeDOM is not available neither. Thus the hosting scenarios will narrow down to Roslyn based `CSScript.Evaluator`. Nomore problems with Mono nor separate Roslyn nuget package.

You can start experimenting even now if you convert your host app in .NET Core.

**Comment by maettu-this** [comment]
So far my app isn't distributed on Mono, so I didn't care about the Mono assemblies. Installing Mono and adding that assembly to my project, just for the sake of source code level debugging CS-Script, is not really an option, I would have to remove it again for distributing my app. So, as long as still using .NET Framework, I will just keep on modifying source code and project.

I know, the .NET consolidation is upcoming, finally. Just means quite some efforts for migrating my WinForms app. I'll see when I can possibly do this. There are a bunch of changes I need to implement and release first...

**Comment by maettu-this** [comment]
Indication that Mono will not be dead that quickly?

"Windows Forms is still a Windows-only framework and only runs on Windows" (https://docs.microsoft.com/en-us/dotnet/core/porting/winforms)

Something to consider when making the decision on dropping Mono support from CS-Script?

**Comment by oleg-shilo** [comment]
It is a difficult one. 

It's not me who is dropping Mono support but MS and Mono team. It's them who decides the fate Mono. 

Sadly Mono has dropped support for dynamic code compilation (scripting with _Mono.CSharp.dll_) 4 years ago. Thus the syntax support stuck at the level 2016 (C#6). 
Now when .NET moves to .NET Core direction Mono assemblies simply cannot be used in .NET5 apps. Is't not a product development decision I made but a technical one made by MS/Mono.  

I do not really blame MS/Mono. It's close to impossible to maintain two streams for such a long time. But I cannot do that instead of them neither.

Saying that, CS-Script for .NET Framework will still be available so you can still use it with Mono applications. It just will be limited to what ever Mono team has implemented in 2016. And new CS-Script features will only be developed in _CS0Script.Core_.

**Comment by maettu-this** [comment]
I see. While I do understand the difficulties with maintaining two streams, I do not understand how possibly they can drop support for the longest standing UI option there was, WinForms, on both Windows and non-Windows. UI platform independency is a nightmare, maybe better turn to Java or Qt... No, not willing to drop C#, so stuck again...

I will carefully evaluate the options. Maybe get stuck in 2016. Maybe hope that somebody will eventually bring WinForms to Linux. Maybe dump the option to ever be runnable on Linux. I'll see. Being partially a hobby project, time to completely redo the UI is not exactly what I want to invest at.

**Comment by oleg-shilo** [comment]
There is an effort happening around portable UI:
- Uno Platforn https://github.com/unoplatform 
- Avalonia
- Xamarin
And of course web. With WebAssembly you can consider Blazor static page app. Though the runtime is so limited that you will not get any scripting on it.

**Comment by oleg-shilo** [comment]
And if I am not mistaken there is a community effort porting WPF and WCF to .NET Core and I think thi port is going to be platform neutral.
