### ISSUE TITLE
Wrong indication of source code error location

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#212]
The error message shown in https://github.com/oleg-shilo/cs-script/issues/25#issuecomment-714497110 erroneously states (0,0) instead of the line of the code where 'Library.dll' is referenced.

(Moved from #25 to new issue here.)

**Comment by oleg-shilo** [comment]
Actually in this case the error message is kind of accurate as the error is not triggered by the source code but incorrectly supplied reference (non existing assembly). Thus C# compiler does not supply file name and line/char location.

This yields the cs-script output (that is formatted according `<file>(<ln>,<ch>)`  template) as below:

![image](https://user-images.githubusercontent.com/16729806/98441715-2fed9180-2154-11eb-8512-bb118cda12f7.png)

Though it is the way .NET compiler reports the error I agree that a little cs-script translation of error messages would improve the readability. 

The next release will non-syntax error messages reported as below:

![image](https://user-images.githubusercontent.com/16729806/98441691-0b91b500-2154-11eb-98f7-600b92a82c9d.png)

=============
Fixed. Will be available in the next release.
