### ISSUE TITLE
css_resource seems to wrongly resolve relative path for calling ResGen

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#216]
With #24, CS-Script extended css_resource to support .resx files. With 3.28.3 the attached example (one of the examples of my hosting application) compiles and runs fine. Continuing the full regression tests revealed an issue with css_resource in 3.30.3 as well as 3.30.4, compilation fails:
```
PS C:\_MKY\Temp\cs-script\Issue #216\Windows.Forms> & '.\cscs (3.30.3).exe' .\Script.cs
Error: Specified file could not be compiled.

System.ApplicationException: Cannot compile resources: ResGen : error RG0000: Error while writing the output file "\MT.AlbatrosScript.Examples.Windows.Forms.SomeInfoForm_WithResources.resources"
ResGen : error RG0000: Specific exception: "UnauthorizedAccessException"  Message: "Der Zugriff auf den Pfad "C:\MT.AlbatrosScript.Examples.Windows.Forms.SomeInfoForm_WithResources.resources" wurde verweigert."
2 error(s).

   bei csscript.CSSUtils.CompileResource(String file, String out_name)
   bei csscript.CSExecutor.Compile(String scriptFileName)
   bei csscript.CSExecutor.ExecuteImpl()
```
It seems as if `css_resource` wrongly resolves the relative path for calling ResGen, resulting in a path to the `C:\` root directory.

The example in [Issue #216.zip](https://github.com/oleg-shilo/cs-script/files/5560375/Issue.216.zip) demonstrates the issue. See `!-ReadMe-PowerShell-Log.txt` for PowerShell output with 3.28.3 (success) and 3.30.3 / 3.30.4 (failure). The example contains a `Form` without resources and a `Form` with local resources. In addition, the project contains the standard Visual Studio generated project resources in `\Properties`.

**Comment by maettu-this** [comment]
PS: The relative path issue we discussed in #107 is not the explanation for this new issue. The path to ResGen is wrong no matter whether `ResolveRelativeFromParentScriptLocation` is `true` or `false`.

**Comment by oleg-shilo** [comment]
Not sure if it is a problem. Your sample works just fine for me:
![image](https://user-images.githubusercontent.com/16729806/99582883-cfedc980-2a36-11eb-8d24-b8ef13d0705b.png)

not sure what is happening.

**Comment by oleg-shilo** [comment]
OK, got your sample working. It triggers the failure on C drive

**Comment by oleg-shilo** [comment]
Solved, the issue was caused by the fact that `//css_res` is a special directive that can have more than a single path. Thus in the `//css_res .\file.rsx, .\file.sesource` only '.\file.rsx' was expanded correctly.

**Comment by maettu-this** [comment]
Wow, that quick was fix! No need to hurry with a 3.30.5 HotFix, I need at least another week to complete the upcoming release.

**Comment by maettu-this** [comment]
Any idea by when a 3.30.5 HotFix or FullRelease can be expected?

**Comment by oleg-shilo** [comment]
I will make a full release if there are more fixes or new features to be released. 
Currently there are none in the pipeline. All dev focus now is on .NET5.

If you are waiting I can bring it forward but to be accurate.... there were no `3.30.5 HotFix` release. only "3.30.3".
The fix for this issue is committed but it was never released.

Ami missing something?

**Comment by maettu-this** [comment]
With "HotFix 3.30.5" I was following the [HotFix 3.30.4](https://github.com/oleg-shilo/cs-script/releases/tag/v3.30.4.0) scheme. Since there are no new features in the pipeline, and thus no full release can be expected, I'd appreciate a HotFix to this very issue.

**Comment by maettu-this** [comment]
PS: I have noted the open https://github.com/oleg-shilo/cs-script/pull/178. Just in case that got forgotten.

**Comment by maettu-this** [comment]
May I ask again, I'd really appreciate a HotFix to this very issue, as I prefer basing my hosting app on "official" releases rather than having to build the `CSScriptLibrary.dll` by myself, eventually resulting in binarily different 3.30.5 builds.

**Comment by oleg-shilo** [comment]
oh my!
I was sure I have merged it. I even thanked the author.

Merged now. Will do the release very soon. Hopefully on weekend.

**Comment by oleg-shilo** [comment]
Done: https://www.nuget.org/packages/CS-Script.lib/

**Comment by maettu-this** [comment]
Verified with https://github.com/oleg-shilo/cs-script/releases/tag/v3.30.5.0-pre and the example attached further above, works 👍

**Comment by oleg-shilo** [comment]
Great. 
Promoted to the release: https://www.nuget.org/packages/CS-Script.lib/3.30.5.1
