### ISSUE TITLE
Accessing hosting application method from the hosted script

### ISSUE THREAD

**Issue by SadE54** [oleg-shilo/cs-script#217]
Hi, I'm new to CS script and I would be able to call some methods defined in my c# application from the hosted script itself . 
For example:
In my application I have a method ProcessCommand(string command) { ... }
An I would like something like that in my script

public ProcessSeveralCommands()
{
 ProcessCommand("first command");
ProcessCommand("second command);
}

I don't figured out the good way to get it working despite the documentation. I guess I missed something :)

**Comment by oleg-shilo** [comment]
When hosting the script engine by default all current AppDomain assemblies are available from the script. Meaning that you need to pass to your script the instance of your app or call static methods directly.

Here is some reading on the topic: https://github.com/oleg-shilo/cs-script/wiki/Hosted-Script-Execution
