### ISSUE TITLE
Release 3.30.4 binaries are dated 2020-05-30 even though released 2020-12-12

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#219]
Something seems to have gone wrong while releasing:

![Bin NET 4 5](https://user-images.githubusercontent.com/24897735/102241946-d4a08300-3ef9-11eb-8d26-887d73ec1fb6.png)

Note that `\cs-script\lib\CSScriptLibrary.dll` is properly dated 2020-12-12, whereas the `.xml` is 2020-05-30 as well.

Also, the trick to release https://github.com/oleg-shilo/cs-script/releases/tag/v3.30.4.0 as well as https://github.com/oleg-shilo/cs-script/releases/tag/3.30.4.0 is likely confusing, especially given that previous releases all used the "v" whereas the current "v" release just is the hotfix. How about replacing the current release with a 3.30.5 instead?

**Comment by oleg-shilo** [comment]
Will need to check the distro. 
Not sure what's wrong with the packaging.
I had to use an alternative dev environment as the default one is completely configured for building with .NET5.

This is one of the reasons why I am trying so hard to converge these two dev streams: .NET Framework + .NET Core.
Maintaining both of them is inviting errors like that. 

As for "v" or no "v" it does not matter. it is just a tag name. It is inconsistent but functional. I was rushing and did not realize that there was a collision between public and pre-releases versions so had to drop "v" to avoid tag duplication. 

I may rerelease but strictly speaking it's not required. As all public releases are continuously versioned here (GitHub) and on nuget.org. And I can even delete the conflicting pre-released from GitHub and as it was not published on nuget.org anyway.

**Comment by maettu-this** [comment]
I have also checked to 3.30.4 NuGet package:
![NuGet packages also dated 2020-05-30](https://user-images.githubusercontent.com/24897735/102589470-56b5c500-410f-11eb-9204-a64d4f216914.png)

And indeed:
![NuGet packages indeed states version 3 30 3 0](https://user-images.githubusercontent.com/24897735/102589480-5c130f80-410f-11eb-9a73-6944ee2275d1.png)

So the **released 3.30.4 indeed is 3.30.3 !!!**

**Comment by oleg-shilo** [comment]
Thank you. You are right. Indeed packaging script has picked the wrong binaries.

I have done repackaging but just in case released it as a pre-release so you can check it before it goes completely public.

Please let me know if it's all working for you and I will elevate the NuGet pre-release (v3.30.5-pre) in to proper one.

**Comment by maettu-this** [comment]
Hmm...

NuGet doesn't show me anything higher than 3.30.4, checking the `.7z` distro instead.

More recent releases always contained various platform releases in `\lib\Bin\`. This release doesn't. Assuming `\lib\CSScriptLibrary.dll` is the NET45 one.

Then, `\lib\CSScriptLibrary.xml` still dates 2020-05-30, maybe something is still wrong in the release scripts.

**Comment by oleg-shilo** [comment]
NuGet by does not list pre-releases as the default package. One needs to go to the package history to see all pre-releases.

**Comment by oleg-shilo** [comment]
Done. The pre-release published now as a production release: https://www.nuget.org/packages/CS-Script.lib/3.30.5.1

Yes all older targets are removed and only NET45 is left. 
And you are right the packaging script was picking `CSScriptLibrary.xml` from the incorrect folder. Fixed in the latest NuGet package.
