### ISSUE TITLE
Reason for not defining TRACE when compiling without the debug flag

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#220]
This inquiry is somewhat related to #25.

The lines in question are `csscript.cs` #1726ff:
```
            if (options.DBG)
                Utils.AddCompilerOptions(compilerParams, "/d:DEBUG /d:TRACE");
```
When the debug flag is enabled, all is fine. But when disabled, `TRACE` no longer get's defined. This is opposite to e.g. Visual Studio, which by default defines `TRACE` in `Release` configurations. What is the reason for this behavior in CS-Script, i.e. the reason for not always defining `TRACE`?

And, is there any way to retrieve the defined symbols out of a script? Probably not, e.g. `CSScript.LastCompilingResult` is `null` from within a script and `.Input.CompilerOptions` only contains the input options anyway, but not those added by `csscript.cs` itself, right? Haven't found the information in neither wiki nor `CSScript.chm` nor `CSScriptLibrary.chm` nor `\cs-script\samples\Hosting\Legacy Samples\CodeDOM\ConditionalCompilation.cs`. Maybe the only way is to go through each code path in `csscript.cs` and see which symbols get defined under which conditions.

**Comment by maettu-this** [comment]
OK, I have further analyzed the topic and realized that `.Input.CompilerOptions` does contain all symbols. So this is fine.

But, in addition to the question why not always defining `TRACE`, isn't using `true` (`Environment.SetEnvironmentVariable(item, "true");`) by `TunnelConditionalSymbolsToEnvironmentVariables()` a bit strange? Wouldn't defining it to `1` be more appropriate?

**Comment by oleg-shilo** [comment]
Re TRACE

No particular reason. `DEBUG` is truly necessary symbol but the `TRACE` is of a lesser value. Though I do agree there is no harm in matching the VS debug vs release model. Done in the latest pre-release: https://github.com/oleg-shilo/cs-script/blob/579be70c259a2f370333efb58850ab8adb063f2a/Source/Settings.cs#L262-L265. 

As for TunnelConditionalSymbolsToEnvironmentVariables I am not sure `1` is more appropriate as it implies possibility of more 2 values. Whereas `true` is more aligned with the boolean nature of the use-case for C# conditional symbols which is "defined or not defined". But of course both approaches will work.

**Comment by oleg-shilo** [comment]
Please let me know if the `Trace` fix worked for you () and I will elevate the NuGet pre-release (v3.30.5-pre) in ta proper one.

**Comment by maettu-this** [comment]
The value of `TRACE` is mainly given by the functionality of `System.Diagnostics.Trace`, which is disabled when `TRACE` is not defined.

**Comment by maettu-this** [comment]
I do agree that `true` is more logical these days, `1` is more something from the "old" days, e.g. C, `true` is fine.

**Comment by maettu-this** [comment]
I'll check 3.30.5-pre tomorrow and give you feedback.

**Comment by maettu-this** [comment]
Some more thoughts on `TRACE`:

While it is true that VS projects by default define `TRACE` for Debug and Release configurations, the user can still remove it. This will no longer be the case with CS-Script, `TRACE` will always be defined. However, already in the past, when `debugBuild` was enabled, `TRACE` also got defined without giving the user the possibility to remove it. So I think the new behavior of always defining `TRACE` is a better and more consistant behavior than before. Still, if someone requires CS-Script **not** defining `TRACE`, the API or the configuration might need to forsee such option. For my use cases, always defining `TRACE` is perfectly fine.

**Comment by maettu-this** [comment]
Verified including tunneling:
```
using System;
using System.Collections;
using System.Collections.Generic;

namespace Issue220
{
	public static class Script
	{
		public static int Main()
		{
		#if (TRACE)
			Console.WriteLine("TRACE OK");
		#else
			TRACE NOT OK
		#endif

			Console.WriteLine("Environment variables for the current process:");
			var envVars = Environment.GetEnvironmentVariables();

			var sorted = new SortedDictionary<string, string>();
			foreach (DictionaryEntry var in envVars)
				sorted.Add(var.Key.ToString(), var.Value.ToString());

			foreach (var var in sorted)
				Console.WriteLine("    {0} = {1}", var.Key, var.Value);

			return (0);
		}
	}
}
```
Environment variables defined when running the script:
```
TRACE OK
Environment variables for the current process:
    ...
    TRACE = true
    ...
```

**Comment by oleg-shilo** [comment]
Thank you. 
Rereleased as a production package https://www.nuget.org/packages/CS-Script.lib/3.30.5.1
