### ISSUE TITLE
CS_SCRIPT does not get tunneled through env vars

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#221]
Related to #25 I found that the `CS_SCRIPT` symbol gets defined on compilation but does not get tunneled through env vars. I think this is a bug, as the `CS_SCRIPT` symbol by documentation is expected to be always defined.

**Comment by maettu-this** [comment]
Script demonstrating this issue:

```
using System;
using System.Collections;
using System.Collections.Generic;

namespace Issue221
{
	public static class Script
	{
		public static int Main()
		{
			Console.WriteLine("Environment variables for the current process:");
			var envVars = Environment.GetEnvironmentVariables();

			var sorted = new SortedDictionary<string, string>();
			foreach (DictionaryEntry var in envVars)
				sorted.Add(var.Key.ToString(), var.Value.ToString());

			foreach (var var in sorted)
				Console.WriteLine("    {0} = {1}", var.Key, var.Value);

			return (0);
		}
	}
}
```

Environment variables defined when running the script:
```
    ...
    ComSpec = C:\WINDOWS\system32\cmd.exe
    cscs_exe_dir = D:\Temp\YAT\3rd Packages\CS-Script\Issue #221
    css_nuget = C:\ProgramData\CS-Script\nuget
    CSScriptRuntime = 3.30.3.0
    CSScriptRuntimeLocation = D:\Temp\YAT\3rd Packages\CS-Script\Issue #221\cscs.exe
    DEVMGR_SHOW_NONPRESENT_DEVICES = 1
    ...
```

**Comment by oleg-shilo** [comment]
It's an interesting one. All compiler options are tunneled as they specified by user either from code or CLI args.
But I agree it would be more logical to tunnel even default one that are cumming from the settings or any other source.

Done. Will be available in the next release.

Please be aware that `RoslynEvaluator`  does not using any compiler options. It just does not have an interface for it.
