### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by egkareem** [oleg-shilo/cs-script#222]
Hello, 
1-I can't find a single complete example of how to use CS-Script in a .NET Console or winforms application! Say I have a file containing c# code that I need to compile and execute, and get the result. What do I do?
2-What is the difference between using CS-Script and the method described here:
https://docs.microsoft.com/en-us/troubleshoot/dotnet/csharp/compile-code-using-compiler
?
3-Is running CS-Script multiple times memroy friendly?
4-Could a solution built with CS-Script deployed without the end-user having to download components manually?

Thank you very much.

**Comment by oleg-shilo** [comment]
1. Have a look at https://github.com/oleg-shilo/cs-script/tree/master/Source/deployment/samples
If you need to compile a C# code into exe you are not really executing it as a script but converting into an executable exactly as VS does.
Though you can use CS-Script for that too:
    ```
    cscs -e ?
    ```  
2. The same principle. But CS-Script let's you use multi-file scripts and does heavy lifting when it coms to referencing and assembly probing. CS-Script also supports latest C# syntax whereas CSharpCodeProvider does not. Though CS-Script for .NET Framework needs an extra config step for that. CS-Script.Core does not. 

3. When you are running your scripts from CLI the execution of scripts is as memory friendly as running any executable.

4. Yes it can but you will need to include Script engine to your distro. I assume you are referring to the app that hosts script engine

**Comment by egkareem** [comment]
Excellent, I will study the samples in the provided link. 
Thank you much.
