### ISSUE TITLE
Support now. Net 5?

### ISSUE THREAD

**Issue by ananck** [oleg-shilo/cs-script#224]

**Comment by oleg-shilo** [comment]
.NET5 release (preview) for CLI is available on Choco from 19 Oct 2020: https://chocolatey.org/packages/cs-script.core/1.4.2.0-preview

Though I have just published the release for the public build of .NET 5 runtime and this release also includes support for script hosting (CSScriptLib.dll).

The release is still marked as pre-release (RC3) as there are still some u-testing to be extended, documentation and WIKI updated and the binaries are to be published on Choco+NuGet. But the release is functionality-complete.

Meaning that if you don't mind downloading it from GitHub then you can start using it right away: https://github.com/oleg-shilo/cs-script.core/releases/tag/v1.4.3.0-.NET5-RC3

**Comment by oleg-shilo** [comment]
Also have a look at [Roadmap](https://github.com/oleg-shilo/cs-script/wiki/Roadamap) to see what to expect

**Comment by ananck** [comment]
> .NET5 release (preview) for CLI is available on Choco from 19 Oct 2020: https://chocolatey.org/packages/cs-script.core/1.4.2.0-preview
> 
> Though I have just published the release for the public build of .NET 5 runtime and this release also includes support for script hosting (CSScriptLib.dll).
> 
> The release is still marked as pre-release (RC3) as there are still some u-testing to be extended, documentation and WIKI updated and the binaries are to be published on Choco+NuGet. But the release is functionality-complete.
> 
> Meaning that if you don't mind downloading it from GitHub then you can start using it right away: https://github.com/oleg-shilo/cs-script.core/releases/tag/v1.4.3.0-.NET5-RC3

OK. Thank you

**Comment by oleg-shilo** [comment]
BTW, executing `css -?` prints the WHOLE documentation. It's a lot. I specifically wanted the executable to be fully descriptive.
While this does not replace wiki it is sufficient enough to get anyone going.

cs-script for .NET Fx output even captured in the repo: https://github.com/oleg-shilo/cs-script/blob/master/help.txt

But for cs-script for .NET Core you will need to execute `css -? > help.txt`
