### ISSUE TITLE
Feature Request: Start with default code

### ISSUE THREAD

**Issue by BrownCoatJustice** [oleg-shilo/cs-script#227]
Hey just wanted to request a feature I use this engine in Notepad ++ and I thought the team should add a new feature which enters some pretext or will add some default code pieces like class declaration.

Although I am a starter to C# I would like to have this feature

**Comment by oleg-shilo** [comment]
Depending on the version you are using the CLI app will be able to create a new script of a specific app type:
```text
C:\dev\temp>css -new ?
-new[:<type>] [<script name>]
    Creates a new script.
    Usage: -new[:<type>] [<otput file>]
          type - script template based on available types.
          output - location to place the generated script file(s).
    Type           Template
    ---------------------------------------------------
    console         Console script application (Default)
    console-vb      Console VB script application
    winform        Windows Forms (WinForms) script application
    winform-vb     Windows Forms (WinForms) VB script application
    wpf             WPF script application
    wpf-cm          Cliburm.Micro based WPF script application
    toplevel|top    Top-level class script application with no entry point
                    (avaliable on C# 9 only)
    Legacy templates:
    auto            Auto-class (classless) script application; use 'toplevel' instead
    freestyle       Free style (no entry point) script application; use 'toplevel' instead
    Examples:
        cscs -new script
        cscs -new:toplevel script.cs
        cscs -new:console console.cs
        cscs -new:winform myapp.cs
        cscs -new:wpf hello
```
Though this feature is implemented in .NET Core  and .NET 5 version of the script engine.

And Notepad++ distribution of CS-Script is only about to get updated to .NET5 edition.
Though even this older edition has the ability to create the proper _new scripts_ with a class declaration: 


![image](https://user-images.githubusercontent.com/16729806/106136222-1c831d00-61bd-11eb-9a71-a055faea2e8a.png)
