### ISSUE TITLE
Unsupported syntax

### ISSUE THREAD

**Issue by snikeguo** [oleg-shilo/cs-script#23]
e.g. 
public int field{get;set;}=48;

 compile error.

**Comment by oleg-shilo** [comment]
https://github.com/oleg-shilo/cs-script/wiki/C%236.0-support

**Comment by snikeguo** [comment]
@oleg-shilo 
In the Linux system, how to set？

**Comment by snikeguo** [comment]
How to operate without using “"//css_args /provider:%CSSCRIPT_DIR%\lib\CSSCodeProvider.v4.6.dll "”?

**Comment by oleg-shilo** [comment]
The same way: 
* Either in css_config.xml (use absolute path if CSSCRIPT_DIR is not set). Though you cannot use GUI and this needs to be done manually.
* Or from code with `//css_args /provider:[path]` 

Though you don't need to. On Linux the latest Mono (v4.6.2) already supports C#6

**Comment by snikeguo** [comment]
OK， Thanks~~.
(^_^)

**Comment by oleg-shilo** [comment]
One thing I forgot to mention it has to be `mono-complete` (http://www.mono-project.com/docs/getting-started/install/linux/)
