### ISSUE TITLE
Issue moving from 1.4.2 (preview) to 2.0

### ISSUE THREAD

**Issue by RubberUK** [oleg-shilo/cs-script#231]
Hi Oleg,

I hope you can help me please!

I use a method called 'ReadyScriptEngine' on my application start-up because of a big delay when the first CSScript is run, So I hide the delay within my splash screen.

But when I upgraded from version 1.4.2 (preview) to version 2.0 it causes an error when running my code. The below method does run but then I will get an error further on in my code. It is almost like my code cannot see the reference assembly any longer??? 

The error I get is;
WPF control throwing 'resource identified by the URI missing' exception

protected virtual void ReadyScriptEngine()
        {
            Application.Current.Dispatcher.Invoke(() =>
            {
                ShowSplashScreen("Ready script engine, please be patient...");
                CSScript.EvaluatorConfig.Engine = EvaluatorEngine.Roslyn;
                CSScript.Evaluator.ReferenceAssembly(Assembly.GetAssembly(typeof(DevExpress.Spreadsheet.Workbook)));
                string code = @"using DevExpress.Spreadsheet;
                            using System.Drawing;
                            using System.Diagnostics;
                            using Microsoft.Data.SqlClient;
                            using System.Collections.Generic;
                            using System.Data;
                            using System.Linq;

                            public class Script
                            {
                                public void ReadyEngine()
                                {
                                    // Create a new workbook.
                                    Workbook workbook = new Workbook();

                                    // Access the first worksheet in the workbook.
                                    Worksheet worksheet = workbook.Worksheets[0];

                                    // Set the unit of measurement.
                                    workbook.Unit = DevExpress.Office.DocumentUnit.Point;

                                    workbook.BeginUpdate();
                                    try
                                    {	
                                        // Create a multiplication table.
                                        worksheet.Cells[""A1""].Value = "" * "";
                                        for (int i = 1; i < 11; i++)
                                        {
                                            // Create the header column.
                                            worksheet.Columns[""A""][i].Value = i;
                                            // Create the header row.
                                            worksheet.Rows[""1""][i].Value = i;
                                        }

                                        // Multiply values of header cells.
                                        worksheet.Range[""B2:K11""].Formula = ""=B$1*$A2"";

                                        // Obtain the data range.
                                        CellRange tableRange = worksheet.GetDataRange();

                                        // Specify the row height and column width.
                                        tableRange.RowHeight = 40;
                                        tableRange.ColumnWidth = 40;

                                        // Align the table content.
                                        tableRange.Alignment.Horizontal = SpreadsheetHorizontalAlignment.Center;
                                        tableRange.Alignment.Vertical = SpreadsheetVerticalAlignment.Center;

                                        // Fill the header cells.
                                        CellRange headerCells = worksheet.Range.Union(worksheet.Range[""A1:K1""], worksheet.Range[""A2:A11""]);
                                        headerCells.FillColor = Color.FromArgb(0xf7, 0x9b, 0x77);
                                        headerCells.Font.Bold = true;

                                        // Fill cells that contain multiplication results.
                                        worksheet.Range[""B2:K11""].FillColor = Color.FromArgb(0xfe, 0xf2, 0xe4);
                                    }
                                    finally
                                    {
                                        workbook.EndUpdate();
                                    }

                                // Calculate the workbook.
                                workbook.Calculate();        
                                }

                            }";

                dynamic script = CSScript.Evaluator.LoadCode(code);
                script.ReadyEngine();
            });
        }

**Comment by oleg-shilo** [comment]
I am not sure what exactly is the problem you are experiencing but one think is definitely incorrect in the sample you shared.

`CSScript.Evaluator` always return a new instance of `Evaluator`. Thus you add reference to one evaluator but call `Evaluator` but load script in another one.

You will need to follow the call pattern as it is shown in the code samples:

```C#
CSScript.EvaluatorConfig.Engine = EvaluatorEngine.Roslyn;
dynamic script = CSScript.Evaluator.ReferenceAssemblyOf<DevExpress.Spreadsheet.Workbook>()
                                   .LoadCode(code); 
```

or 

```C#
CSScript.EvaluatorConfig.Engine = EvaluatorEngine.Roslyn;

var eval = CSScript.Evaluator;
eval.ReferenceAssemblyOf<DevExpress.Spreadsheet.Workbook>();
dynamic script = eval.LoadCode(code); 
```
Note that you can reference assembly by the type it implements with `ReferenceAssemblyOf`.
