### ISSUE TITLE
Can the body of the method be dynamically compiled 

### ISSUE THREAD

**Issue by HalfasonYc** [oleg-shilo/cs-script#236]
Can the body of the method be dynamically compiled just？Using 'this' context, other properties or methods.

E.g.  

    public class TestClass : BaseClass, IOtherInterface
    {
          readonly static Logger _Logger = LoggerFactory.GetLogger(nameof(TestClass));
          /*.....Other Property or Method etc.....*/
          public async Task MainTest()
          {
                 /*dynamic method body */
                 /*Different logic using _Logger, other property and method*/
                 /*Except for this method, the basic instance members remain unchanged */
          }
    }

thx!

**Comment by oleg-shilo** [comment]
Is this what you mean?
```C#
dynamic script = CSScript.RoslynEvaluator
                         .LoadMethod(@"public object func()
                                    {
                                        return new[] {0,5};
                                    }");

var result = (int[])script.func();
```

**Comment by HalfasonYc** [comment]
It's not static method. Method body contains other object instance's property or field.

---Original---
From: "Oleg ***@***.***&gt;
Date: Tue, Apr 20, 2021 16:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [oleg-shilo/cs-script] Can the body of the method be dynamically compiled  (#236)




 
Is this what you mean?
 dynamic script = CSScript.RoslynEvaluator                          .LoadMethod(@"public object func()                                     {                                         return new[] {0,5};                                     }"); var result = (int[])script.func();

**Comment by oleg-shilo** [comment]
Give me example of what you are trying to achieve

**Comment by HalfasonYc** [comment]
[CSScriptDemo.zip](https://github.com/oleg-shilo/cs-script/files/6366825/CSScriptDemo.zip)
see region block.

**Comment by HalfasonYc** [comment]
I upload it. Can?



---Original---
From: "Oleg ***@***.***&gt;
Date: Fri, Apr 23, 2021 19:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [oleg-shilo/cs-script] Can the body of the method be dynamically compiled  (#236)




 
Give me the example of what you are trying to achieve

**Comment by oleg-shilo** [comment]
Sorry, your example does not contain any use of CS-Script. Did you send me the wrong sample?
