### ISSUE TITLE
How to terminate a script

### ISSUE THREAD

**Issue by pazicb** [oleg-shilo/cs-script#237]
I have a script running
dynamic script = CSScript.LoadCode (modelRun) .CreateObject ("*")
script.execute (null);
How can I programmatically terminate the execution of this script?

**Comment by oleg-shilo** [comment]
It's tricky.

C# script is effectively an assembly that is compiled on-fly. 

Meaning that if you have a class `<my_class>` in your assembly `modelRun.dll` and you want to terminate  the method `<my_class>.execute(null)` after you call it... you will have the same challenge as you do now.

The chellenge you are describing is not a scripting problem but a programming problem. I am not aware about any runtime that allows you to terminate the execution of the call in progress. Possibly highly dynamic languages can do it but CLR cannot.

The closes behavier that mimics your scenario is to run your routine in a separate thread/task and abort the whole thread.

**Comment by pazicb** [comment]
Thank you for answer. And I have one more question. I have a variable eg public static bool stop = false in class Calculation.
I read the value Calculation.stop in the script. However, if I change Calculation.stop = true by another application while the script is running, the script still reads false.

**Comment by oleg-shilo** [comment]
Please post your code here. It's not entirely clear what it means "I have a variable". 
It supposed to work so I am happy to have a look at it but you need to share the test case so I can look at it.
