### ISSUE TITLE
AsmHelper replacement

### ISSUE THREAD

**Issue by zubialevich** [oleg-shilo/cs-script#238]
Hi,

It's not an issue, more of a question.

I used old version of cs-scrip on .net 4.7.1 and it has AsmHelper to prevent from memory leaks.
And this worked pretty well, and memory on mono was used pretty effective.

But after migration to .net 5 I can't find AsmHelper anymore and memory started to leak again.

Are there any recommended ways of migration from AsmHelper or memory clean up?

Thank you!

**Comment by oleg-shilo** [comment]
AsmHelper was designed to solve two problems:
1. Simplify calling members of the dynamically loaded assemblies.
2. Allow unloading dynamically loaded assemblies

First problem was solved via not ideal but much simpler dispatch style syntax.
Second problem was solved via not ideal but working AppDomain based `IDisposable` syntax. 

However with the latest advances of C# both problems are now solved directly and rather nicely 😄 :
1. Via `dynamic` type.
2. Via `AssemblyLoadContext.Unload`

Thus the need for AsmHelper is no longer there. 

Please have a look at this sample. It might be exactly what you are looking for: 
https://github.com/oleg-shilo/cs-script/blob/ac885f8042dbe0ceb18f0f87ef8236a019b13894/src/CSScriptLib/src/CSScriptLib/samples.cs#L61

**Comment by oleg-shilo** [comment]
Basically the solution looks something like that:

```C#
var  asm = new AssemblyLoadContext(isCollectible: true);

CSScript.Evaluator
        .ReferenceAssemblyOf<ICalc>()
        .CompileAssemblyFromCode(
              @"using System;
                public class Script : ICalc
                {
                    public int Sum(int a, int b)
                    {
                        return a+b;
                    }
                }", asmFile);

ICalc script = (ICalc)asm.LoadFromAssemblyPath(asmFile)
                         .CreateObject("*"); // or `CreateInstance("css_root+Script")`

int result = script.Sum(1, 3);

asm.Unload();
```

**Comment by zubialevich** [comment]
Great!

As I see it works in case when we want to compile our code as an assemly in a file.
What if we want to keep it all in memory, without off loading it to a file?

Is there a way to unload assembly in this case?

**Comment by oleg-shilo** [comment]
Your request have triggered some thoughts :) and in result I have re-implemented assembly loading routine of CSScriptLib to allow loading it into  "IsCollectible" `AssemblyLoadContext` and combine it with the `Assembly.Unload()` extension method.

It uses heavy reflection to set up the `AssemblyLoadContext` at runtime without user involvement. Thus the result API is ultimately dev-friendly:

https://github.com/oleg-shilo/cs-script/blob/4e2ce98a87247680fd64184d008327e2d385b368/src/Tests.CSScriptLib/Evaluator.Roslyn.Tests.cs#L31

```C#
[Fact]
public void call_UnloadAssembly()
{
    // CSScriptLib.Runtime.DisableAssemblyUnloading = true;

    dynamic script = CSScript.RoslynEvaluator
                             .LoadMethod(@"public object func()
                                           {
                                               return new[] {0,5};
                                           }");

    var result = (int[])script.func();

    var asm_type = (Type)script.GetType();

    asm_type.Assembly.Unload();
}

``` 

The feature will be available with the very next release
