### ISSUE TITLE
Error evaluating cs-script with touchscreen enabled

### ISSUE THREAD

**Issue by ghost** [oleg-shilo/cs-script#239]
Hello,
we are using cs-script library v. 3.30.5.1 from NuGet in a big production project, but, due to this bug:
https://supportcenter.devexpress.com/ticket/details/t431199/serialization-xrserializationexception-is-thrown-on-an-attempt-to-load-a-report-when-a

we have been stepping into the infamous issue (already mentioned in the forum, but not fully grasped in my opinion) : "The type 'System.Attribute' is defined in an assembly that is not referenced [...]" while evaluating a cs script. Just note that this happens only when the touchscreen is enabled (as it kicks in WinRT wmd stuff). In fact, a straightforward workaround is to switch off the touchscreen driver in the system devices.

To fully fix this, instead, I had to patch version 3.50.5.1, so I am asking if it would be possibile/make sense to bring such fix upstream, or maybe if you suggest a totally different way.
Here the details.
We need to isolate the script execution environment so as to exclude the dlls WINDOWS.UI.WINMD and WINDOWS.FOUNDATION.WINMD from being chain-loaded by the various dependencies. Unfortunately, this cannot be done with GetReferenceAssemblies(), as that brings as a side-effect the LoadFrom(), which triggers the error in the aforementioned conditions. So we first need to merely get the list of involved assemblies. This is the fix that I came up with.

```
		private static readonly string[] _assemblyExclusionList = new string[]
		{
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.AI.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.ApplicationModel.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.Data.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.Devices.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.Foundation.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.Gaming.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.Globalization.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.Graphics.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.Management.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.Media.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.Networking.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.Perception.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.Security.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.Services.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.Storage.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.System.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.UI.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.UI.Xaml.winmd",
			"C:\\WINDOWS\\SYSTEM32\\WINMETADATA\\Windows.Web.winmd"
		};

        protected static AsmHelper CreateSandboxedHelper(string scriptClass)
        {
            AsmHelper helper;
            // Preparazione dell'ambiente in cui risolvere gli assembly per non avere conflitti
            CSScript.ShareHostRefAssemblies = false; // si crea un ambiente isolato dal sistema, proprio per non avere problemi, ma questo
                                                     // richiede di caricare le dipendenze singolarmente
            CSScript.AssemblyResolvingEnabled = false;
            CSScript.EvaluatorConfig.Engine = EvaluatorEngine.CodeDom;
            CSScript.Evaluator.DisableReferencingFromCode = false;
            var evalContext = CSScript.Evaluator.ReferenceAssembliesFromCode(scriptClass);
            var followedRefAssLocations = evalContext.GetReferencedAssembliesPaths();
            followedRefAssLocations.RemoveAll(s => _assemblyExclusionList.Contains(s, StringComparer.CurrentCultureIgnoreCase));
            helper = new AsmHelper(CSScript.LoadCode(scriptClass, followedRefAssLocations
                .Select(i => i)
                .Distinct()
                .ToArray()));
            return helper;
        }
```

Would it be possible to expose this self-explaining method (overloaded), GetReferencedAssembliesPaths() so that this fix can be ported upstream to your library?

```
        public List<string> GetReferencedAssembliesPaths()
        {
            return _referencedAssemblies;
        }
```

Thanks in advance.

**Comment by oleg-shilo** [comment]
I think it is an fact a great idea to allow assembly exclusions. 

The problem is of bringing the feature in the product. The version you are using is an old .NET Framework version and currently CS-Script can only rely on .NET Core (.NET5). This in tern forced me to drop [CSScript.Native](https://github.com/oleg-shilo/cs-script.net-framework/wiki/Choosing-Compiler-Engine#csscriptnative)  interface (the one that you are using) because .NET5 has dropped completely support for CodeDOM. Thus the current CS-Script only supports [CSScript.Evaluator](https://github.com/oleg-shilo/cs-script.net-framework/wiki/Choosing-Compiler-Engine#csscriptevaluator) due to the framework limitations imposed by the recent .NET versions (starting from .NET5)

Thus bringing this functionality the way you are asking is not possible. But... I am going to bring in in the Evaluator with some alternative API. Something like this:

```C#
dynamic script = CSScript.RoslynEvaluator
                         .SetRefAssemblyFilter(asms => asms.Where(a => !a.GetFileName().Contains("WINMD")))       
                         .SetRefAssemblyFilter(asms => asms.Except(exclusionAssemblyList))        
                         .LoadMethod(@"public object func()
                                    {
                                        return new[] {0,5};
                                    }");
```

Saying that, if you truly need to patch the older version we can still do it as a parallel fork for this does not exist: https://github.com/oleg-shilo/cs-script.net-framework.

**Comment by mcecchistark** [comment]
Hello Oleg,
thanks for your reply. It's good that you liked the approach.
As for the .NET5 version of your library, it looks great that you are planning to include such an API to exclude assemblies from loading. Unfortunately for us, it will still be a long way to go before we migrate. So if 3.30.5.1 is too outdated, maybe it would be easier for you to patch the latest pre .Net 5 version (and for us to migrate)? I actually do not know what number that would be on top of my head, but what do you think?

Thanks,
Marco

**Comment by mcecchistark** [comment]
I see, the version that I took from NUGet, CS-Script.lib, is the latest pre 4.0 already. So I took the right version, indeed.
Just let me know in case you are willing to port the suggested API addition on that version.

Thanks in advance,
Marco.
