### ISSUE TITLE
Feature request to support .resx compilation and embedding intrinsically

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#24]
Hi Oleg,

As discussed via email, I request support for intrinsic .resx compilation and embedding. The support may be provided by css_resource/css_res or another css_... statement.

Use case/sequence:

1. A form (e.g. MyForm, derived from System.Windows.Forms.Form) is created using the Visual Studio designer. Some kind of resource is added to the form, e.g. an image or a long string, resulting in MyForm.resx and MyProject\Properties\Resources.resx files created by the designer.
2. The form shall be referenced/loaded by a css script, by //css_import .\MyForm.cs; and //css_import .\MyForm.Designer.cs; (which currently results in a "MissingManifestResourceException was unhandled by user code" due to the missing resource file). The designer generated .resx file shall be referenced directly, without the need to first compile it to a .resource file.

Rationale/background info:

- Designer generated forms shall be usable by scripts, without the need to first compile the .resx file.
- Generating the .resource file by res.cs technically works, but...
  - ...requires a script user to perform two steps, and...
  - ...requires to either install the CSScript extensions, just res.cs, or a clone of that script at the user's machine. This prevents use cases where an application (MyApp.exe) embeds CSScriptLibrary.v<x.y>.dll and provides script functionality to some (dummy) user of the application, who does not need to know the very details of CSScript, and does not need to install CSScript and the CSScript extensions at his target machine.

Suggested preferred solution:

```
//css_import .\MyForm.cs;
//css_import .\MyForm.Designer.cs; 
//css_import .\MyForm.resx;  =>  css_import automatically detects this as a resource and compiles and embeds it.
```

Suggested alternative solution:

```
//css_import .\MyForm.cs;
//css_import .\MyForm.Designer.cs; 
//css_resource .\MyForm.resx;  =>  css_resource compiles and embeds the resource.
```

Thanks & Best regards,
Matthias

**Comment by oleg-shilo** [comment]
The fix is available in the v3.20.0 release (https://github.com/oleg-shilo/cs-script/releases/tag/v3.20.0)

**Comment by maettu-this** [comment]
I have verified the feature with v3.20.0 and it works, thanks!

However, I am **requesting a change to the implementation**. Currently, it seems that "ResGen.exe" is invoked. I request to only invoke "ResGen" and let the system find out whether an .exe or something else is meant.

Rationale:
ResGen is e.g. located in "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\ResGen.exe". I don't want to add that path to PATH, as it contains much more. And, I already have a "C:\Program Links" folder which I have already added to PATH. There, I have placed a "ResGen.cmd":
`call "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\ResGen.exe" %*`

Advantages:
+ No need to fully install CSScript (= defining %CSSCRIPT_DIR%) on the computer running the script.
+ No need to add an additional path to the Windows SDK.
+ Diversion to an existing file instead of copying that file to my own folder.

**Comment by maettu-this** [comment]
Update:

It just seemed to work at first, i.e. it could properly compile the code. However, when executing the script, I get a System.Resources.MissingManifestResourceException as soon as the runtime tries to load the resources.

I will send my test script which shows the issue. You may run it by simply calling:
`cscs .\Windows.Forms\Script.cs`

As you will see, the two .resources are properly generated ("\Windows.Forms\SomeInfoForm_WithResources.resources" and "\Properties\Resources.resources"). But then something goes wrong with embedding them...

**Comment by oleg-shilo** [comment]
The v3.20.0 release delivers the first cut of the resgen.exe integration. I had plans to extend it with the dedicated direct environment variable for the executable (similarly to NuGet.exe location). But I wanted to synchronize this change with another enhancement - the update for the cscs.exe std out help that would print all environment variables cscs.exe may rely on. 

Thus the latest codebase already contains the support for CSS_RESGEN. I appreciate your proposal for having resgen without the extension but I am concerned about the approach that it would require special handling on Linux.  I have done the change nevertheless but I will roll it back if any problems arise.

As for the System.Resources.MissingManifestResourceException, it is important that the resources are named correctly before being embedded into the assembly. I will have a look at your sample but you probably can already sense it that it is slowly getting out of the CS-Script scope and becoming a WinForms dynamic resource management issue.

**Comment by oleg-shilo** [comment]
The latest binary build (not released) from the source code: https://github.com/oleg-shilo/cs-script/tree/v3.20.0/Source/Build
contains the CSS_RESGEN and "extension-less" change.

**Comment by oleg-shilo** [comment]
Please find the test project that shows how to embedd winforms resources
[WindowsFormsApplication1.zip](https://github.com/oleg-shilo/cs-script/files/695324/WindowsFormsApplication1.zip)
Note that you will need to use the very latest today build of cscs.exe form https://github.com/oleg-shilo/cs-script/tree/v3.20.0/Source/Build

**Comment by maettu-this** [comment]
I have further analyzed with yesterday's v3.20.0 and maybe have found the root cause:
It's the name of the resources file or the name of the resources inside that file.

(Note that I was not able to download the latest build from https://github.com/oleg-shilo/cs-script/tree/v3.20.0/Source/Build as my IT's anti virus tells me that "maybe untrustworthy" because "very few users" and "very new" - all true - but dear IT, let us do our work, please ;-)

The error message is something like "...ensure that _MyProject_.Windows.Forms.SomeInfoForm_WithResources.resources is been properly embedded in the assembly...". When compiling resources in Visual Studio, that's exactly what happens, a _MyProjectPath_\Windows.Forms\SomeInfoForm_WithoutResources.resx file will be compiled into _MyProjectPath_\obj\Debug\_MyProject_.Windows.Forms.SomeInfoForm_WithResources.resources file. So, the .resources file name does not have the same name as the .resx file. And I guess the name of the resources inside the file is the same, i.e. prefixed with the full namespace.

The location of the file surely doesn't matter. It should be fine to generate the .resources file to the location where the .resx file resides.

Note that I was not able to follow the WindowsFormsApplication1.zip example. In my case (with v3.20.0), I cannot adapt the example...
```
//css_res Resources.resx, WindowsFormsApplication1.Properties.Resources.resources;
//css_res Form1.resx, WindowsFormsApplication1.Form1.resources;
```
...to my example. This is probably what you expected, as the latest cscs.exe would be required, right?

So, the ", _Name_.resources", does that solve the naming issue I mentioned above? That would be perfect I guess.

**Comment by maettu-this** [comment]
I did a little trick:

1. Ran the script to compile the .resx files, e.g. //css_resource ..\Properties\Resources.resx;
2. Renamed the resulting .resources files to e.g. _MyProject_.Properties.Resources.resources
3. Ran the script again using the .resources files, e.g. //css_resource ..\Properties\_MyProject_.Properties.Resources.resources;

This seems to work, at least brings me to the next issue:
System.IO.FileNotFoundException file or assembly "System.Drawing, **Version=4.0.0.0**, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" could not be found.
Why version 4.0.0.0 ?!? I am using .NET 3.5, i.e. the 2.0.0.0 assemblies should be loaded...

When looking into the .resources file, I indeed find "...System.Resources.ResourceReader, mscorlib, Version=4.0.0.0, Culture=neutral,...". However, when compiling the resources using Visual Studio, I find "...System.Resources.ResourceReader, mscorlib, Version=2.0.0.0, Culture=neutral,...". I have tried to re-direct my call the ResGen.exe from the v10.0A SDK (.NET 4.6/4.6.1) to v7.0A (.NET 3.5), but that didn't help either... I still get Version=4.0.0.0.

Note the /str switch of ResGen.exe:
/str:_language_[,_namespace_[,_class name_[,_file name_]]]]
                Creates a strongly-typed resource class in the specified
                programming language using CodeDOM. In order for the strongly
                typed resource class to work properly, the name of your output
                file without the **.resources must match the
                [namespace.]classname of your strongly typed resource class**.
                You may need to rename your output file before using it or
                embedding it into an assembly.

This holds the finding that the file name must include the namespace. But still doesn't answer why 4.0.0.0 is loaded and not 2.0.0.0... Quite tricky indeed...

**Comment by oleg-shilo** [comment]
You findings are correct. The location of the resource file is irrelevant but the file name is very important as it is used as a key for the embedded resource. Thus "need to rename your output file" is essential and this is what the latest change in the `//css_res` does (v3.20.1).

The  "Version=4.0.0.0" most likely is coming from your resx file where this assembly is fully specified along with its exact version.
 
I think the latest build and a careful examination of your resx file should be the answer to your problems. Thus I have attached to another copy of it (test project and exe) to this post 
[WindowsFormsApplication1.zip](https://github.com/oleg-shilo/cs-script/files/695978/WindowsFormsApplication1.zip). 

You can also download the same zip from dropbox: https://dl.dropboxusercontent.com/u/2192462/CS-S/cs-s.v3.20.1/WindowsFormsApplication1.z-i-p-f-i-l-e

Note, I have renamed the zip file so you have no problems with downloading it.
 
If it becomes all too much for you, you can change the approach and allow VS to build your `*.resources` and treat them as source code. Then it will be a very simple case of //css_res <name>.resources

**Comment by oleg-shilo** [comment]
BTW if you have "anti-virus" difficulties downloading any source file from GitHub you can always pull them with git.

**Comment by maettu-this** [comment]
//css_res of v3.20.1 indeed works, it's compiling the resources and then embedding them properly, perfect!

The 2.0.0.0 -vs- 4.0.0.0 issue was related to the ResGen.exe lookup. I am now explicitly referring to "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin" containing the .NET 3.5 ResGen.exe and it works. I'd personally still prefer the possibility for ResGen.cmd re-direction but fully understand the reluctance if this would lead to conflicts on Linux.

So from my side, this issue has been resolved :-)

**Comment by oleg-shilo** [comment]
Great. The feature will be released as soon as I finish a few other tasks for the next release (~week).
Keep in mind that despite of my concerns I have implemented in the build you tested the fallback name for the resgen tool as "ResGen". Thus if non is found then it will pick your batch file.

**Comment by maettu-this** [comment]
Hmm, I'm a bit puzzled, the batch redirect doesn't work on my machine:
```
_MyWorkspace_\CSScript\Issue #24\WindowsFormsApplication1>cscs.exe Program.cs
C# Script execution engine. Version 3.20.1.0.
Copyright (C) 2004-2017 Oleg Shilo.

Error: Specified file could not be compiled.

System.ApplicationException: Cannot invoke ResGen: Das System kann die angegebene Datei nicht finden
Ensure resgen.exe is in the %CSSCRIPT_DIR%\lib or its location is in the system PATH. Alternatively you can specify the direct location of resgen.exe via CSS_RESGEN environment variable.
   at csscript.CSSUtils.CompileResource(String file, String out_name)
   at csscript.CSExecutor.Compile(String scriptFileName)
   at csscript.CSExecutor.ExecuteImpl()
```
But Windows can locate 'resgen':
```
_MyWorkspace_\CSScript\Issue #24\WindowsFormsApplication1>where resgen
_MyLinks_\ResGen.cmd
```
And:
```
_MyWorkspace_\CSScript\Issue #24\WindowsFormsApplication1>resgen
Microsoft (R) .NET Resource Generator
[Microsoft .Net Framework, Version 2.0.50727.5485]
Copyright (c) Microsoft Corporation.  All rights reserved...
```
ResGen.cmd is:
```
@ECHO OFF
CALL "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin\ResGen.exe" %*
```

**Comment by oleg-shilo** [comment]
>I request to only invoke "ResGen" and let the system find out whether an .exe or something else is meant.

My bad. I accepted that proposal assuming `Process.Start` uses the same invocation model as Windows shell. I guess we both became victims of this. :)
Well it doesn't.  `Process.Start` cannot invoke a batch file without extension. I am rolling it back to "resgen.exe".

For you, no changes. You'll need to use CSS_RESGEN, PATH or %CSSCRIPT_DIR%\lib.

**Comment by maettu-this** [comment]
OK, agreed.
