### ISSUE TITLE
Classless evaluation

### ISSUE THREAD

**Issue by amadare42** [oleg-shilo/cs-script#240]
Hi,
I want to treat global scope as body of entry function, so every statement will be executed as is, but classes and namespaces to be declared normally. So this code will be executed:

```c#
using System;

void Test()
{
    Console.WriteLine("Test()");
}

class SomeClass
{
    void Foo()
    {
        Console.WriteLine("Foo()");
    }
}

Test();
new SomeClass().Foo();
Console.WriteLine("Global scope");
```

Is it possible to achieve this using cs-script from .net application?

Thanks.

**Comment by oleg-shilo** [comment]
Hi Igor,

It's not possible as the syntax of the script supposed to be plain-vanilla C# (ECMA-compliant C#). Specifically syntax of a C# code module or a syntax of a C# class method definition. 

Thus if you move away `SomeClass` definition then your script is compliant (a method definition)/ Or, if you wrap last three lines in a method (e.g. `main`) then it is also compliant (a module definition).

It is not even a limitation. It is how all C# compilers work. And CS-Script is a scripting engine that does not interpret the script but instead relies on the stock compilers.
