### ISSUE TITLE
.NET 5.0 execution csscript code makes dlls load second time and breaks WPF styles

### ISSUE THREAD

**Issue by apoznanskiy** [oleg-shilo/cs-script#242]
I have WPF .net5 applicaiton with Infragistics contorls, if I don't use csscript lib all works fine(I use other wpf libs and it breaks them as well), after using simple example code. Don't know exactly what is happening but if you look to Output during debug it shows that all dlls after executing example code loaded again. I included my small test project. It also needs infragistics nugets, they can be obtained from their trial version https://www.infragistics.com/free-downloads.

[Test CSSript.zip](https://github.com/oleg-shilo/cs-script/files/6599534/Test.CSSript.zip)

**Comment by oleg-shilo** [comment]
You sample seems to work just fine:
![image](https://user-images.githubusercontent.com/16729806/120881256-29a09480-c613-11eb-9815-aec598f71c77.png)

Can you please give the details on " it breaks them as well". What is the error, what is the exception trace stack?

**Comment by apoznanskiy** [comment]
First it should not go black screen and be white blank. Now u see undocked state if you try to dock it back(to first position) it goes to internal style exception, that we don't have if we don't use CSScript. If you check VS debug output window it shoes that all project libraries were loaded second time.

**Comment by apoznanskiy** [comment]
With net48 csscript works ok with wpf controls.

**Comment by oleg-shilo** [comment]
OK, now you are actually describing the problem and the test. :o)

```C#
The problem you are experiencing is triggered by the assemblies of the current AppDomain being referenced by the script by the you are trying to execute. This is default behavier as it is quite common that you may want to access AppDomain types from the script. I am guessing Infragistics assemblies "do not like it" for some reason.

The simplest work around is to disable referencing appdomain assemblies automatically and instead reference the assemblies manually and only the ones that you need.

Thus as starting point just set `RefernceDomainAsemblies` to false;   

t has fixed  your test.

```C#
public MainWindow()
{
    InitializeComponent();

    CSScript.EvaluatorConfig.RefernceDomainAsemblies = false;

    var log = CSScript.Evaluator
        .CreateDelegate(@"void Log(string message)
                            {
                                Console.WriteLine(message);
                            }");

    log("Test message");

```

**Comment by apoznanskiy** [comment]
Thanks for solution. Didn't know about this option.

**Comment by oleg-shilo** [comment]
And this is how you can reference the assemblies manually:

https://github.com/oleg-shilo/cs-script/blob/f304bcbd18acc6180df44c5b64199e985189b794/src/CSScriptLib/src/CSScriptLib/samples.cs#L258-L268
