### ISSUE TITLE
System.Data from GAC_32 in 64 bit process (ver 3.30.5.2)

### ISSUE THREAD

**Issue by andergtz** [oleg-shilo/cs-script#248]
Hello:
I was experiencing an issue similar to these: #9 and #122.

When executing a script with Roslyn engine the system.data library gets loaded from the 32 bit GAC when the process is 64 bits. This results in the following error (the same as the previously mentioned issues) :
No se puede cargar el archivo o ensamblado 'file:///C:\windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll' ni una de sus dependencias. Se ha intentado cargar un programa con un formato incorrecto.

I found that setting DisableReferencingFromCode to true does indeed work but digging a little deeper I found a fix for the problem that you may want to include in the code:

In the class CSScriptLibrary.AssemblyResolver the ADD THIS commented lines:

```csharp
public static string[] FindGlobalAssembly(String namespaceStr)
{
	var retval = new List<string>();

	if (Runtime.IsMono)
	{
		 if (Runtime.MonoGAC.Contains(namespaceStr))
		 {
			  retval.Add(namespaceStr);
		 }
	}

	if (!retval.Any() && Runtime.IsWin)
	{
		 try
		 {
			  AssemblyEnum asmEnum = new csscript.AssemblyEnum(namespaceStr);

			  string highestVersion = "";
			  string asmName = "";
			  do
			  {
					asmName = asmEnum.GetNextAssembly();
                                        ///// ADD THIS:
					if (asmName != null 
						 && (Environment.Is64BitProcess && asmName.Contains("processorArchitecture=x86"))
							 || (!Environment.Is64BitProcess && asmName.Contains("processorArchitecture=x64")))
						 continue;
                                         ///// 

					if (string.Compare(asmName, highestVersion) > 0)
						 highestVersion = asmName;

					if (namespaceStr.Contains(", Version=")) //the assembly was specified by its full name
						 break; //stop searching for the higher version
			  }
			  while (asmName != null);

			  if (highestVersion != "")
			  {
					string asmLocation = AssemblyCache.QueryAssemblyInfo(highestVersion);
					retval.Add(asmLocation);
			  }
		 }
		 catch (Exception)
		 {
			  // fuslion.dll cannot be found under Mono even if it is running on Windows
			  //If exception is thrown it is very likely it is because where fusion.dll does not exist/unavailable/broken.
			  //We might be running under the MONO run-time.
		 }
	}

	if (retval.Count == 0 && namespaceStr.EndsWith(".dll", StringComparison.CurrentCultureIgnoreCase))
		 retval.Add(namespaceStr); //in case of if the namespaceStr is a dll name

	return retval.ToArray();
}
```

Thanks for this great tool!

**Comment by oleg-shilo** [comment]
Thank you.

It is a valid correction but not for the current version of CS-Script, which targets .NET 5 that no longer support discovery of the GAC assemblies. Meaning that the reported problem is not relevant for CS-Script v4 and higher.

However it is still relevant for the legacy versions that target .NET Framework. So I have implemented the change there: https://github.com/oleg-shilo/cs-script.net-framework/commit/b1dd04a2a95175b1682562020164346b442463b9

**Comment by andergtz** [comment]
Thanks again!
