### ISSUE TITLE
Possible to use "wsdl" in the .NET Core release of CS-Script?

### ISSUE THREAD

**Issue by UweKeim** [oleg-shilo/cs-script#249]
Just tried to update CS-Script on one of my servers, to see that this line fails:

```cs
//css_pre wsdl(https://example.org/my.asmx, MySoapEndpoint);
```

with the error message:

> Could not find file "wsdl".
> Ensure it is in one of the CS-Script search/probing directories.

### Question

Is it somehow possible to still use WSDL to automatically generate Proxy classes in the .NET Core version of CS-Script?

**Comment by oleg-shilo** [comment]
Hi Uwe,

Pre-scripts work the same way for .NET 5 so wsdl can be run as before. Except, it is no longer included in cs-script distro.

Older distros had wsdl.cs and wsdl.exe included but they did not make into .NET 5 edition. I am not opposing reinstating wsdl.cs but it still cannot work without the actual wsdl.exe which is a part of Win SDK. Thus to avoid any license breaching I had to remove it from the distro.  

If you want to bring this functionality you can simply copy wsdl.cs in one global search directories. You can find them with `-config`:
```ps
PS C:\Users\user> css -config:get:searchdirs
SearchDirs: "%CSSCRIPT_ROOT%\lib;C:\ProgramData\cs-script\commands;%CSSCRIPT_INC%;"
PS C:\Users\user>
```You will also need to to update this line in `wsdl.cs` with the correct path to the executable on your system:
```c#
                string wsdlExe = Environment.ExpandEnvironmentVariables(@"%CSSCRIPT_DIR%\lib\tools\wsdl.exe");
```

**Comment by UweKeim** [comment]
Awesome, thanks a lot, Oleg!
