### ISSUE TITLE
Manual installation under Windows 10

### ISSUE THREAD

**Issue by vasagle-gleblu** [oleg-shilo/cs-script#250]
I apologize if this is not the correct forum for this topic.

I am trying to install CS-Script manually because I cannot use Chocolatey or css_config.exe because the ChooseDefaultProgram / PsExec utility is blocked by my laptop's antivirus (work computer).  How can I setup the features manually (e.g. file associations and shell extensions)?

Thank you.

**Comment by oleg-shilo** [comment]
Shell extensions are now a separate product: https://github.com/oleg-shilo/shell-x/releases/tag/v1.2.0.0
You can download and simply follow the [manual installation](https://github.com/oleg-shilo/shell-x/tree/v1.2.0.0#installation) instructions.

But most likely your antivirus will not like it neither.
