### ISSUE TITLE
Script merger for hosted scripts

### ISSUE THREAD

**Issue by JayBeAl** [oleg-shilo/cs-script#254]
Hello Oleg,

first of: thank you for your continued work on the cs-script project, I am using it to host scripts in a desktop application to provide a scripting interface for users. I am going with the Roslyn compiler so that users won't need an additional SDK.
For ease of mantainance I´d like to deploy scripts with multiple files, which is not natively possible with the Roslyn compiler according to your documentation.
However, I have seen that you have included script merging in the CLI version of CS-Script. Is there any reason why this feature is only available in the CLI version? 
Do you plan to include this script merger in the hosting version as well?

**Comment by maettu-this** [comment]
Came across @JayBeAl's issue by accident and would like to express the same need.

My hosting application is used in a testing environment with almost a thousand test script files. They are available in a Visual Studio solution. Each top-level script has its own namespace. `css_import` (934 occurences) as well as `css_reference` (20 occurences) is used to combine the top-level and helper scripts into larger scopes.

The largest scope consists of approx. 500 files. The top-level `Device` imports all of them. The files implement the vendor specific command sets of a family of devices. Many scripts use that `Device`.

Another scope consists of approx. 100 files. Each file implements a specific test of a compliance regulation. 6 top-level scripts sequentially run the tests, depending on regulation variant.

In both cases, a single blob or not using namespaces would be totally unmaintainable.

**Comment by oleg-shilo** [comment]
It's a difficult one. Roslyn has quite a few critical limitations so I made the decision not to overinvest as the value would be very limited.

There is no workaround for these limitations:
- Roslyn does not allow namespaces
- Roslyn compiles all user-defined classes as nested classes 
- Roslyn compiled assemblies cannot be referenced by other scripts (see `CompileCodeWithRefs` test). There is something strange there.

But, if your hosting scenario is not impacted by these limitations then indeed multi-scripting can be achieved.

I am actually working on it :)

**Comment by oleg-shilo** [comment]
Done.
Will release it as a pre-release so can be tested before going fully public.

**Comment by oleg-shilo** [comment]
Prerelease package v4.1.3.0-pre has been just published

**Comment by maettu-this** [comment]
Good to see the `css_*` directives also with Roslyn, even though the Roslyn limitations still are a no-go for my hosting application. I ask you to also update the documentation accordingly. In the past, https://github.com/oleg-shilo/cs-script/wiki/Choosing-Compiler-Engine mentioned something about the `css_*` support of the different engines. Also, `CSScript.chm` listed them:

![Help on css_](https://user-images.githubusercontent.com/24897735/134871787-cef1ef2d-53e2-4099-83da-8dec1609fb63.png)

And as stated at the top of the page, the content is yet partial only. If you like, I would be available for reviewing the content and giving suggestions on the missing pieces of information, especially regarding hosting, where currently nothing is stated about `css_*` directives.

**Comment by oleg-shilo** [comment]
@maettu-this sorry for getting back to you with such a delay.

You are right I will need to update that article with the new support for `//css_*`. Though that  CSScript.chm is legacy documentation for CLI only. So it is not exactly suitable for describing hosted scenarios. Meaning that it needs to be done on the wiki.

Yes, it would be great if you can scan the document for obvious gaps. The original documentation was for .NET Framework editions of both CS-Script CLI and hosted library. 

Since CS-Script has switched to the  .NET5 edition the documentation needs to be reviewed and updated where required (e.g. gaps). All wiki docs that are not reviewed yet are marked as partial.  

Finding time is very challenging for me :(
I am struggling to allocate enough time to maintain all me OSS projects. So I oscillate between all of them. Now I am mainly on WixSharp. But CS-Script will be the very next.

**Comment by maettu-this** [comment]
Easy, no need to hurry, I fully understand the time constraints such OSS projects mean. Not seeing `css_` directives in the documentation just makes me uneasy sometimes, knowing that in my environment tons of them are around. Not being able to upgrade my hosting application to .NET 5 for this reason would mean a nightmare to me... But I guess as long as the **CodeDom** engine is still around I should be safe.

Just let me know once content is ready to be reviewed. I will then look at it thoroughly and report my findings.
