### ISSUE TITLE
Ability to catch AppDomain.UnhandledException in a not-hosted script (cscs) ?

### ISSUE THREAD

**Issue by MarLupin** [oleg-shilo/cs-script#257]
I'd like to be able to catch unhandled exceptions in a script, just like in a regular console application (where try-catch was missing for some reason). For example (run by cscs.exe):

```csharp
using System;
class Script {
	static void Main()
	{
		AppDomain.CurrentDomain.UnhandledException += new UnhandledExceptionEventHandler(ExceptionEventHandler);
		AppDomain.CurrentDomain.ProcessExit += new EventHandler(ProcessExitEventHandler);
		throw new Exception("I'd like to intercept it without try-catch.");
	}
	static void ProcessExitEventHandler(object sender, EventArgs args)
	{
		Console.WriteLine("ProcessExit intercepted");
	}
	static void ExceptionEventHandler(object sender, UnhandledExceptionEventArgs args)
	{
		Console.WriteLine("UnhandledException intercepted");
		Console.WriteLine("Message: "+((Exception)args.ExceptionObject).Message);
		Environment.Exit(0);
	}
}
```
The result of running script is:

	Error: Specified file could not be executed.
	I'd like to intercept it without try-catch.
	ProcessExit intercepted

I would rather get something like this:

	Error: Specified file could not be executed.
	UnhandledException intercepted
	Message: I'd like to intercept it without try-catch.
	ProcessExit intercepted

I think I understand why this is happening. When the script is run through cscs there are really no unhandled exceptions because they are all caught on the way:

```csharp
try {
... executor.Execute ...
catch
{
	if (!CSSUtils.IsRuntimeErrorReportingSuppressed)
		print("Error: Specified file could not be executed." + NewLine);
	throw;
} ...
```

So, I would like to ask, if it would be possible for cscs to check, after catching an unhandled exception:
If there is a delegate in CurrentDomain.UnhandledException, then pack the exception into UnhandledExceptionEventArgs and call that delegate ?
Or maybe there is some other way to achieve this?

**Comment by oleg-shilo** [comment]
I think it is possible.
Marking it as "enhancement"
