### ISSUE TITLE
Can not run scripts after installing VS2022

### ISSUE THREAD

**Issue by caesay** [oleg-shilo/cs-script#258]
VS2022 installs the dotnet6 sdk, and this has caused cs-script to fail to execute all scripts, of any kind. I can't see any command line arguments that might be helpful. 

```
C:\Users\Caelan>cscs "C:\Tools\scripts\\locking.cs"
Error: Specified file could not be executed.

Could not load type 'System.Runtime.CompilerServices.DefaultInterpolatedStringHandler' from assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

Presumably related to some of the changes mentioned here https://devblogs.microsoft.com/dotnet/string-interpolation-in-c-10-and-net-6/

Is there a way to instruct cs-script to use the dotnet 5 runtime that I'm unaware of?

**Comment by oleg-shilo** [comment]
Hi Caelan, sorry for the delay. It was a 4-days weekend in Mel :)

That is an interesting problem. `cscs` is compiled for .NET five and I expect it to run compilers for .NET 6, not .NET 6.

Can you please check if forcing it to compile against .NET 5 Roslyn would do the trick:

```
cscs -ng:roslyn "C:\Tools\scripts\locking.cs"
```

**Comment by caesay** [comment]
Hi Oleg, thanks for the response. 

`cscs` was working fine before I installed VS2022 / net6 SDK. I have tried with your suggestion and the result is the same, I've also tried with all kinds of scripts, even a simple Console.WriteLine causes the issue when SDK6 is installed. 

```txt
C:\Users\Caelan>cscs -ng:roslyn "C:\Tools\scripts\locking.cs"
Error: Specified file could not be executed.

Could not load type 'System.Runtime.CompilerServices.DefaultInterpolatedStringHandler' from assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

For reference, this is the list of runtimes I have installed

```txt
>dotnet --info

NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21505.57
 Commit:    ab39070116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by oleg-shilo** [comment]
Found the problem when installed .NET 6 SDK. Though not entirely sure that it is absolutely the same as in your environment.
The cause is the deployment model .NET is relying on.

While all SDKs installed are fully independent (e.g. their compilers `csc.exe`), the launch `dotnet.exe` is patched after the SDK installation with the version specific to the last SDK installed. Meaning that a simple `dotnet csc.dll` call will fail if the csc is a .NET 5 (x86) assembly and `dotnet` is a .NET6 (x64) executable. Like in my case.

In your case, you may have both SDKs of the same architecture but still, they may not be compatible type wise.

I will prepare a hotfix release so you can test the build with the deterministic probing of both csc and dotnet. This may fix the problem. 

But... if it does not then please send me your exact script as in my environment .NET 6 SDK breaks the execution but with the CPU architecture incompatibility. And Roslyn engine does fix the problem. Meaning that there are differences in between our tests either in our environments or our scripts.

Sstay tuned

**Comment by oleg-shilo** [comment]
Done: https://github.com/oleg-shilo/cs-script/releases/tag/v4.1.4.0-HotFix
