### ISSUE TITLE
Spelling issue?

### ISSUE THREAD

**Issue by UweKeim** [oleg-shilo/cs-script#264]
While not being native English speaker, I do think [this sentence](https://github.com/oleg-shilo/cs-script/blob/9eab825642fcb92ad43f25750298b1a9cface9a7/src/cscs/csscript.cs#L1004) has a spelling error:

> A new NuGet package has been installed. If some of it's components are not found you may need to restart the script again.

In my opinion it should read 

> **its** component

and not

> **it's** component

Sorry, if I misunderstood the sentence.

**Comment by oleg-shilo** [comment]
You are absolutely right. It is a typo. 
Fixed.
