### ISSUE TITLE
Add new method CSScript.CodeDomEvaluator.ReferenceAssembliesByName(list<string)

### ISSUE THREAD

**Issue by TomBruns** [oleg-shilo/cs-script#267]
Request:  
Enable loading referenced assemblies from a list of strings (assy names) instead of explicit individual ReferenceAssemblyByName(string) for each assy,

Current State:
We must add a ReferenceAssemblyByName line for the number of referenced assys that we want to be able to load.

Scenario:
We are executing scripts written by a separate team that may have 0..N referenced assys.  This would make our code that wraps the CSScript library support this use case.

**Comment by oleg-shilo** [comment]
Well, I can understand what you are trying to solve and will consider converting the signature to the "params" version. It is because I am trying to keep the API as lean as possible. And "params" will completely address your issue.

Saying that, I would prefer users to extend the engine interface as much as possible instead of modifying it.

Thus this simple extension in your code will completely address your issue even without waiting the the next release:

```C#
static class CSScriptExtensions
{
    public static IEvaluator ReferenceAssemblyByNames(this IEvaluator  evaluator, string[] assemblyNames)
        => assemblyNames.ToList().ForEach(asm => evaluator.ReferenceAssemblyByName(asm));
}
```

**Comment by TomBruns** [comment]
A small modification to the code below was required


    internal static class CSScriptExtensions
    {
        internal static IEvaluator ReferenceAssemblyByNames(this IEvaluator evaluator, List<string> assemblyNames)
        {
            foreach(var assemblyName in assemblyNames)
            {
                evaluator.ReferenceAssemblyByName(assemblyName);
            }

            return evaluator;
        }
    }


Hint the code below did not return a IEvaluator

Tom

**Comment by oleg-shilo** [comment]
Correct. 👍 

Though the signature can be improved even further:

```C#
static class CSScriptExtensions
{
    public static IEvaluator ReferenceAssemblyByNames(this IEvaluator evaluator, IEnumerable<string> assemblyNames)
    {
            foreach(var assemblyName in assemblyNames)
                evaluator.ReferenceAssemblyByName(assemblyName);
            return evaluator;
     }
}
```

**Comment by oleg-shilo** [comment]
Done. Will be available in the very next release.

**Comment by TomBruns** [comment]
Thank you!

Tom

Sent via the Samsung Galaxy S10e, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by TomBruns** [comment]
A follow-up for people interested in this new feature...

The v4.3 release notes reference this enhancement request:
Issue #267: CSScript.CodeDomEvaluator.**ReferenceAssembliesByName**(list<string)

The actual implementation is a change to the signature of this method
public IEvaluator **ReferenceAssemblyByName**(params string[] assemblyName);
