### ISSUE TITLE
How to use DisableReferencingFromCode in dotnet core? Use .ReferenceAssembliesFromCode instead of LoadeCode?

### ISSUE THREAD

**Issue by mrockwell** [oleg-shilo/cs-script#269]
This error means that the script referenced assembly is of a wrong CPU architecture. The error itself is not a defect but a limitation of the assembly probing mechanism available  with Mono compiler (default evaluator engine). It uses name of the assembly/namespace  (e.g. System.Data) and resolves it into assembly file path without taking the notice of the host application CPU architecture.

You can solve the problem by disabling namespace resolving (DisableReferencingFromCode) and referencing System.Data assembly file explicitly:

``` C#
dynamic script = CSScript.Evaluator
                         .ReferenceAssemblyOf<DataSet>()
                         .With(eval => eval.DisableReferencingFromCode = true)
                         .LoadCode(@"using System;
                                     using System.Data;

                                     public class Update_DatabaseViews
                                     {
                                         public void Execute(IDbConnection databaseConnection)
                                         {
                                             Console.WriteLine(""Test""); 
                                         }
                                     }");
script.Execute(null);
```

However, there is even an easier way. You can switch to CodeDOM engine. It uses Fusion for assembly probing and it locates the correct assembly by taking the host CPU architecture into consideration. Though Fusion is only available on Windows.
_As an extra benefit you will be able to debug your scripts_ 

``` C#
CSScript.EvaluatorConfig.Engine = EvaluatorEngine.CodeDom;
```

_Originally posted by @oleg-shilo in https://github.com/oleg-shilo/cs-script/issues/9#issuecomment-240287498_

**Comment by oleg-shilo** [comment]
Please be aware that the later releases of CS-Script are targeting .NET 5 (.NET Core) thus Monoi is not available and the whole assembly probing mechanism is heavily reworked. 

Thus `DisableReferencingFromCode` remains the preferred solution.
