### ISSUE TITLE
Mono evaluator does not support nested classes

### ISSUE THREAD

**Issue by koenj** [oleg-shilo/cs-script#27]
The current CSScript mono evaluator does not support nested classes;
This is a consequence of the following mono issue: [https://github.com/mono/mono/pull/1058](https://github.com/mono/mono/pull/1058)

This issue has been fixed by Mono, any plans to upgrade CSScript's mono lib?

**Comment by oleg-shilo** [comment]
The latest Mono.CSharp.dll v4.6.57.0 has been included in the latest v3.20.0 release (https://github.com/oleg-shilo/cs-script/releases/tag/v3.20.0)

**Comment by oleg-shilo** [comment]
Updating it makes even more sense as Mono.CSharp.dll v4.6.57.0 supports C# 6 syntax.
Txs
