### ISSUE TITLE
Porting .net framework version to core, what is equivalent core code for replacing AsmHelper? 

### ISSUE THREAD

**Issue by mrockwell** [oleg-shilo/cs-script#270]
System.Reflection.Assembly assembly = (System.Reflection.Assembly)CSScriptLibrary.CSScript.LoadCode(scriptCode);

                    using (AsmHelper scriptAsm = new AsmHelper(assembly))
                    {
                        string className = assembly.DefinedTypes.FirstOrDefault().FullName;
                        object obj = scriptAsm.CreateObject(className);

                        result = scriptAsm.Invoke(className + "." + methodName, parameters);
                    }

**Comment by oleg-shilo** [comment]
There is no direct equivalent as the reflection-based Dispatch interface was a temporary measure till `dynamic` type became available.
  
Today you can use a muck cleaner code:

```C#
dynamic script = CSScript.Evaluator.LoadCode(scriptCode);
var result = script.methodName(param1, param2);
```
though you can still use reflection. I suggest you create a simple extension method for that if you want to use this approach
```C#
object script = CSScript.Evaluator.LoadCode(scriptCode);
script.YourReflectionExtensionMethod(methodName, parameters);
```
