### ISSUE TITLE
Any Special considerations running in a linux docker container?

### ISSUE THREAD

**Issue by TomBruns** [oleg-shilo/cs-script#271]
Baseline: Working ASP.NET 5 WebAPI hosting CSScript.CodeDomEvaluator (Cs-Script.Core (2.0.0) running on Windows Dev laptop

1. Converted csproj to Linux Docker Container

2.0 Updated docker file to make sure .NET SDK is installed
  #FROM base AS final
  **FROM build AS final**
  WORKDIR /app
  COPY --from=publish /app/publish .
  ENTRYPOINT ["dotnet", "GatewayShim.WebAPI.dll"]

2.1  From inside container...
        root@b37cd5190971:/app# dotnet --list-sdks
        5.0.404 [/usr/share/dotnet/sdk]

3. At runtime the CodeDomEvaluator returns "Unknown compiler error" with no inner exception

**Comment by TomBruns** [comment]
additional info... after upgrading to 4.2

if i debug inside the container I get this...

"No such file or directory"

with this stack trace...
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CSScriptLib.CoreExtensions.RunAsync(String exe, String args, String dir) in C:\Users\xtobr\Source\Repos\cs-script\src\cscs\Utils\CoreExtensions.cs:line 43
   at CSScriptLib.CodeDomEvaluator.CompileAssemblyFromFileBatch_with_Csc(String[] fileNames, String[] ReferencedAssemblies, String outAssembly, Boolean IncludeDebugInformation, CompileInfo info) in C:\Users\xtobr\Source\Repos\cs-script\src\CSScriptLib\src\CSScriptLib\Evaluator.CodeDom.cs:line 257
   at CSScriptLib.CodeDomEvaluator.Compile(String scriptText, String scriptFile, CompileInfo info) in C:\Users\xtobr\Source\Repos\cs-script\src\CSScriptLib\src\CSScriptLib\Evaluator.CodeDom.cs:line 129
   at CSScriptLib.EvaluatorBase`1.CompileCode(String scriptText, String scriptFile, CompileInfo info) in C:\Users\xtobr\Source\Repos\cs-script\src\CSScriptLib\src\CSScriptLib\EvaluatorBase.cs:line 229
   at CSScriptLib.EvaluatorBase`1.CompileCode(String scriptText) in C:\Users\xtobr\Source\Repos\cs-script\src\CSScriptLib\src\CSScriptLib\EvaluatorBase.cs:line 132
   at CSScriptLib.EvaluatorBase`1.LoadCode[T](String scriptText, Object[] args) in C:\Users\xtobr\Source\Repos\cs-script\src\CSScriptLib\src\CSScriptLib\EvaluatorBase.cs:line 589
   at FIS.Merchant.GatewayShim.MappingEngine.Scripting.ScriptingEngineManager.BuildMessageMappingAssy(MessageMappingConfigDTO gatewayMappingConfig) in /src/FIS.Merchant.GatewayShim.MappingEngine/Scripting/ScriptingEngineManager.cs:line 647

**Comment by TomBruns** [comment]
it is on this call to RunAsync
exe = "dotnet.exe"
args = "/usr/local/share/cs-script/bin/compiler/4.2.0.0/build.dll" -listen -port:17001 -csc:"/usr/share/dotnet/sdk/5.0.404/Roslyn/bincore/csc.dll"
WorkingDir = null

**Comment by TomBruns** [comment]
FYI: A peer of mine got a similar error message running v4.2 in ASP.NET 5 webapi NOT in containers on macOS

**Comment by oleg-shilo** [comment]
Not sure why it is failing. Any problems with port being unavailable?
Can you test it with the RoslynEvaluator

**Comment by oleg-shilo** [comment]
RoslynEvaluator will not need any external process.

**Comment by TomBruns** [comment]
1.  Changed to use RoslynEvaluator

           IShimMappingScript mappingAssy = null;
            try
            {
                // create the script
                mappingAssy = CSScript.RoslynEvaluator //.CodeDomEvaluator
                                            .ReferenceAssemblyByName(@"xxx.Merchant.GatewayShim.MappingEngine.Shared")
                                            .ReferenceAssemblyByName(@"xxx.Merchant.GatewayShim.ISO8583v3.Shared")
                                            .ReferenceAssemblyByName(@"xxx.Merchant.GatewayShim.ISO8583v3")
                                            .ReferenceAssemblyByName(gatewayMappingConfig.ScriptEngineConfig.SourceGatewayMessagesAssemblyName)
                                            .ReferenceAssemblyByName(gatewayMappingConfig.ScriptEngineConfig.TargetGatewayMessagesAssemblyName)
                                            .LoadCode<IShimMappingScript>(finalScriptLOC);

                scriptCacheEntry.AssemblyQualifiedName = mappingAssy.GetType().AssemblyQualifiedName;
                scriptCacheEntry.MappingAssy = mappingAssy;
                scriptCacheEntry.IsValidAssy = true;
            }
            catch (Exception ex)
            {
                scriptCacheEntry.IsValidAssy = false;
                s

            2.        Had to Add this reference

              ***@***.***


  1.  Now I get this error

<script>(38,1): error CS7021: Cannot declare namespace in script code

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by TomBruns** [comment]
More info (after changing back to CodeDomEvaluator...
If I set a breakpoint in **CodeDomEvaluator** in line 257
                `              dotnet.RunAsync(startBuildServerCommand);`

and run my code until execution breaks in that line....

connect to the container and run the same command from the command line...
`  dotnet "/usr/local/share/cs-script/bin/compiler/4.2.0.0/build.dll" -listen -port:17001 -csc:"/usr/share/dotnet/sdk/5.0.404/Roslyn/bincore/csc.dll"`

and skip over the RunAsync line in Visual Studio

**everything works as expected!**

Any suggestions?  (Using RoslynEvaluator is problematic because of the namespace declarations in the script code)

**Comment by TomBruns** [comment]
### Root Cause of the "No such file or directory" error message found.

<TL/DNR>  On Linux based O/S the dotnet exe name is "dotnet" not "dotnet.exe"

The issue is in Global.cs  (this code always returns dotnet.exe on linux)

   ```
     /// <summary>
        /// Gets the path to the dotnet executable.
        /// </summary>
        /// <value>
        /// The dotnet executable path.
        /// </value>
        static public string dotnet
        {
            get
            {
                var file = "".GetType().Assembly.Location
                  .Split(Path.DirectorySeparatorChar)
                  .TakeWhile(x => x != "dotnet")
                  .JoinBy(Path.DirectorySeparatorChar.ToString())
                  .PathJoin("dotnet", "dotnet.exe");

                return File.Exists(file) ? file : "dotnet.exe";
            }
        }
```

The filename of dotnet on linux (and macOS) is not **dotnet.exe** it is just **dotnet**

Here is a directory list from inside my container

root@6b235faf45d4:/app# ls -al /usr/share/dotnet       
total 224
drwxr-xr-x 1 root root   4096 Dec 14 15:37 .
drwxr-xr-x 1 root root   4096 Dec 14 15:37 ..
-rw-r--r-- 1 root root   1116 Nov 16 04:39 LICENSE.txt
-rw-r--r-- 1 root root  60108 Nov 16 04:39 ThirdPartyNotices.txt
-rwxr-xr-x 1 root root 133632 Nov 16 04:43 **dotnet**            **<==============**
drwxrwxr-x 3 root root   4096 Nov 16 04:45 host
drwxrwxr-x 6 root root   4096 Nov 22 22:45 packs
drwxrwxr-x 3 root root   4096 Nov 22 22:45 sdk
drwxrwxr-x 1 root root   4096 Dec 14 15:36 shared
drwxrwxr-x 3 root root   4096 Nov 22 22:45 templates

### This explains the same error message when my peer was running outside of containers on macOS
====================================================
The check to make sure the SDK is installed works because the code uses "dotnet" explicitly without the extension

```
Runtime.cs
	    /// <summary>
        /// Determines whether .NET SDK is installed.
        /// </summary>
        /// <returns>
        ///   <c>true</c> if [is SDK installed]; otherwise, <c>false</c>.
        /// </returns>
        public static bool IsSdkInstalled()
        {
            var output = "";
            "dotnet".Run("--list-sdks", null, onOutput: x => output += x);
            return output.IsNotEmpty();
        }
```
====================================================
Here is a proposed solution

```
        /// <summary>
        /// Gets the path to the dotnet executable.
        /// </summary>
        /// <value>
        /// The dotnet executable path.
        /// </value>
        static public string dotnet
        {
            get
            {
                var dotnetExeName = Runtime.IsLinux ? "dotnet" : "dotnet.exe";      <=======

                var file = "".GetType().Assembly.Location
                  .Split(Path.DirectorySeparatorChar)
                  .TakeWhile(x => x != "dotnet")
                  .JoinBy(Path.DirectorySeparatorChar.ToString())
                  .PathJoin("dotnet", dotnetExeName);       <=======

                return File.Exists(file) ? file : "dotnet.exe";
            }
        }
```

**Comment by oleg-shilo** [comment]
Fantastic. Thank you so much.
That's exactly why I assigned it the "Help wanted" label.

I will try to do the release as soon as Christmas commitments are over :)

Merry Christmas Tom
