### ISSUE TITLE
CSScript does not detect System.IO.FileSystem assembly in .NET6

### ISSUE THREAD

**Issue by jacknugent** [oleg-shilo/cs-script#272]
In .NET6, CSScript does not list System.IO.FileSystem as a referenced assembly in compiled code. The code does compile and run fine, though.

Recreation:

Test.csproj
```C#
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CS-Script" Version="4.2.0" />
  </ItemGroup>

</Project>
```

Program.cs
```C#
using CSScriptLib;
using System;
using System.Linq;

namespace Test
{
    public interface ITest
    {
        void FindTestFile();
    }

    internal class Program
    {
        static void Main(string[] args)
        {
            var script = @"
                public void FindTestFile()
                {
                    if (System.IO.File.Exists(""C:\\someText.txt""))
                        System.Console.WriteLine(""File found"");
                    else
                        System.Console.WriteLine(""File not found"");
                }";

            CSScript.Evaluator.LoadMethod<ITest>(script).FindTestFile();

            var assemblies = CSScript.Evaluator
                .CompileCode(script)
                .GetReferencedAssemblies()
                .Select(p => p.Name!);

            foreach (var assembly in assemblies.ToList())
                Console.WriteLine($"Assembly referenced: {assembly}");
        }
    }
}
```

Call `dotnet run` and get this result:
```
File not found
Assembly referenced: System.Private.CoreLib
Assembly referenced: System.Console
```

However, if I change TargetFramework to net5.0, I get this result:
```
File not found
Assembly referenced: System.Private.CoreLib
Assembly referenced: System.IO.FileSystem
Assembly referenced: System.Console
```

So in net6.0, we lose the `System.IO.FileSystem` assembly. The same issue happens if I compile using `LoadCode` instead of `LoadMethod`

**Comment by oleg-shilo** [comment]
Just in time. I am going to make a .NET 6 targeting release this week (or so). Will check.
...
Oh, wait a second. 
The sample you provided does not throw the error. So what is the problem?

The behaviour simply indicates that when script engine references your host app assemblies the up already loaded `System.IO.FileSystem` if it is .NET5 and did not if it is .NET6.  But this is the difference in the default CLR initialization between .NET v5 and 6. So it does not really has anything to do with the scripting.

So what exactly we are trying to solve here?

**Comment by jacknugent** [comment]
We are trying to block FileSystem access from a script
