### ISSUE TITLE
.NET 5 vs .NET 6 confusion

### ISSUE THREAD

**Issue by TomBruns** [oleg-shilo/cs-script#273]
Background:
 - hosting CS-SCRIPT v4.2 in a .NET 5 WebAPI
 - dev workstation had .NET 5 now also has .NET 6 installed
 - using CodeDOM CS-SCRIPT model
 
Issue
 - debugging i see this command sent to start the build server...
 **"'C:\ProgramData\cs-script\bin\compiler\4.2.0.0\build.dll' -listen -port:17001 -csc:'C:\Program Files\dotnet\sdk\5.0.404\Roslyn\bincore\csc.dll'"**

- I see this error coming back from BuildServer.SendBuildRequest...
**System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.**

It seems like the build server is using the newest version.

This kind of issue would typically be addressed with a global.json file.  Is there a comparable approach with cs-script in this scenario?

**Comment by oleg-shilo** [comment]
Try to upgrade cs-script to v 4.3.0.0. This may help. But...
I just tested it with v4.2.0 and it sees to work as well:
![image](https://user-images.githubusercontent.com/16729806/149621452-a46b78b3-0ae7-4453-a642-709993c5130b.png)

I have attached the project that worked for me.
[WebApplication1.zip](https://github.com/oleg-shilo/cs-script/files/7874933/WebApplication1.zip)

Try it.

**Comment by TomBruns** [comment]
Interesting, I get the same original error on my laptop using 4.2 or 4.3

CS-Script returns:
***@***.***

Here is what I have installed:

***@***.***

Here is the underlying error when I debug using CS Script source code.

***@***.***
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by TomBruns** [comment]
Additional Info

CSScript.RoslynEvaluator works fine, it is only an issue with CSScript.CodeDomEvaluator

Tom

From: Tom ***@***.***>
Sent: Monday, January 17, 2022 7:28 AM
To: ***@***.***>; ***@***.***>
Cc: ***@***.***>
Subject: RE: [oleg-shilo/cs-script] .NET 5 vs .NET 6 confusion (Issue #273)

Interesting, I get the same original error on my laptop using 4.2 or 4.3

CS-Script returns:
***@***.***

Here is what I have installed:

***@***.***

Here is the underlying error when I debug using CS Script source code.

***@***.***
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by TomBruns** [comment]
Resolved.

I found that I still had an older instance of build.dll running on port 17001 started before I upgraded the project.
Once I killed that "orphan" process it worked correctly as expected.

"C:\Program Files\dotnet\dotnet.exe" "C:\ProgramData\cs-script\bin\compiler\2.0.0.0\build.dll" -listen -port:17001 -csc:"C:\Program Files\dotnet\sdk\5.0.404\Roslyn\bincore\csc.dll"
