### ISSUE TITLE
C#-files included with same name into different scripts

### ISSUE THREAD

**Issue by oleg-shilo** [oleg-shilo/cs-script#274]
On behalf of Ralf,

Looking at the scripts we found the following situation:

    each script is located in its own folder
    each file that is css_import(ed) into a script is located in the script’s folder
    both scripts css_import a file with the same name
    after renaming one of these files all problems were gone

It seems as if the second file will not get into an internal cache if there’s already the same file name from the first scrip registered/stored.

**Comment by oleg-shilo** [comment]
I tested the scenario I have recreated from your description and I could not reproduce the problem.
The test project is attached.
[Client.NET-Core.zip](https://github.com/oleg-shilo/cs-script/files/7933898/Client.NET-Core.zip)

Please provide the test case (VS project) so it is possible to reproduce the problem.

**Comment by rp0815** [comment]
Hi Oleg,

meanwhile I managed to create a small Visual Studio 2019 solution containing a WPF app and a class library to encapsulate the access to cs-script (the preview nuget 4.4.3 you sent to me). The projects are based on .NET Framework 4.8. We are using the compiler that comes with the framework.

When trying to start a script the compiler brings up the error (CS1703) we discussed in our last e-mails. It seems as if the compiler wants to load several System.* assemblies that are already loaded but from another location.

BTW, the scripts are located in the subfolder Scripts.

Hope you can reproduce the problem.

Best regards
Ralf

[ScriptTest.zip](https://github.com/oleg-shilo/cs-script/files/8618332/ScriptTest.zip)

**Comment by oleg-shilo** [comment]
Not sure if you sample is complete. It cannot be built. There is no references to cs-script at all.

Will still try to make sense of it.

**Comment by rp0815** [comment]
I put the nuget package you gave me into a local nuget source folder and referenced this. Please see the image beneath.

![image](https://user-images.githubusercontent.com/36657828/166648941-20fd395e-3aa8-4b4b-8745-7821f3cf4905.png)

**Comment by oleg-shilo** [comment]
What is the test case that I need to execute?
![image](https://user-images.githubusercontent.com/16729806/166658318-b8bdb4d9-88ac-430b-bf7c-7e63ce1132da.png)

I loaded the scripts, and... how should I trigger the error condition?

**Comment by oleg-shilo** [comment]
This is the auto-detected compiler
![image](https://user-images.githubusercontent.com/16729806/166660378-b36bf578-599c-4990-add8-1b9a35b84483.png)

**Comment by rp0815** [comment]
I get the same output in the Immediate Window.
![image](https://user-images.githubusercontent.com/36657828/166661699-f043c9d8-cd8c-4694-bbb0-9f4f89765776.png)

In the Output I get this
![image](https://user-images.githubusercontent.com/36657828/166661862-4898de1e-b9f7-488f-9fa0-3adfa15cd552.png)
The compiler's version in the Output is the right one.

Sorry for not routing the compile errors to the UI. They can only be observed in the Output. But, as I see in the image of the test app there are no error at your computer. The pathes of the started scripts are visualized in the list which they should not when errors occurred.

**Comment by oleg-shilo** [comment]
The debug output is empty. There is no any exception. 
Somehow, in our environments it is not happening the same way.
![image](https://user-images.githubusercontent.com/16729806/166671710-76e65c18-0138-4f64-b4bb-a96dd0d3d430.png)

Just in case, to make it really "apple and apple" can you add the nuget reference from nuget.org. This is what I did.

**Comment by oleg-shilo** [comment]
Please package a simple test case with the all dlls included so that I can see the problem happening. Otherwise, it is too many guesses.

I hope you understand

**Comment by oleg-shilo** [comment]
I will share my sample with you...

**Comment by oleg-shilo** [comment]
I have reworked your sample a little (updated UI, added the script routine and invoked it after loading)
See the attached solution.

The problem was caused by the wrong compiler being used. The actual solution (selecting the right compiler) is in the samples that are part of CS-Script codebase: https://github.com/oleg-shilo/cs-script/tree/master/src/CSScriptLib/src/Client.NET-Framework%20(CodeDom)
Though it might not be easy to find.

I have used (and included) the latest pre-release copy of CSScriptLib.dll. But you can also get it from NuGet: https://www.nuget.org/packages/CS-Script/4.4.4-pre 

[ScriptTest.zip](https://github.com/oleg-shilo/cs-script/files/8621370/ScriptTest.zip)

**Comment by rp0815** [comment]
Thank you for the solution. I checked it out and yes it is compiling and running with method Who.

After adding the method ShowMessage(string msg) to TheFirstScript it compiles and runs only when I use System.Windows.Forms.MessageBox.Show() (WINFORMS) although there is no reference to System.Windows.Forms.dll anywhere.

When I use System.Windows.MessageBox.Show() (WPF) it does not compile. Instead I get error CS0234 telling me that type MessageBox is not part of namespace System.Windows. This might be true for project ConsoleApp1 since there is no reference to PresentationFramework.dll in its AppDomain. But project WpfApp should work because there is a reference to PresentationFramework.dll in its AppDomain. Thus it should see the MessageBox of WPF.

Please see the modified script file (zipped for upload).
[TheFirstScript.zip](https://github.com/oleg-shilo/cs-script/files/8629299/TheFirstScript.zip)

**Comment by rp0815** [comment]
Ahh... yes. That was the missing link. Thanks a lot. Now I can check how our hosting app and the new scripting will work together. I meanwhile accepted that we will deliver a new version of the compiler to our customers. BTW, we will have the new syntax which is a nice side effect :-)
