### ISSUE TITLE
Unable to find dependency 'MONO.POSIX' (Signature='0738EB9F132ED756' Version='4.0.0.0') of assembly 'CSScriptLibrary.v3.5.dll'

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#28]
Warning that occurs when building the distributable of my application hosting CSScriptLibrary.v.3.5.dll. This warning did not occur with v3.3.0 / v3.3.5.0 but occurs now with v3.19.0 / v3.19.0.0. Looks like there is some undesirable dependency in CSScriptLibrary.v.3.5.dll.

**Comment by oleg-shilo** [comment]
You can just ignore it. It is expected compile time behavior, that has no effect at runtime. 

The recent work around for broken Mono Mutex implementation on Linux required runtime access to  
MONO.POSIX.dll, which is a Linux interop Mono assembly. 

CS-Script is referencing this assembly but on Windows it is never actually loaded/needed at runtime and on Linux it is always in GAC. That is why there is no need to distribute this assembly via NuGet. The only side effect is that warning when cs-script host is compiled on Windows.
