### ISSUE TITLE
Resolve issue in Compile method in class CodeDomEvaluator (Evaluator.CodeDom.cs)

### ISSUE THREAD

**Issue by TomBruns** [oleg-shilo/cs-script#284]
**<tl/dbr>**
Remove extra text from "Contains" statement that breaks the intention 

**details**
Currently this method contains the following code (I assume to allow some time for the separate process to startup and start listening on the specified socket/port
```
       bool buildServerNotRunning() => response.GetLines()
                                                                    .FirstOrDefault()?
                                                                    .Contains("System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061)")
                                                                    == true;
```
I ran into a scenario where my 1st call always failed (see below) but the 2nd one succeeded.

![image](https://user-images.githubusercontent.com/13077238/154696148-a00b9a3e-5006-4719-accd-2cd625ba06ad.png)

The issue is that the number after the exception for me was different then the hardcoded string **(10061)** in source code

I resolved this by removing that trailing text ` (10061)` in the Contains clause
```
                            bool buildServerNotRunning() => response.GetLines()
                                                                    .FirstOrDefault()?
                                                                    .Contains("System.Net.Internals.SocketExceptionFactory+ExtendedSocketException")
                                                                    == true;
```

**Comment by oleg-shilo** [comment]
Thank you.
Fixed.
Will be available in the very next release
