### ISSUE TITLE
.NET 5?

### ISSUE THREAD

**Issue by StefH** [oleg-shilo/cs-script#285]
You say:
> Please note that this repository is hosting the releases of CS-Script (v4.0.0 and higher), which target .NET 5. 

However the dependencies are listed as:
![image](https://user-images.githubusercontent.com/249938/154840200-92684e7a-3758-4dbc-af42-889b7360e608.png)

So this library can be used fine for .NETStandard 2.0 and higher?

**Comment by oleg-shilo** [comment]
The read me has been updated to explicitly say that the nuget package is compiled for _Standard 2.0_ and CLI for _.NET 5_
