### ISSUE TITLE
v4.4.2 availability on NuGet

### ISSUE THREAD

**Issue by TomBruns** [oleg-shilo/cs-script#288]
As of 15.Apr, **v4.4.1** is the most recent version available.

It looks like you release **v4.4.2** on 16.Mar.

I am interested in getting the official release containing a fix for [Issue #284](https://github.com/oleg-shilo/cs-script/issues/284)

**Comment by oleg-shilo** [comment]
Apologies. It was my mistake. After assessing the changes before the release I incorrectly concluded that v4.4.2 has no changes in the CS-ScriptLib. So did not upload it to nuget.org.

Fixed now. Published. Please ignore the fact that the package says `no changes`, it does have the fix for #284.
