### ISSUE TITLE
Can't use LoadMethod<T> where T is a generic type.

### ISSUE THREAD

**Issue by stephenriddell** [oleg-shilo/cs-script#293]
`LoadMethod<T>` doesn't support generic types for `T`. It seems relatively simple to implement. I'm not sure if there's a particular subtlety informing this choice, or if it was just overlooked.

**Comment by stephenriddell** [comment]
I didn't see any contribution guidelines, I have https://github.com/stephenriddell/cs-script/tree/%23293
Should I create a pull request?

**Comment by oleg-shilo** [comment]
Yes, please do so. There are no extra requirements for that beyond the GitHub contribution guideline :)
