### ISSUE TITLE
No support for nested //css_imp

### ISSUE THREAD

**Issue by rp0815** [oleg-shilo/cs-script#297]
All of the scripts running in our hosting app import one cs-file with //css_imp. This imported file only contains some //css_ref for usually used assemblies and some //css_imp for files containing several needfull classes (Command-implementation, MVVM-support and so on). This worked well with the .NET framework version of cs-script. But, it does not work with the current version. Diving into the cs-script code I came to the conclusion that //css_imp and //css_ref in nested scenario is not supported. Thus, only the first stage import is resolved but not all other imports inside it. There is a very large script code base that must be reworked without the support of nested //css_*

**Comment by oleg-shilo** [comment]
It's a difficult one. But doable.

With the introduction of the Roslyn .NET (base of CS-Script.IEvaluator implementation) team decided to abandon support for multi-file scripts. When I extended `IEvaluator` with csc.exe I was only aiming on matching Roslyn functionality. But... there is no conceptual problems with extending CodeDomEvaluator even further.

Making the issue into "enhancement".
Will look at the best way achieving it.

**Comment by oleg-shilo** [comment]
Done.
Interestingly enough the infrastructure was already there I only needed to integrate it all.
The release is here:
https://www.nuget.org/packages/CS-Script/4.4.5
https://github.com/oleg-shilo/cs-script/releases/tag/v4.4.5.0

**Comment by oleg-shilo** [comment]
Not a problem. 

> So, possibly don’t be too quick with a new version…

That's exactly the reason why I would like to test all your use-cases before releasing it. Txs for your help

**Comment by rp0815** [comment]
I corrected the code in the Common files and checked the compilation. It works.

But i'm getting an error when it comes to create the instance from the script class. I use Evaluator.LoadFile() which internally calls CreateObject(ExtractClassName(scriptText) args). The extraction of the class name returns "*" which leads to an ordered list of types exposed by the script assembly. The first type is taken to create an instance. But it is Common1, not the script class.

OK, in the Zip I have another solution (currently commented out). I use Evaluator.CompileCode() and find the script class by convention.

[cs-script_.297.1.zip](https://github.com/oleg-shilo/cs-script/files/8797145/cs-script_.297.1.zip)

**Comment by rp0815** [comment]
Just an update.
In my last post I told you that I use Evaluator.CompileCode() to seek for the script class by myself. Hmm... this way I get the old problem of //css_imp of files with same names. It all works fine using Evaluator.LoadFile() (except the problem with the wrong script class name). I attached a new ZIP with a third script to check this out by loading second and third script.

IMO there is a difference between the CompileCode() and the LoadFile().

[cs-script_.297.2.zip](https://github.com/oleg-shilo/cs-script/files/8797925/cs-script_.297.2.zip)

**Comment by oleg-shilo** [comment]
Re: cs-script_.297.1.zip

Correct. The compiled assembly happens not to preserve  order of the declaration in the file. Note it is not the result of ordering the types by CS-Script engine but the behavior of the CLR (`Assembly.ExportedTypes`):
![image](https://user-images.githubusercontent.com/16729806/171171484-45d7ad84-2ed6-444c-8959-dc8463229cae.png)
And script engine does ordering as well though not alphabetically but based on the type being a user defined one or internal.

Annoyingly the correct order of the files in the CMD line passed to the CodeDom compiler does not guarantee the same order in the assembly:

![image](https://user-images.githubusercontent.com/16729806/171172035-86d6964f-f80a-4d58-96e5-f6356e36e40e.png)

I have updated the XML API documentation to reflect this fact:
![image](https://user-images.githubusercontent.com/16729806/171172327-59e20010-eebb-43dd-b553-b39c9e9e0808.png)

**Comment by oleg-shilo** [comment]
Re: cs-script_.297.2.zip

Hm... I am not sure how it is possible. 
`LoadFile` and `CompileCode` is essentially the same implementation:
```C#
public object LoadFile(string scriptFile, params object[] args)
{
    var code = File.ReadAllText(scriptFile);
    return CompileCode(code, scriptFile, null).CreateObject(ExtractClassName(code), args);
}
``` 
Will check your sample

**Comment by oleg-shilo** [comment]
Re: cs-script_.297.2.zip
I successfully loaded the third script:
![image](https://user-images.githubusercontent.com/16729806/171174122-4e38eaa6-d51c-4b08-a83a-94ce5f06adea.png)

Is it possible that when you tested you accidentally loaded the nuget package instead of the patched script engine assembly?

**Comment by oleg-shilo** [comment]
![image](https://user-images.githubusercontent.com/16729806/171180820-6c2e49b6-d571-495d-8897-c9563c432d0a.png)

Can you please describe the exact sequence of steps to reproduce the problem in cs-script_.297.2.zip

**Comment by rp0815** [comment]
Ahhh... pain, argony, head banging on my workbench!!! You are absolute right! I changed the AddSearchDirectory into this:

```c#
        private static void AddSearchDirectory(string directory)
        {
            //if (CSScript.GlobalSettings.SearchDirs.FirstOrDefault(d => d.Equals(directory, StringComparison.OrdinalIgnoreCase)) != null)
            //    return;
            CSScript.GlobalSettings.ClearSearchDirs();
            CSScript.GlobalSettings.AddSearchDir(directory);

            Debug.WriteLine("SEARCH DIRS");
            foreach (var d in CSScript.GlobalSettings.SearchDirs)
                Debug.WriteLine(d);
        }

```

and it works. The logical error was to think it is needed to collect search dirs all over the life time of the hosting app which is nonsense once the script is compiled. Now I simply clear the search dirs before adding the script dir.

Thank you so much. Now I can test it in a feature branch of our application.

One thing is strange though. Why are LoadFile and CompileCode behave that different? Maybe it comes from the knowledge of the file name in LoadFile. That's the only difference I can see from the outside.

**Comment by oleg-shilo** [comment]
Great!
Glad we found it.
Let you test a little more.
Let me know when you are comfortable and I will publish the release so you can use nuget package

**Comment by oleg-shilo** [comment]
Great. Thank you. 
Released: https://github.com/oleg-shilo/cs-script/releases/tag/v4.4.6.0

```txt
Install-Package CS-Script -Version 4.4.6
```
