### ISSUE TITLE
Xml Documentation

### ISSUE THREAD

**Issue by ManniManfred** [oleg-shilo/cs-script#30]
Hi,
is it possible to generate Xml Documention too?

**Comment by oleg-shilo** [comment]
Of course. The xml documentation is included in the Choco and NuGet packages as well as available from GitHub release (&lt;cs-script&gt;\lib\CSScriptLibrary.xml).

**Comment by ManniManfred** [comment]
Sorry, my question was if it is possible to generate xml documentation for my scripts (not for CSScriptLibrary).
Is there an option to generate xml documentation when i call CSScript.LoadFiles(files, asmPath, false) for that generated assembly. (See c# compiler option /doc:File)

**Comment by ManniManfred** [comment]
I found the solution. I use //css_co /doc:"C:\GeneratedAssemblies\815c2560-1402-4c8c-b5a9-c8f092b422f6.xml" in script

**Comment by oleg-shilo** [comment]
You can just pass the compiler option to the `LoadWithConfig`: 
```C#
var script = @"<your path>\Script.cs";
var script_xml = Path.ChangeExtension(script, ".xml");

var asm = CSScript.LoadWithConfig(script, null, false, null, "/doc:" + script_xml);
```
And for `LoadFiles` you will need to consolidatedo it by yourself:
```C#
var script = @"<your temp path>\Script.cs";
var script_xml = Path.ChangeExtension(script, ".xml");
string[] sourceFiles = ...

var code = new StringBuilder();
foreach (string item in sourceFiles)
        code.AppendFormat("//css_inc {0};{1}", item, Environment.NewLine);
File.WriteAllText(script, code);

var asm = CSScript.LoadWithConfig(script, null, false, null, "/doc:" + script_xml);}
```

**Comment by oleg-shilo** [comment]
I posted my answer before receiving your "I found the solution" message. Of course //css_co is a winner. I just overlooked it :)

**Comment by ManniManfred** [comment]
thanks anyway
