### ISSUE TITLE
Compatibility with Microsoft.CodeAnalysis version 4.2.0?

### ISSUE THREAD

**Issue by mo-russo** [oleg-shilo/cs-script#303]
Hello,

We're trying to move to Microsoft.CodeAnalysis version 4.2.0 but we're having an issue with with CS-Script that says it can't find version 4.1.0 at runtime. According to nuget.org, the dependencies is supposed to be ">= 4.1.0".

Should CS-Script be compatible with 4.2.0?

Thanks.

**Comment by oleg-shilo** [comment]
That is an interesting problem.

CS-Script is compatible with Microsoft.CodeAnalysis v4.2.0. 
On the screenshot below you can see that VS correctly defined dependencies are defined quite correctly (>=4.1.0).

![image](https://user-images.githubusercontent.com/16729806/183246549-6ef3961e-6809-42f2-b14c-cfdcfa6e5f0c.png)

Thi is how nuget package manager works. It does not pull the latest available version but the one that it was published against. Though it allows you to upgrade the dependencies if `>=` was used in the dependencies specification..

And I have just tested it. I create a hello world app. added CS-Script and updated Microsoft.CodeAnalysis packages to v4.2.0.

![image](https://user-images.githubusercontent.com/16729806/183247228-e89e60ea-0486-4521-82c5-1d45e5e33333.png)

**Comment by mo-russo** [comment]
Thanks for the quick reply Oleg. It seems it was an issue with another nuget package we were referencing. Updating it to a newer version made this error go away.
