### ISSUE TITLE
cscs does not use compilation cache when path to the script has unicode characters  

### ISSUE THREAD

**Issue by eugene-vv** [oleg-shilo/cs-script#307]
It compile it all the time before execution, it does not depends that script was not changed.
Just create simple script file in path with unicode characters like "фыва":
`using System;
class MyClass
{
    public static void Main()
    {
        Console.WriteLine("Script finished");
    }
}`
run cscs -verbose <script_name>.cs

**Comment by oleg-shilo** [comment]
Thank you. Will have a look at it next week

**Comment by oleg-shilo** [comment]
Done. Will be available in the very next release

**Comment by oleg-shilo** [comment]
Released. You can get it from choco

**Comment by eugene-vv** [comment]
thanks Oleg!
