### ISSUE TITLE
Can we compile script into console application executable using csc or roslyn engines?

### ISSUE THREAD

**Issue by sken130** [oleg-shilo/cs-script#314]
I tried `"C:\cs-script\netcore\cs-script.win.v4.4.7.0\cscs.exe" -e -engine:csc "MyScript.cs"`
but if MyScript.cs contains `//css_co -nullable:enable -warnaserror:nullable`, then it gives `error MSB1001: Unknown switch.`

This makes me think it is not using the csc engine to compile the script into execute file.

**Comment by oleg-shilo** [comment]
Correct. It is because csc.exe cannot build exe so the building assembly is tunnelled to dotnet.exe engine instead.

[```C](https://github.com/oleg-shilo/cs-script/blob/8edd2d3cc18caf76ad59535fe16a035fc8cdb8eb/src/cscs/CodeDom/Proxies.cs#L97-L101)

Though despite having a good reason for this behaviour must be reflected in the documentation but it's not.
The code has been updated and the enhancement will be available in the very next release

**Comment by sken130** [comment]
Thanks for the update. Also, I suggest mentioning the same thing in this wiki:
https://github.com/oleg-shilo/cs-script/wiki/CS-Script---Command-Line-Interface

**Comment by oleg-shilo** [comment]
Yes but only when the release is out.
This page is generated from `css -?` so when the release is out the page will be refreshed as well.
