### ISSUE TITLE
could it be installed by dotnet tool install

### ISSUE THREAD

**Issue by heartacker** [oleg-shilo/cs-script#317]
```
dotnet tool install --global cs-script
```

**Comment by oleg-shilo** [comment]
Done. Ready for the release.
With the very next release (in a few days), it will be published as `cs-script.cli` tool on nuget.org.

_Note, before uninstalling the tool you may need to ensure the tool executable file is not locked. Choco manages such situations automatically but with dotnet you need to stop the process if it is running. You can do it from the command prompt or any other shell terminal: `css -servers:stop`_

**Comment by oleg-shilo** [comment]
Done
https://www.nuget.org/packages/cs-script.cli
