### ISSUE TITLE
Inconsistent time stamp (.dll -vs- .pdb) when using CSScript.CompileFile() with 'debugBuild = true'

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#32]
The time stamp of the compiled assembly file (.dll) is set to the time stamp of the original script file (.cs). I guess that behavior is intended (even if it's a bit surprising to find a .dll file that has just been compiled with a time stamp of e.g. last year...). So far so good.

However, the accompanying debug database file (.pdb, 'debugBuild = true') is set to the time stamp when the compilation took place. In my opinion, this is inconsistent. Both files should be set to the same time stamp if this is possible.

**Comment by oleg-shilo** [comment]
Compiled assembly is a to part of assembly CS-Script caching based on file timestamps. However .pdb is not. Thus this inconsistency is intended. And if it doesn't cause any undesirable side effects the existing behavior is to stay unchanged.

Keep in mind that the assemblies (of the script being executed) are CS-Script specific artefacts that are only CS-Script is concerned about. The intention is that these files are not to be further distributed but only used by the script engine.

**Comment by maettu-this** [comment]
I agree that these artifacts are CSScript specific. Still, a user sees the two files and may get confused (as I have gotten). I mainly got confused by the fact that both timestamps mismatch, I'd be fine if both timestamps reflected the script's original timestamp. Maybe you find an easy way to adjust the .pdb's timestamp at or after compilation.

Note that 'my' hosting application always uses 'debugBuild = true' in order to have all resulting assemblies prepared for potential debugging.

**Comment by oleg-shilo** [comment]
Done in 4843d60badbea5dc0d122f2d40d8f834c2312ca3
Will be available in v3.21 Release

**Comment by oleg-shilo** [comment]
Addressed in Release v3.21.1
