### ISSUE TITLE
How do I generate xml documents for assemblies compiled by my cs scripts?

### ISSUE THREAD

**Issue by WeiJunFenYou** [oleg-shilo/cs-script#320]
Assembly compiled by cs script:

`var assembly = CSScript.RoslynEvaluator.CompileCode(Class1.Code);`

How do I use its comments to generate an xml document?

At In csproj, you can set GenerateDocumentationFile to True to generate xml documents, but I can't find the corresponding method for the cs script

#30 

The code for the solution to this problem cannot be compiled

**Comment by damian-666** [comment]
btw iove the snowflake algorithm... one issue to be aware of is that rosyln is  flux and visual studio is regressing now. when my code completon slow to a craw in dev studio, 2 week ago i rolled back one verson otehrs have rolled back more .    its seems to me the code analysis analysers themselves that are especially delicate seems like..    **so if you can provide exact version of visual studio or your tool chain,  and the .net versons  you are using,  and such it would help.**  i was using net 7 and previews wtihot  trouble and i had to rollback last week for the first time,  but the official release has similar regressoins  and its not even clear which version they are talking about  , there arent giving the full verson numbers.   and some of the tooling is closed source.     net 6 and net standard and the toolchain have a ton of problems and old dependences, and from looking at the netcore vaults is a bit scary right now, im hoping it wil get sorted but its not stable right now evne microsoft  flagship tooling cant use rosyln 

reliably nor do they control the source fully.   https://github.com/dotnet/arcade/issues/11848     i mean , the issues are just piling up.. 
 https://github.com/dotnet/roslyn/issues

**Comment by WeiJunFenYou** [comment]
> btw iove the snowflake algorithm... one issue to be aware of is that rosyln is flux and visual studio is regressing now. when my code completon slow to a craw in dev studio, 2 week ago i rolled back one verson otehrs have rolled back more . its seems to me the code analysis analysers themselves that are especially delicate seems like.. **so if you can provide exact version of visual studio or your tool chain, and the .net versons you are using, and such it would help.** i was using net 7 and previews wtihot trouble and i had to rollback last week for the first time, but the official release has similar regressoins and its not even clear which version they are talking about , there arent giving the full verson numbers. and some of the tooling is closed source. net 6 and net standard and the toolchain have a ton of problems and old dependences, and from looking at the netcore vaults is a bit scary right now, im hoping it wil get sorted but its not stable right now evne microsoft flagship tooling cant use rosyln
> 
> reliably nor do they control the source fully. [dotnet/arcade#11848](https://github.com/dotnet/arcade/issues/11848) i mean , the issues are just piling up.. https://github.com/dotnet/roslyn/issues

My question is how to use this library to generate xml documents instead of using vs to generate xml documents.

**Comment by oleg-shilo** [comment]
Hi @WeiJunFenYou ,

Generating XML documentation is a type of functionality that does not belong to the scripting domain. Thus it is best to be done with IDE. VS in this case.

While technically it is possible (and relatively simple) it is unlikely this functionality if implemented in the script engine will be utilized by the users (except you of course 😄). 

If you feel strongly that it needs to be part of cs-script functionality then log the feature request and if uitv is upvoted I will implement it.

**Comment by WeiJunFenYou** [comment]
> Hi @WeiJunFenYou ,
> 
> Generating XML documentation is a type of functionality that does not belong to the scripting domain. Thus it is best to be done with IDE. VS in this case.
> 
> While technically it is possible (and relatively simple) it is unlikely this functionality if implemented in the script engine will be utilized by the users (except you of course 😄).
> 
> If you feel strongly that it needs to be part of cs-script functionality... let's wait and see if this feature request (I marked this issue as a Feature Request) upvoted I will implement it.

Thank you for your reply. I see.😊
