### ISSUE TITLE
csscripter hangs on compilation step

### ISSUE THREAD

**Issue by eugene-vv** [oleg-shilo/cs-script#321]
Hi Oleg,
We found that simple script with error hangs cscs on compilation.
```c#
using System; 
class MyClass
{
    public static void Main()
    {
        throw new Ex ception();
    }
}
```
Running cscs script.cs hangs.
We checked that 4.4.7 works, 4.4.8 and 4.4.9 hangs.
Will it be possible to provide binaries for .Net6?
Happy new year!

**Comment by oleg-shilo** [comment]
Sorry @eugene-vv,
But releasing binaries targeting older versions of runtime is not a viable option.

Thus you can either just use the older version of CS-Script or recompile the script engine by yourself.
You may need to adjust the build file to use the corresponding compiler:
![image](https://user-images.githubusercontent.com/16729806/209657145-91d3ab3c-3b00-45f6-a44d-817a725dc5ed.png)
