### ISSUE TITLE
Unloading Script assemply issue

### ISSUE THREAD

**Issue by BernhardPollerspoeck** [oleg-shilo/cs-script#322]
i check the count of all loaded assemblies at the start and a few seconds after my unloat atempt.

but in "loadedAssemblies3" there is still the user generated assemply loaded.

either my method of checking is wrong, or there is some issue with unloading the script generated code.

is it even possible to fully unload/clear all script code data at runtime?

![grafik](https://user-images.githubusercontent.com/105512133/210850786-c670d8c5-7fa9-41f1-bef0-2f0d4deb8fda.png)

**Comment by oleg-shilo** [comment]
Hi Bernhard,

Yes, it is supposed to be possible. In .NET Framework the task was quite hard but in .NET Core it became possible.

I have created an example for that:
https://github.com/oleg-shilo/cs-script/blob/8894d6d1972c34af27c784304791d6468c1a0801/src/CSScriptLib/src/Client.NET-Core/Program.cs#L95-L110

After the activation of the cs-script runtime, the amount of AppDomain assemblies stays the same regardless how many times ou execute the script.

![image](https://user-images.githubusercontent.com/16729806/210913250-5b23ff8a-7fee-4fea-aac0-c4cb23fc0c68.png)

**Comment by BernhardPollerspoeck** [comment]
Hi Oleg, 
thank you for your sample.
i can see your script loading the assemblies once, but i was looking for removing all traces of the code the script introduced. 
(I try to save me to restart the code runner instances after each run. But due to security requirements i need the system to report all previous code traces gone before i can load new code into.

**Comment by oleg-shilo** [comment]
> can see your script loading the assemblies once

Not exactly. It loads the compiled script 20 times and unloads it 20 times.
BTW you will also need to ensure your script is not cached since you have such a strong requirement.
`...Evaluator.With(eval => eval.IsCachingEnabled = false)...`. 
Though it is disabled by default anyway.

**Comment by BernhardPollerspoeck** [comment]
> Not exactly. It loads the compiled script 20 times and unloads it 20 times.
Yeah, bad wording by me. sorry :)

> BTW you will also need to ensure your script is not cached since you have such a strong requirement.
> 
> ```cs
> CSScript.Evaluator
>         .With(eval => eval.IsCachingEnabled = false)
>         .Load...
>             
> ```
> 
> Though it is disabled by default anyway.
With "IsCachingEnabled = false" i still have the generated assembly in memory. i will dig more into the contents, but i cant see any change when my unload is done. this lets me suspect that, the script is not unloaded. but i am unsure if it might be indeed unloaded, and my method of checking is wrong.

**Comment by oleg-shilo** [comment]
>  With "IsCachingEnabled = false" i still have the generated assembly in memory.

Caching is about keeping a compiled script file on your file system so you don't need to compile the script if it is not changed since the last compilation. But of course, you are going to load the script in the memory. You have to. Otherwise, you cannot execute it.

> ...but i cant see any change when my unload is done

`script.GetType().Assembly.Unload();`

**Comment by BernhardPollerspoeck** [comment]
Loading the script into memory is totaly fine.
but after the execution it should get cleared.
i used the AssemblyLoadContext to try to unload. that dint crash, but also did not unload the assembly.

now i tried your tipps(seperate and und combination, and also in combination with and without the unload of the Context(before and after the assembly unloat atempt.
but if i try to unloat the assemply(in every test) i get a ExecutionEngineException.
i try to prepare a mvp sample later and link it for you.

**Comment by BernhardPollerspoeck** [comment]
`var script = """
	public int Add(int x, int y)
	{
		return x + y;
	}
	""";

var assemblies1 = AppDomain.CurrentDomain.GetAssemblies().ToList();

var runnable = CSScript.Evaluator.With(eval =>
{
	eval.IsAssemblyUnloadingEnabled = true;
	eval.IsCachingEnabled = false;
})
.LoadMethod<IRunnable>(script);

var assemblies2 = AppDomain.CurrentDomain.GetAssemblies().ToList();

var result = runnable.Add(1, 2);

var assemblies3 = AppDomain.CurrentDomain.GetAssemblies().ToList();

//unload via context
//var asm = runnable.GetType().Assembly;
//var ctx = AssemblyLoadContext.GetLoadContext(asm);
//ctx!.Unload();

//unload via assembly
var asm2 = runnable.GetType().Assembly;
asm2.Unload();`

just paste this into a empty net 5/6/7 console program. The Exception i mentioned in my comment before, i could find. was a mistake by me. 
but either way the assembly is not unloaded.

**Comment by oleg-shilo** [comment]
Sorry Bernhard, there may be some confusion.

I have shared with you the sample that does what you want to achieve. 
I suggest you use it as a benchmark and port it to your scenario. 

>now i tried your tipps(seperate and und combination, and also in combination with and without the unload of the Context(before and after the assembly unloat attempt.

This is where it is kinda confusing. It was not a tip but a working sample that shows you how to achieve the desired behaviour. If it does not do what it is supposed to do then we can have a look at it.

Please note, if you try to use any "combination" then it's impossible to interpret what is happening at runtime. The extension method `Unload()` calls `AssemblyLoadContext.Unload()` thus combining them may lead to the attempt to unload the assembly twice.

Note, the problem you are dealing with has nothing to do with the scripting. It is a generic problem.
You can even separate your task into two phases (pseudo-code):

1. Compile assembly
   ```C#
   string assemblyFile = CSScript.CompileAssemblyFromCode(...);
   ```
2. Manage Loading/Unloading assembly
    ```C#
   Assembly asm = <load assembly file>(assemblyFile);
   . . .
   <unload assembly>
   ```

**Comment by oleg-shilo** [comment]
Please note that in order to trigger assembly collection by GC you will need to ensure that its references go out of scope. 
That's why it is important that you follow the sample I provided. It does it correctly.

**Comment by BernhardPollerspoeck** [comment]
@oleg-shilo  just checking in and let you know i will build a full mvp project this weekent to test it out and reporting back then.

**Comment by oleg-shilo** [comment]
Txs

**Comment by BernhardPollerspoeck** [comment]
Hi @oleg-shilo ,

ive built a small sample, where i log the number of loaded assemblies. At the end the ammount of loaded assemblies stays the same. this is only one indication, that it is still loaded.

I did a few things to try get it unloaded.

*   Moved all script references in a own method, to be able to make sure i can propperly remove all references to the script
*   Executed the script in another thread.

in the Run method i have 2 seperate ways of unloading the assembly.

I dont know what else is nessecary to get the assembly unloaded. Is it possible, that you may have a standalone working sample, that proves the assembly got unloaded correctly? 

unfortunally i cant get it to work.

**Comment by BernhardPollerspoeck** [comment]
[https://github.com/BernhardPollerspoeck/CsSrcipt.unload.issue](https://github.com/BernhardPollerspoeck/CsSrcipt.unload.issue)

Stupid me... here is the link. sorry i forgot

**Comment by oleg-shilo** [comment]
Will have a look. Thank you

**Comment by oleg-shilo** [comment]
Your script is fine.
The only problem is that you never give your CLR the chance to collect the assembly. GC is never executed. 
`Unload` only marks the assembly for unloading. It is GC who collects it.

Modify the code like that and you will see that the very last `LogAssemblyCount` does not detect the script assembly any more:

```C#
using CSScripting;
using CSScriptLib;
using CsSrcipt.unload.issue;
using System.Runtime.Loader;
using System.Text;

void test()
{
    LogAssemblyCount();

    var runner = new ScriptRunner();

    LogAssemblyCount();

    runner.Runner.Start();

    while (runner.Runner.ThreadState != ThreadState.Stopped)
    {
        LogAssemblyCount();
        Thread.Sleep(1000);
    }

    runner = null;

    Thread.Sleep(10000);
    LogAssemblyCount();

    Console.WriteLine("Hello, World!");
}
void LogAssemblyCount()
{
    Console.WriteLine($"{DateTime.Now}      {AppDomain.CurrentDomain.GetAssemblies().Length}");
    Console.WriteLine($"  script assembly > {AppDomain.CurrentDomain.GetAssemblies().FirstOrDefault(x => x.FullName.Contains("#1-0"))}");
}

test();
GC.Collect();
LogAssemblyCount();
```
and
```C#
. . .
        var script =
                        """
			public int Add(int x, int y)
			{
				Console.WriteLine(this.GetType().Assembly.FullName);
				return x + y;
			}
			""";
```

**Comment by BernhardPollerspoeck** [comment]
@oleg-shilo works like a charm.. thank you a lot for your continued efforts. 

i am really looking forward to use your awesome project.
