### ISSUE TITLE
Upgraded to CS-SCript 4 version and unable to find UseAlternativeCompiler setting.

### ISSUE THREAD

**Issue by caesarm** [oleg-shilo/cs-script#330]
I was trying to migrate from CS-Script.bin 3.30 package to CS-Script 4.6.5 version and cannot find a way to use the CSSCodeProvider to specify VB for the script. The UseAlternativeCompiler settings seems to be removed from the GlobalSettings.

```
CSScript.EvaluatorConfig.DebugBuild = Application.IsDebugBuild;
CSScript.EvaluatorConfig.Engine = EvaluatorEngine.CodeDom;
CSScript.EvaluatorConfig.Access = EvaluatorAccess.Singleton;
CSScript.GlobalSettings.UseAlternativeCompiler = Assembly.GetExecutingAssembly().Location;
```
Is this still supported?

**Comment by oleg-shilo** [comment]
In CLI interface the alternative compiler is still supported but for the hosted execution (your case) only CodeDom and Roslyn engines are supported currently.

Saying that you can specify your custom compiler but I do not know if it will work straight away:

```C#
CodeDomEvaluator.CompileOnServer = false;
Globals.csc = @"your vbc.exe file";
```

**Comment by oleg-shilo** [comment]
Agree. Done.
The change will be available in the very next release.
Thank you for investigating it.
