### ISSUE TITLE
how to use this to run csharp string as script in netapp

### ISSUE THREAD

**Issue by heartacker** [oleg-shilo/cs-script#333]
for example:
code:
```csharp
 using System;
 using ns = My.other.NameSpce.Foo;// the net app
 
 public class Script
 {
      public int Sum(int a, int b)
      {
          return a+b;
      }
 }
 
 var s = new Script();
 var result = s.Sum(2, 3);
 Console.WriteLine(result);
 
 System.Console.WriteLine(ns.Bar(result));// call the bar functions  of the host net app
 
 System.Console.WriteLine("The code run end");
```

I want to run the code(string) in my net app by using CSScript.
how can we?

is there any API like `CSScript.Evaluator.Run(string codestring)` for us to evaluate
thanks

**Comment by heartacker** [comment]
https://github.com/dotnet/roslyn/blob/main/docs/wiki/Scripting-API-Samples.md

**Comment by oleg-shilo** [comment]
The example above is not using CS-Scriprt but Roslyn API. But I assume your question was about CS-Script (since it is CS-Script project page).  😄 If it is correct then have a look at the corresponding Wiki: https://github.com/oleg-shilo/cs-script/wiki/Hosted-Script-Execution

This is the simplest possible sample from it:

```C#
dynamic calc = CSScript.Evaluator
                       .LoadMethod(@"int Multiply(int a, int b)
                                     {
                                         return a * b;
                                     }");

int result = calc.Multiply(3, 2);
```

If you add CS-Script nuget package to your VS project, it will also add the samples file to it.

**Comment by heartacker** [comment]
no, your example is only the method, I also need to run the method in the script
I want to run this 
```
 using System;
 using ns = My.other.NameSpce.Foo;// the net app
 
 public class Script
 {
      public int Sum(int a, int b)
      {
          return a+b;
      }
 }
 
 var s = new Script();
 var result = s.Sum(2, 3);
 Console.WriteLine(result);
 
 System.Console.WriteLine(ns.Bar(result));// call the bar functions  of the host net app
 
 System.Console.WriteLine("The code run end");

```
with one API,

**Comment by oleg-shilo** [comment]
Please read the Wiki that I provided the link for. As I indicated I only gave you the simplest example and the article contains plenty of others.

And if you do use the nuget package I suggested it will bring all other possible samples.

You can also browse some of the samples in the repo:
![image](https://github.com/oleg-shilo/cs-script/assets/16729806/ae34de11-8fc1-47bc-87a9-a965170c3a6a)
