### ISSUE TITLE
Is UnloadOwnerDomain no longer needed?

### ISSUE THREAD

**Issue by oskarjf** [oleg-shilo/cs-script#338]
I'm upgrading from an older version of CS-Script and after installing the latest version the compiler complains that UnloadOwnerDomain is not a method of object.
Can I just remove this?

Sample code:
`CSScript.Evaluator.Reset();
                var compiledObject = CSScript.Evaluator.LoadCode(ServerCompileIncludes + code);
                var result = compiledObject?.ToString();
                compiledObject?.UnloadOwnerDomain();
                compiledObject = null;`

**Comment by oleg-shilo** [comment]
Sorry for the delay with the response.

Can you guide me on which sample you are referring to?

The repo seems to not have any sample with this method:
![image](https://github.com/oleg-shilo/cs-script/assets/16729806/ef2803d2-6049-4054-a7e1-b49b823ac18b)

Just in case, please be aware that with the new API there is a somewhat similar extension `void Unload(this Assembly asm)`:

```C#
var script = CSScript.Evaluator
                     .With(eval => eval.IsAssemblyUnloadingEnabled = true)
                     .LoadMethod<ICalc>(@"public int Sum(int a, int b)
                                          { return a+b; }");

script.Sum(1, 2);

script.GetType().Assembly.Unload();
```

**Comment by oskarjf** [comment]
Sorry, I didn't mean that this was code from one of your samples. Only that the code is taken from the system I'm upgrading.

**Comment by oskarjf** [comment]
I'll try to use the Assembly.Unload() instead

**Comment by oleg-shilo** [comment]
Yep, since.NET Core introduced the mechanism for direct assembly unloading the old workaround `UnloqadOwnerDomain` is no longer needed. 
That's why this method is no longer in the API.
