### ISSUE TITLE
Publish to single file gives an empty Assembly.Location which crashes Roslyn Evaluator

### ISSUE THREAD

**Issue by angrynik** [oleg-shilo/cs-script#343]
I'm running a .NET 7 WPF app with a reference to CSScriptLib nuget.

My project works great and scripts run right in debug mode. When I publish I get the error:

"Current version of Roslyn-based evaluator does not support referencing assemblies which are not loaded from the file location."

I publish to a single file which merges most of the referenced dlls into a single dll. Looks like this code in Evaluator.Roslyn.cs is having a problem with it:

```
        public override IEvaluator ReferenceAssembly(Assembly assembly)
        {
            //Microsoft.Net.Compilers.1.2.0 - beta
            if (assembly.Location.IsEmpty())
```
I checked this in my code when publishing both to many files and to a single file and in the latter case Location is empty.

```
            if (string.IsNullOrEmpty(typeof(IRunScriptAsync).Assembly.Location))
                throw new System.Exception("Assembly.Location is empty");

```

**Comment by angrynik** [comment]
I think it's a Roslyn problem, this issue has gone nowhere for a few years:

https://github.com/dotnet/roslyn/issues/50719

That page links to a workaround here: https://github.com/andersstorhaug/SingleFileScripting

I'm new to this so I don't know if that's something I can do myself, or if it could be used in cs-script ? For now I'm going to switch off single file output, and add a hundred dlls to my Wix installer.

**Comment by oleg-shilo** [comment]
I am not sure it is a real workaround. 
We have the problem here that Roslyn scripts cannot reference loaded assemblies but only assembly files. The code there does not show the script that references any of such assemblies. It only references core assembly. You can do it with CS-Script too. 
Your problem is more fundamental. After merging all your dependency assemblies in a single file it's no longer an assembly that can be referenced.

But... I will play a little with it today to confirm what I just described.

**Comment by oleg-shilo** [comment]
Looked at the sample more...
it might be the way out, actually.
give me some time, I think it is something that can be the way out for cs-script in this scenario.

**Comment by angrynik** [comment]
Thanks for looking, would be very nice....

**Comment by oleg-shilo** [comment]
I can confirm now that with that work around it is now possible to execute scripts from the host app built as a single self-contaied file. Thank you for sharing the info.

I will a little time to properly integrate it and release the update. The future syntax will look like this:

```C#
var calc = CSScript.Evaluator.Execute("1 + 2");

```
or
```C#
var calc = CSScript.Evaluator
                   .Execute(@"using System;
                              public class Script
                              {
                                  public int Sum(int a, int b)
                                  {
                                      return a+b;
                                  }
                              }
                              return new Script();");

int sum = calc.Sum(1, 2);
```

**Comment by oleg-shilo** [comment]
Done.
Please update your nuget ref to v4.8.3.

```C#
var calc = CSScript.Evaluator
                   .Eval(@"using System;
                           public class Script
                           {
                               public int Sum(int a, int b)
                               {
                                   return a+b;
                               }
                           }
                           return new Script();");

int sum = calc.Sum(1, 2);
Console.WriteLine(sum);
```

The complete sample can be found [here](src/CSScriptLib/src/CSScriptLib/samples.cs).

**Comment by angrynik** [comment]
Ok, awesome, I have refactored from LoadMethod to now use Eval, and it works great in debug mode. I publish to a single file and now I get:

> CodeBase is not supported on assemblies loaded from a single-file bundle

I'm pretty sure my code is similar to your example, but with lots of "using " statements for other referenced assemblies.

**Comment by oleg-shilo** [comment]
I did test the code sample (https://github.com/oleg-shilo/cs-script/blob/master/src/CSScriptLib/src/Client.SingleFileBuild/Program.cs) after publishing so there is something new in your case.

Can you share the solution you are testing so I can have a look? A sanitized version of it. 
Or a hello-world example that demonstrates the problem.

**Comment by angrynik** [comment]
Right, I added a class library with one class that runs a script.
```
namespace BreakLib;
public class BreakClass
{
    public static string RunScript()
    {
        var calc = CSScript.Evaluator
                           .Eval(@"using System;
                           public class Script
                           {
                               public int Sum(int a, int b)
                               {
                                   return a+b;
                               }
                           }
                           return new Script();");

        int sum = calc.Sum(1, 2);
        return $"sum is {sum}";
    }
}
```
Then I reference the project and call that method from the Client.SingleFileBuild sample.
```
...
...
var result = BreakLib.BreakClass.RunScript();
Console.WriteLine(result);
```
This is the setup I use, where the script runner is in a dedicated project and I call that from my apps.

**Comment by oleg-shilo** [comment]
I repeated the test. Seems to work as expected.
I have attached the test project
[cs-script.#343.zip](https://github.com/oleg-shilo/cs-script/files/12787329/cs-script.343.zip)

**Comment by angrynik** [comment]
Hmmm. Can I ask how you publish? I do it through Visual Studio with these settings, and managed to crash this sample.

<img width="236" alt="image" src="https://github.com/oleg-shilo/cs-script/assets/66042174/8d2fa52e-d4f5-44bb-9b04-27f91fd5f800">

**Comment by oleg-shilo** [comment]
it's in the code `program.cs`. 

![image](https://github.com/oleg-shilo/cs-script/assets/16729806/e832264d-8aa5-4ed1-b6e3-c5d058ec0b96)

![image](https://github.com/oleg-shilo/cs-script/assets/16729806/cb17a34b-3109-4f9a-abbe-8d17cfe0a4a4)

![image](https://github.com/oleg-shilo/cs-script/assets/16729806/a771ae97-5e21-4a60-93eb-d27bab503e10)

**Comment by angrynik** [comment]
It looks like the Deployment Mode must be set to Self-contained.

**Comment by oleg-shilo** [comment]
Can you please give me the project sample then. So we are working on the same things

**Comment by angrynik** [comment]
Sorry for the confusion, I am using your project and yes it does work in self contained mode. The problem arises when deployed as Framework dependent, or self-contained = false.

I have always used Framework dependent deployments, due to a smaller file size, but I'm thinking self-contained does have benefits, and the bandwidth is not such a big deal these days. So deploying self-contained as the solution is not a problem.

**Comment by angrynik** [comment]
`dotnet publish -c Release --no-self-contained`

**Comment by oleg-shilo** [comment]
Great, it works.

In the code I analyze if it is a single-file deployment. The analysis is done like this:

```C#

public static bool IsSingleFileApplication { get; } = "".GetType().Assembly.Location.IsEmpty();

. . .

catch (Exception ex)
{
#if class_lib
    if (Runtime.IsSingleFileApplication)
        return null; // a single file compilation (published with PublishSingleFile option)
#endif
    throw;
}                
```

But if the app compiled as in your case the `IsSingleFileApplication` does not detect "danger of calling CodeBase".

The updated version with the fallback exception handler looks like this:
```c#
catch (Exception ex)
{
#if class_lib
    if (Runtime.IsSingleFileApplication)
        return null; // a single file compilation (published with PublishSingleFile option)
    else if (ex.Message.Contains("CodeBase is not supported on assemblies loaded from a single-file bundle")
            || ex.StackTrace.Contains("at System.Reflection.RuntimeAssembly.get_CodeBase()"))
        return null;
#endif
    throw;
}
```

And it works just fine.
![image](https://github.com/oleg-shilo/cs-script/assets/16729806/d0086de3-186c-4baa-894d-bf3fb8e23714)

**Comment by oleg-shilo** [comment]
I do not want to do premature release so will release this change as a pre-release.

You can probably appreciate now why I always ask for a VS test project 😄 
A verbal description of the test actions is never as accurate as code.

**Comment by oleg-shilo** [comment]
Done, you can get the latest v4.8.4-pre pre-release from nuget.org.

```
dotnet add package CS-Script --version 4.8.4-pre
```

**Comment by angrynik** [comment]
It works! Amazing thank you.

**Comment by jackhab** [comment]
@oleg-shilo 

Hi Oleg

I'm also trying to build single-file executable so I used your [example](https://github.com/oleg-shilo/cs-script/files/12787329/cs-script.343.zip) which works fine but when I moved the code from the class library into Main() and removed the library from the solution the generated exe failed with 
```
Unhandled exception. CSScriptLib.CompilerException: <script>(1,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
<script>(2,35): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
...
```
Is it supposed to be like this and I should always use the library to publish single-file executable?

**Comment by oleg-shilo** [comment]
That is a very interesting scenario which, ironically, is already covered in the samples but not well reflected in the documentation. The reason is... I did not know about this behaviour. :)

Your post pushed me to re-test both samples:
1. The [sample](https://github.com/oleg-shilo/cs-script/files/12787329/cs-script.343.zip) shared in this thread (uses host app that loads the library doing script execution with CSScriptLib)
2. The [sample included](src/CSScriptLib/src/Client.SingleFileBuild/Program.cs) in the repo codebase (uses the host app that does script execution with CSScriptLib). This is the case you are enquiring about.

This is what I have found:
- Sample \# 1 
  works with: `dotnet publish -c Release  --self-contained true` 
  does not work with: `dotnet publish -c Release --self-contained false`
  
- Sample \# 2 
  does not work with: `dotnet publish -c Release  --self-contained true` 
  works with: `dotnet publish -c Release --self-contained false`
     
This means that the different deployment strategies lead to different points of failure. And while it sounds very hacky, the way you structure your single-file build is the only way to control this behaviour today. Unfortunately. Thus, I suggest you either keep that library. Or change the value of `--self-contained` you use for the build (if it is acceptable for you).

What is kinda disappointing is that Roslyn does not deliver any proper solution, and the workaround found and discussed in this thread (using `CSharpParseOptions.kind = SourceCodeKind.Script`) is kinda flaky and may fail because of the single-file build structuring. But at least it gives us some way of achieving what is needed.

Have a look at the [sample](src/CSScriptLib/src/Client.SingleFileBuild/Program.cs). It might be exactly wat you need.

**Comment by jackhab** [comment]
Oleg,
keeping the script engine in a library is not a problem, I just thought I'm dong something wrong in my project settings.

Thank you very much for this wonderful project and your support effort.
