### ISSUE TITLE
Debug using Hosted Script Execution

### ISSUE THREAD

**Issue by MUN1Z** [oleg-shilo/cs-script#347]
Hello, i iam trying debug my csx scripts using the hosted script execution, but i do not have success.
Its my code example:
![image](https://github.com/oleg-shilo/cs-script/assets/17263249/7feac68c-92e3-48b9-aee1-bf41904512bd)
![image](https://github.com/oleg-shilo/cs-script/assets/17263249/dd7f6731-e907-4971-ac50-cd9f4747b31b)

Its possible debug using hosted script execution?

**Comment by oleg-shilo** [comment]
You can do this. You just need to tell the compilers that you need a debug build. Similar to what you do with VS.

```C#
CSScript.EvaluatorConfig.DebugBuild = true;

dynamic script = CSScript.RoslynEvaluator
                         .LoadMethod(@"public (int, int) func()
                                       {
                                           return (0,5);
                                       }");

(int, int) result = script.func();
```

**Comment by oleg-shilo** [comment]
Yep, you are right. Giving the temp file.cs extension does the trick.
Done.
Will be available in the very next release

**Comment by MUN1Z** [comment]
Thanks @oleg-shilo i have tested your last commit: 
![image](https://github.com/oleg-shilo/cs-script/assets/17263249/acc6075c-0f44-4a16-85df-56fa642adcdc)
I going close this issue.
