### ISSUE TITLE
CSScript.ShareHostRefAssemblies issues

### ISSUE THREAD

**Issue by folibis** [oleg-shilo/cs-script#35]
As I understand a script loaded with `CSScript.LoadCode` can access all host variables. For me it looks strange since I cannot control user activity. So I've found that setting `CSScript.ShareHostRefAssemblies` to false forbids that. But I still want to pass to the script some custom object. Is that possible?

**Comment by oleg-shilo** [comment]
>As I understand a script loaded with CSScript.LoadCode can access all host variables. 

Not exactly. The script code can access all public **types** defined in your host code. The same way as your code can access all public types defined in the `System.Windows.Forms.dll`. If one considers this to be a security risk then the risk is of the same level as the whole .NET programming model. Thus you are safe here. 

`CSScript.ShareHostRefAssemblies` simply means that when the script is compiled then the all host appdomain assemblies are being referenced by the script. Assemblies (files) but not their runtime context.

I can imagine a few use-cases when it is not desirable but none of them is realistic. Even though, you can set `ShareHostRefAssemblies` to `false` but then you most likely will need to pass your assemblies manually in your `LoadCode`:
```C#
static public Assembly LoadCode(string scriptText, params string[] refAssemblies)
```

**Comment by folibis** [comment]
Thanks Oleg, now that looks clearer for me. But what if I need is to pass some proxy object or rather reference to the object, not assembly? Such model is just known for me from other script engines like ClearScript etc. I mean I want to provide some API through proxy object passed to script. Is that possible?

**Comment by oleg-shilo** [comment]
Not a problem. You just create that object and pass it to the script. 

The strongest point of CS-Script as a scripting solution is that it is does not form heterogeneous relationship with the host application as many other scripting solutions do. Instead it exhibits the same behavior (even the same syntax) and shares the same runtime as the host application does.  The easiest and the most correct way to think about CS-Script execution is to imagine that the script is a fully compiled assembly that you need to interact with from the hos app. It's just happens that this assembly is compiled on fly. 

Thus for passing objects to your script/assembly you need to have an appropriate signature in the routine you are invoking. That is it. 
```C#
namespace Testing
{
    public class SharedData
    {
        public int Count;
    }

    class Program
    {
        static void Main(string[] args)
        {
            var code = @"using System;
                         public class Script
                         {
                             public void Update(Testing.SharedData data)
                             {
                                 data.Count = 77;
                             }
                         }";

            dynamic script = CSScript.LoadCode(code, typeof(SharedData).Assembly.Location)
                                     .CreateObject("*");

            var data = new SharedData { Count = 33 };
            script.Update(data);
            Console.WriteLine(data.Count);
        }
    }
}
```

If you set `CSScript.ShareHostRefAssemblies = true;` then you can skip `typeof(SharedData).Assembly.Location` as it will be referenced automatically (default behavier).

And if you want (for whatever reason) to avoid dependencies at all then you can pass your proxy as `dynamic`. 
```C#
public void Update(dynamic data)
{
    data.Count = 99;
}
```
This way you can even disable `ShareHostRefAssemblies` and remove `typeof(SharedData).Assembly.Location`. But of course such a late binding solution is error prone and for something really serious you may want to base your data/script model on interfaces. 

The NuGet package comes with plenty of samples so you may want to have a look at them.
