### ISSUE TITLE
Error in Eval using a referenced assembly with unloading enabled.

### ISSUE THREAD

**Issue by MUN1Z** [oleg-shilo/cs-script#355]
Hello @oleg-shilo , i am trying reload my script files. I have a assembly loaded called Libs, all my scripts uses this Libs with reference in Roslyn Eval method.

![image](https://github.com/oleg-shilo/cs-script/assets/17263249/760bb8f6-ee30-4f92-b2d9-19e31f43032d)

Could not load file or assembly 'ℛ*1240c384-fa14-4563-9208-e649e77e3a95#1-0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the specified file.

The Eval method do not find the referenced assembly before addition of "IsAssemblyUnloadingEnabled" flag in CompileCode method.

 If i remove the flag, the Eval find the assembly and works fine, but i cannot unload the asm assembly:

![image](https://github.com/oleg-shilo/cs-script/assets/17263249/6a65a8f6-f3ed-4fbd-8697-5a14d6a35770)

![image](https://github.com/oleg-shilo/cs-script/assets/17263249/4d27623f-3a19-41dc-8d42-90552db8d70a)

**Comment by MUN1Z** [comment]
This is a example project to reproduce the issue: https://github.com/MUN1Z/CsSrcipt.unload.issue

**Comment by oleg-shilo** [comment]
This is a very interesting problem and it's not an easy task to solve...but possible. I have provided the code sample for that.

Anyway, let's try.

Though, in your first code snippet you are preparing for unloading the referenced assembly `asm`, what kinda doesn't make sense as you indicated you want to reference it from multiple eval-scrips.

Next, if you remove `IsAssemblyUnloadingEnabled` from your shared script then you are fine and your code will run and you will be able to unload. 

Though with the very current API you cannot unload assembly if your eval-script does not return anything. Thus the API needs to change to allow that. I have done the change (https://github.com/oleg-shilo/cs-script/commit/af55aabd60c1502f9466ee062f062faa9dd8c88c) and it will be available in the very next release. For your convenience I have provided the extension method for that so you do not have to wait. 

Next, you need to be careful with eval type of scenarios. Every time an instance of the tipe from a give assembly typecasted to `dynamic` it becomes un-unloadable. It is either a bug or a feature of CLR. But we cannot change it. Ironically avoiding `dynamic` and relying on interfaces arguably is a better approach anyway. `EvalAndUnload` also takes care of that. 

Note in the code sample below I had to call `GC.Collect` explicitly and deliberatly place it outside of the host-call method. Just to demonstrate the fact that the eval-script is unloaded.

And below is the complete working sample that shows the use of the shared script form the unloadable eval-script:

_I do recommend avoid using eval and using LoadMethod instead. It's more manageable (`useDelegate` option)._

```c#
using System.Reflection;
using Microsoft.CodeAnalysis;
using CSScripting;
using CSScriptLib;

namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var useDelegate = false;

            for (int i = 0; i < 20; i++)
            {
                Console.WriteLine("Loaded assemblies count: " + AppDomain.CurrentDomain.GetAssemblies().Count());

                call_UnloadAssembly(useDelegate);

                GC.Collect();
            }
        }

        static Assembly printer_asm;

        static void call_UnloadAssembly(bool useDelegate)
        {
            var info = new CompileInfo { RootClass = "Printing", AssemblyFile = "Printer.dll" };

            if (printer_asm == null)
                printer_asm = CSScript.Evaluator
                                      .CompileCode(@"using System;
                                                     using System.Diagnostics;
                                                     public class Printer
                                                     {
                                                         public static void Print() =>
                                                             Console.WriteLine(""Printing..."");
                                                     }", info);
            if (useDelegate)
            {
                var script = CSScript.Evaluator
                                     .With(eval => eval.IsAssemblyUnloadingEnabled = true)
                                     .ReferenceAssembly(printer_asm)
                                     .LoadMethod<ICalc>(@"public int Sum(int a, int b)
                                                          {
                                                              Printing.Printer.Print();
                                                              return a+b;
                                                          }");
                script.Sum(1, 2);
                script.GetType().Assembly.Unload();
            }
            else
            {
                var result = CSScript.Evaluator.With(eval => eval.IsAssemblyUnloadingEnabled = true)
                                     .ReferenceAssembly(printer_asm)
                                     .EvalAndUnload("Printing.Printer.Print();");
            }
        }
    }

    public interface ICalc
    {
        int Sum(int a, int b);
    }
}

static class Extension
{
    public static object EvalAndUnload(this IEvaluator evaluator, string scriptText, bool unloadableDependency = true)
    {
        var info = new CompileInfo { CodeKind = SourceCodeKind.Script };
        var asm = evaluator.CompileCode(scriptText, info);

        // note that the leading dot is missing "css_Root" vs ".css_Root"; this is required for asms compiled with inloadable context
        var entryPointType = asm.GetType($"{info.RootClass}", true, false);

        var entryPointMethod = entryPointType?.GetTypeInfo().GetDeclaredMethod("<Factory>") ?? throw new InvalidOperationException("Script entry point method could be found.");

        var submissionFactory = (Func<object[], Task<object>>)entryPointMethod.CreateDelegate(typeof(Func<object[], Task<object>>));

        var result = submissionFactory.Invoke(new object[] { null, null }).Result;

        asm.Unload();

        return result;
    }
}
```


![image](https://github.com/oleg-shilo/cs-script/assets/16729806/00fe6752-f3d4-47f1-a402-2c4301a96486)

**Comment by MUN1Z** [comment]
I understand, I'm not at home right now but in a little while I'll run the example you sent, thank you very much. Regarding the use of Eval, it was the closest I could get to simulating the behavior of lua scripts that I use on Tibia servers. 

I need the developer who will create the scripts to be free to create and call objects, variables, methods, create his own business rule in that script and override one or two delegates to in the end return the script instance to be stored and called when some player performs a certain action. 

but I will analyze the use of the load method calmly, it may be possible to change it if I change some behaviors in the scripts. 

I'm going to leave an example of the pattern that is used in lua and as I'm recreating it in eval, I want to make it very similar so I can convert these lua scripts to csx automatically in the future.

![image](https://github.com/oleg-shilo/cs-script/assets/17263249/0723fcc1-b6b3-4e24-92c0-4f57cf6060db)

**Comment by MUN1Z** [comment]
@oleg-shilo  I tested it now, so the same problem still occurs, the problem occurs when you put "IsAssemblyUnloadingEnabled = true" in the printer assembly.

In my case I need to reload both the assemblies created from scripts and the scripts that only use those assembly.

![image](https://github.com/oleg-shilo/cs-script/assets/17263249/dc190956-55fe-4f8c-8a62-3b23afe7998a)

![image](https://github.com/oleg-shilo/cs-script/assets/17263249/5fb68f88-0233-4474-9d40-0116e76ddc4a)

**Comment by kimdiego2098** [comment]
> 
> Next, you need to be careful with eval type of scenarios. Every time an instance of the tipe from a give assembly typecasted to `dynamic` it becomes un-unloadable. It is either a bug or a feature of CLR. But we cannot change it. Ironically avoiding `dynamic` and relying on interfaces arguably is a better approach anyway. `EvalAndUnload` also takes care of that.
> 

This is an unbearable bug, if we keep compiling dynamic methods (with ``dynamic`` type) but cannot uninstall them, will there be memory leaks and other situations

**Comment by oleg-shilo** [comment]
> This is an unbearable bug,...

Agree. Though most likely Roslyn team would reply to that "It's not a bug but a feature" :)
.NET roadmap was always very rigid when it comes to dynamic syntax features. And unloading is not the only hiccup with Roslyn.

Mind you, in late 2002, I lodged the feature request on MS Connect for unloading dynamically loaded assemblies. Interestingly enough the ticket handler (.NET ASP lead) agreed with my request but admitted... "it would be too hard to implement". But 17 years later they did it. So it came a long way...

Anyway, indeed uncontrolled evals may lead to effective memory leaks. So it's your call. You can be OK with it as long as your set of dynamic assemblies is fixed. Or if you prefer, you can switch to the unloadable options as I mentioned (e.g. using interfaces, in many cases, it's a preferred option for architectural reasons).
