### ISSUE TITLE
Strongly-named assembly required

### ISSUE THREAD

**Issue by steveskalski** [oleg-shilo/cs-script#359]
Hello,
  First I would like to thank you for the amazing work you've done with CS-Script.

  I am using CS-Script from with a signed DLL that is used by other applications (hosted scenario).  The DLL I am creating must be signed.  I am finding the CS-Script is not signed/strongly named.  Are there any plans to sign the project?  I am using CSScriptLib v4.8.1, pulled via nuget in VS2019.

  In case my thinking is wrong, below is the error I get when trying to use CS-Script from a signed DLL.  

System.IO.FileLoadException: 'Could not load file or assembly 'CSScriptLib, Version=4.8.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

**Comment by oleg-shilo** [comment]
It looks like after migrating to .NET Core the signing accidentally got disabled.
Fixed now. Please use nuget package v4.8.13, which is identical to v4.8.12 except it's signed.

https://www.nuget.org/packages/CS-Script/4.8.13

Thank you for bringing pointing this out.

**Comment by steveskalski** [comment]
Great!  Thanks Oleg-Shilo.
