### ISSUE TITLE
No way to install extension pack using chocolatey

### ISSUE THREAD

**Issue by ivanatpr** [oleg-shilo/cs-script#36]
Chocolatey seems to be the current recommended means of installing cs-script, but as far as I can tell installing it that way does not include the extension pack and there is currently no way, using chocolatey commands, to get the extension pack.

The workaround is simple, download the extension pack from the [releases page](https://github.com/oleg-shilo/cs-script/releases) here on github and extract the archive to your chocolatey install location (most likely C:\ProgramData\chocolatey\lib\cs-script\tools\cs-script). 

But, in order to make things a little easier for others, I'd suggest that either the main choco installer should install the extension pack, or there should be a second chocolately package with the extension pack, or there should at least be a note in the releases page (and in the package desc on chocolately's website) explaining how to get the extension pack.

Personally, I find it super useful to be able to easily specify that a given script should always run elevated by adding "//css_pre elevate()" at the beginning, which is my main use for the extension pack since it gives you the elevate library.

**Comment by oleg-shilo** [comment]
OK. Agree. 

Firstly `elevate.cs` should go to the default pack. It's easy and just makes sense. The initial _default_ vs. _extension pack_ split was made arbitrary and the idea was that further item transitions from one package to another should be triggered by the user feedback.  Now I have yours. The next release (v3.21) will have it done. I don't have any objections even moving it to %CSSCRIPT_INC% (typically C:\ProgramData\CS-Script\inc)

Maintaining separate package seems to be an overkill unless extension pack gained real popularity. Special disclaimer in the release notes is ideal at this stage. 

[GitHub](https://github.com/oleg-shilo/cs-script/releases/edit/v3.20.0) - done
[Choco](https://chocolatey.org/packages/cs-script) - done but will be available in the next release (released Choco packages are not editable). 

Thank you for your feedback.

**Comment by oleg-shilo** [comment]
Addressed in Release v3.21.1

In this release 
* `elevate.cs` is placed in %CSSCRIPT_INC% folder
* Implemented suppressing elevation during syntax checking (with `-check`) for the scripts with `//css_pre elevate;` directive

**Comment by ivanatpr** [comment]
Awesome, thank you!

**Comment by oleg-shilo** [comment]
BTW, forgot to mention. You can use `//css_pre elevate` without empty brackets since it has no arguments to take. Small thing... I know... :)
