### ISSUE TITLE
Too deeply nested script executions lead to not found NuGet packages

### ISSUE THREAD

**Issue by UweKeim** [oleg-shilo/cs-script#364]
I migrated a larger project of mine from using CS-Script for .NET Framework to the "new" CS-Script for .NET Core.

## Errors

While most of the scripts run successfully I experience errors like these:

> error CS0246:  Der Typ- oder Namespacename "ICSharpCode" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).

Translated to English this should read:

> error CS0246: The type or namespace name 'ICSharpCode' could not be found (are you missing a using directive or an assembly reference?).

This happens only when the script is executed from within other scripts.

## My script "architecture"

Basically I'm doing a chain of something like this.

1. start "a.cmd" which internally calls "css a.cs".
1. "a.cs" does some processing and later uses Process.Start to start "b.cmd".
1. "b.cmd" calls "css b.cs".
1. "b.cs" does some processing and later uses Process.Start to start "c.cmd".
1. "c.cmd" calls "css c.cs".
1. "c.cs" does some processing and later uses Process.Start to start "d.cmd".
1. etc.

I'm not quite sure but I do think the maximum nesting level is about 3 or 4.

In addition, I sometimes execute child scripts in a loop and this also seems to fail after some loops.

## Assumption

This works for some nesting depth but suddenly leads to above errors when the nesting depth is too deep.

(At least this is my strong assumption)

## Discoveries

I do log a lot of stuff, beside others the `Path` environment variable.

To my surprise for every call to my scripts, it seems to get larger and something like this is _appended_:

> C:\P\zp-develop\ZetaProducerContent\Development\Build\Build;C:\Users\ukeim\.dotnet\tools\.store\cs-script.cli\4.8.12\cs-script.cli\4.8.12\tools\net8.0\any;C:\Users\ukeim\.nuget\packages\sharpziplib\1.4.2\lib\net6.0;C:\Users\ukeim\.nuget\packages\jetbrains.annotations\2023.3.0\lib\netstandard2.0;C:\Users\ukeim\.nuget\packages\morelinq\4.1.0\lib\net8.0;C:\Users\ukeim\.nuget\packages\newtonsoft.json\13.0.3\lib\net6.0;C:\Users\ukeim\.nuget\packages\restsharp\110.2.0\lib\net7.0;C:\Users\ukeim\.nuget\packages\zetadeployer.runtimeuploader\1.0.86\lib\net8.0;C:\Users\ukeim\.nuget\packages\zetashortpaths\2.0.35\lib\net7.0;C:\Users\ukeim\.dotnet\tools\.store\cs-script.cli\4.8.12\cs-script.cli\4.8.12\tools\net8.0\any\lib;C:\ProgramData\cs-script\commands;C:\ProgramData\cs-script\inc;C:\Users\ukeim\AppData\Local\Temp\csscript.core\cache\449437209

and later it gets bigger:

> C:\P\zp-develop\ZetaProducerContent\Development\Build\Build;C:\Users\ukeim\.dotnet\tools\.store\cs-script.cli\4.8.12\cs-script.cli\4.8.12\tools\net8.0\any;C:\Users\ukeim\.nuget\packages\sharpziplib\1.4.2\lib\net6.0;C:\Users\ukeim\.nuget\packages\jetbrains.annotations\2023.3.0\lib\netstandard2.0;C:\Users\ukeim\.nuget\packages\morelinq\4.1.0\lib\net8.0;C:\Users\ukeim\.nuget\packages\newtonsoft.json\13.0.3\lib\net6.0;C:\Users\ukeim\.nuget\packages\restsharp\110.2.0\lib\net7.0;C:\Users\ukeim\.nuget\packages\zetadeployer.runtimeuploader\1.0.86\lib\net8.0;C:\Users\ukeim\.nuget\packages\zetashortpaths\2.0.35\lib\net7.0;C:\Users\ukeim\.dotnet\tools\.store\cs-script.cli\4.8.12\cs-script.cli\4.8.12\tools\net8.0\any\lib;C:\ProgramData\cs-script\commands;C:\ProgramData\cs-script\inc;C:\Users\ukeim\AppData\Local\Temp\csscript.core\cache\449437209;C:\P\zp-develop\ZetaProducerContent\Development\Build\Build;C:\Users\ukeim\.dotnet\tools\.store\cs-script.cli\4.8.12\cs-script.cli\4.8.12\tools\net8.0\any;C:\Users\ukeim\.nuget\packages\sharpziplib\1.4.2\lib\net6.0;C:\Users\ukeim\.nuget\packages\jetbrains.annotations\2023.3.0\lib\netstandard2.0;C:\Users\ukeim\.nuget\packages\morelinq\4.1.0\lib\net8.0;C:\Users\ukeim\.nuget\packages\newtonsoft.json\13.0.3\lib\net6.0;C:\Users\ukeim\.nuget\packages\restsharp\110.2.0\lib\net7.0;C:\Users\ukeim\.nuget\packages\zetadeployer.runtimeuploader\1.0.86\lib\net8.0;C:\Users\ukeim\.nuget\packages\zetashortpaths\2.0.35\lib\net7.0;C:\Users\ukeim\.dotnet\tools\.store\cs-script.cli\4.8.12\cs-script.cli\4.8.12\tools\net8.0\any\lib;C:\ProgramData\cs-script\commands;C:\ProgramData\cs-script\inc;C:\Users\ukeim\AppData\Local\Temp\csscript.core\cache\449437209

(My largest `Path` value was 3421 characters long in total)

My assumption is that the `Path` variable gets larger for every nested call to the a script and then it is too large and it cannot find the paths to the NuGet packages anymore and thus results in the above error.

## Request for help

Does the above makes some sense?

Is there a way to not completely rewrite/redesign my nested calling structure and still fix this issue?

**Comment by oleg-shilo** [comment]
Uwe, just letting you know... I am looking into it.
Give me another day or so.

**Comment by oleg-shilo** [comment]
Uwe, I just changed the implementation of that algorithm (https://github.com/oleg-shilo/cs-script/commit/a368d5bf2535ff766f6f762776bd5d47e7980615)

Can you check if it addresses the problem of growing PATH?
It is a prerelease: https://github.com/oleg-shilo/cs-script/releases/tag/v4.8.14.1

Please note that PATH can also be updated by any other apps sunning in the same parent-child process branch.

**Comment by UweKeim** [comment]
Thank you very much, Oleg! I've copied the content of the 7z pre-release into:

> C:\Users\ukeim\.dotnet\tools\.store\cs-script.cli\4.8.12\cs-script.cli\4.8.12\tools\net8.0\any

Then running `css --version` from another directory prints:

> 4.8.14.1

I do think this should indicate I'm using the correct version, I guess?

**Comment by oleg-shilo** [comment]
The preview was a throw-away build just to quickly test the immediate idea in your environment. Most likely I have made some mistake there. Please remove that preview and I will rebuild it after I troubleshoot it. The change itself is valid. There is also another possibility to oversaturate envars via storing assembly path. I have fixed it by allowing switching off in CSScriptLib.dll but I did not do it for exe. I did not anticipate an intensive parent-child process forking. I just overlooked it. 

I am looking into it.

What will also help, is a hello-world test case that shows the problem for the v4.8.14. Will need it if I cannot get anywhere on my own.

**Comment by UweKeim** [comment]
Thanks, Oleg. As I added in my [above comment](https://github.com/oleg-shilo/cs-script/issues/364#issuecomment-1931869452), even 4.8.12, when _not_ running as a .NET Tool, no `*.cs.nuget.cs` files are being created.

I cannot get my head around what is different (on _my_ system) to have such a behavior.

**Comment by oleg-shilo** [comment]
I am also a little puzzled.
I am looking at the code and "*.cs.nuget.cs" is only being processed if you have `legacyNugetSupport` disabled. But in case of prerelease, it is enabled because you have not disabled it explicitly as you did for the globally installed version.

So it explains. 

This will do the trick.
```ps
.\css -config:set:LegacyNugetSupport=false
```
But... I do not see eny code that actually creates this file regardless of the settings. CS-Script seems to read it but not to create it. It does not make sense but I am trying to see what is going on. 

Any ideas?

**Comment by UweKeim** [comment]
I see, thanks a lot, Oleg. In fact I did call `css -config:set:LegacyNugetSupport=false` for the global .NET Tool but not for the local test download versions.

Will try now whether this makes any difference.

**Comment by oleg-shilo** [comment]
Yep. This will create that *.nuget.cs file.
I have misinterpreted the code. It was right in front of me:

![image](https://github.com/oleg-shilo/cs-script/assets/16729806/fb2c4b70-4057-4670-b8b1-6e21bc2f0af4)

creation of this file is part of the new Nuget support. It contains all nuget assemblies that dotnet aggregates on the `dotnet restore` and then `dotnet publish`.

Thus your problem with pre-release will be solved by disabling the LegacyNugetSupport algorithm. I probably should now disable it by default. 

After that you can see if the change in the path makes any difference.

I also check in your scripts if `Environment.GetEnvironmentVariables` is growing as you go to the children scripts. Probably it is

**Comment by oleg-shilo** [comment]
I have also added a more detailed description about the way nuget support works: https://github.com/oleg-shilo/cs-script/wiki/NuGet-Support#how-does-it-work

**Comment by oleg-shilo** [comment]
With your pre-release binaries, I expect your PATH variable to sto growing.

Though for aver script execution there will be a single **new** variable:
![image](https://github.com/oleg-shilo/cs-script/assets/16729806/85f7cba0-bf9f-46f9-9f24-bec43466b87e)

If you have a huge amount of nested execution it can exhaust your envar buffer.
If it's what is happening there I can create a mechanism for disabling the storing location of the script assembly in the envars.

**Comment by UweKeim** [comment]
Thanks again, Oleg!

I'm just in the middle of letting my scripts run with v4.8.14.1 and until now it seems to run _way_ better.

I'll post here an update when if succeeded or failed.

**Comment by UweKeim** [comment]
A first, shorter run through the scripts succeeded. 🥰

Will try another more thorough run now.

**Comment by oleg-shilo** [comment]
I also disabled that location-envar by default. But it will only be available with the next pre- or a proper release.

**Comment by oleg-shilo** [comment]
OK, then let's put it on pause until it is ready.
In the meantime, I will do a formal prerelease so you can try it in isolation. But most likely I will need a testcase (hello-world) that lets me troubleshoot and catch it in the action.

**Comment by UweKeim** [comment]
Thanks. I've tried several hours to create a test case without success 😭

**Comment by UweKeim** [comment]
The names of the packages seems to be arbitrary. One of them is e.g. [SharpZipLib](https://www.nuget.org/packages/SharpZipLib).

**Comment by oleg-shilo** [comment]
I have attached the automated test that is testing deep to 25 levels of nesting.
So far I have not triggered the problem. Runs fine.
If you want to run it you will need to update the `rootDir` available in the script. And ensure _NugetLegacySupport_ is disabled. :)

[cs-script_#364.zip](https://github.com/oleg-shilo/cs-script/files/14217761/cs-script_.364.zip)

**Comment by UweKeim** [comment]
Thank you!

I've let your script run for several hours now and I even added looping.

Even with v4.8.12 I could not generate any errors.

Drives me crazy!

**Comment by oleg-shilo** [comment]
I know the feeling..... :o(
