### ISSUE TITLE
How can behavior similar to Python's reloading be implemented?

### ISSUE THREAD

**Issue by int2e** [oleg-shilo/cs-script#367]
How can I achieve behavior similar to Python's importlib.reload() in CS-Script? This is very important. Is it currently possible to do this?

**Comment by oleg-shilo** [comment]
Can please you explain the desired behaviour so do not misinterpret your request?

I have a feeling that you are referring to recompiling already loaded scripts but I do not want to be guessing.

**Comment by oleg-shilo** [comment]
Not sure I follow. I still have no visibility of the problem you are trying to solve. 
Are you executing a script from the shell? Or you are executing it from the app where you host the script engine.
. . .
OK, I just googled it. `importlib.reload()` is user to reload previously loaded modules. 
In .NET the closest equivalent of module is an assembly. Thus what you are trying to solve is a pure .NET challenge that is not related to C# scripting as such.

In .NET you cannot reload a statically loaded assembly. But if your assembly is loaded dynamically then you can definitely reload it.
Something like this pseudo-code (e.g. you are loading a printer assembly):

```C#

object CreatePrinter()
{
    var asmFile = "<path to the DLL>";
    Assembly asm = Assembly.Load(File.ReadAllBytes(asmFile));
    Type targetType = loadedAssembly.GetType("Printing.Printer");
    return Activator.CreateInstance(targetType);
} 

// load Printer assembly and create a Printer 
dynamic printer = CreatePrinter();

// reload Printer assembly and create a Printer 
printer = CreatePrinter();
```
In scripting the only thing the is going to be different is the assembly loading:

```C#
var scriptFile = "<path to the C# file>";
Assembly asm = CSScript.LoadFile(scriptFile));
```

**Comment by oleg-shilo** [comment]
CS-Script always recompiles the script every time you load it if it has been changed since you loaded it last time. 

> Are you executing a script from the shell?

You still did not answer :)

**Comment by oleg-shilo** [comment]
Yes it will compile a new assembly (script assembly):

Thus once you load the assembly it's not going to change or impact the routines being executed. When you modified your script and loaded it again. Another assembly is loaded and executed independently:

![image](https://github.com/oleg-shilo/cs-script/assets/16729806/f5e88d66-e496-441f-9906-21bf57ea2c04)

**Comment by oleg-shilo** [comment]
In this example I loaded the script from the string variable but you can do the same from the file.

Also, keep in mind that loading too many assemblies does not have but may create some pressure on your process memory. In most of the cases you might be OK with that but if not then you may need to think about unloading the assemblies that are no longer needed. But only if you indeed need to do that.

**Comment by oleg-shilo** [comment]
In case you need my code to test:

```C#
static void TEST()
{
    var code = @"public class Script
                 {
                     public string Foo()
                     {
                         return ""value1"";
                     }
                 }";

    dynamic script = CSScript.RoslynEvaluator
                                .LoadCode(code);
    // load the script
    string result1 = script.Foo();

    // modifying code
    code = code.Replace("value1", "value2");

    // reload the script
    script = CSScript.RoslynEvaluator
                        .LoadCode(code);

    string result2 = script.Foo();
}
```
