### ISSUE TITLE
Location of script file Unable to get correct results in hosted script

### ISSUE THREAD

**Issue by int2e** [oleg-shilo/cs-script#371]
[https://github.com/oleg-shilo/cs-script/wiki/CS-Script-Runtime-Environment-%28script-reflection%29](https://github.com/oleg-shilo/cs-script/wiki/CS-Script-Runtime-Environment-%28script-reflection%29)

```
using System.Linq;
using System.Reflection;


public static class StringExtensions
{
    public static string GetScriptName(this Assembly assembly)
    {
        return assembly.GetCustomAttributes(typeof(AssemblyDescriptionAttribute), false)
            .Cast<AssemblyDescriptionAttribute>()
            .FirstOrDefault()?.Description;
    }
}
```

`var scriptName = Assembly.GetExecutingAssembly().GetScriptName();`

scriptName is null

Does it only work in cli?

**Comment by oleg-shilo** [comment]
I just have published the pre-release of the fix on nuget.org

```ps
dotnet add package CS-Script --version 4.8.16-pre
```
