### ISSUE TITLE
Wrong slash used when building/running anything on windows

### ISSUE THREAD

**Issue by Kamek437** [oleg-shilo/cs-script#374]
Looks like the wrong slash / is used to run stuff on windows, and there is no csc.exe in the package is that supposed to be like this? I run something and C:\proj\code\code.cs/program.exe is run, which doesn't exist. also neither does csc.exe. Did i set it up wrong? Yes I have dotnet installed, yes dotnet is in my path. why not just use dotnet build and dotnet run for solutions, and roslyn for scripts?

**Comment by oleg-shilo** [comment]
I am not sure I fully understand your message.

> Looks like the wrong slash / is used to run stuff on windows

You will need to elaborate on this one.

>there is no csc.exe in the package

It is not part of CS-Script. It is one of the three compiling engines for CS-Script available with .NET SDK. Thus if you want to use `csc.exe` or `dotnet` for running the scripts you need to install .NET SDK (v8.0). If you only want to run your scripts with Roslyn then you may do it with even only .NET Runtime installed.

> Did i set it up wrong? 

Quite possibly.
I suggest you install .NET SDK and then you can create and run your scripts (e.g. `test` script) as follows:

![image](https://github.com/oleg-shilo/cs-script/assets/16729806/f92f811a-7789-4571-a09e-0b73a3a253cb)

**Comment by Kamek437** [comment]
The tool dotnet. dotnet.exe? dotnet run? dotnet create app? It's the main way to make dotnet projects. And yes I have dotnet sdk 6-9 installed in 3 different ways. The problem is it uses unix style slashes when it's running on windows. Otherwise it works.

**Comment by oleg-shilo** [comment]
> I know it's for single scripts, but what I meant was if I have a project with a .sln in it or the file is part of a project then it should use 'dotnet run' to run the solution.

I still don't see what you are trying to do. If you have a single file then you run it as a script with cs-script. If you have a project file then you execute it as a project (`dotnet run`) and you do not need cs-script. Anyway. it looks like one of the "lost in translation" cases 😄 

let's talk about Sublime. You said "when I hit run in sublime" but your screenshot indicates that you do not execute the script but some executable. Are we talking about the same things?
Are you trying to execute the script with some sort of a sublime file executor?

The output on your screen is not made by CS-Script.
If I execute a script (F5) with CS-Script plugin this is the output I get:

![image](https://github.com/oleg-shilo/cs-script/assets/16729806/57e5b24c-3f93-40fb-93e0-c8ea14cbeed6)

Ctrl+F5 executes it in the external terminal/shell:
![image](https://github.com/oleg-shilo/cs-script/assets/16729806/b3b850eb-ac25-4b4d-8a51-9d338d9ac653)

**Comment by Kamek437** [comment]
I had another C# plugin that was interfering, and I confused the two sorry.

**Comment by oleg-shilo** [comment]
All good. Not a problem
