### ISSUE TITLE
VSCode intellisense

### ISSUE THREAD

**Issue by snikeguo** [oleg-shilo/cs-script#375]
I developed a program named A.exe. The code is as follows:
```

//A.exe:
namepsace A
{
    public class Program
    {
        public static void helloword()
        {
            .....
        }
        public void Main()
        {
                var content = File.ReadAllText("D:/TestIntellisense.cs");
                Assembly assembly = CSScript.RoslynEvaluator.CompileCode(content, new CompileInfo { CodeKind = SourceCodeKind.Script });
                CallScriptInvokeHostMethod...
        }
    }
}
```

TestIntellisense.cs
```
using A;
public class Test
{
    public void InvokeHostMethod()
    {
        Program.helloword();
    }
}
```
I run A.exe, and it works very well.
OK ~
but I have installed the C# (CS-Script) extension in VSCode, but when editing TestIntellisense.cs, "Program.helloword();" does not show code suggestions. How can I fix this issue?

I think I should put A.exe into a certain directory of Cs-Script, so that the language server can parse A.exe and enable IntelliSense functionality.

**Comment by oleg-shilo** [comment]
If you are editing/running `TestIntellisense.c`s as a script then indeed you can use CS-Script extension for that.

1. In order for this to work you need to ensure that when you open the file in VSCode it does not have any workspace open. While strictly speaking CS-Script plugin can still do the job with the workspace/folder loaded there is a big chance that it may interfere with the CS-Script syntaxer.

2. You need to reference your `A.exe`. In a typical .NET project you would do it by placing the reference path in the project file. But in case of the script you can do it directly from the script code:

Note the all dependencies of A.exe (e.g. CSScriptLib.dll) should be present in that location too.

```C#
//css_ref <your path to A.exe>

using A;
public class Test
{
    public void InvokeHostMethod()
    {
        Program.helloword();
    }
}
```
