### ISSUE TITLE
Bump Request -> Microsoft.CodeAnalysis.CSharp.Scripting 4.10.0

### ISSUE THREAD

**Issue by hmiguel** [oleg-shilo/cs-script#378]
Microsoft.CodeAnalysis.CSharp.Scripting has been updated. 

Latest version: 4.10.0

https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Scripting

**Comment by oleg-shilo** [comment]
Done. v4.8.17.0

NuGet.lib: ready
NuGet.tool: ready
Chocolatey: pending
WinGet: pending

**Comment by oleg-shilo** [comment]
done to v4.14
The release is coming within a week

**Comment by oleg-shilo** [comment]
BTW, it's not a workaround but the intended dev scenario. 
CS-Script is expected to periodically go out of sync with the latest dependencies, so the host app can always bump up the dependencies.  
But with any CS-Script it does make sense to update the dependencies. Agree.
