### ISSUE TITLE
Installed .NET version is incompatible.

### ISSUE THREAD

**Issue by Kamek437** [oleg-shilo/cs-script#380]
Upgraded to .Net 9.0.100-preview.6.24328.19 now when I start up sublime I get:
```
current_dotnet_version: 9.0.100-preview.6.24328.19
current_css_version: 4.6.2.0
current_syntaxer_version: 3.1.1.0
Runtime.min_compatible_dotnet_version: 6.0.0
Runtime.max_compatible_dotnet_version: 9.0.0
*************** CS-Script ******************
ERROR: 
Installed .NET version is incompatible.
```

**Comment by oleg-shilo** [comment]
The range of the .NET versions supporting CS-Script is `higher than 6.0.0` - `lower than 9.0.0`
Though the plugin allows some flexibility you can simply point it to the alternative installation of cs-script of any version and then you will only be bound by the compatibility constraints between .NET and CS-Script.

Currently, the latest version of CS-Script is compiled against .NET 8.0. Thus it cannot fully function on .NET 9.
From the moment .NET 9 is released then CS-Script will be recompiled against it and immediately released.

Meaning, that we still have to wait. Or you can downgrade your preview version to .NET v8.*

**Comment by Kamek437** [comment]
I have them both installed. 6-9sdk Why doesn't it switch for me to another version that allows it to function? The user should not have to deal with config script etc if they have a compatible version installed.

**Comment by oleg-shilo** [comment]
.NET SDK does not have a concept of switching. 
Only a single version is active at the time.
If you execute `dotnet --version` it will show you which one.

> The user should not have to deal with config script 

There is nothing in cs-script configuration that you can use to achieve what you want. To load .NET9 compiled script (assembly) into .NET8 compiled script engine. What you are experiencing is a logical problem multiple .NET versions installed on the target system. I assist cs-script users by immediately releasing new cs-script build when a new version of .NET is released. But until it is available I have to wait.

I cannot exclude that there is a routing setting somewhere in config file that can force `dotnet.exe` to use different SDK version profile. But I have no idea how to achieve this.

Saying that, cs-script comes with one compiling engine that is independent on the version of .NTE . Roslyn. 
Thus you can execute scripts even without SDK. You need to indicate the engine by supplying `//css_ng roslyn` as the first line in the script or supplying the CLI switch from the terminal:

```C#
css -ng:roslyn script.cs
#or
dotnet cscs.dll -ng:roslyn script.cs
``` 

Most likely it will work. Though Roslyn has some limitations. It can only work with static main and does not allow declaring namespaces:

This is the sample code that works:
```C#
//css_engine roslyn
using System;

public static void Main()
{
    Console.WriteLine("Hello World!");
}
```

Saying that I am willing to have a look at the exact problem and see if there is some work around (even though unlikely). So I am changing this issue to `enhancement`

**Comment by oleg-shilo** [comment]
I have done some investigation and it turns out that there is a relatively straightforward way of changing the target runtime for the script engine to the runtimes higher than the one that the engine was compiled for. 
While I would consider this as a "if-I-have-to" workaround it's not a hack but a normal .NET configuration operation.

![image](https://github.com/user-attachments/assets/9442e0cb-8de9-4a7b-a87f-e213101285c4)

I will provision it in the next release distributable package. The dev experience will be something like this:

```txt
# set current runtime version for the script engine assembly
css -set-rt-self 

# set current runtime version for the given assembly
css -set-rt <assembly file> 
``` 

As for you, you don't have to wait for the release and you can manually update your latest CS-Script deployment to work on .NET9.0-Preview.
You will need to update C:\ProgramData\chocolatey\lib\cs-script\tools\cscs.runtimeconfig.json config content to the new dotnet:

![image](https://github.com/user-attachments/assets/1fb6a67f-a0ee-466d-bc7f-419a9b3cb15e)

If you are using CS-Script with some of IDEs that it is integrated with then you need to repeat the same for the `syntaxer.exe` file, which is an intellisense service for CS-Script scripts.

**Comment by oleg-shilo** [comment]
Not sure but it looks like you are using Sublime.
If it is the case, I can guide you through updating the Sublime config.

**Comment by Kamek437** [comment]
Wow thanks! Yes I am using sublime. I made the changes to C:\ProgramData\chocolatey\lib\cs-script\tools\cscs.runtimeconfig.json, but I still get this:
```
Runtime.min_compatible_dotnet_version: 6.0.0
Runtime.max_compatible_dotnet_version: 9.0.0
*************** CS-Script ******************
ERROR: 
Installed .NET version is incompatible.
```
I can just roll back to .net 9.0, I just wanted to check out what was coming and all.

**Comment by Kamek437** [comment]
The above example script run and compiles fine, so I don't see any reason to bother you further. Thank you, you make an awesome product keep up the good work!

**Comment by oleg-shilo** [comment]
> Runtime.max_compatible_dotnet_version: 9.0.0
> Installed .NET version is incompatible.

Technically speaking it is an intended behaviour as the plugin is build for version 6.0.0(inclusive) - 9.0.0(exclusive).
But the message is misleading. I will replace it with something like this:

```
Compatible dotnet versionsrange: 
v6.0.0 - v9.0.0 (exclusive)
*************** CS-Script ******************
ERROR: 
Installed .NET version is incompatible.
```

**Comment by Kamek437** [comment]
It seemed to still work fine for me, so maybe put "Defaulting to x.x version" or some such. That message makes it seem like it's broken.

**Comment by oleg-shilo** [comment]
correct. the message is misleading.
this should be better:

```
Compatible dotnet versions range: 
v6.0.0 - v9.0.0 (exclusive)
*************** CS-Script ******************
WARNING: 
The plugin may not work correctly with this .NET version.
```
Will do the change in the next release

**Comment by Kamek437** [comment]
Thanks! Keep up the good work man.
