### ISSUE TITLE
Can you run scripts with a "globals" object?

### ISSUE THREAD

**Issue by GreemDev** [oleg-shilo/cs-script#382]
Hey! 
I found this library searching for an alternative to `Microsoft.CodeAnalysis.CSharp.Scripting`, because it still (since the introduction of .NET 5) cannot reference loaded assembles in a single-file application, and it seems like nobody cares that the project is basically useless when used in combination with one of the best parts of .NET: single-file app publish.

I'm currently trying to migrate the [core of scripting](https://github.com/Polyhaze/Volte/blob/v4/src/Bot/Helpers/EvalHelper.cs) in my project, but I can't figure out how to evaluate scripts that can use code defined in the `EvalEnvironment` type (this is a Discord bot and quick one-liner evals are nice to write on a short notice, plus a lot of helpers that make any given eval easier. Oh and also type inheritance trees and object property value dumps).

Is this even possible with this project?

**Comment by oleg-shilo** [comment]
Hi there,

> single-file app publish.
> Is this even possible with this project?

Well, it depends on which compiler is used to compile the script. CS-Script is not a compiler or interpreter. It is rather a scripting orchestrator. You can configure it (at runtime) to use one of the 3 possible compilers: Roslyn, dotnet.exe and csc.exe.

Roslyn is the only compiler that is appropriate for single-file published apps.

And as you correctly stated Roslyn is really bad when it comes to referencing compiled scripts from the single-file apps.
So sadly, you can not achieve what you want with Roslyn.

You can use cs-script to compile normal assemblies if the target OS has .NET SDK installed. And then compile your scripts as another assembly while referencing the script assembly. But this is all a completely different scenario and it's very unlikely you are going to be OK with the dependency on the SDK.

**Comment by GreemDev** [comment]
Thanks for the reply. Unfortunately it seems like I won't be using this library, and will likely do the [MS.CA.CS.Scripting wild workaround](https://github.com/andersstorhaug/SingleFileScripting) as having globals is pretty important to me, I'd rather not radically change the scripting I have now into something, frankly, harder to write a script for (specifically in a Discord bot), referencing contextual values in a script is super nice.
That being said this library is pretty cool. Glad there's a scripting library that works in single-file publish with no hassle, when that glaring issue with `MS.CA.CS.Scripting` is apparently slated for a future release and not soon.

**Comment by oleg-shilo** [comment]
Just rereading your post...

Referencing objects from the host application is not a problem it works just out of the box:

```c#
public class Settings
{
    public static string Value = "test value";
}
...
var calc = CSScript.Evaluator
                   .Eval(@"using System;
                           public class Script
                           {
                               public int Sum(int a, int b)
                               {
                                   Console.WriteLine(Settings.Value);
                                   return a+b;
                               }
                           }
                           return new Script();");

int sum = calc.Sum(1, 2);
Console.WriteLine("CSScript.Evaluator.Eval|class: " + sum);
```
The result:
![image](https://github.com/user-attachments/assets/8f9907ac-72f0-4c54-87f0-6253284ec178)

References one script assembly from another script assembly is difficult. This is the weak spot of Roslyn. Interestingly enough is still works for a single file build but only if you do not embed runtime `--self-contained false`.
