### ISSUE TITLE
Suggestion for minor improvement in AsmHelper.Invoke()

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#39]
A NullReferenceException occurs when calling AsmHelper.Invoke() with a 'null' value (e.g. Invoke("MyProperty", someObj) where someObj unfortunately is 'null'). Stack trace:

System.NullReferenceException was caught
  Message="Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt." ("object reference not set to an instance of an object")
  Source="mscorlib"
  StackTrace:
    Server stack trace: 

- bei System.Object.GetType()
- bei CSScriptLibrary.AsmBrowser.MethodSignature..ctor(String name, Object[] args)
- bei CSScriptLibrary.AsmBrowser.Invoke(Object obj, String methodName, Object[] list)
- bei CSScriptLibrary.AsmBrowser.Invoke(String methodName, Object[] list)
- bei CSScriptLibrary.AsmRemoteBrowser.Invoke(String methodName, Object[] list)
- bei System.Runtime.Remoting.Messaging.StackBuilderSink.\_PrivateProcessMessage(IntPtr md, Object[] args, Object server, Int32 methodPtr, Boolean fExecuteInContext, Object[]& outArgs)
- bei System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg, Int32 methodPtr, Boolean fExecuteInContext)
- Exception rethrown at [0]:
   - bei System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   - bei System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   - bei CSScriptLibrary.IAsmBrowser.Invoke(String methodName, Object[] list)
   - bei CSScriptLibrary.AsmHelper.Invoke(String methodName, Object[] list)
   - bei _MyProject_._MyMethod_ in _MyWorkspace_\\_MyFile_

Instead of simply forwarding the values (resulting in that NullReferenceException) I suggest to check the arguments higher up in the call sequence and throw an ArgumentNullException with a more comprehensive error message instead.

**Comment by oleg-shilo** [comment]
Yes `AsmHelper.Invoke` is just not suitable for the task when the argument(s) is a null. Mind you that `AsmHelper.Invoke` was developed before `dynamic` became available and it was the only alternative to the  raw Reflection. Today, I would encourage the use of better alternatives. Saying that if you want to minimise the code changes you may go with `AsmHelper.GetMethod*` API (though not compatible with AsmHelper remote execution).
```C#
var asm = CSScript.LoadCode(@"using System;
                              public class Script
                              {
                                  public  void Print(string a)
                                  {
                                      Console.WriteLine(a);
                                  }
                              }");

var Print = new AsmHelper(asm).GetStaticMethod("Script.Print", "");
Print("Hello World!");
``` 
Anyway, I have address your main point and now it throws the following exception: 
```
At least one of the invoke parameters is null. This makes impossible to match method signature by the parameter type. Consider using alternative invoking mechanisms like:
 AsmHelper.GetMethod()
 AsmHelper.GetStaticMethod()
 Assembly.GetStaticMethod()
 using type 'dynamic'
 using interfaces
```
