### ISSUE TITLE
Suggestion for minor improvement in ScriptParser..ctor()

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#40]
A NullReferenceException occurs when ScriptParser..ctor() is invoked without a 'searchDirs' argument (i.e. new ScriptParser("MyScript.cs")). Stack trace:

System.NullReferenceException was unhandled by user code
 Message="Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt." ("object reference not set to an instance of an object")
 Source="CSScriptLibrary"
 StackTrace:

   - bei csscript.Utils.Concat(String[] array1, String item)
   - bei CSScriptLibrary.FileParser..ctor(String fileName, ParsingParams prams, Boolean process, Boolean imported, String[] searchDirs, Boolean throwOnError)
   - bei CSScriptLibrary.ScriptParser.Init(String fileName, String[] searchDirs)
   - bei CSScriptLibrary.ScriptParser..ctor(String fileName)

I guess you are always using 'searchDirs', so ScriptParser..ctor(String fileName) is never called and this case never occurs.

**Comment by oleg-shilo** [comment]
Done in ef933b5814a065571abb3b91b68568200107fae3
Waiting to be released
