### ISSUE TITLE
Request to support compiler options for CSScript.Load() and CSScript.LoadFile()

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#41]
Hi Oleg, sorry for requesting yet another thing, but I have gotten very motivated in significantly improving the CSScript's integration into my hosting application and have therefore extended the automated test environment. This has resulted in this very request.

I have created a bunch of test scripts that contain certain conditional code guarded with #if TEST. I need to load those scripts with and without "//css_co /define:TEST;\n", i.e. cannot place this into the scripts, but rather need specifying this when invoking CSScript.Load() or CSScript.LoadFile(). Unfortunately, this isn't directly possible and I have to read the file, prepend "//css_co /define:TEST;\n", save the file again, and then load it. Somewhat cumbersome.

I'd prefer if CSScript.Load() or CSScript.LoadFile() provided an additional parameter that allows specifying a list of additional compiler options. I agree this is kind of nice to have, I fully understand if this request is handled with low priority.

**Comment by oleg-shilo** [comment]
You can use `CSScript.LoadWithConfig` for that. It accepts compiler options string directly.

**Comment by maettu-this** [comment]
Sorry for not having seen the ...WithConfig() methods, works as required.

Then I only request to update the documentation to easier find this.

- "Compiler Options Directories" => "Compiler Options" or "Compiler Option Directives"
- Additional example with LoadWithConfig() instead of LoadCode() only.

**Comment by oleg-shilo** [comment]
Of course. Thanks for pointing this out.
Doc is fixed. http://www.csscript.net/help/CompilerOptionsDirective.html
Samples are updated: https://github.com/oleg-shilo/cs-script/commit/4a60d05b8ba4302f7ddd9bcec3695b60a4ee0617
