### ISSUE TITLE
ICodeCompiler is obsolete

### ISSUE THREAD

**Issue by gwynge** [oleg-shilo/cs-script#42]
[I apologise in advance as this is the first time I have written on a github issue board so I may not be following the normal route for queries but I can find no alternative forum]

I am trying to integrate CSScript into a vb.net application. My application is the host application and will allow the user to create and edit scripts which the server side code will use to extend the application's functionality.

I want the user to have the option of writing C# or VB and I see from the help file with the downloaded binaries 3.4.1.2 that the code compile can be changed by including this code:

Public Class CSSCodeProvider
    Public Shared Function CreateCompiler(ByVal sourceFile As String) As ICodeCompiler
        Return New Microsoft.VisualBasic.VBCodeProvider().CreateCompiler()
    End Function
End Class

However VS2013 flags this as an issue "ICodeCompiler is obsolete .... use CodeDomProvider".

Is this expected?

**Comment by oleg-shilo** [comment]
Yes it is expected. 

MS marked this class as obsolete as they are trying to discourage people from using any CodeDom API, which returns this interface and use static methods instead. However in the same "obsolete warning message" they say that developers should use/implement this interface if they are implementing their own compilers - this is what you do. So you are good...
