### ISSUE TITLE
Ability to timeout scripts

### ISSUE THREAD

**Issue by gwynge** [oleg-shilo/cs-script#43]
I see a big danger with scripting, especially server side, that you can end up with a hosted script that goes into a loop and never completes. What we don't really want is the server to then need to be restarted.

Am I correct that there is no way to give a time limit to scripts using cs-script?

The only way that I can see of doing it would be to run the scripts on separate threads and then monitor them, which is probably fine server side but if you're working client-side you'd then get issues with the single-threaded nature of WinForms.

If there is no facility within cs-script then I guess I'll have to wrap my own "watchdog" processing around it.

**Comment by oleg-shilo** [comment]
I think there is some misunderstanding about what CS-Script is. 

It is not an interpreter nor compiler. CS-Script is an orchestrator that facilitates execution of the C# code by compiling it on-fly with the standard .NET compiling infrastructure. CS-Script does not bring anything new into the runtime environment nor affects any of the environment features. 

When you are executing the script you are actually dynamically loading a compiled assembly and as such it is a subject of any benefits and limitations associated with the assembly dynamic execution. 
```C#
// Executing assembly with raw .NET manually
var assembly = Assembly.Load("my.dll");
AppDomain.CurrentAppDomain.ExecuteAssembly(assembly);

// Executing C# file with  CS-Script. 
var my_dll = ICodeCompiler.Compile("my.cs");
var assembly = Assembly.Load(my_dll);
AppDomain.CurrentAppDomain.ExecuteAssembly(assembly);
```
Thus if you indeed see "a big danger with scripting" then you cannot deny that there is the same danger associated with any assembly executed dynamically. What I am trying to say is that if your concerns are valid then they are not associated with CS-Script but with the very nature of CLR. And any solution (e.g. threading) to address these concerns will be found within the generic .NET problem domain but not within CS-Script. 

BTW, the CS-Script execution model is not something unique. It is 100% consistent with what is happening in the ASP.NET runtime for non-compiled web applications.
