### ISSUE TITLE
AsmHelper does not 'deleteOnExit' and keeps a reference to the assembly in case an invoked method throws

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#46]
Sequence:
```
try
{
	helper = new AsmHelper(assemblyFilePath, "ScriptDomain", true);
	scriptResult = (int)helper.Invoke(scriptMainMethod, new object[] { scriptStartArgs });
}
finally
{
	if (helper != null)
		helper.Dispose();
}
```

All works fine as long the scriptMainMethod() properly returns. However, in case that method throws, two things go wrong:

- 'deleteOnExit' does not happen.
- The AsmHelper seems to keep a reference to the assembly file (.dll), as a consequence, the assembly file cannot be deleted (by the application or Cmd or Windows Explorer or ...).

As a consequence, my hosting application cannot subsequently start a script that throws. In such case, the user has to exit the application and then start the script again. This is somewhat cumbersome.

I know this issue only occurs in case a script throws. Therefore I consider this issue low priority. Still this limitation is a bit annoying as it is hard to make people understand this and as it limits automated testing capabilities.

**Comment by maettu-this** [comment]
Sorry, false-alarm, you can reject this issue. It has been caused by a reference of the hosting application's AppDomain to the the script's assembly file.

**Comment by oleg-shilo** [comment]
Not a problem. I prefer a "false alarm" over a "real bug" :)
