### ISSUE TITLE
Is there a way to specify the working directory for a script?

### ISSUE THREAD

**Issue by DerekSMorin** [oleg-shilo/cs-script#48]
I'm trying to run a script that references an exe.

I put on fuslogvw to get some binding information.  It doesn't look like it is trying to load the exe from the current folder in the command prompt.

```
C:\Users\Derek.Morin\Documents\Visual Studio 2010\Projects\ScriptCode\ScriptCode.ConvertedToC#\bin\x86\Debug>cscs /l "new script (3).cs"
C# Script execution engine. Version 3.18.0.0.
Copyright (C) 2004-2016 Oleg Shilo.

Error: Specified file could not be executed.

System.IO.FileNotFoundException: Could not load file or assembly 'ScriptCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'ScriptCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Script.Main(String[] args)

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\cs-script\cscs.exe
--- A detailed error log follows.

=== Pre-bind state information ===
LOG: DisplayName = ScriptCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/cs-script/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/cs-script/ScriptCode.DLL.
LOG: Attempting download of new URL file:///C:/cs-script/ScriptCode/ScriptCode.DLL.
LOG: Attempting download of new URL file:///C:/cs-script/ScriptCode.EXE.
LOG: Attempting download of new URL file:///C:/cs-script/ScriptCode/ScriptCode.EXE.
```

**Comment by oleg-shilo** [comment]
References to the assemblies are relative to the script file location. 

Thus if you are not using an absolute path you will need to specify them with respect to the location of the script. Alternatively you can add probing directories either globally or per script.  The attached sample shows the technique. Note that the sample was tested against v3.24.0  

```C#
//css_dir lib
//css_ref lib.exe
using System;

class Script
{
    static public void Main()
    {
        Lib.Foo();
    }
}
```
![image](https://cloud.githubusercontent.com/assets/16729806/23593267/afae9be2-0260-11e7-8280-fe323613d569.png)


[DerekSMoris.zip](https://github.com/oleg-shilo/cs-script/files/819914/DerekSMoris.zip)

**Comment by DerekSMorin** [comment]
I am able to get it to compile a number of different ways, but it always fails to load the exe at runtime.

NOTE: the exe targets .NET framework 4.6, but I have configured cs-script to allow this and I use things like string interpolation all the time in cs-scripts.

I get the same errors whether I run with the -l option or not.  Enabling fusion log viewer show that it seems to be trying to load the exe from: C:/cs-script

For example, I put the script in the same directory as the executable:

//css_ref ScriptCode.exe;
using System;
using System.Windows.Forms;
using Dynamic;
using System.IO;

class Script
{
    [STAThread]
    static public void Main(string[] args)
    {
        DirectoryInfo info = new DirectoryInfo(@"C:\Users\Derek.Morin\Documents\Visual Studio 2010\Projects\ScriptCode\ScriptCode.ConvertedToC#");
        info.GetFiles("*.cs", SearchOption.AllDirectories).ToPickList(x => x.FullName).GetSinglePickListItem();
    }
}

C:\Users\Derek.Morin\Documents\Visual Studio 2010\Projects\ScriptCode\ScriptCode.ConvertedToC#\bin\x86\Debug>cscs -l TestCsScript.cs
C# Script execution engine. Version 3.18.0.0.
Copyright (C) 2004-2016 Oleg Shilo.

Error: Specified file could not be executed.

System.IO.FileNotFoundException: Could not load file or assembly 'ScriptCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'ScriptCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Script.Main(String[] args)

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\cs-script\cscs.exe
--- A detailed error log follows.

=== Pre-bind state information ===
LOG: DisplayName = ScriptCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/cs-script/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/cs-script/ScriptCode.DLL.
LOG: Attempting download of new URL file:///C:/cs-script/ScriptCode/ScriptCode.DLL.
LOG: Attempting download of new URL file:///C:/cs-script/ScriptCode.EXE.
LOG: Attempting download of new URL file:///C:/cs-script/ScriptCode/ScriptCode.EXE.

**Comment by oleg-shilo** [comment]
> exe targets .NET framework 4.6,

This is actually irrelevant as at runtime it always targets CLR v4.0 as if it was VS project targeting .NET framework 4.0

As per my prev post, you are still using for testing the old version of CS-Script so some uncertainty has been introduced from there.
 
Anyway I have attached the sample that shows how you can reference exe from the script. [Round2.zip](https://github.com/oleg-shilo/cs-script/files/822892/Round2.zip). Be aware that using WinZip for extraction will silently lock any assembly found in the archive so probably it makes sense to rebuild.

Note, if you want to use C# 6 specific features from the script (not in ref assembly) you need to read this [wiki](https://github.com/oleg-shilo/cs-script/wiki/C%236.0-support).

And sorry for misspelling your name in my prev post.

**Comment by DerekSMorin** [comment]
I updated to the latest cs-script.  C# Script execution engine. Version 3.24.2.0.


I think the problem is that my exe is x86.


You can duplicate the problem by changing your sample to build  x86, and changing the code in the script to be:


//css_ref ScriptCode\bin\x86\Debug\ScriptCode.exe
using System;
using System.Windows.Forms;

public class Host
{
    static void Main()
    {
        Lib.Hello("Derek");
    }
}


I also tried to add this to the top of the script file but it still didn't work for me:


//css_co /platform:x86

________________________________

**Comment by oleg-shilo** [comment]
`//css_co` specifies compiler options but not how to host the script.
You need to use different directive:
```C#
//css_host /platform:x86;
```

Read more here http://www.csscript.net/help/hosting_control.html

**Comment by DerekSMorin** [comment]
Thanks!  Got it working now!

________________________________
