### ISSUE TITLE
using css_reference for interop service

### ISSUE THREAD

**Issue by sueds** [oleg-shilo/cs-script#5]
Hi, 
I have a problem when using : 
`  "//css_reference System.Runtime.InteropServices.dll;"`
or simply "using System.Runtime.InteropServices; "

the compiler doesn't recognize this struct and throw an error.  
`  [StructLayout(LayoutKind.Explicit, Size =64 )]
   public struct asteckMaterialVertexConstants
    {
            [FieldOffset(0)]
            public Matrix ViewProj;
        }`

error : 

`(12,9): error CS0589: Internal compiler error during parsingSystem.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Mono.CSharp.Undo.AddTypeContainer(TypeContainer current_container, TypeDefinition tc)
   at Mono.CSharp.CSharpParser.push_current_container(TypeDefinition tc, Object partial_token)
   at Mono.CSharp.CSharpParser.case_104()
   at Mono.CSharp.CSharpParser.yyparse(yyInput yyLex)
   at Mono.CSharp.CSharpParser.parse()
`
Wondering if it's a bug or interop is not supported.

thanks

**Comment by oleg-shilo** [comment]
It looks like a problem with Mono compiler, which cannot handle nested structs. The code below works fine:
```C#
dynamic script = CSScript.MonoEvaluator
                         .LoadCode(@"
                            using System;
                            using System.Runtime.InteropServices;

                            public class Script
                            {
                                public TestStruct Test()
                                {
                                    return new TestStruct();
                                }
                            }

                            [StructLayout(LayoutKind.Explicit, Size = 64)]
                            public struct TestStruct
                            {
                                [FieldOffset(0)]
                                public int Index;
                            }");

var result = script.Test();
``` 
However it fails with the same error as yours if it's changed to this:
```C#
...
.LoadCode(@"
    using System;
    using System.Runtime.InteropServices;

    public class Script
    {
        public TestStruct Test()
        {
            return new TestStruct();
        }

        [StructLayout(LayoutKind.Explicit, Size = 64)]
        public struct TestStruct
        {
            [FieldOffset(0)]
            public int Index;
        }
    }");
...
```
Interestingly enough both CodeDom and Roslyn don't exhibit this problem. Chances of Mono team addressing this problem are 0 thus I cannot offer you a good solution for this. 

I can only suggest that you either change the compiler engine or use top-level struct declarations only.

**Comment by sueds** [comment]
Thanks for your help. I'l use top-level struct workaround.
