### ISSUE TITLE
Question about cs-script and app domains and working directory.

### ISSUE THREAD

**Issue by DerekSMorin** [oleg-shilo/cs-script#52]
Is there a way to specify the working directory and the app domain base directory from inside a script?

I reference some dlls that use:

AppDomain.CurrentDomain.BaseDirectory

I am able to get things working but putting my script files into the desired output folder, then compiling to an exe, and running the exe from that folder.  Ideally I'd be able to keep my files in a different folder and just specify the output folder.

I basically need the exe to be running out of the folder:   C:\Development\Source\DotNet\bin\x64\release

I guess maybe I need a way to specify the output exe location?

If I am trying to run from in Notepad++, I guess it would need to build an exe to a specific location and then run it from there?

**Comment by oleg-shilo** [comment]
It's not really up to a script to decide what current dir should be. The only exception is the `-l` switch that you use. It "says" set current dir to the script dur path. If you don't wnat this behavier, drop the switch and ensure the current dir the usual shell-way: `cd <desured dir>`
