### ISSUE TITLE
Visual Studio 2017 extenstion support

### ISSUE THREAD

**Issue by midiway** [oleg-shilo/cs-script#53]
Now that VS2017 is out, can you add support to the VSIX extension?
https://marketplace.visualstudio.com/items?itemName=OlegShilo.CS-ScriptToolsVS2012-15

**Comment by oleg-shilo** [comment]
Yes, I am working on it. As a temporary measure you can do these steps:
- download CS-ScriptToolsVS2012-15 vsix file
- extract manifest file with 7Zip/WinZip
- change in the manifest file highest supported version 14.0->15.0 (VS2017)
- place manifest back to vsix file

Now it supports both VS2017. On install there will be a warning but you can ignore it as this extension doesn't use any VS edition specific features.

If you are comfortable using binary from this post you can use already patched vsix that I have attached. I tested it on my VS2017 and it works just fine.
[CSScript.zip](https://github.com/oleg-shilo/cs-script/files/836162/CSScript.zip)

**Comment by oleg-shilo** [comment]
Done. https://marketplace.visualstudio.com/items?itemName=OlegShilo.CS-ScriptToolsVS2017

**Comment by midiway** [comment]
hey, link is broken, or you deleted the extension?

**Comment by oleg-shilo** [comment]
MS Marketplace is still broken. The plugin was published 2 month ago and they still fail to list it.

You can grab it from GitHib: https://github.com/oleg-shilo/CS-Script.VSIX
