### ISSUE TITLE
Concurrency control for hosted scripts needs to be system wide

### ISSUE THREAD

**Issue by oleg-shilo** [oleg-shilo/cs-script#56]
Triggered by https://github.com/oleg-shilo/cs-script/issues/50 (Issue 3)
__________________
`CSScript.GetCompilerLockName()` should use system wide Mutex based on source/compiled script location. Currently it is based on combination of Process.ID and script location.

**Comment by oleg-shilo** [comment]
Fixed in v3.25.1: https://github.com/oleg-shilo/cs-script/releases/tag/v3.25.1.0 

Now concurrency of hosted execution is controlled by `CSScript.HostingConcurrencyControl`, which is set by default to system wide synchronization for a given script file.

**Comment by maettu-this** [comment]
I'm a bit confused as the release notes of v3.25.1 don't mention anything about #56.

I'll wait until tomorrow and then try v3.25.1 and comment here and #50 with my findings.

**Comment by oleg-shilo** [comment]
The release note was inaccurate. Corrected now.

**Comment by maettu-this** [comment]
I confirm that running the same script in parallel instances of my hosting application now perfectly works :-) Once more, thanks for fixing! Also thanks for confirmation and correction of the release notes.

By the way, there's a "\Source\ReleaseNotes.txt" which I think is obsolete, as it only covers information up to v3.8.8.1.

So, as far as I can tell, this #56 as well as 'Issue 3' of #50 have been resolved :-)

**Comment by oleg-shilo** [comment]
Thank you, closing it now...
