### ISSUE TITLE
Support for CS-Script Tools in VS 2017?

### ISSUE THREAD

**Issue by carey-at-xta** [oleg-shilo/cs-script#57]
Please forgive me if this has been asked and answered. I promise that I looked.

Will CS-Script Tools for VS 2017 exist any time soon?

**Comment by oleg-shilo** [comment]
Please do not apologize. It's not your fault. 
The VS2017 expesnion has been published on VS Marketplace 23 Mar 2017 but yet it hasn't been listed as neither of my other VS2017 migrated extensions. 
 
Please downloa\d the extension from GitHub: https://github.com/oleg-shilo/CS-Script.VSIX

**Comment by carey-at-xta** [comment]
Hi again. I get the message "We're sorry, the page you requested cannot be found!" when I go to the link in  the readme. I guess I'll just wait a little while longer :-)

**Comment by oleg-shilo** [comment]
It's strange. The link in my post is a GitHub link. No restrictions. I was able to navigate there right now from a browser "anonymous session".

**Comment by carey-at-xta** [comment]
I can get to the GitHub link. It's the link https://marketplace.visualstudio.com/items?itemName=OlegShilo.CS-ScriptToolsVS2017 that doesn't work... In Chrome and in IE. Am I missing something?

**Comment by oleg-shilo** [comment]
Yes you are missing something :)

On GitHub the front page is a README.md file with has a the link to the marketplace extension page. I can see and edit that page but no other users can. It's a Marketplace glitch. 

But the binaries (extension itself) are as with any GitHub hosted product can be found at the releases page: https://github.com/oleg-shilo/CS-Script.VSIX/releases

![image](https://cloud.githubusercontent.com/assets/16729806/24427736/c805fe0c-1457-11e7-9ca2-50d8458ba359.png)

**Comment by carey-at-xta** [comment]
Doh! Thanks, she said looking sheepish. :-)
