### ISSUE TITLE
Warnings treated as errors on Mono

### ISSUE THREAD

**Issue by henon** [oleg-shilo/cs-script#59]
Hello,
Thanks for this great C# scripting framework. I used CsScriptLibrary for a long time without issues on .NET but on Mono I need to disable all warnings using #pragma directives inside the scripts in order to get them to compile. Here is my code (I am using CodeDom to execute scripts inside my application). 

    // the following simple script will not execute on Mono due to a warning that a is not used.
    var code = "public class Script { public object Run() { var a=1; return 2+3; }}"
    // here is how the script is executed using CsScriptLibrary
    try
    {
        var asm = new AsmHelper(CSScript.LoadCode(code, "cs", null, true));
        // if we reach that point, the script compiled
        var obj = asm.CreateAndAlignToInterface<IScript>("*");
        // now run it:
        var result=obj.Run();
    }
    catch (CompilerException e)
    {
        // on .net compiler exceptions are only raised when there are errors
        // on mono I get an exception here, even for warnings like unused variable
    }    

I already tried to set the default compiler parameters of CSScript to instruct the mono compiler to disregard warnings. Here is what I tried (based on documentation of compiler switches of Mono compiler:

`CSScript.GlobalSettings.DefaultArguments = "-warn:0 -warnaserror-";`

But I had no success and I am not even sure if this is the right way to go. Anyway, for the sake of completeness I note here that CSScript.GlobalSettings.DefaultArguments defaults to "/c /sconfig /co:/warn:0".

Does anyone know how to get CSScript.LoadCode to disregard warnings on Mono or at least not treat them as errors?

Thanks for any pointers!

**Comment by oleg-shilo** [comment]
Hi there,

Well, you are doing it almost right way.  The `DefaultArguments` property contains CS-Script **CLI** arguments: 
![image](https://cloud.githubusercontent.com/assets/16729806/24592551/e69d7aa4-185b-11e7-8c5f-3444798c0f25.png)

That is why they have no effect for hosted execution (your case).

You cabn easily solve this problem by including your desired compiler options/parameters directly from the script:
```C#
//css_co -warn:0 -co:-warnaserror- 
using System;
...
```

Alternatively you can substitute `CSScript.LoadCode` with `CompileWithConfig`, which allows passing compiler options directly. Something like this:

```C#
static public Assembly LoadCode(string scriptText, bool debugBuild, params string[] refAssemblies)
{
    string tempFile = CSExecutor.GetScriptTempFile()+".cs";
    
    try
    {
        using (StreamWriter sw = new StreamWriter(tempFile))
            sw.Write(scriptText);
        
        return CompileWithConfig(scriptFile, null, debugBuild, CSScript.GlobalSettings, "-warn:0 -co:-warnaserror-", refAssemblies);
    }
    finally
    {
        if (!debugBuild)
        {
            //delete temp file
        }
    }
}
```

**Comment by henon** [comment]
Thank you very much for your quick reply. I tested both your suggestions successfully albeit some changes required to make them work. Here they are for everyone who might be interested, the -co: flag did cause the compiler to fail but this works.

    //css_co -warn:0  
    using System;
    ...

This is enough on Mono to get rid of all the pesky warnings. 
The second option needed some minor changes to work in principle, however, it does not do the nice assembly caching that the original LoadCode function does. 

```
static public Assembly LoadCode(string scriptText, bool debugBuild, params string[] refAssemblies)
{
    string tempFile =  System.IO.Path.GetTempPath() + Guid.NewGuid().ToString() +".cs";        
    try
    {
        using (StreamWriter sw = new StreamWriter(tempFile))
            sw.Write(scriptText);        
        return LoadWithConfig(scriptFile, null, debugBuild, CSScript.GlobalSettings, "-warn:0", refAssemblies);
    }
    finally
    {
        if (!debugBuild)
        {
            //delete temp file
        }
    }
}
```

No big deal though, as caching can easily be added.

Thanks!

**Comment by oleg-shilo** [comment]
Yes, you are right. that `-co:` was an accidental copy-paste leftover.  I meant to provide:
```C#
//css_co -warn:0 -warnaserror-
```
