### ISSUE TITLE
CS-Script source files, default setting xml, and docs referencing incorrect Roslyn assembly filename spelling causes C#7 support failure

### ISSUE THREAD

**Issue by CollinChaffin** [oleg-shilo/cs-script#62]
# Issue
- Links in this repo source and docs incorrectly use misspelled Roslyn support assembly filename of:  **"CSSCodeProvider.v.4.6.dll"**.

# Cause
- https://github.com/oleg-shilo/cs-script/wiki/C%23-7-support (uses incorrect CSSCodeProvider.v.4.6.dll)
- https://github.com/oleg-shilo/cs-script/blob/18deff67a1d306138d092bbb9eff7f4b10925627/Source/css_config.default.xml (uses incorrect CSSCodeProvider.v.4.6.dll)
- https://github.com/oleg-shilo/cs-script/blob/8af0b64aff337a818344994b535e2128f6e4c63d/Source/Settings.cs (uses correct CSSCodeProvider.v4.6.dll)

# Fix
- Correct all references to the correct physical assembly filename of:  **"CSSCodeProvider.v4.6.dll"** which is also currently partially referenced in source and docs.

# Background / additional detail
This one caused me (and I'm guessing others) a lot of wasted time fighting with just why this support seemed to be incomplete in my systems (even on clean test builds) and the NPP plugin will not fully activate the support.  It did not help that there are currently major stability issues with the NPP plugin manager that is flattening plugins' subfolders.  That also caused problems with v1.70, but that is not what was causing all the C#7 Roslyn support issues in my testing.

ALL the checks in the NPP plugin for enabling the C#7 Roslyn support that continually now fail and indicate I don't even have it installed.......is all due to this one extra period character in this string that has been used in the repo source and docs for some time.  Since the filename in fact does not contain the extra period that is installed with this app/plugin, the default settings xml and other incorrect references cause failures.

# Additional Testing
On a clean VM system I built to test this and a good visual of the issue - here is Everything's system-wide search for the filename listed in this repo of "CSSCodeProvider.v.4.6.dll" (NONE - and no Roslyn support can be enabled in CS-Script):
http://i.imgur.com/jc7SuOl.png

Here's the REAL corrected assembly filename search on the same VM test system for the correct filename of "CSSCodeProvider.v4.6.dll" (Two instances found installed by CS-Script both NPP plugin and the main Choco package):
http://i.imgur.com/PMw5zbR.png

I think I pulled out half my hair as to why the plugin was insisting the support was not there and failed to enable no matter what I tried.  Once both the above source files I listed and the wiki docs on how to enable it, then the C#7 Roslyn support should again work properly.

To show you just how hard this was for anyone to catch - this older page for C#6 support actually still incorrectly blends both the correct and incorrect spelling.  It uses the incorrect spelling in the screenshot of the source code comments (and back in that actual  source file comment), and then sure enough showing a screenshot using the real filename missing the period in the assembly window.  The issue is that now it's crept from wiki docs into the above newer source code files actually referencing not-existent assembly spelling, which have now borked it's ability to correctly detect the support:

Open this page for C#6 support info:
https://csscriptsource.codeplex.com/wikipage?title=.NET%204.6%20Support

Search the C#6 support page for "CSSCodeProvider.v.4.6.dll" and it's found here:
http://i.imgur.com/1esCz6H.png

Search the C#6 support page for "CSSCodeProvider.v4.6.dll" and it's found in every actual assembly screenshot since it is correct:
http://i.imgur.com/L6okFRi.png

**Comment by CollinChaffin** [comment]
After installing the prerelease of 1.7.3.07, I really do need help to debug this because the Roslyn support is still not working properly.

Here's what I've done to simplify this because I am getting a bit frusterated:  

Removed the env variable for CSScript as I don't want the non-prerelease via chocolately to interfere with this test.  I assume the NPP plugin should use the embedded assembles and intellisense executables etc.
Moved EVERYTHING for plugins out of APPDATA temporarily and back to the default programfiles86 and renamed the xml flag file so that NPP is running in default plugin config mode
Installed 1.7.3.07 via unzip manually into plugins folder

Upon executing NPP now, and every execution, I receive this:
![snag_4-9-2017_16-03-10](https://cloud.githubusercontent.com/assets/9301483/24841076/ca4ce68e-1d40-11e7-8352-d68b6ec01524.png)

However, there is a change because now, my plugin config the Rosylyn checkbox for some reason remains enabled continually, despite it not working, whereas previous versions upon relaunch the checkbox would be unchecked:
![snag_4-9-2017_16-03-20](https://cloud.githubusercontent.com/assets/9301483/24841082/f58d9c08-1d40-11e7-9429-35e33b05b507.png)

As you can see, it maintains the setting to utilize the embedded engine to keep this simple:
![snag_4-9-2017_16-04-45](https://cloud.githubusercontent.com/assets/9301483/24841083/ffcefcca-1d40-11e7-93a5-154af8491f57.png)

...and I am not certain what other steps I can take to fully debug this plugin, but my logic pushed me to execute the "CompatibilityTest.exe" that, unlike before was throwing an exception and crashing hard, now says all is great (just to take the other half of my hair):
![snag_4-9-2017_16-09-44](https://cloud.githubusercontent.com/assets/9301483/24841092/40632d92-1d41-11e7-95da-3987ccf5dc95.png)

So, @oleg-shilo, I really appreciate your assistance to help me enable the Roslyn C#7 support.

**Comment by oleg-shilo** [comment]
Fixed, thank you for reporting it.
I am closing this issue and we will continue in the CS-Script.Npp wiki. I have created the dedicated issue there:  https://github.com/oleg-shilo/cs-script.npp/issues/1
