### ISSUE TITLE
Nuget package issue

### ISSUE THREAD

**Issue by rbmanian75** [oleg-shilo/cs-script#63]
Hi,
We have a class library targetting .net 4.6. But installing the nuget pacakge adds .net standard dlls?. Please allow full .net framework target also so that we dont need to install the .net standard dependencies.

Thanks

**Comment by oleg-shilo** [comment]
Hi there, 

>But installing the nuget pacakge adds .net standard dlls?

I think you are referring to the Roslyn assemblies not ".net standard dlls". These assemblies are not included in the CS-Script package but simply referenced as the dependency of the package and NuGet resolves (adds) these assemblies to the VS project. 

I am not sure what do you mean by "allow full .net framework target". If you are referring to `Client Profile` target edition vs full one then .NET 4.6 doesn't have such a target.  4.0 does but 4.6 doesn't.
Please elaborate. 

![image](https://cloud.githubusercontent.com/assets/16729806/24935973/f9aecf76-1f68-11e7-833b-a3cbe5c196b8.png)

**Comment by rbmanian75** [comment]
Hi,

I have create c# class library project targeting .net 4.6 and initially my references are
![beforecsscript](https://cloud.githubusercontent.com/assets/1324600/24949866/fa428470-1f66-11e7-8764-ebbfb5a636e0.JPG)
and after installing csscript nuget package my references are
![aftercsscript](https://cloud.githubusercontent.com/assets/1324600/24949893/0a61163c-1f67-11e7-9bb0-585130932a32.JPG)
You can see that lots of system dll are referenced from the package folder. for example system.io already exist in .net 4.6 but it is being  referenced from packages folder. Sample applies other system dll packages download. Am i understanding something wrong?  ie the system dlls referenced does not exist in full .net framework?
Thanks

**Comment by oleg-shilo** [comment]
You have missed the major point in my answer. 

These all assemblies are not part of .NET 4.6, including `System.IO.*.dll`. They do look like standard .NET assemblies but they are not. The are all part of Roslyn. Analyse their location (in the reference properties) and you will see that they come from the Microsoft dependency packages (Roslyn). CS-Script package only includes two assemblies. Everything else is the dependency packages. 

This is the very nature of NuGet model. This is what you need to do to bring C# 6/7 syntax to your host application.

**Comment by rbmanian75** [comment]
Thank you for the details. Now i get the point.

Regards

**Comment by oleg-shilo** [comment]
BTW your confusion is quite natural. 

For years and years MS was distributing compilers with standard .NET installation. Ironically it still does but only for up to C#5 syntax. Starting from C#6 the new compilers have to be added as an extra dependency - either as a NuGet package or a set of raw dlls. 

Personally, think it is ridiculous and creates absolutely unnecessary pressure for any development that involves dynamic C# compilation. But... nothing we can do about it. :(
