### ISSUE TITLE
Add option to take Main from primary script file

### ISSUE THREAD

**Issue by rconde01** [oleg-shilo/cs-script#68]
Sometime in the last few versions you started detecting multiple Main methods and throwing an error one was detected. This broke our scripting system. We worked around it, but it might be nice to add an option which takes the Main from the primary script file instead of throwing an error.

**Comment by oleg-shilo** [comment]
You can use `//css_import`  instead of  `//css_include`. The difference - import renames "Main"

**Comment by rconde01** [comment]
In my case I'm using newincludes in the precompiler....is there a newimports?

**Comment by oleg-shilo** [comment]
No there is none. 

I changed your post into an "enhancement". To allow this feature in future but for now you will need to:
- Manually change "Main" into "main" (or something similar) in your imported script
- Save new content into a temp file
- Add this temp file to the new includes.

**Comment by rconde01** [comment]
Yeah - that's the approach I took.

**Comment by oleg-shilo** [comment]
Implemented. The script engine is now exposed to the precompiler and now it can use CS-Script API. And for the cases like yours I have added a new method to the ScriptParser class for importing the scripts:
```C#
var includes = (List<string>)context["NewIncludes"];
includes.Add(CSScriptLibrary.ScriptParser.ProcessImportedScript("<your script to import>"));
```
