### ISSUE TITLE
Enhancement: Have a way to import all the script files in a directory.

### ISSUE THREAD

**Issue by DerekSMorin** [oleg-shilo/cs-script#7]
Is there a way to import all script files in a directory?

I'd like to use a folder as a grouping mechanism for helper classes.

//css_dir ..\Shared;
//css_import BatchMethods;
//css_import BatchConstants;
//css_import SharedMethods;
...

It would be nice to be able to include all the files in "Shared"

From Oleg:

If you are hosting your script engine then it can be done very easy with dynamically composed includes script similarly to CS-Script "linq.includes.cs"

Though for stand alone script execution it's problematic.

I actually see this as a good (easy to implement) feature with syntax similar to this: //css_include *.cs 

Derek:

That syntax looks good to me.  It would be good to make sure it works with relative paths like:
//css_include ..\Shared\\*.cs

**Comment by oleg-shilo** [comment]
Done.
Please use "Release v3.13.3.0 - HotFixes" to test the feature
