### ISSUE TITLE
Minor issue related to platform dependent line breaks, e.g. in error messages

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#70]
Hi Oleg,

Minor issue related to the following code:

`throw new FileNotFoundException(string.Format("Could not find file \"{0}\".\nEnsure it is in one of the CS-Script search/probing directories.", file));`

`\n` may not be detected as good-enough line break, in my case resulting in an error message with neither line break nor space:

> System.IO.FileNotFoundException: Could not find file "..\CommunicationObject.cs".Ensure it is in one of the CS-Script search/probing directories.

I suggest to use `Environment.NewLine` in such cases. Note that this may apply to several other locations.

Best regards,
Matthias

**Comment by oleg-shilo** [comment]
Of course. :)
Done. Txs.

**Comment by maettu-this** [comment]
Verified, thanks.
