### ISSUE TITLE
Passing arguments to the base constructor of a derived class in a script

### ISSUE THREAD

**Issue by Nacimota** [oleg-shilo/cs-script#72]
I've just started experimenting with CS-Script for the first time and I'm having trouble getting it to work the way I want. I have an abstract class that I want my scripts to derive from, which declares a constructor that initializes a field in the class like so:

    public abstract class Module
    {
        protected Random randField;
        public Module(Random randObj)
        {
            this.randField = randObj;
        }
        public abstract string Name { get; }
        public virtual void Process(string str) { }
    }

What I want to do is load a script where the constructor is not defined, but where an existing object can be passed as an argument to the constructor defined in the base class. Something like this:

    namespace scripttest
    {
        class Program
        {
            static void Main(string[] args)
            {
                Random rand = new Random();
                CSScript.GlobalSettings.UseAlternativeCompiler = null;
                CSScript.EvaluatorConfig.Engine = EvaluatorEngine.Roslyn;

                var red = (Module)CSScript.Evaluator.LoadCode(@"using System;
        using scripttest;
        public class Red : Module
        {
            public override string Name { get { return ""Red""; } }
            public override void Process(string str)
            {
                var prevColour = Console.ForegroundColor;
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine(str + "", "" + randField.Next());
                Console.ForegroundColor = prevColour;
            }
        }", rand);

                string[] words = new string[] { "This", "is", "a", "test" };
                foreach (var word in words)
                {
                    Console.Write($"{red.Name}: ");
                    red.Process(word);
                }
            }
        }
    }

In the above example, the `CSScript.Evaluator.LoadCode` method throws the following exception:

>**Microsoft.CodeAnalysis.Scripting.CompilationErrorException:** '(3,18): error CS7036: There is no argument given that corresponds to the required formal parameter 'randObj' of 'Module.Module(Random)''

The problem goes away if I remove the constructor from the abstract class and declare it in the script but I'd rather not do that if I can avoid it because it would mean more boilerplate to write in each script. Is what I'm trying to do easily achievable in CS-Script, or is it not supposed to be used with abstract classes in this way?

Thanks

**Comment by oleg-shilo** [comment]
You code contains an error. Even without CS-Script it cannot be compiled:

![image](https://user-images.githubusercontent.com/16729806/27677113-d4ea1844-5cf3-11e7-86d3-25987309ed33.png)


In order to fix it you need to have a matching constructor in your Red class.

```c#
public class Red : Module
{
    public Red(Random randObj) : base(randObj)
    {
    }
    ...
```

**Comment by Nacimota** [comment]
Ah, of course; how silly of me. I'd really rather not have to write a constructor in the script if I can avoid it but I'm not sure how I will go about that. I think I'll have to replace the constructor with an `Initialize` method in the base class and call it after the code is loaded or something. Thanks for your help!
