### ISSUE TITLE
In 3.26.0.0 running default install gives error about alternative compiler

### ISSUE THREAD

**Issue by rconde01** [oleg-shilo/cs-script#73]
```
PS E:\myFolder> cscs .\myScript.cs
C# Script execution engine. Version 3.26.0.0.
Copyright (C) 2004-2017 Oleg Shilo.

Error: Specified file could not be compiled.

System.ApplicationException: Cannot use alternative compiler (). You may want to adjust 'CSSCRIPT_DIR' environment variable or disable alternative compiler by setting 'useAlternativeCompiler' to empty value in the css_config.xml file.

Error Details: ---> System.ApplicationException: Cannot find alternative compiler ""
   at csscript.CSExecutor.LookupAltCompilerFile(String altCompiler, String firstProbingDir)
   at csscript.CSExecutor.LoadCompiler(String scriptFileName, String[]& filesToInject)
   --- End of inner exception stack trace ---
   at csscript.CSExecutor.LoadCompiler(String scriptFileName, String[]& filesToInject)
   at csscript.CSExecutor.Compile(String scriptFileName)
   at csscript.CSExecutor.ExecuteImpl()
PS E:\myFolder>
```

3.25.3.0 appears to work ok.

**Comment by oleg-shilo** [comment]
Did you have CS-Script previously installed?

As part of the troubleshooting can you please check what your css_config.xml has as an alternative compiler.

It supposed to have `%CSSCRIPT_DIR%\lib\CSSRoslynProvider.dll`

**Comment by rconde01** [comment]
1. Just to clarify, this is on windows
2. I just unzipped the 7z file and ran
3. There is no css_config.xml except in the linux directory

**Comment by oleg-shilo** [comment]
Great, thank you. Will provide the fix very soon.

**Comment by oleg-shilo** [comment]
The problem is caused by the mistake in the routine responsible for loading default code provider (absence of css_config.xml). This error affects the cases when CS-Script was not installed (I assume your case) but a raw cscs.exe is used. 

I changed the issue into "Defect".

**Comment by oleg-shilo** [comment]
Can you please test [v3.26.1.0](https://github.com/oleg-shilo/cs-script/releases/tag/v3.26.0.0). It supposed to fix the issue.

**Comment by rconde01** [comment]
Works! Thanks!
