### ISSUE TITLE
Enhancement: Embedded Roslyn support in separate nuget

### ISSUE THREAD

**Issue by seertenedos** [oleg-shilo/cs-script#76]
It would be great to have a nuget package that contains a static class that could be called to enable Roslyn by doing the following commands below.
CSScript.GlobalSettings.UseAlternativeCompiler = <CSSRoslynProvider.dll path>;
CSScript.GlobalSettings.RoslynDir = <Roslyn path>;

The required files should also be embedded and either accessed as an embedded resource or extracted locally when the methods on the static classes to configure CS-Script to use Roslyn is called. I understand this DLL would be large and may not be suited for everyone but it would work really well for people that reference projects or nuget packages that use CS-Script. CS-Script use to be great as you just referenced it once and it works.  It would be great to get that happening again with Roslyn even though Roslyn itself tries to make it impossible.

**Comment by son-huynh-zocdoc** [comment]
Sort of related to this, I actually think it would be great to split Roslyn support into a separate Nuget package altogether. That would lower the requirements on the current CSScript Nuget package (currently it requires your application target .NET 4.6 due to the Roslyn dependencies). It's cleaner than having to ignore Nuget dependencies or set explicit DLL references in 4.0/4.5 apps.

**Comment by oleg-shilo** [comment]
Hi there,
there is a little confusion about this item. It was logged this upon my request. The idea was that it supposed to be an enhancement proposal for **enabling** Roslyn support by potentially embedding RoslynAdapter (CS-Script internal utility) into the script engine executable. But it was not about changing packaging model. Unfortunately the title is misleading as it implies that it has something to do with NuGet packaging.

Roslyn is already a separate nuget package and there is nothing from cs-script that needs to be done for that. There is also a dedicated "raw" nuget package (CS-Script.lib) that has no dependency on Rolsyn (or any other package). This package can also target any platform version. Meaning that any other dependency needs to be managed by the user.
```
Install-Package CS-Script.lib
```
Ironically @seertenedos, the originator of the issue had also something else in mind. Let me know if the  s l author of the `CS-Script.lib` package addresses your problem and I will close this issue to avoid any future confusion.

**Comment by son-huynh-zocdoc** [comment]
Hey @oleg-shilo, thanks for the response. Correct me if I'm wrong though, currently if I want to use CS-Script with Mono, I would need to either 1) maintain and reference my own copy of Mono (along with CS-Script.lib) or 2) add the CS-Script or CS-Script.bin package which requires .NET 4.6 due to Roslyn dependencies. None of these are real blockers but I guess going the package route makes it slightly better in case there were any specific version dependencies from CS-Script to Mono.

**Comment by oleg-shilo** [comment]
Yes you are correct. Both of the options are valid.

When I designed the package content I split it into the tree packages:

- cs-script.lib
    Raw CS-Script content - single assembly. Target-neutral. No dependency. User is in complete control of how to bring required dependencies. For example via external packages: `Microsoft.CodeAnalysis.CSharp.Scripting` and `Mono.CSharp`  

- cs-script.bin
    All CS-Script binaries. Targets: net40, net45 and net46. Dependencies are included. Mono.Sharp.dll is directly embedded into the package and Roslyn as a package dependency (Microsoft.CodeAnalysis.CSharp.Scripting).

- cs-script
    Includes `cs-script.bin` and code samples.

Now, about running on Mono. 

You may not need any dependency at all. 

- If you are using [CSScript.Native](https://github.com/oleg-shilo/cs-script/wiki/Choosing-Compiler-Engine#csscriptnative) or [CSScript.Evaluator](https://github.com/oleg-shilo/cs-script/wiki/Choosing-Compiler-Engine#csscriptevaluator) with the `CodeDom` engine you don't need any extra files, just CSScriptLibrary.dll. Though your syntax will be limited to C# 6.

- If you are using CSScript.Evaluator with the `Mono` engine you will need to have Mono.CSharp.dll. You can bring it manually or via any of the nuget packages you can find (e.g. ['cs-script.bin'](https://www.nuget.org/packages/CS-Script.bin/), ['Mono.CSharp'](https://www.nuget.org/packages/Mono.CSharp/)). Alternatively, if you may implement custom assembly probing and locate  Mono.CSharp.dll on local file system (in one of the Mono dirs) at runtime.  
Your syntax will also be limited to C# 6.

- If you are using CSScript.Evaluator with the `Roslyn` you will need to bring it with the ['Microsoft.CodeAnalysis.CSharp.Scripting'](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Scripting/) package. The runtime must be v4.6+. You will be able to use C# 7 syntax.

**Comment by oleg-shilo** [comment]
Closing this issue...
Please reopen it if any further support is required

**Comment by son-huynh-zocdoc** [comment]
Yes that's fine @oleg-shilo, thank you. One last thing though if you could confirm for me, to reference an assembly in CodeDom, it needs to either be in the GAC or live in the local file system correct? Only Mono and Roslyn lets you reference an assembly that's already loaded in code (e.g. `ReferenceAssembly(Assembly.Load("MyAssembly"))`?

**Comment by oleg-shilo** [comment]
> to reference an assembly in CodeDom, it needs to either be in the GAC or live in the local file system correct?

Yes it is correct. 

> Only Mono and Roslyn lets you reference an assembly that's already loaded in code (e.g. ReferenceAssembly(Assembly.Load("MyAssembly"))?

No it's incorrect. You can always reference an assembly that is already loaded. The important point is that the assembly must have the actual file present on the file system so the CodeDom compiler (csc.exe) can find it. But you can reference any already loaded assembly. 
```C#
CSScript.CodeDomEvaluator
        .ReferenceAssembly(Assembly.Load("MyAssembly"))
        .ReferenceAssemblyOf<Form>()
        .ReferenceAssemblyByName("System.Xml")
        .ReferenceDomainAssemblies()
        .ReferenceAssemblyByNamespace("System.Linq")
        .ReferenceAssembliesFromCode("<script code with //css_ref directives>")
        .CreateDelegate<int>(@"int Sqr(int a)
                               {
                                   return a * a;
                               }");
```
In fact cs-script references already loaded assemblies of the current app domain by default. 

All engines exposed via 'CSScript.Evaluator' are identical in terms of how you use them. They only differ by the underlying compiling services. For example CodeDom generates debug symbols so the script can be debugged (Mono and Roslyn don't). 

BTW CodeDom is superior to any other engine in almost any aspect except a couple. And only one that is actually serious - support for the latest syntax (C# 7).

**Comment by son-huynh-zocdoc** [comment]
Yes thanks for that distinction.
