### ISSUE TITLE
Dynamically include SOAP service?

### ISSUE THREAD

**Issue by UweKeim** [oleg-shilo/cs-script#77]
Having something like the following right at the begnning of my CS Script file:

```csharp
//css_pre wsdl(http://example.org/my-service.asmx, MySoapService);
```

This works perfectly.

Now I want to be able to dynamically change the URL based on command line parameters I pass to my CS Script file.

E.g.:

```batch
cscs.exe "MyScript.cs" --url="http://example.com/my-other-service.asmx"
```

**My question:**

Is something like this possible?

Or any workarounds to dynamically call SOAP services and still be able to get proxy classes generated?

**Comment by oleg-shilo** [comment]
If you are looking for truly dynamic SOAP client I can recommend ServiceStack - on my personal opinion the best WS framework available for managed applications.

If you are looking for a conservative solution then you can slightly modify wsdl.cs pre-script to access the parent script arguments. The code below shows the technique:

_primary script_
```C#
//css_pre wsdl_custom();
using System;

void main()
{
    Console.WriteLine("Hello...");
}
```
_pre-script_
```C#
using System;
using System.Linq;

void main(string[] args)
{
    var url = Environment.GetCommandLineArgs()
                         .Where(x => x.StartsWith("--url="))
                         .Select(x => x.Replace("--url=", ""))
                         .FirstOrDefault();

    dbg.print("url =>", url);
}
```
_output_
```
C:\tmp>cscs -nl script.cs --url="http://example.com/my-other-service.asmx"
url => http://example.com/my-other-service.asmx
Hello...
```

**Comment by UweKeim** [comment]
Will I be able to put my modified wsdl.cs script somewhere locally into my own folder (let's say in the same folder als my primary script)?

I want to avoid copying something into the CS-Script installation folder and later forget about having a custom script there.

**Comment by oleg-shilo** [comment]
Yes, this is how I tested the code. All from the same folder.

**Comment by UweKeim** [comment]
Thank you very much 😊
