### ISSUE TITLE
Can't open project in visual studio after performing upgrade to latest hotfix

### ISSUE THREAD

**Issue by DerekSMorin** [oleg-shilo/cs-script#8]
After installing Release v3.13.3.0 RC

When I right click a script file to do "Open in Visual Studio 2015"
I get similar results for 2013, etc.

csscript.CompilerException: c:\Dropbox\Installs\cs-script\lib\debugVS14.0.cs(1626,71): error CS1729: 'csscript.CSharpParser' does not contain a constructor that takes 2 arguments

   at csscript.CSExecutor.ProcessCompilingResult(CompilerResults results, CompilerParameters compilerParams, ScriptParser parser, String scriptFileName, String assemblyFileName, String[] additionalDependencies)
   at csscript.CSExecutor.Compile(String scriptFileName)
   at csscript.CSExecutor.ExecuteImpl()

If I open visual studio 2015, and try to do "Open Script..." I get:

CS-Script cannot generate on-fly VS2010 project

I'm not 100% sure on the upgrade / removal process.  I had installed previously with chocolatey, and then uninstalled with chocolatey.  For the latest hotfix I just extrated into a folder and then ran the install batch file.  I didn't make any changes the visual studio extension I had installed.

**Comment by oleg-shilo** [comment]
Hi Derek, 

Yes this problem is caused by the upgrade. 
Note that this release is a **pre-release** with the only objective to test wild card resolution in "//css_include". And you reporting the defects that have been missed by me only indicates that making a preview of the release was warranted :)

The shell extensions and other depended scripts will be updated after I am happy with the new functionality. As a quick work around replace  in debugVS14.0.cs(line1626)
```C#
...new csscript.CSharpParser(scriptFile, true).CmdScripts) ...
//with
...new csscript.CSharpParser(scriptFile, true, null).CmdScripts) ...
```
But if you can wait a few hours I will make another prerelease with the required changes for dealing with the affected shell extensions.

**Comment by DerekSMorin** [comment]
Hi Oleg,

There is absolutely no rush. I will try the work around or the next pre-release tomorrow morning in about ten hours :). I'll let you know how it goes.

Derek

On Aug 1, 2016 9:45 PM, oleg-shilo <notifications@github.com> wrote:

Hi Derek,

Yes this problem is caused by the upgrade.
Note that this release is a pre-release with the only objective to test wild card resolution in "//css_include". And you reporting the defects that have been missed by me only indicates that making a preview of the release was warranted :)

The shell extensions and other depended scripts will be updated after I am happy with the new functionality. As a quick work around replace in debugVS14.0.cs(line1626)

...new csscript.CSharpParser(scriptFile, true).CmdScripts) ...
//with
...new csscript.CSharpParser(scriptFile, true, null).CmdScripts) ...

But if you can wait a few hours I will make another prerelease with the required changes for dealing with the affected shell extensions.

**Comment by oleg-shilo** [comment]
OK. All done. Pre-release v3.13.4.0. Should be working now.

**Comment by DerekSMorin** [comment]
Thanks Oleg,


It all seems to be working very well now.


I have been starting to use:

//css_inc ..\Shared\*.cs;


It seems to be working very well and is greatly appreciated.


Derek



________________________________
