### ISSUE TITLE
More specific error message in case of file resolution fails related to //css_import

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#82]
Currently, if file resolution fails, `CSScriptLibrary.CSScript.Compile...()` throws a `System.IO.FileNotFoundException` (stack trace see below) stating:

> Could not find file "\<Path\>".
> Ensure it is in one of the CS-Script search/probing directories.

Would it be possible to add more details, like stating the file where the `//css_import` cannot be resolved? That would help very much when implementing a highly hierarchical script code, e.g. a script library.

Stack trace:
```
CSScriptLibrary.FileParser.ResolveFilesDefault()
CSScriptLibrary.FileParser.ResolveFile()
CSScriptLibrary.FileParser..ctor()
CSScriptLibrary.ScriptParser.ProcessFile()
CSScriptLibrary.ScriptParser.ProcessFile()
CSScriptLibrary.ScriptParser.ProcessFile()
CSScriptLibrary.ScriptParser.ProcessFile()
CSScriptLibrary.ScriptParser.ProcessFile()
CSScriptLibrary.ScriptParser.ProcessFile()
CSScriptLibrary.ScriptParser.Init()
csscript.CSExecutor.Compile()
CSScriptLibrary.CSScript.CompileWithConfig()
CSScriptLibrary.CSScript.CompileWithConfig()
<HostingApplication>.ScriptRunner.CompileScript()
```

**Comment by oleg-shilo** [comment]
Yes it makes sense.
The latest commit does it:
```C#
//css_inc fake_dir\utils.cs
...
```
![image](https://user-images.githubusercontent.com/16729806/29155754-5bfe33a2-7de1-11e7-9fc0-cf4fd1d7a3fc.png)

Soon I'll be doing release for VSCode so you'll be able to start using this feature very soon.

**Comment by maettu-this** [comment]
Upgraded to 3.27.2 and forced the exception. Three things:

Suggesting to change "Exception" on line 867 of fileparser.cs to "FileNotFoundException" to get a more specific exception type. Alternatively, retrieve the effective type of 'e' and call that constructor via reflection, or, additionally catch the more specific FileNotFoundException an then create a wrapping instance of that specific type.

Very nice that the whole calling chain is output. However, the stated "from" script is not the respective parent script but rather the top level script. That seems rather confusing. Here's a concrete example:
```
    Cannot import '<ScriptRootFolder>\.\Device.cs' from the '<ScriptRootFolder>\Script.cs' script.
        Cannot import '<ScriptRootFolder>\.\Library\Generic\Device.cs' from the '<ScriptRootFolder>\Script.cs' script.
            Cannot import '<ScriptRootFolder>\Library\Generic\.\IGenericDevice.cs' from the '<ScriptRootFolder>\Script.cs' script.
                Cannot import '<ScriptRootFolder>\Library\Generic\.\GenericCommand.cs' from the '<ScriptRootFolder>\Script.cs' script.
                    Cannot import '<ScriptRootFolder>\Library\Generic\.\GenericSingleLineExecuteCommand.cs' from the '<ScriptRootFolder>\Script.cs' script.
                        Cannot import '..\Framework\SingleLineExecuteCommand.cs' from the '<ScriptRootFolder>\Script.cs' script.
                            System.IO.FileNotFoundException:
                                Could not find file "<ScriptRootFolder>\Library\Generic\..\Framework\SingleLineExecuteCommand.cs".
                                Ensure it is in one of the CS-Script search/probing directories.
```
The last three message lines are OK, but the last forth last is confusing since `Script.cs` doesn't import `SingleLineExecuteCommand.cs` at all. It's rather `GenericSingleLineExecuteCommand.cs` that contains the invalid `//css_import` statement. I'd expect that the second stated file is the file where the error is located, not the top level script.

Finally, a minor inconsistency:
The "Cannot import" statement uses single quotes ' whereas the "Could not find file" statement uses double quotes " for the file path.

**Comment by oleg-shilo** [comment]
All valid points.
Txs. All done. Will be available in the next release.

**Comment by maettu-this** [comment]
Perfect! Users should now be able to much easier locate an issue in a larger script library like the one I've been working on the last couple of weeks. Thanks!
