### ISSUE TITLE
Fail to create New Script in VS2017

### ISSUE THREAD

**Issue by alexeykuznetsov** [oleg-shilo/cs-script#84]
Hello!

I,m trying to create New Script with CS-Script Tools, but catching message box: "CS-Script cannot generate on-fly VS project".
VS2017 Community ver. 15.2 (26430.6)
CS-script Engine ver. 3.27.5.0
CS-script Extension ver. 1.6 (For some reason CS-Script Tools menu displays it as 1.5.0.0)
https://yadi.sk/i/ZRph-IWF3MRpTS
What I'm doing wrong?

Thank you!

**Comment by oleg-shilo** [comment]
Hi Alexey, 

Sorry I could not get to you earlier, I am not fully available and any serious support will have to wait until I am back on project (~ one more week).  

But I had a look at my deployment and yes there is a typo in the displayed version but this one is rather cosmetic. The functionality itself seems to work and I have the same toolset as yours.

There is a good chance that your CS-Script installation is somehow corrupted. I suggest that you install CS-Script from Choco (https://chocolatey.org/packages/cs-script) and try it again (after restarting the VS). This way you will eliminate at least one variable from the equation.

**Comment by alexeykuznetsov** [comment]
Installing CS-Script from Choco solved the problem, thank you!
