### ISSUE TITLE
Referencing assemblies by namespace fails on Mono evaluator

### ISSUE THREAD

**Issue by Rohansi** [oleg-shilo/cs-script#85]
CSScript tries to `Assembly.LoadFrom("System")` and then file not found is thrown.

```
Mono JIT compiler version 5.2.0.215 (tarball Mon Aug 14 15:46:23 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
```

https://github.com/oleg-shilo/cs-script/releases/tag/v3.27.5.0

**Comment by oleg-shilo** [comment]
If you are using `Assembly.LoadFrom("System")` from your script then this is a C# error, not scripting one. `LoadFrom` requires file name not the assembly name. You may try to use `Assembly.Load("System")` instead.

**Comment by Rohansi** [comment]
It is failing here: https://github.com/oleg-shilo/cs-script/blob/master/Source/CSScriptLibrary/CSScriptLib.Eval.Mono.cs#L431

I'll get a stack trace for you.

**Comment by Rohansi** [comment]
```
System.IO.FileNotFoundException: 
File name: 'System'
  at (wrapper managed-to-native) System.Reflection.Assembly:LoadFrom (string,bool)
  at System.Reflection.Assembly.LoadFrom (System.String assemblyFile) [0x00000] in <204f770036d441bb8dfd3daba3550e83>:0 
  at CSScriptLibrary.MonoEvaluator.ReferenceAssembly (System.String assembly) [0x00084] in <9b25d89a841a44829aec92b8c8803de5>:0 
  at CSScriptLibrary.MonoEvaluator.ReferenceAssemblyByNamespace (System.String namespace) [0x0000f] in <9b25d89a841a44829aec92b8c8803de5>:0 
  at RohBot.Rooms.Script.ScriptRoom.Compile () [0x00032] in <563d8819edc74582be0e96daac794fbe>:0
```

```c#
CSScript.Evaluator.ReferenceAssemblyByNamespace("System");
```

Also needed to set `DisableReferencingFromCode` to true because it ended up with the same error.

**Comment by oleg-shilo** [comment]
OK thank you. 

`ReferenceAssemblyByNamespace` relies on Fusion.dll (COM interface)  for resolving namespaces on Win. Thus it supposed to fail on Linux where Fusion.dll  is absent. That is why `ReferenceAssemblyByNamespace` was not available for Linux for quite some time. However a recent `Utils.MonoGAC` work around supposed to fill this gap. And it looks like it doesn't, at least in some cases.

Will look into it.
in a mean time you can try 
```C#
CSScript.Evaluator.ReferenceAssemblyByName("System");
```

**Comment by oleg-shilo** [comment]
Fixed. Will be available in the next release.
Thank you.
