### ISSUE TITLE
com.cs file is absent in CS-Script distributive

### ISSUE THREAD

**Issue by SergeyBogdanov** [oleg-shilo/cs-script#87]
Hi,
Is the [Using COM](http://csscript.net/help/Using_COM_tutorial.html) tutorial still actual?
I can't find com.cs file in the CS-Script 3.27.5.

**Comment by oleg-shilo** [comment]
Yes it is in still actual. But COM itself is not so relevant :) 
At least not as it was at the time when COM support was released. You can find `com.cs` in the cs-script.ExtensionPack.7z pack from the [release page](https://github.com/oleg-shilo/cs-script/releases).

**Comment by SergeyBogdanov** [comment]
_>>You can find com.cs in the cs-script.ExtensionPack.7z pack from the release page._
Great, thanks!

_>>But COM itself is not so relevant :)_
Yeah, by unfortunately Microsoft still did not realize this)
Currently if some CS script references VS2017 TFS or MSBuild assemblies then some pre or precompile script should be used that will set search dirs for the primary script (VS2017 no longer puts it's assemblies to GAC so scripts should load TFS ans MSBuild assemblies from VS2017 install path now). And the only official programmatic way to get VS2017 install path is to use [SetupConfiguration](https://github.com/Microsoft/vs-setup-samples) COM class.
COM class...)

**Comment by oleg-shilo** [comment]
Fair enough...
