### ISSUE TITLE
Why CS-Script.RoslynProvider add all net assemble references to my project?

### ISSUE THREAD

**Issue by TruePluto** [oleg-shilo/cs-script#88]
____I just want to try C# script feature.  I am using netframework **4.7**. but I found when I add the package CS-Script.RoslynProvider to my project via Nuget, the entire netframework **4.3** assembles references was added to my projects. and the **packages** directory full with entire netframework **4.3** nupkg(s).
____Dose somebody tell me the reason why CS-Script.RoslynProvider add all net assemble references to my project?
Thanks.

**Comment by UlyssesWu** [comment]
That's caused by Roslyn (Microsoft.Net.Compilers). It contains all BCL libs.
My advice: Just use "CS-Script.bin" or "CS-Script" instead of "CS-Script.RoslynProvider".

**Comment by TruePluto** [comment]
Thank you UlyssesWu.
But unfortunately. Both "**CS-Script.bin**" and "**CS-Script**" do the same stupid things that add the entire netFramework 4.3 to my project.

**Comment by oleg-shilo** [comment]
@TruePluto 
I fully share your frustration. It is indeed a stupid thing to do but... it has nothing to do with CS-Script. A couple years ago MS has made decision to stop shipping .NET compilers with .NET installations and required developers who wants to script with C# 6/7 to include entire ~20M of Roslyn (as NuGet package) in every VS project. That ridiculous derision affected **everyone** and **every product**. And CS-Script. was the first victim of it. 

CS-Script NuGet package never brings on your PC any includes any "entire netframework 4.3". What it does, is what MS requires, it express in the package definition that it needs to use .NET compilers. The rest is dome by MS. 

Saying that  @UlyssesWu is absolutely right. You don't need to use the full CS-Script package if you are OK with C# 5 syntax. If you explore CS-Script packages on NuGet you will see that there is one that has no dependencies whatsoever. It is "[cs-script.lib](https://www.nuget.org/packages/CS-Script.lib/)". @UlyssesWu just named it wrong.

Why I am explaining this with such a level of details? Every time I need to distribute products using .NET compilers, by blood is boiling. I have implemented CS-Script plugins for Sublinime Text, Notepad++, VSCode and every time I had to deal with this nonsense :(

**Comment by UlyssesWu** [comment]
I‘m sorry for the mistake... Actually I haven't used that package yet. I used to use the traditional "import dll" way.

**Comment by oleg-shilo** [comment]
It's easy to get them confused: `cs-script.bin` vs `cs-scrip.lib`

The later one is suitable for the most of the cases when you know what you are doing. It is in fact just a single dll package.

As for Roslyn polluting project folders, you can change the VS2017 settings and it will start managing all NuGet packages globally from a single system wide location without copying them to the project folders:

![image](https://user-images.githubusercontent.com/16729806/31000464-0d10588c-a51f-11e7-9f32-2ce082b72d19.png)

**Comment by TruePluto** [comment]
Thank you ,Both of you @oleg-shilo @UlyssesWu .
It is a amazing package still, Hope MS will fix the ridiculous derision soon.
I think I should create a new dll project to seperate them. hope them not to conflict.
Thank you.

**Comment by TruePluto** [comment]
HI, last week, the new version visualstudio 15.4 released. it supports the .NET Standard 2.0. 
Could changing to .NET Standard 2.0. solve this problem?
Thanks.

**Comment by oleg-shilo** [comment]
Unfortunately not. 

MS has released NET Standard 2.0 but not the compilers. 

It is still the problem, which is due to the fact that you can have the system with and version of .NET installed and yet the compilers wouldn't be available unless a dedicated NuGet package is distributed along with your product.
