### ISSUE TITLE
Problem with System.Data Reference in Script.

### ISSUE THREAD

**Issue by treinsberg** [oleg-shilo/cs-script#9]
If I use the Version 3.14.0 with the following sample I get an exception on evaluate.
            
         try
            {
                dynamic script = CSScript.Evaluator
                                             .LoadCode(@"using System;
                                                         using System.Data;
                                                         public class Update_DatabaseViews
                                                         {
	                                                      public void Excute( IDbConnection databaseConnection)
	                                                      {
                                                              }
                                                          }
                                                     ");
           }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

The Exception ist:
System.BadImageFormatException
Die Datei oder Assembly "file:///C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Es wurde versucht, eine Datei mit einem falschen Format zu laden.

This only happens, when I set the CompileOptions to x64. With AnyCPU and x86 everything works fine.

**Comment by oleg-shilo** [comment]
This error means that the script referenced assembly is of a wrong CPU architecture. The error itself is not a defect but a limitation of the assembly probing mechanism available  with Mono compiler (default evaluator engine). It uses name of the assembly/namespace  (e.g. System.Data) and resolves it into assembly file path without taking the notice of the host application CPU architecture.

You can solve the problem by disabling namespace resolving (DisableReferencingFromCode) and referencing System.Data assembly file explicitly:

```C#
dynamic script = CSScript.Evaluator
                         .ReferenceAssemblyOf<DataSet>()
                         .With(eval => eval.DisableReferencingFromCode = true)
                         .LoadCode(@"using System;
                                     using System.Data;
                         
                                     public class Update_DatabaseViews
                                     {
                                         public void Execute(IDbConnection databaseConnection)
                                         {
                                             Console.WriteLine(""Test""); 
                                         }
                                     }");
script.Execute(null);
```
However, there is even an easier way. You can switch to CodeDOM engine. It uses Fusion for assembly probing and it locates the correct assembly by taking the host CPU architecture into consideration. Though Fusion is only available on Windows.
_As an extra benefit you will be able to debug your scripts_ 
```C#
CSScript.EvaluatorConfig.Engine = EvaluatorEngine.CodeDom;
```
