### ISSUE TITLE
Metadata file could not be found (Mono)

### ISSUE THREAD

**Issue by oleg-shilo** [oleg-shilo/cs-script#92]
Mirror of https://groups.google.com/forum/#!topic/cs-script/zr2XWvQMPko

-----

The error (CS0006: Metadata file ) is a C# compiler error. Meaning that ...3-4074-af74-de06af75cf2f.tmp.compiled.dll was specified as a referenced assembly (intentionally or by accident) when the C# code pas passed for the compilation to the Mono C# compiler. 

I tried to recreate the test case and test it on Linux with the latest NuGet CS-Script package. Everything works as expected. The test project (with the all binaries) is below.  
[ConsoleApp20.zip](https://github.com/oleg-shilo/cs-script/files/1452062/ConsoleApp20.zip)

It was tested on linuxmint-18.1-cinnamon-64bit.

We will have the best chances to solve it if you can create a simple HelloWorld style test case that shows the problem.

Thank you

**Comment by Bukran** [comment]
ConsoleApp20 throws an exception when run at

- CentOS Linux release 7.3.1611
- Mono JIT compiler versión 4.6.2

But it works correctly on a 

- Ubuntu 14.04 LTS
- Mono JIT compiler version 5.0.0

And also OK in:

- Debian 8 (jessie)
- Mono JIT compiler version 5.4.0

So I'm guessing the problem has to do with mono versions under 5.

**Comment by oleg-shilo** [comment]
Apparently on some Linux distros the user temp dir mey have incompatible permissions:
![image](https://user-images.githubusercontent.com/16729806/32652788-97f5bb58-c659-11e7-9e98-6a3841329aa5.png)

The solution should be to detect and report the problem as a specific CS-Script-cache-permissions problem.

Allow user to specify custom location for temp/cache folder. Currently it is possible for hosted but not for the standalone execution.

**Comment by oleg-shilo** [comment]
Done. The error is reported as below:
```
cscs "New Script32.cs"
You do not have write privileges for the CS-Script cache directory (C:\Program Files (x86)\NewCache2). Make sure you have sufficient privileges or use an alternative location as the CS-Script temporary  directory (cscs -config:set=CustomTempDirectory=<new temp dir>)
```
