### ISSUE TITLE
Error in long script with many methods

### ISSUE THREAD

**Issue by sk222sw** [oleg-shilo/cs-script#95]
I have a script file consisting of 4627 lines of code, and ~180 methods. There are no errors in the code.

I use the default CS-Script C# compiler and the latest nuget version (3.27.2)

When I compile I get this error:

```
System.ArgumentException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.
   at System.Delegate.CreateDelegate(Type type, MethodInfo method, Boolean throwOnBindFailure)
   at System.Delegate.CreateDelegate(Type type, MethodInfo method)
   at CSScriptLibrary.CSScript.LoadDelegate[T](String methodCode, String assemblyFile, Boolean debugBuild, String[] refAssemblies)
   at CSScriptLibrary.CSScript.LoadDelegate[T](String methodCode)
   at CAR.ScriptManager.ViewModels.ScriptVersionEditing.CompileStatusViewModel.<Compile>d__23.MoveNext() in C:\Path\To\File\CompileStatusViewModel.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CAR.ScriptManager.ViewModels.ScriptVersionEditing.CompileStatusViewModel.<GetCompileResult>d__24.MoveNext() in C:\Path\To\File\CompileStatusViewModel.cs:line 87
```

If I remove the first method I get this error:
```
error CS0107: More than one protection modifier
error CS1004: Duplicate 'static' modifier
```

If I remove the protection modifier and static modifier from the now uppermost method it's back to the original error.

__However__, here's the extra weird part: if I keep the first method and remove __two__ other random methods, the script compiles. It can be any methods, as long as removing them doesn't break the code of course.

Unfortunately I can't provide the script as it's not open source.

Is there some kind of method/length limit that could cause this? Or do you have any other ideas to what could cause this?

**Comment by oleg-shilo** [comment]
I am not sure I fully follow. 

There is a strange discrepancy. You are saying that you load a file but the error trace clearly indicates that you load a delegate form the _method code_. Something similar to this:
```C#
var Product = CSScript.LoadDelegate<Func<int, int, int>>(
            @"static int Product(int a, int b)
              {
                  return product_impl(a, b);
              }

              static int product_impl(int a, int b)
              {
                  return a * b;
              }");

int result = Product(3, 2);
``` 

If indeed you have a problem with LoadDelegate, then ensure that your primary method is the first method in the code. 

In some earlier versions modifier `static` was **always** injected at start, what could cause problem similar to yours. If it is your case then just drop the first `static` at the code start. But keep everywhere else as your first routine is in fact `static` when it's compiled.

The latest version is immune to the `static` double insertion. 

If it doesn't help, try to provide a code sample. Remove all sensitive code and leave only empty signatures if possible.

**Comment by sk222sw** [comment]
We have an internal company tool that read the scripts, that's why I referred to it as a script but still got the delegate error, sorry for the confusion.

Anyway, we had two methods that were _public_, and the rest were _private_, and we managed to solve our problem by changing the public methods to private. 

I don't really have time to look in to why, so if you think that this isn't due to some error in CS-script, please feel free to close this. Thanks for your reply! :)
