### ISSUE TITLE
RemotingException when running a hosted script for more than 5 minutes

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#98]
Yesterday I ran into this issue:

```
    Exception:
        Type: System.Runtime.Remoting.RemotingException
        Message:
            Object '/2f8b6872_ccdf_4474_abde_8734902f56eb/9rbuzqrht6u_zqzoub6hesdq_3.rem' has been disconnected or does not exist at the server.
        Source: mscorlib
        Stack:
           at System.IDisposable.Dispose() @ asmBrowser.Dispose();
           at CSScriptLibrary.AsmHelper.Dispose(Boolean disposing) @ line 1056 = asmBrowser.Dispose();
           at CSScriptLibrary.AsmHelper.Finalize() @ line 1068
```

The issue is reproducible in my hosted application that is based on CSScript 3.27.5. It occurs after the script has completed, application still running afterwards, though crashing when exiting. But it only occurs for scripts running more than 5 minutes. Scripts running for less than 5 minutes work fine. The issue does not happen with the previous version of my hosted application that was based on CSScript 3.3.5. Both versions of my application still target .NET 3.5 SP1. So the issue is either caused by a change in my hosted application, or a change in CSScript.

I explicitly call `AsmHelper.Dispose()` after the script got finished. This seems to provoke the exception. However, `try/catch` doesn't help since the timeout exception happens asynchronously in the runtime. Debugging using CSScript source code reveals the same issue:

```
    Exception:
        Type: System.Runtime.Remoting.RemotingException
        Message:
            Object '/70f13525_9536_4b25_8ff6_8b420f4e7c5a/kpfod8v0orj58jntfhsfpuvv_3.rem' has been disconnected or does not exist at the server.
        Source: mscorlib
        Stack:
           at System.IDisposable.Dispose() @ asmBrowser.Dispose();
           at CSScriptLibrary.AsmHelper.Dispose(Boolean disposing) @ line 1056 = asmBrowser.Dispose();
           at CSScriptLibrary.AsmHelper.Dispose() @ line 1043
```

The only difference is, now the explicit call to `AsmHelper.Dispose()` provokes the timeout exception. Still, it cannot be handled here, as another exception will be thrown by the runtime at a later stage, e.g. when exiting the application.

Digging for several hours, I realized that this issue already occurred in 2013. Urs Fiechter back then solved it (probably after communicating with you, he called it "lost connection"), by the following code:

```
	public override object InitializeLifetimeService()
	{
		var lease = (ILease)base.InitializeLifetimeService();
		if (lease.CurrentState == LeaseState.Initial)
			lease.InitialLeaseTime = TimeSpan.Zero;

		return (lease);
	}
```

This piece of code is still contained, but for some reason it no longer prevents the timeout exception from happening. Diffing my own code didn't reveal a potential root cause. So I started diffing CSScript files 3.3.5 -vs- 3.27.5 for changes to the lease/timeout/disposal behavior. Findings:

1. `AsmHelper` now offers `ExtendLife...()` methods what 3.3.5 didn't. But that probably isn't related to my issue, since it "extends the life of the instance created in the **remote** AppDomain" whereas my issue is related to the object in the hosting application's AppDomain, i.e. the **local** AppDomain.
2. `AsmHelper.Dispose()` of 3.27.5 calls `asmBrowser.Dispose()` what 3.3.5 didn't. Seems to fully make sense though, after all, an object shall properly cleanup.
3. AssemblyExecutor doesn't seem to have a change that could be the root cause of the issue.

By the way, I haven't found anything on "remoting timeout" nor "lease" in the CSScript help/documentation.

Finding 2. seemed most promising. I simply added a `try/catch` around `asmBrowser.Dispose()`, and voilà, no more timeout exception! Scripts longer than 5 minutes run again, for as many times I want. Disadvantage: I have to build `CSScriptLibrary.dll` by myself. At least I have incremented its version to 3.27.5.1.

To be honest, I don't fully get the situation, and, it rather looks like an ugly workaround than a true solution, but, it fixes the exception. Hope you can shed some light into this lease topic, and one day release an update fixing this issue.

**Comment by maettu-this** [comment]
Since the simple `try/catch` around `asmBrowser.Dispose()` too much looked workaround-ish, I have tried another approach: Applying the `InitializeLifetimeService()` override described above to the `AsmRemoteBrowser` class (i.e. the related class that is a `MarshalByRefObject`.

This approach also fixes the timeout exception and looks more like a solution than the above workaround. After all, the script engine mechanism is not a real inter-process communication. The connection between script and the hosting application uses .NET Remoting, but within a single process. So it is acceptable to switch off the timeout mechanism. When the hosting application is terminated, all objects will be finalized anyway.

Still, I don't fully get the situation and I hope you can shed some light into this lease topic, and asses whether the `InitializeLifetimeService()` override indeed is the solution or yet another approach has to be found.

**Comment by oleg-shilo** [comment]
Excellent. Thank you for looking into it. 

I think there may be another change between these two versions. If i remember this right the later releases have changed the default for using in-memory assemblies (compiled scripts) instead of loading from file. This may affect the CLR in one or another way. 

You can test this theory by forcing assembly loading to be from the file:
```C#
CSScript.GlobalSettings.InMemoryAssembly = false;
``` 
As for "try/catch around asmBrowser.Dispose()" it is actually is not a hack at all. Yes it my be just a work around but in any case having exception in Dispose is no-no. Thus I will actually need to place try/catch there regardless of other findings and actual causes of the problem. 

Dispose should not throw no matter what.

**Comment by oleg-shilo** [comment]
Please let me know if 'InMemoryAssembly' made any difference.  

And another question.
> This piece of code is still contained,.. 

I cannot see it . Am I blind :o )

Where is it?

**Comment by maettu-this** [comment]
> This piece of code is still contained,..

Sorry for confusing. This piece of code is still contained in my hosting application, so the lease of the application's `ScriptEngine` will never time out.

I agree that `Dispose()` must never throw. Still, applying infinite lifetime seems to make sense as well. Maybe both fixes should be done.

`InMemoryAssembly` I'll try tomorrow, gotta go...

**Comment by oleg-shilo** [comment]
> Maybe both fixes should be done.

Yes, absolutely, and this is what I have done already. Though I haven't committed the code just in case you discover some more info on the subject.

**Comment by maettu-this** [comment]
OK, I have run with globally disabled `InMemoryAssembly`. I also used `CSScript.CompileWithConfig(..., settingsWhereInMemoryAssemblyIsFalse,...)`, just in case this has impact on the execution behavior.

It doesn't make any difference regarding this issue. I still get an exception at `asmBrowser.Dispose()`. However, note that my hosting application...

1. ...explicitly `CSScript.CompileWithConfig()` the `.cs` file to a `.dll` file,...
2. ...uses `new AsmHelper(assemblyFilePath, "ScriptRunner", false);`,...
3. ...and finally invokes the assembly using that helper.

I do this for compatibility with the previous version of the hosting application. There are some use cases where the `.dll/.pdb` files are explicitly required by the users. In the next-next version of the application, I intend to add an option to let the user chose whether or not to build the `.dll/.pdb` files. I also do this to be able to output more fine granular error information, i.e. first explicitly handle compilation errors, then explicitly handle invocation and execution errors.

I have attached a sketch of the application setup for reference. The upper drawing shows the current setup, the lower is my intention to separate the `ScriptRunner` into its own `AppDomain`. This will allow loading and later unloading exception types that are defined by the remote script. Currently, I load such exception types into the `AppDomain` of the hosting application, thus never unloading these types anymore.

[Overview.pdf](https://github.com/oleg-shilo/cs-script/files/1663655/Overview.pdf)

**Comment by maettu-this** [comment]
A question related to the fairly new `ExtendLife()` methods in `AsmHelper.cs`. In which cases it is useful to call one of these methods? So far I only ran into lease timeouts the opposite way around, i.e. when an MBR-object of the hosting application timed out. Remote objects haven't timed out (yet).

Just for curiosity, I tried calling `helper.RemoteObject.ExtendLifeFromMinutes(6);` after creating the helper, and voilà, no more timeout exception! After all `RemoteObject` **is** the `asmBrowser`! So I guess, setting infinite lease timeout in `AsmBrowser` even eliminates the need for the `...ExtendLife...()` methods.

Isn't the comment "Extends the life of the instance created in the remote AppDomain." a bit confusing? Isn't the `AsmBrowser` actually residing in the local `AppDomain`? Or do I still not get the setup? Then this would be exactly the some issue Urs FIechter ran into in 2013, a timed out **local** MBR-object, and settings infinite lease timeout indeed is the solution.

**Comment by maettu-this** [comment]
Let me add a peculiarity:

As visible in the previously attached .pdf, the script may call I/O, logging,... (lower green arrow) as well as access a few elements for user interaction (upper green arrow). If the script only accesses low level functionality, the timeout exception occurs (without fixes). But, if the script also accesses view functionality, i.e. accesses something somewhere in WinForms, the timeout exception doesn't occur. For some reason, the runtime must automatically renew the lease of that MBR-object when something somewhere in WinForms is accessed.

No difference with the `AsmBrowser`, that timeout exception occurs in any case.

**Comment by oleg-shilo** [comment]
I have attached the legacy sample 'LifetimeManagement.cs' it can shed some light on this.
[LifetimeManagement.zip](https://github.com/oleg-shilo/cs-script/files/1666761/LifetimeManagement.zip). It shows how to extend life of both your script and its host AsmRemoteBrowser, which can be accessed via AsmHelper.RemoteObject. 

As for `AsmBrowser` itself, it is indeed always hosted from the calling (local domain). Tough it's remote counterpart is called `AsmRemoteBrowser`. Both have the same interface `IAsmBrowser`.

Unfortunately I cannot dedicate much time to this problem as I have to fulfill my promise to other users and finally release .NET Core version of CS-Script. But when I am back and if you havent sorted it out yet we can have a closer look at it.

**Comment by maettu-this** [comment]
I fully understand, not urgent at all, I have the "infinite-lease" fix in place and can easily live with having to build 3.27.5.1 myself.

Thanks for the insight in `AsmBrowser` -vs- `AsmRemoteBrowser`. I may look into it in the next days, though I will focus on releasing the next version of my hosting application as well.

**Comment by maettu-this** [comment]
Helper class to solve this issue in multiple locations:
```
	/// <summary>
	/// Enables access to objects across application domain boundaries in applications that support
	/// remoting, giving them infinite lease time by setting <see cref="ILease.InitialLeaseTime"/>
	/// to <see cref="TimeSpan.Zero"/>.
	/// </summary>
	/// <remarks>
	/// The script engine mechanism is not a real inter-process communication. It does use remoting,
	/// but within a single process. So it is acceptable to switch off the timeout mechanism. When
	/// the hosting application is terminated, all objects will be finalized anyway.
	/// 
	/// Without the modification, if there is no interaction between script and host for more than
	/// 5 minutes (the default lease time for .NET remoting), a <see cref="RemotingException"/>
	/// may be thrown, stating:
	/// <![CDATA[Object '/<guid>/<id>.rem' has been disconnected or does not exist at the server.]]>
	public class MarshalByRefObjectWithInfiniteLifetime : MarshalByRefObject
	{
		/// <summary>
		/// Obtains a lifetime service object to control the lifetime policy for this instance.
		/// </summary>
		public override object InitializeLifetimeService()
		{
			var lease = (ILease)base.InitializeLifetimeService();
			if (lease.CurrentState == LeaseState.Initial)
			{
				// If the 'InitialLeaseTime' property is set to 'TimeSpan.Zero', then the lease will
				// never time out and the object associated with it will have an infinite lifetime:
				lease.InitialLeaseTime = TimeSpan.Zero;
			}

			return (lease);
		}
	}
```

**Comment by oleg-shilo** [comment]
Excellent. Thank you. I will integrate it in the code base. I will also need to create a dedicated wiki page for this topic. Other users also posted questions on this topic.

And I assume that the use case for this new class is like this:
```C#
public interface IScript
{
     void Hello(string greeting);
}

var code = @"using System;
             public class Script : MarshalByRefObjectWithInfiniteLifetime 
             {
                 public void Hello(string greeting)
                 {
                     Console.WriteLine(greeting);
                 }
             }";

using (var helper = new AsmHelper(CSScript.CompileCode(code), null, deleteOnExit: true))
{
    IScript script = helper.CreateAndAlignToInterface<IScript>("*");
    script.Hello("Hi there...");
}
```
Is it correct?

**Comment by maettu-this** [comment]
Hmm... Maybe that also solves something. But in my case...

> So far I only ran into lease timeouts the opposite way around, i.e. when an MBR-object of the hosting application timed out. Remote objects haven't timed out (yet).

...there is no need to apply this fix to a script, rather it has to be done to the `AsmBrowser`, i.e. local objects which may time out. No issue with remote object, i.e. scripts.

**Comment by oleg-shilo** [comment]
I see.
Look, anyway your solution is generic by nature and it is beneficial for anyone  who wants to create a long living object to be accessed from remote domain. This definition covers both scenarios 

- _actual object being created in the script domain and accessed by host_ 
- _actual object being created in the host domain and accessed by script_

That's why I included your code and now `MarshalByRefObjectWithInfiniteLifetime` is available as a top level type from CSScriptLibrary.dll assembly.

**Comment by maettu-this** [comment]
Makes sense. Just wanted to point out that it's not sufficient to decorate the script, `AsmBrowser` has to be decorated as well.

**Comment by oleg-shilo** [comment]
Yes, I overlooked that. Thank you.

**Comment by maettu-this** [comment]
I have looked at the `LifetimeManagement.zip` script you attached earlier. It indeed looks just the same as the issue I ran into. So most likely, with the fix to this issue, you could obsolete and eventually remove the lease related `ExtendLife...()` extension methods.

Regarding to implementation of `MarshalByRefObjectWithInfiniteLifetime`, isn't it rather unusual (and also a bit dangerous) to place such class into the root namespace? Root namespace classes will immediately conflict with equally named classes. I think the class should be placed into the `CSScriptLibrary` namespace.

Bad news is, the remoting exception still occurs with the 3.28.0 release. Good news though, adding `MarshalByRefObjectWithInfiniteLifetime` to `RemoteExecutor` at line 288 in `CSScriptLib.cs` solves it. If there's 3.28.1 coming up soon, I'd appreciate a fix. If not, I can easily fix that and create a 3.28.0.1 DLL myself.

Minor: Commented-out code `//public class AsmReader : MarshalByRefObject` which is also a candidate for using `MarshalByRefObjectWithInfiniteLifetime`.

Super-minor: Superfluous space `However  <see` at line 279 in `CSScriptLib.cs`.

**Comment by oleg-shilo** [comment]
Thank you. You are absolutely right. `RemoteExecutor ` needs to be inherited from `MarshalByRefObjectWithInfiniteLifetime`. I though I patched it. Apparently not. During making this change I have also discovered some other cases. So now they are all fixed. 

> Minor: Commented-out code...

I have removed it. It's not needed any more. If my memory does not fail me it was a poor man equivalent of `Assembly.ReflectionOnlyLoad`, when it wasn't available yet.

> Super-minor:
 
Done.

> isn't it rather unusual (and also a bit dangerous) to place such class into the root namespace?

:o) Yes it is unusual. I was tossing if I should enclose it in namespace or not... None of the choices is ideal.
Using namespace will be canonical but it would force users to always place `using CSScriptLibrary;`. Root class is extremely convenient but can lead to the naming collisions. I opted to the root-class. But to minimize the probability of the collision I named the class  with a long purpose specific name.

As for `ExtendLife...()` agree they are becoming kind of redundant. I have already marked all of them as obsolete but left `ExtendLifeFromMinutes<T>(this MethodDelegate<T> method,...` untouched as I am afraid there is no other way for delegates. I am also not sure if I ever completely remove `ExtendLife...()`. I kind of like the fact that if users are not comfortable with cs-script's `MarshalByRefObjectWithInfiniteLifetime` trick they can always fallback to the canonical Remoting approach.

**Comment by maettu-this** [comment]
> users to always place `using CSScriptLibrary;`

Well, with namespace, users could still use `MyClass : CSScriptLibrary.MarshalByRefObjectWithInfiniteLifetime` without having to place `using CSScriptLibrary;`.
In my opinion, root-classes are no-go's. Consider what happens if every library was extensively using root-classes...

> they can always fallback to the canonical Remoting approach

Makes sense.

**Comment by oleg-shilo** [comment]
> ...without having to place `using`...

My objection was not about 'using' but about the need to utilize namespace regardless of the syntax being used for that.

> , root-classes are no-go's.

:) By no means I am promoting root-classes as a general technique. You probably noticed, CSScriptLibrary has only a single root-class out of 51 public classes.

I simply felt that braking the rule in this case would bring more benefits than sticking to it. 

Though I knew it was the edge case and I was prepared to rollback my original decision in case of even single complain. Well, I got it. So I'll wrap `MarshalByRefObjectWithInfiniteLifetime` into namespace.

> Consider what happens if every library was extensively using root-classes...

While it is indeed a common rule you will be surprised to know how frequently it is broken by frameworks without any daemage and users even noticing this. For example Roslyn complies all code in the root-classes. All the time, unconditionally. It's done to allow seamless referencing between scripts. My motivation was the same.

**Comment by maettu-this** [comment]
Thanks :)
